### ISSUE TITLE
Download extension bundle directly in azure files

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#10214]
Host downloads extension bundle if there isn't a matching version already present on the disk. However, this download can happen over and over if the extraction fails due to storage space in issue.
Here is a sample stack trace.

```Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error building configuration in an external startup class. ---> System.IO.IOException : There is not enough space on the disk. : 'C:\local\Temp\9f43302d-ce9b-4f5a-b417-0252775efcfa\Microsoft.Azure.Functions.ExtensionBundle.Preview.4.19.0.zip'
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.TryDownloadZipFileAsync(Uri zipUri,String filePath,HttpClient httpClient) at /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 213
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.DownloadExtensionBundleAsync(String version,HttpClient httpClient) at /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 174
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetBundle(HttpClient httpClient) at /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 113
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetExtensionBundlePath(??) at /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 82
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetExtensionBundleBinPathAsync() at /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 298
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 122
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__10_0() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 53
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 68
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalConfigurationStartup(IWebJobsConfigurationBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator,WebJobsBuilderContext context,ILoggerFactory loggerFactory) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 362
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_3.<AddScriptHostCore>b__8(IWebJobsStartupTypeLocator locator) at /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 263
   End of inner exception```

**Comment by pragnagopa** [comment]
Does this apply to all SKUs? also, please track documentation update for using Preview Bundles, Cx should have Azure Files App setting? detector if not set?
