### ISSUE TITLE
Deploying to K8s

### ISSUE THREAD

**Issue by neadtree** [Azure/azure-functions-host#10266]
#### Is your question related to a specific version? If so, please specify:
no
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
c#
#### Question
I am trying to containerize my azure durable functions in K8s. ). I am running into the below failure. I noticed [https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/Kubernetes/KubernetesClient.cs#L61](url) that uses some type of env var called HTTP_LEADER_ENDPOINT. Do you have any ideas/insights to the error? Should I set env var HTTP_LEADER_ENDPOINT to something? If so, what should I set it to.

The listener for function 'Functions.TimeStarter' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'Functions.TimeStarter' was unable to start.
---> System.NotSupportedException: The 'file' scheme is not supported.
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Microsoft.Azure.WebJobs.Script.KubernetesClient.TryAcquireLock(String lockId, String ownerId, TimeSpan lockPeriod, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/Kubernetes/KubernetesClient.cs:line 64
at Microsoft.Azure.WebJobs.Script.KubernetesDistributedLockManager.TryLockAsync(String account, String lockId, String lockOwnerId, String proposedLeaseId, TimeSpan lockPeriod, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/Kubernetes/KubernetesDistributedLockManager.cs:line 54
at Microsoft.Azure.WebJobs.Host.SingletonManager.TryLockAsync(String lockId, String functionInstanceId, SingletonAttribute attribute, CancellationToken cancellationToken, Boolean retry) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonManager.cs:line 113
at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.StartAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonListener.cs:line 48
at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 68

**Comment by kshyju** [comment]
@AmeyaRele Could you please take a look at this?

**Comment by kshyju** [comment]
@vivekjilla FYI

**Comment by krishnajaju** [comment]
Hi @neadtree, do you have `POD_NAMESPACE` environment variable in functions pod running in K8S? If yes, can you please remove POD_NAMESPACE environment variable and validate if it fixes the issue? Additionally, can you also set WEBSITE_SITE_NAME environment variable to a FunctionApp name since you are running functions in Kubernetes?

**Comment by neadtree** [comment]
Yes, @krishnajaju I had POD_NAMESPACE environment variable defined. After removing this and adding WEBSITE_SITE_NAME, all started to work, Thank you very much :).

**Comment by neadtree** [comment]
Issue has been resolved.

**Comment by neadtree** [comment]
Issue has been resolved.

**Comment by AmyJeanes** [comment]
This is the code that is causing it to detect the environment incorrectly: https://github.com/Azure/azure-functions-host/blob/5656de4fde9865d83614d07fdf60cc87c34c8d67/src/WebJobs.Script/Environment/EnvironmentExtensions.cs#L426-L431

Removing the `POD_NAMESPACE` also works for us, but it is not ideal as we've had to add a special edge case for it.
