### ISSUE TITLE
Getting the error "Container is disposed and should not be used exception" intermittently after .NET 8 upgrade and change to Azure Durable Function Isolated model

### ISSUE THREAD

**Issue by BrunoCandia** [Azure/azure-functions-host#10478]
#### Is your question related to a specific version? If so, please specify:
We are using: 
-C# with .Net 8, 
-Azure function v4, 
-Isolated model
-Service bus trigger
-Service plan: Windows / Elastic plan

#### Here are the nuget packages I use:
![image](https://github.com/user-attachments/assets/45f8be1c-442e-4c85-bc8e-e300174945eb)

#### I found the following exception in the log for an Azure Function in production environment:

```log
---> DryIoc.ContainerException: Container is disposed and should not be used: Container is disposed.
sbt-tenant-notifications/Subscriptions/SendRecordTrackingInfoEvent-d91645d7-7ca4-4995-bd82-73c41feab5ab: User message handler complete: Message: SequenceNumber: 228486, Exception: Microsoft.Azure.WebJobs.Script.HostDisposedException: The host is disposed and cannot be used. Disposed object: 'Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver'; Found IListener in stack trace: 'Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener, Microsoft.Azure.WebJobs.Extensions.ServiceBus, Version=5.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'
You may include Dispose stack-trace into the message via:
container.With(rules => rules.WithCaptureContainerDisposeStackTrace())
at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in /_/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 9002
at DryIoc.Container.ThrowIfContainerDisposed() in /_/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 411
at DryIoc.Container.WithCurrentScope(IScope scope, Boolean preferInterpretaion) in /_/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 437
at DryIoc.ResolverContext.OpenScope(IResolverContext r, Object name, Boolean trackInParent, Boolean preferInterpretation) in /_/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 2709
at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver.CreateChildScope(IServiceScopeFactory rootScopeFactory) in /_/src/WebJobs.Script.WebHost/DependencyInjection/ScopedResolver.cs:line 42
at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.CreateScope() in /_/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 106
--- End of inner exception stack trace ---
at Microsoft.Azure.WebJobs.Script.HostDisposedException..ctor(String disposedObjectName, Exception inner) in /_/src/WebJobs.Script/HostDisposedException.cs:line 24
at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.CreateScope() in /_/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 106
at Microsoft.Azure.WebJobs.Host.Executors.DefaultInstanceServicesProvider.get_InstanceServices() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultInstanceServicesProvider.cs:line 26
at Microsoft.Azure.WebJobs.Host.Executors.FunctionInstance.get_InstanceServices() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInstance.cs:line 56
at Microsoft.Azure.WebJobs.Host.Bindings.FunctionBindingContext..ctor(IFunctionInstanceEx functionInstance, CancellationToken functionCancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Bindings\FunctionBindingContext.cs:line 66
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken)
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken)
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutorExtensions.TryExecuteAsync(IFunctionExecutor executor, Func`1 instanceFactory, ILoggerFactory loggerFactory, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutorExtensions.cs:line 50
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutorExtensions.TryExecuteAsync(IFunctionExecutor executor, Func`1 instanceFactory, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 59
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken)
at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessSessionMessageAsync(ProcessSessionMessageEventArgs args)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessSessionMessageAsync(ProcessSessionMessageEventArgs args)
at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessSessionMessageAsync(ProcessSessionMessageEventArgs args)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessSessionMessageAsync(ProcessSessionMessageEventArgs args)
at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessSessionMessageAsync(ProcessSessionMessageEventArgs args)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessSessionMessageAsync(ProcessSessionMessageEventArgs args)
at Azure.Messaging.ServiceBus.SessionReceiverManager.OnMessageHandler(EventArgs args)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Azure.Messaging.ServiceBus.SessionReceiverManager.OnMessageHandler(EventArgs args)
at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage triggerMessage, CancellationToken cancellationToken)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage triggerMessage, CancellationToken cancellationToken)
at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessageWithinScopeAsync(ServiceBusReceivedMessage message, String activityName, CancellationToken cancellationToken)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessageWithinScopeAsync(ServiceBusReceivedMessage message, String activityName, CancellationToken cancellationToken)
at Azure.Messaging.ServiceBus.SessionReceiverManager.ReceiveAndProcessMessagesAsync(CancellationToken processorCancellationToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at Azure.Messaging.ServiceBus.ServiceBusReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, Boolean isProcessor, CancellationToken cancellationToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, CancellationToken cancellationToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__44_0>d.MoveNext()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
at System.Threading.Tasks.TaskFactory`1.<>c__DisplayClass38_0`1.<FromAsyncImpl>b__0(IAsyncResult iar)
at Microsoft.Azure.Amqp.AsyncResult.TryComplete(Boolean didCompleteSynchronously, Exception exception)
at Microsoft.Azure.Amqp.AsyncResult.Complete(Boolean didCompleteSynchronously, Exception e)
at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()
, LockToken: d55934c4-0fa8-47ce-8963-9dbb4ee66f1f
```

#### Question
How this issue could be fixed or get a clue where is the issue?

**Comment by jviau** [comment]
@BrunoCandia is there any impact to your application beyond this error log?

Looking at the call stack this error appears to be mostly noise. The JobHost is shutting down, which will necessitate aborting ongoing invocations. The exact exception that surfaces will vary depending on where the invocation is at in its execution. But overall I believe this is noise as the invocation must be aborted one way or another: be it an object disposed, or operation cancelled.

Additionally, we have switched from DryIoC to Microsoft.Extensions.DependencyInjection for our service provider here which may change the behavior. Verify if your application is on `4.1036` host runtime and let us know if this - or a different object disposed exception in a similar stack - is still occurring.

**Comment by boblarson-ka** [comment]
I'm a coworker of Bruno's. We're chasing this with Azure Support as well. This is happening in the Service Bus Trigger binding before any of our custom code can be invoked. The net impact is all queue messaging ends up Dead Lettering. We're working on work arounds to accommodate the DLQ processing in response as the issue has been open for a while and impacts business processes that require successful execution within minutes and not the hour or two later when we've finally had a moment to react.

runtime stack currently is: 4.1036.3.23284

The issue hasn't happened again in a week, but support has been mostly approaching this as something that was within our control for assemblies, configs, etc... The oddity that set us down this path is the stack trace was referencing files from azure source code that haven't been in play for a while.

Is there a commit or tag we could review for the host source to try and understand the resolution? I can't find anything in Azure Change Analysis to know if that runtime stack value has changed in the last 7 days or not.

I will say that with no code changes deployed that the Function App Down or Reporting Errors portion of function Diagnostics is reporting a ton of errors:

They all look something like this

Overwriting 'SomeKeyValue' with existing value 'OldValue' with 'NewValue'
 
It's just pages of red that wasn't there before.

**Comment by AlexMasson** [comment]
@jviau coming from this [issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/2730), I have the same problem as @boblarson-ka, the impact is that our service bus message ends up dead lettering randomly. It's like a disposed host try to process a message. The host startup, create listeners, then stop for an obscure reason.

> Additionally, we have switched from DryIoC to Microsoft.Extensions.DependencyInjection for our service provider here which may change the behavior. Verify if your application is on 4.1036 host runtime and let us know if this - or a different object disposed exception in a similar stack - is still occurring.

When did you do the switch ? I get another `DryIoc.ContainerException` 2 days ago, 29 october, on a function running with this version: 4.1036.3.23284.

**Comment by BrunoCandia** [comment]
@jviau, the consequences are the ones mentioned by @boblarson-ka

**Comment by surgupta-msft** [comment]
Apologies for the delayed response. I have a few questions to help investigate this issue -

- Are you still experiencing this issue with the latest Host (4.1038.300) and nuget packages?
- Since it's an intermittent issue and sometimes doesn't occur for a week, can you share the timestamp, app name, invocationId the next time it happens? so that we can check our logs. Please refer to - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
