### ISSUE TITLE
Microsoft Azure error message: Failed to proxy request with ForwarderError: RequestBodyDestination

### ISSUE THREAD

**Issue by phuongvtqtx** [Azure/azure-functions-host#10623]
I used an HTTP trigger to trigger an Azure function.
My request body is only around 30MB, and the URL Length is below 4KB. 
The function still runs normally but when returning a response or throwing an exception. I will get the Error and never receive a response (always status code 500). If the body size is around or less than 25MB, the function works normally and still receives a response.

This is error message:

`Failed to proxy request to the worker. Retrying in 50ms. Attempt 1 of 3.`
` Failed to proxy request to the worker. Retrying in 100ms. Attempt 2 of 3.`
 `System.Private.CoreLib: Exception while executing function: Functions.function-name. Microsoft.Azure.WebJobs.Script.Grpc: Failed to proxy request with ForwarderError: RequestBodyDestination. One or more errors occurred. (Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..) (An error occurred while sending the request.). System.Net.Sockets: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.. An existing connection was forcibly closed by the remote host.
`

**Comment by liliankasem** [comment]
Can you share more information about the function app you're running? i.e. which version of the host? What version of core tools? What language? Can you share a code snippet of the function that's failing?

**Comment by ipetrouchtchak-fi** [comment]
@liliankasem, I've just encountered the same error... https://github.com/Azure/azure-functions-host/issues/10640
I have a HttpTrigger function, which reads from a File part in multipart/form-data. The function was just converted from the in-process model (where it doesn't have any issues with uploading large files ~200 MB). 
In the .NET 8.0 Isolated model, when attempting to upload files larger than about 30 MB a 500 error is returned.

Error message:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.DocUpload 
---> System.InvalidOperationException : Failed to proxy request with ForwarderError: RequestBodyDestination 
---> System.IO.IOException : Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.. 
---> System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine.

   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async System.Net.Http.HttpConnection.<WriteAsync>g__AwaitFlushAndWriteAsync|72_0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async System.Net.Http.HttpConnection.ChunkedEncodingWriteStream.<WriteAsync>g__WriteChunkAsync|4_0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(??)
   End of inner exception
   at async Microsoft.Azure.WebJobs.Script.Grpc.DefaultHttpProxyService.EnsureSuccessfulForwardingAsync(ScriptInvocationContext context) at /_/src/WebJobs.Script.Grpc/Server/DefaultHttpProxyService.cs : 65
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.InvokeResponse(InvocationResponse invokeResponse) at /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs : 1116
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs : 101
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at /_/src/WebJobs.Script/Description/FunctionInvokerBase.cs : 82
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) at /_/src/WebJobs.Script/Description/FunctionGenerator.cs : 225
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 53
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 581
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 523
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 306
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 352
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 108
...
hostVersion: 4.1036.3.23284
```

**Comment by JAdluri** [comment]
Thank you for sharing the issue here. Will further investigate and come back .

**Comment by JAdluri** [comment]
Can you share more information about the function app you're running? i.e. which version of the host?. Could you also share me the code snippet you are trying to run
