### ISSUE TITLE
mscorlib: Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by HowardEdidin** [Azure/azure-functions-host#1447]
Please provide a succinct description of the issue.

#### Repro steps

NPM installed from my GitHub repository 
https://github.com/HowardEdidin/blue-button

![kudo](https://cloud.githubusercontent.com/assets/19954905/25317269/187b4530-283b-11e7-8338-0d14b9f6ec9b.png)

1. Step A
Body: 
[CCD_1.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/950013/CCD_1.txt)

Screenshot for test:
![2017-04-23_15-33-50](https://cloud.githubusercontent.com/assets/19954905/25317237/6027d1ba-283a-11e7-9cd9-af481c989384.png)

2. Step B

#### Actual behavior

2017-04-23T18:48:34.388 Function started (Id=25035345-a3b6-46f2-8d26-ab346f41f479)
2017-04-23T18:48:34.403 JavaScript HTTP trigger function processed a request.
2017-04-23T18:48:34.658 Function completed (Failure, Id=25035345-a3b6-46f2-8d26-ab346f41f479, Duration=261ms)
2017-04-23T18:48:34.689 Exception while executing function: Functions.ParseCcd2Section. mscorlib: Error: A dynamic link library (DLL) initialization routine failed.\\?\D:\home\site\wwwroot\ParseCcd2Section\node_modules\libxmljs\build\Release\xmljs.node    
at Error (native)    
at Object.Module._extensions..node (module.js:583:18)    
at Module.load (module.js:473:32)    
at tryModuleLoad (module.js:432:12)    
at Function.Module._load (module.js:424:3)    
at Module.require (module.js:483:17)    
at require (internal/module.js:20:19)    
at bindings (D:\home\site\wwwroot\ParseCcd2Section\node_modules\bindings\bindings.js:76:44)    
at Object.<anonymous> (D:\home\site\wwwroot\ParseCcd2Section\node_modules\libxmljs\lib\bindings.js:1:99)    
at Module._compile (module.js:556:32).

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 

 ```
	module.exports = function (context, req) {
	    context.log('JavaScript HTTP trigger function processed a request.');
	
	    var bb = require('blue-button2');
	
	
	    if (req.query.id && req.body) {
	
	        var doc = req.body;
	        var section = req.query.id;          
	    
	
	        var result = bb.parseString(doc, { component: section });
	
	        if (result) {
	
	            context.res 
	            .status(200)
	            .set("Content-Type", "application/json")
	            .set("x-ms-description", "Success" )
	            .send(JSON.stringify(result, null, 4));
	            
	
	        } else {
	            context.res 
	            .status(400)
	            .set("Content-Type", "application/json")
	            .set("x-ms-description", "Bad Request" )
	            .send( "Invalid Document Type");
	            
	        }
	
	    } else {
	        context.res
	        .status(405)
	        .set("Content-Type", "application/json")
	        .set("x-ms-description", "Method No Allowed" )
	        .send("Missing XmlDoc or Section Id");
	
	
	    }   
	    context.done();
	};
	
```

* Links to source

**Comment by christopheranderson** [comment]
Blue Bottle has native dependencies which our Edge.js runtime doesn't like. :(

We're working on improving this, but there is no simple workaround for the time being.

**Comment by pragnagopa** [comment]
Please try Functions V2. Closing this issue for now.  Please reactivate if you still run into issues with v2.
