### ISSUE TITLE
Crash WebJobs.Script.Host when load custom extension

### ISSUE THREAD

**Issue by SenyaMur** [Azure/azure-functions-host#2138]
#### Investigative information
I use WebJobs.Script.Host from dev brahch (latest commit at 16 nov 2017 28e2fbed7ae2408cf6d1902e7ab334a2ad37439f ).
When I tryied to load a custom extension using extensions.json the WebJobs.Script.Host crashed.

#### Repro steps

1. Download Sample.Extension from https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/Sample.Extension
2. Build Sample.Extension
3. Put  Sample.Extension.dll to [azure-webjobs-sdk-script]\sample\bin\
4. Create extensions.json in [azure-webjobs-sdk-script]\sample\bin\ with content:
```json
{
	"extensions": [{
			"name": "SampleExtension",
			"typeName": "Microsoft.Azure.WebJobs.SampleJobHostConfigurationExtensions+SampleExtensionConfig, Sample.Extension, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null"
		}
	]
}
```
5. Go to WebJobs.Script.Host project properties and set Application arguments 
[azure-webjobs-sdk-script]\sample
6. Run WebJobs.Script.Host 
7. After load custom extension, functions in host.json tries to compile and application crashes.

host.json in [azure-webjobs-sdk-script]\sample folder:
```json
{
    "watchDirectories": [ "Shared" ],
    "sendGrid": {
        "from": "Azure Functions <samples@functions.com>"
    },
    "http": {
        "routePrefix": "api",
        "maxConcurrentRequests": 5,
        "maxOutstandingRequests": 30
    },
    "tracing": {
        "fileLoggingMode": "always"
    },
    "queues": {
        "visibilityTimeout": "00:00:10"
    },
    "swagger": {
        "enabled": true
    },
    "eventHub": {
        "maxBatchSize": 1000,
        "prefetchCount": 1000,
        "batchCheckpointFrequency": 1
    },
    "functionTimeout": "00:05:00",
    "functions": ["TimerTrigger-CSharp","HttpTrigger-CSharp"]
}
```

Output:
```
Reading host configuration file 'm:\~\jira\azure-webjobs-sdk-script\sample\host.json'
Host configuration file read:
{
  "functionTimeout": "00:05:00",
  "http": {
    "routePrefix": "api",
    "maxConcurrentRequests": 5,
    "maxOutstandingRequests": 30
  },
  "watchDirectories": [
    "Shared"
  ],
  "functions": [
    "TimerTrigger-CSharp",
    "HttpTrigger-CSharp"
  ],
  "queues": {
    "visibilityTimeout": "00:00:10"
  },
  "eventHub": {
    "maxBatchSize": 1000,
    "prefetchCount": 1000,
    "batchCheckpointFrequency": 1
  },
  "tracing": {
    "fileLoggingMode": "always"
  }
}
info: Host.Startup[0]
      Reading host configuration file 'm:\~\jira\azure-webjobs-sdk-script\sample\host.json'
info: Host.Startup[0]
      Host configuration file read:
      {
        "functionTimeout": "00:05:00",
        "http": {
          "routePrefix": "api",
          "maxConcurrentRequests": 5,
          "maxOutstandingRequests": 30
        },
        "watchDirectories": [
          "Shared"
        ],
        "functions": [
          "TimerTrigger-CSharp",
          "HttpTrigger-CSharp"
        ],
        "queues": {
          "visibilityTimeout": "00:00:10"
        },
        "eventHub": {
          "maxBatchSize": 1000,
          "prefetchCount": 1000,
          "batchCheckpointFrequency": 1
        },
        "tracing": {
          "fileLoggingMode": "always"
        }
      }
A function whitelist has been specified, excluding all but the following functions: [TimerTrigger-CSharp, HttpTrigger-CSharp]
Loading custom extension 'SampleExtension'
Loaded custom extension: SampleExtensionConfig from 'M:\~\jira\azure-webjobs-sdk-script\src\WebJobs.Script.Host\bin\Debug\netcoreapp2.0\Sample.Extension.dll'
info: Host.Startup[0]
      Loaded custom extension: SampleExtensionConfig from 'M:\~\jira\azure-webjobs-sdk-script\src\WebJobs.Script.Host\bin\Debug\netcoreapp2.0\Sample.Extension.dll'
Assert Failure
Expression: [Recursive resource lookup bug]
Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic
Stack Trace:
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.Threading.Tasks.TaskCanceledException..ctor(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__71.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetCanceled(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1.<>c__DisplayClass18_0.<CompleteCore>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I step through in debug and found where it crashed CSharpCompilation.cs 
```csharp
 public async Task<Assembly> EmitAsync(CancellationToken cancellationToken)
        {
            try
            {
                using (var assemblyStream = new MemoryStream())
                using (var pdbStream = new MemoryStream())
                {
                    var compilationWithAnalyzers = _compilation.WithAnalyzers(GetAnalyzers());
                    var diagnostics = await compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync(); <<< on this line crash is happening
```
I found fix bug 'recursive resource lookup bug' https://github.com/dotnet/corefx/issues/23608

**Comment by SenyaMur** [comment]
I update : 
1. .NET Core to 2.0.3 (https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.3.md)
2. VS 2017 to 15.4.4
3. Packages in WebJobs.Script\WebJobs.Script.csproj:
```
      <PackageReference Include="FSharp.Core" Version="4.2.3" />
    <PackageReference Include="Google.Protobuf" Version="3.4.1" />
    <PackageReference Include="Grpc.Core" Version="1.7.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.WebApiCompatShim" Version="2.0.1">
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="2.4.0" />
    <PackageReference Include="Microsoft.FSharp.Compiler" Version="4.2.0-rtm-171104-0" />
    <PackageReference Include="NuGet.Frameworks" Version="4.4.0" />
    <PackageReference Include="NuGet.LibraryModel" Version="4.4.0" />
    <PackageReference Include="NuGet.ProjectModel" Version="4.4.0" />
    <PackageReference Include="NuGet.Versioning" Version="4.4.0" />
```
and problem has gone

**Comment by paulbatum** [comment]
This is a .NET core bug fixed in .NET Core 2.0.3.
https://github.com/dotnet/corefx/issues/22586
