### ISSUE TITLE
OutOfMemory Exception with ILogger on V2 runtime

### ISSUE THREAD

**Issue by dersia** [Azure/azure-functions-host#2167]
My function is loading some assemblies and executes just well, but after some more execution calls I'm getting OutOfMemory-Exceptions during ILogger.AddConsole, which seems to be called by the runtime.

#### Investigative information

- Timestamp: 2017-11-28T19:36:11.166 
- Function App version: beta
- Function App name: dhub-imports-readmodel-service-ci
- Function name(s) (as appropriate): readmodeljob
- Invocation ID: e7ba24f9-d9f2-46c1-a187-fdca620bfaf4
- Region: eastus
```
2017-11-28T19:36:11.166 Function started (Id=e7ba24f9-d9f2-46c1-a187-fdca620bfaf4)
2017-11-28T19:36:11.200 System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(Object parameter)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions)
   at System.Threading.Tasks.TaskFactory.StartNew(Action`1 action, Object state, TaskCreationOptions creationOptions)
   at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor..ctor()
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider..ctor(Func`3 filter, Boolean includeScopes)
   at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggerFactory factory, Boolean includeScopes)
   at Submission#0.<Run>d__1.MoveNext() in D:\home\site\wwwroot\readmodeljob\run.csx:line 41
2017-11-28T19:36:11.200 Function completed (Success, Id=e7ba24f9-d9f2-46c1-a187-fdca620bfaf4, Duration=34ms)
```

**Comment by andycmaj** [comment]
seeing someting very similar in AWS actually:

```
"errorMessage": "An exception was thrown by a TaskScheduler.",
  "stackTrace": [
    "at System.Threading.Tasks.Task.ScheduleAndStart%28Boolean needsProtection%29",
    "at System.Threading.Tasks.Task.InternalStartNew%28Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions%29",
    "at System.Threading.Tasks.TaskFactory.StartNew%28Action`1 action, Object state, TaskCreationOptions creationOptions%29",
    "at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor..ctor%28%29",
    "at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider..ctor%28IConsoleLoggerSettings settings%29",
    "at TheChunnel.ServiceCommon.Modules.LoggingModule.RegisterServices%28Container container%29 in /channels/TheChunnel/src/TheChunnel.ServiceCommon/Modules/LoggingModule.cs:line 36",
    "at ImsHealth.Patterns.SimpleInjector.AbstractConsoleApplicationContext..ctor%28Lifestyle defaultLifestyle, ScopedLifestyle scopedLifeStyle, IModule[] modules%29",
    "at ImsHealth.Patterns.SimpleInjector.ConsoleApplicationContext..ctor%28Lifestyle defaultLifestyle, IModule[] modules%29",
    "at TheChunnel.ActivityService.LambdaEntrypoint.LambdaHandler%28LambdaActivityInput input, ILambdaContext lambdaContext%29 in /channels/TheChunnel/src/TheChunnel.ActivityService/LambdaEntrypoint.cs:line 45",
    "at lambda_method%28Closure , Stream , Stream , LambdaContextInternal %29"
  ],
  "cause":   {
    "errorType": "OutOfMemoryException",
    "errorMessage": "Exception of type %27System.OutOfMemoryException%27 was thrown.",
    "stackTrace": [
      "at System.Threading.Thread.StartInternal%28StackCrawlMark& stackMark%29",
      "at System.Threading.Thread.Start%28Object parameter%29",
      "at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask%28Task task%29",
      "at System.Threading.Tasks.Task.ScheduleAndStart%28Boolean needsProtection%29"
    ]
  }
```

**Comment by i02coroj** [comment]
Hi!
Getting exactly this same issue.
I see this thread last update is from last year. Any update?

**Comment by paulbatum** [comment]
It looks like I failed to follow up on this very old issue, sorry.

Our general advice for dealing with out of memory exceptions is to capture memory dumps and analyze the memory usage of your application. This blog post has an overview of the process for web apps, but the same steps would work for a function app too:
https://blogs.msdn.microsoft.com/jpsanders/2017/02/02/how-to-get-a-full-memory-dump-in-azure-app-services/

Keep in mind that function apps in the consumption plan are limited to 1.5GB (see the resource consumption section of https://azure.microsoft.com/en-us/pricing/details/functions/)

I'm going to close this issue. If after looking at memory dumps as I advised above you believe your function app is encountering out of memory exceptions in error, (i.e. you believe the app should be staying under the 1.5GB limit), then please file a new issue, and fill out the issue template so that we can investigate.
