### ISSUE TITLE
Optimize file system access when in ZIP mode

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2230]
Run-From-Zip feature: https://github.com/Azure/app-service-announcements/issues/84

If the WEBSITE_USE_ZIP environment variable is set, we need to avoid unnecessary file system access. For example, do not attempt to perform any write operations to the contents of wwwroot, as these will fail. Looks like we do this for hostingstart.html and for host.json. See below for an example stacktrace of this.

We need to look carefully at all file access operations and review whether they can be avoided with ZIP enabled.

Write failure stacktrace:
```
System.UnauthorizedAccessException : Access to the path 'D:\home\site\wwwroot\host.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode,String maybeFullPath)
   at System.IO.FileStream.Init(String path,FileMode mode,FileAccess access,Int32 rights,Boolean useRights,FileShare share,Int32 bufferSize,FileOptions options,SECURITY_ATTRIBUTES secAttrs,String msgPath,Boolean bFromProxy,Boolean useLongPath,Boolean checkHost)
   at System.IO.FileStream..ctor(String path,FileMode mode,FileAccess access,FileShare share,Int32 bufferSize,FileOptions options,String msgPath,Boolean bFromProxy,Boolean useLongPath,Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path,Boolean append,Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path,Boolean append,Encoding encoding,Int32 bufferSize,Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path,String contents,Encoding encoding,Boolean checkHost)
   at System.IO.File.WriteAllText(String path,String contents)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 288
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment,IScriptEventManager eventManager,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager,ProxyClientExecutor proxyClient) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 806
```

**Comment by paulbatum** [comment]
We'll probably only focus on doing zip optimizations for v2, so labelling appropriately.
