### ISSUE TITLE
[V2] Non-existent blob crashes the runtime

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-functions-host#2236]
Hi, everyone!
Below is my `function.json` - essentially, I have an HTTP-triggered function that based on the query string `blobname` gets an `in` blob binding.

If the blob exists, everything is fine - if it doesn't, the entire runtime crashes, exception at the bottom.
Is this supposed to behave this way?

(Unrelated to the issue here: for blob trigger I get all blob metadata; for in blob binding I only get the content and the name - is this by design?)

Thanks,
Radu M

```json
{
    "entryPoint" : "Run",
    "bindings": [
      {
        "authLevel": "anonymous",
        "type": "httpTrigger",
        "direction": "in",
        "name": "req"
      },
      {
        "name": "myBlob",
        "type": "blob",
        "direction": "in",
        "path": "demo/{blobname}",
        "connection": "AzureWebJobsStorage"
    }
    ],
    "disabled": false
  }
```

Here is the exception:

```
info: Host.Executor[0]
      => RequestId:0HLA4KAER7EBM:00000002 RequestPath:/api/HttpTriggerBlobBindingGo => System.Collections.Generic.Dictionary`2[System.String,System.Object] => System.Collections.Generic.Dictionary`2[System.String,System.Object]
      Function started (Id=ade582ec-708b-4bb0-bd0e-bdca20332009)
Executing 'Functions.HttpTriggerBlobBindingGo' (Reason='This function was programmatically called via the host APIs.', Id=ade582ec-708b-4bb0-bd0e-bdca20332009)
fail: Host.Executor[0]
      => RequestId:0HLA4KAER7EBM:00000002 RequestPath:/api/HttpTriggerBlobBindingGo => System.Collections.Generic.Dictionary`2[System.String,System.Object] => System.Collections.Generic.Dictionary`2[System.String,System.Object]
      Exception while executing function: Functions.HttpTriggerBlobBindingGo. System.Runtime.Extensions: Value cannot be null.
      Parameter name: stream.
Exception while executing function: Functions.HttpTriggerBlobBindingGo
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.HttpTriggerBlobBindingGo ---> System.ArgumentNullException : Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream,Encoding encoding,Boolean detectEncodingFromByteOrderMarks,Int32 bufferSize,Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.ConvertStreamToValue(Stream stream,DataType dataType,Object& converted) at /runtime/src/WebJobs.Script/Binding/FunctionBinding.cs :313
   at async Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.BindStreamAsync(BindingContext context,FileAccess access) at /runtime/src/WebJobs.Script/Binding/FunctionBinding.cs : 245
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Binding.ExtensionBinding.BindAsync(BindingContext context) at /runtime/src/WebJobs.Script/Binding/ExtensionBinding.cs : 63
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker.<>c__DisplayClass7_0.<BindInputsAsync>b__1(??) at /runtime/src/WebJobs.Script/Description/Rpc/WorkerLanguageInvoker.cs : 93
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker.BindInputsAsync(Binder binder) at /runtime/src/WebJobs.Script/Description/Rpc/WorkerLanguageInvoker.cs : 97
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at /runtime/src/WebJobs.Script/Description/Rpc/WorkerLanguageInvoker.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at /runtime/src/WebJobs.Script/Description/FunctionInvokerBase.cs : 90
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) at /runtime/src/WebJobs.Script/Description/FunctionGenerator.cs : 225
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 63
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 583
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 534
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 477
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 264
   End of inner exception
```

**Comment by paulbatum** [comment]
@radu-matei what language are you using here?

**Comment by radu-matei** [comment]
@paulbatum - I encountered this while building the Golang worker - but I don't really think it is a language worker related issue, as the runtime crashes and it doesn't send any message to the worker.

**Comment by paulbatum** [comment]
@radu-matei ok makes sense. Definitely looks like a bug.
