### ISSUE TITLE
System.UnauthorizedAccessException when using FSharp.Data

### ISSUE THREAD

**Issue by 2moveit** [Azure/azure-functions-host#2260]
#### Investigative information

- Timestamp: 2017-12-19T23:32:29.551
- Function App version (1.0 or 2.0-beta):  1.0.11388.0
- Invocation ID: 233a8f97-34c9-4eb6-a333-7e3d726c7bac
- Region: West Europe

#### Repro steps

The functions gets a tweet via Logic App. The tweet is parsed to find the URL. The URL is used to Load a HtmlDocument to parse the HTML and get a value of a tag.
I use FSharp.Data for it.
If I use this code I get an UnauthorizedAccessException

    let getProduct (url:string) = async{
        let! doc = HtmlDocument.AsyncLoad(url) // this throws an UnauthorizedAccessException 
        return doc.Descendants["div"]
            |> Seq.filter (fun a -> 
                a.TryGetAttribute("class")
                |> Option.map (fun cls -> cls.Value()) = Some "produktbezeichnung_fett")
            |> Seq.map (fun l -> l.InnerText()) 
            |> Seq.head
    }

#### Expected behavior

Execution without Errors 

#### Actual behavior

    2017-12-19T23:32:29.318 F# HTTP trigger function processed a request.

    2017-12-19T23:32:29.504 Exception while executing function: Functions.XYZ. mscorlib: Exception has been thrown by the target of an invocation. mscorlib: Access to the path 'D:\Program Files (x86)\SiteExtensions\Functions\1.0.11388' is denied.

    2017-12-19T23:32:29.551 Function completed (Failure, Id=233a8f97-34c9-4eb6-a333-7e3d726c7bac, Duration=698ms)

---

F# HTTP trigger function processed a request.

    Exception while executing function: Functions.LMWarnungVerbessern

    Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.LMWarnungVerbessern ---> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException : Access to the path 'D:\Program Files (x86)\SiteExtensions\Functions\1.0.11388' is denied.

    at System.IO.__Error.WinIOError(Int32 errorCode,String maybeFullPath)

    at System.IO.FileStream.Init(String path,FileMode mode,FileAccess access,Int32 rights,Boolean useRights,FileShare share,Int32 bufferSize,FileOptions options,SECURITY_ATTRIBUTES secAttrs,String msgPath,Boolean bFromProxy,Boolean useLongPath,Boolean checkHost)

    at System.IO.FileStream..ctor(String path,FileMode mode,FileAccess access,FileShare share)

    at FSharp.Data.Runtime.IO.asyncRead@237-5.Invoke(Unit unitVar) at C:\Git\FSharp.Data\src\CommonRuntime\IO.fs : 237

    at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)

    at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)

    at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token,FSharpAsync`1 computation,FSharpOption`1 timeout)

    at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation,FSharpOption`1 timeout,FSharpOption`1 cancellationToken) 

    End of inner exception

    at System.RuntimeMethodHandle.InvokeMethod(Object target,Object[] arguments,Signature sig,Boolean constructor)

    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj,Object[] parameters,Object[] arguments)

    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj,BindingFlags invokeAttr,Binder binder,Object[] parameters,CultureInfo culture)

    at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.InvokeCore(Object[] parameters,Function… 
 
  
#### Known workarounds

If I use WebClient.DownloadString and then HtmlDocument.Parse it works:

    let getProduct (url:string) = async{
        //let! doc = HtmlDocument.AsyncLoad(url) // this throws an UnauthorizedAccessException     
        let wc = new WebClient()
        let lines = wc.DownloadString url
        let doc = HtmlDocument.Parse lines
        return doc.Descendants["div"]
            |> Seq.filter (fun a -> 
                a.TryGetAttribute("class")
                |> Option.map (fun cls -> cls.Value()) = Some "produktbezeichnung_fett")
            |> Seq.map (fun l -> l.InnerText()) 
            |> Seq.head 
    }

#### Related information 
https://stackoverflow.com/questions/47896854/why-do-i-get-an-exception-in-azure-functions-where-mscorlib-says-access-denied

**Comment by christopheranderson** [comment]
That's really weird because it just calls `HtmlParser.ParseDocument` under the covers. https://github.com/fsharp/FSharp.Data/blob/master/src/Html/HtmlParser.fs#L871-871

That's different from your `Parse` call which uses `ParseFragment`. 
https://github.com/fsharp/FSharp.Data/blob/master/src/Html/HtmlParser.fs#L890

Given that it works locally, it's likely due to file permissions because you don't have write access to the 'D:\Program Files (x86)\SiteExtensions\Functions\1.0.11388' location. Potentially something that F# is calling. When I look through the call stack, I see the line where FSharp.Data IO asyncRead is throwing an exception. 

https://github.com/fsharp/FSharp.Data/blob/master/src/CommonRuntime/IO.fs#L213

If you look there, it tries to call web requests, or it uses File System if it can't resolve your URI.

So what `url` are you using? It falls back to using File system when it can't parse it with the URL parsing library, so my best guess is that the url isn't resolving. You can test that by checking what `uriResolver.Resolve uri` returns for your url.

**Comment by 2moveit** [comment]
Thanks @christopheranderson I will have a look at it. Sounds strange as it seems to be a valid url. I just parse the url from a tweet like this one https://mobile.twitter.com/LMWarnung/status/951979608513110017?p=v  and download the website to find some more information. I will check if my regex and url are correct or if the might run into that case.  I wasn't aware that there might be a IO access...

**Comment by paulbatum** [comment]
Closing this issue due to age, please comment and I can reopen if you think there is still a problem here.
