### ISSUE TITLE
Add support for 'ScheduleType' on attribute 'TimerTriggerAttribute'

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2388]
_From @eloekset on October 25, 2017 13:34_

# Tooling Information

- **Visual Studio:** 15.4.1
- **Azure Functions SDK:** 1.0.6
- **VSTS Visual Studio Version:** Latest
- **VSTS Visual Studio Build Task Version:** 1.*

# Issue Description
I want to schedule a task based on the outcome of the previous run. I'm accessing an API from an Azure Function, and that API fails if I try to send multiple requests at the same time. To overcome this, I've written a custom `TimerSchedule` to slow down the Azure Function when it fails.

This is the Run method signature of my function:
```
Run([TimerTrigger(typeof(CustomTriggers.CustomerInfoSyncIntervalTrigger))]TimerInfo myTimer, TraceWriter log)
```

When debugging the function locally in Visual Studio, it runs and the `GetNextOccurrence` method in my custom trigger gets executed. But when I build the project in VSTS, I get a build error that says:

```
2017-10-25T12:59:49.2234014Z ##[error]C:\Users\buildguest\.nuget\packages\microsoft.net.sdk.functions\1.0.6\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(32,5): Error : System.NotImplementedException: Property 'ScheduleType' on attribute 'TimerTriggerAttribute' is not supported in Azure Functions.
   at MakeFunctionJson.AttributeExtensions.CheckIfPropertyIsSupported(String attributeName, PropertyInfo property)
   at MakeFunctionJson.AttributeExtensions.ToJObject(Attribute attribute)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodInfo method, String assemblyPath)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()
Error generating functions metadata
```

This check looks like it's intended on build, but still it runs locally when debugging in Visual Studio. 

1. Could it be a miss that this check breaks the build?

2. ..if not, could custom TimerTriggers be supported by Azure Functions in a future version?

_Copied from original issue: Azure/azure-functions-vs-build-sdk#130_

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1577
