### ISSUE TITLE
Azure function with optional paramter in route path

### ISSUE THREAD

**Issue by TulyOpt** [Azure/azure-functions-host#2419]
Hello,

I am trying an azure function with an optional parameter (ie **Route = "underlying/{underlying?}"** ) and when debugging locally with visual studio (15.5.4, webjobs tools v1.0.0 vers 15.0.40108) 

However, i have the following exception : 

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: ts ---> System.InvalidOperationException: Exception binding parameter 'underlying' ---> System.InvalidOperationException: Binding data does not contain expected value 'underlying'.
   at Microsoft.Azure.WebJobs.Host.Bindings.Data.ClassDataBinding1.BindAsync(BindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Data\ClassDataBinding.cs:line 62
   at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding1.<BindCoreAsync>d__8.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 98

Provide the steps required to reproduce the problem:

1. create an azure function with the following signature : 
```csharp
 [FunctionName("timeseries")]
        public static HttpResponseMessage Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "underlying/{underlying?}")]HttpRequest req, String underlying, TraceWriter log)
```
2. launch azure function locally with visual studio
3. request : http://localhost:7071/api/undelrying/ftse=> it works
3. request : http://localhost:7071/api/undelrying => it should work ( underlying is optional) but there is an exception

Thank you in advance.

**Comment by TulyOpt** [comment]
I move this issue to the correct repo

**Comment by alrod** [comment]
There is a bug in preview V2 Preview (.NET Core), scenario works fine in  V1 (.NET Framework). 

@TulyOpt, you can create your function using V1 (.NET Framework) to avoid this bug.

**Comment by TulyOpt** [comment]
Hi,
thanks @alrod for your quick response. However I am targeting the .net core framework so I will wait for a bug fix. Do you know when it will be released ? Thanks

**Comment by paulbatum** [comment]
@alrod you said this is a v2 bug, is this tracked somewhere? otherwise we need more details.

**Comment by alrod** [comment]
I changed original "Active question" to "Bug"/"2.0". So this item itself is the bug.

**Comment by paulbatum** [comment]
@alrod  OK thanks

@TulyOpt I don't have an ETA for you right now, but what I can say is that we have some pretty significant work items for V2 that are going to take priority over this, so the timeframe is probably something like a couple of months

**Comment by swgriffith** [comment]
Any update here? I'm hitting this issue right now in V2.

**Comment by paulbatum** [comment]
No updates at this time.

**Comment by swettstein** [comment]
any update on this? i'm hitting this issue now too
