### ISSUE TITLE
Unable to convert trigger to CosmosDBTrigger.

### ISSUE THREAD

**Issue by alohaninja** [Azure/azure-functions-host#2435]
#### Investigative information
Unable to use .NET for new cosmos triggers (`Exception binding parameter 'documents'`). Modifying existing ones is also breaking with this same error when updating assemblies. Javscript cosmos triggers are working just fine. 

[First reported on SO about 9 hours ago...](https://stackoverflow.com/q/48862833/175679)

#### Repro steps
Create new cosmos db c# trigger from the portal. 

#### Expected behavior

Cosmos trigger fires as expected and bindings work without issue

#### Actual behavior

```
Exception while executing function: Functions.onCollectionChanged 
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.onCollectionChanged ---> System.InvalidOperationException : Exception binding parameter 'documents' ---> System.InvalidOperationException : Unable to convert trigger to CosmosDBTrigger.
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.CosmosDBTriggerBinding.BindAsync(Object value,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```

**Comment by alohaninja** [comment]
You cannot trigger (_aka RUN_) a new cosmos trigger from the portal directly or you receive this error. You just need to update a document in the monitored collection and the trigger will fire as expected.

**Comment by psfinaki** [comment]
@alohaninja Confirmed, works. Thank you! (just wanted to say thanks somewhere, I am the guy who asked the SO question)

**Comment by jimwilliam** [comment]
i'm not running a trigger function from the portal but getting it when items arrive and the trigger reading off of the change feed fires. I've not seen that before.
