### ISSUE TITLE
Flaky Test: Script Host Manager

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#2458]
The test `Microsoft.Azure.WebJobs.Script.Tests.ScriptHostManagerTests.IsHostHealthy_ReturnsExpectedResult` succeeds locally but fails in AppVeyor for v1.x

**Error message**
Moq.MockException : ScriptSettingsManager.IsZipDeployment invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.

**Error stack trace**
 at Moq.ExtractProxyCall.HandleIntercept(ICallContext invocation, InterceptorContext ctx, CurrentInterceptContext localctx)
   at Moq.Interceptor.Intercept(ICallContext invocation)
   at Moq.Proxy.CastleProxyFactory.Interceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ScriptSettingsManagerProxy.get_IsZipDeployment()
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager..ctor(ScriptHostConfiguration config, ScriptSettingsManager settingsManager, IScriptHostFactory scriptHostFactory, IScriptEventManager eventManager, IScriptHostEnvironment environment, HostPerformanceManager hostPerformanceManager) in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs:line 85
   at Castle.Proxies.ScriptHostManagerProxy..ctor(IInterceptor[] , ScriptHostConfiguration , ScriptSettingsManager , IScriptHostFactory , IScriptEventManager , IScriptHostEnvironment , HostPerformanceManager )

**Comment by mhoeger** [comment]
@fabiocav FYI

**Comment by fabiocav** [comment]
Thanks @mhoeger!

**Comment by mathewc** [comment]
Yes I checked in a fix for this earlier this morning and the build is green.
