### ISSUE TITLE
host.json documentation says that null is the default for functionTimeout  but setting it to null causes a ArgumentNullException

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2468]
The documentation for [host.json](https://github.com/Azure/azure-functions-host/wiki/host.json) says that thr default value for `functionTimeout` is null. However this host.json 

```json
{
    "functionTimeout": null
}
```

causes 

```
System.ArgumentNullException : String reference not set to an instance of a String.
Parameter name: input
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(ParseFailureKind failure,String failureMessageID,Object failureMessageFormatArgument,String failureArgumentName)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(String input,TimeSpanStandardStyles style,IFormatProvider formatProvider,TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.Parse(String input,IFormatProvider formatProvider)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ApplyConfiguration(JObject config,ScriptHostConfiguration scriptConfig) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 1476
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 376
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 181
```

**Comment by ahmelsayed** [comment]
reported by a user on [the forums](https://social.msdn.microsoft.com/Forums/en-US/8c68ba0f-80a8-4f1c-b7c3-a86d061c339f/mscorlib-string-reference-not-set-to-an-instance-of-a-string-parameter-name-input?forum=AzureFunctions)

**Comment by mathewc** [comment]
We should look at this setting and other settings and fix them all together.

**Comment by Dalmirog** [comment]
The documentation still says the same https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout

Should `"functionTimeout": null` work or not? It's currently giving me `String reference not set to an instance of a String. Parameter name: input`
