### ISSUE TITLE
NullReferenceException at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.FunctionInvocationFilterInvoker.InvokeAsync(Object instance,Object[] arguments)

### ISSUE THREAD

**Issue by JimiSmith** [Azure/azure-functions-host#2470]
#### Investigative information

Please provide the following:

- Timestamp: 27-02-2018 7:36 GMT
- Function App version (1.0 or 2.0-beta): 1.0
- Invocation ID: f0639e62-2d56-4546-8969-9f2c12fc899c
- Region: west-europe

#### Related information

We see this exception when sending a lot of messages through the function. In this case the db was pegged at 100% DTU usage so that very likely caused the error. However the stack trace is not useful and doesn't contain any of our code. Which makes this very difficult to diagnose. This isn't a major issue as the function normally executes correctly after a few attempts or if we scale the database but I would like to be able to get better stacktraces

CSharp Function
Using ServiceBus bindings

<details>
<summary>StackTrace from kudu</summary>

```
Exception while executing function: QueueChatPushNotifications
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: QueueChatPushNotifications ---> System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.FunctionInvocationFilterInvoker.InvokeAsync(Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```
</details>

<details>
<summary>Stack Trace from App Insights</summary>

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: QueueChatPushNotifications ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.FunctionInvocationFilterInvoker.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__16.MoveNext()
--- End of inner exception stack trace ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__13.MoveNext()
```
</details>

**Comment by mathewc** [comment]
We'll investigate this. Were you using the Invocation Filters feature here?

**Comment by JimiSmith** [comment]
There aren't any Invocation Filters but we are using a config provider and custom bindings to do dependency injection similar to what is described in this blog post https://blog.wille-zone.de/post/azure-functions-proper-dependency-injection/

**Comment by JimiSmith** [comment]
I can spend some time and create a sample project if needed

**Comment by markogrady** [comment]
I had pretty much the same issue. I realised I wasnt Scoping the functions themselves.

Ie  if you class is 

```
public class Functions 
{
public async Task ProcessQueueMessage([QueueTrigger("testqueue")] string message)
{
//dostuff

}
}
```

in your service collection setup then you must add the following line

`services.AddScoped<Functions, Functions>();`

**Comment by mathewc** [comment]
Closing this since I haven't heard back from @JimiSmith. @JimiSmith - if you're still having issues, please provide a repro.

**Comment by JimiSmith** [comment]
@mathewc Apologies for the delay. I've attached a sample project. I was mistaken in the earlier comment when I said we weren't using invocation features - it turns out they are used
[2470Repro.zip](https://github.com/Azure/azure-functions-host/files/2039659/2470Repro.zip)

**Comment by JimiSmith** [comment]
This sample project doesn't have the same stack trace as the one I pasted earlier but it still doesn't contain any code from the project.

**Comment by PankajRawat333** [comment]
I'm getting same error with HTTP Azure function V1. [here is my code](https://github.com/PankajRawat333/FunctionAppWithAOPLogging)
