### ISSUE TITLE
Issue with running Azure Function 2.0.11651.0 (latest beta)

### ISSUE THREAD

**Issue by vsadams** [Azure/azure-functions-host#2649]
I have been working through upgrading my functions to the latest version of the beta.  I first had to get around mismatched versions in Newtonsoft and then with Application Insights. I have all that working. Now, the latest issue I cant get around is the following...
The function runtime is throwing
```
Warning: Only got partial types from assembly: XXX.XXX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
```
Then in turn calling the below in my own code is giving a similar error.
```
Assembly.GetExecutingAssembly().GetTypes()
```

 I was able to track down the specific failing reference by using a type loader akin to the one in the function runtime code base
```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;

namespace XXX.XXX.Core.DependencyInjection
{
	static class TypeLoader
	{
		public static IEnumerable<Type> GetTypes()
		{
			Type[] types = null;
			var assembly = typeof(TypeLoader).Assembly;
			try
			{
				types = assembly.GetTypes();
			}
			catch (ReflectionTypeLoadException ex)
			{
				Trace.WriteLine($"Warning: Only got partial types from assembly: {assembly.FullName}");
				if (ex?.LoaderExceptions != null)
				{
					foreach (var loaderException in ex.LoaderExceptions)
					{
						Trace.WriteLine($"Exception message: Loader Exception: {loaderException}");
					}
				}

				Trace.WriteLine("Exception message: {0}", ex.ToString());

				// In case of a type load exception, at least get the types that did succeed in loading
				types = ex.Types;
			}
			catch (Exception ex)
			{
				Trace.WriteLine($"Warning: Failed to get types from assembly: {assembly.FullName}");
				Trace.WriteLine($"Exception message: {ex}");
			}

			return types.Where(t => t != null);
		}
	}
}

```

I could then see that it was trying to load 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11.  
```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)File name: 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)   at System.Reflection.Assembly.LoadFrom(String assemblyFile)   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

By eating the error above and just returning the found types I was able to get the functions to at least load. However whenever they would attempt to run, they would tell me that the function.json was  missing (which was not the case). 

I am able to run my functions locally. Its just when I deploy them to azure that I have an issue. Unfortunately, I can not just downgrade to the old version of the runtime because I am using the durable functions heavily.

At this point, I am at a loss and do not know what else to do. Any help would be appreciated.

**Comment by vsadams** [comment]
Ended up getting around this by downgrading and removing various packages.
