### ISSUE TITLE
NullReferenceException in execution pipeline when function doesn't have [FunctionName] attribute

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-host#2785]
#### Investigative information
* Function app v1.x running locally

#### Repro steps

1. Install [Durable Functions extension](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-install)
2. To save time, create a basic orchestration template
3. Remove the `[FunctionName]` attribute on the `SayHello` activity
4. Run the orchestration

#### Expected behavior

I was expecting one of two possible options:
1. The durable extension throws because the modified `SayHello` activity function is not found (meaning, it's not indexed).
2. The function call succeeds, just like it would with WebJobs (which doesn't required `[FunctionName]`.

#### Actual behavior

The function shows as indexed in the CLI output, but when our extension tries to invoke it, the invoker fails with the following exception;
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Azure.WebJobs.Host
  StackTrace:
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.NotifyCompleteAsync(FunctionInstanceLogEntry intanceLogEntry, IDictionary`2 arguments, ExceptionDispatchInfo exceptionInfo)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.<TryExecuteAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.<RunAsync>d__5.MoveNext() in C:\Code\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 60
```

#### Known workarounds
Add the `[FunctionName]` attribute. The problem, however, is that it's not at all obvious that this is the cause of the null-ref.

#### Related information 
Reported initially in the Durable Functions repo: https://github.com/Azure/azure-functions-durable-extension/issues/169

**Comment by pragnagopa** [comment]
Needs investigation to figure out if we can throw a better error instead of Null ref on calling a function that does not have [FunctionName] attribute

**Comment by paulbatum** [comment]
@cgillum You noted this happens for V1 - does it happen for V2 as well?

**Comment by cgillum** [comment]
@paulbatum Yes, in fact if I run in v2 VS automatically pulls in the source code, so I was able to investigate it a bit further on my own.  Here is the callstack:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Azure.WebJobs.Host
  StackTrace:
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.NotifyCompleteAsync(FunctionInstanceLogEntry intanceLogEntry, IDictionary`2 arguments, ExceptionDispatchInfo exceptionInfo) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 706
```

And here is the offending line of code:

```csharp
intanceLogEntry.LiveTimer.Stop();
```

`instanceLogEntry` is null.

BTW, I apologize for code-reviewing code that I'm not actually familiar with, but these kinds of null-refs can often be caught by the compiler if one refrains from initializing local variables to `null`.

*(From TryExecuteAsync.cs - `NotifyPreBindAsync` throws earlier in the failure chain because a function.json is not found, thus `instanceLogEntry` is never assigned)*

```csharp
FunctionInstanceLogEntry instanceLogEntry = null;

using (_resultsLogger?.BeginFunctionScope(functionInstance, HostOutputMessage.HostInstanceId))
using (parameterHelper)
{
    try
    {
        instanceLogEntry = await NotifyPreBindAsync(functionStartedMessage);
```

**Comment by davidebbo** [comment]
Clearing backlog to get it on the radar as it came up in a support case.

**Comment by mathewc** [comment]
I've been seeing this come up as well and logged https://github.com/Azure/azure-webjobs-sdk/issues/1741 recently. Not sure why my issue was put in backlog - we need to fix this.

**Comment by paulbatum** [comment]
@mathewc  it was put in backlog because I asked you "this sprint, next sprint, or later?" and you told me "later" :)
