### ISSUE TITLE
Microsoft.Azure.KeyVault (Microsoft.Azure.Services.AppAuthentication) issue on functions runtime 2.0.11651-alpha

### ISSUE THREAD

**Issue by Bubeee** [Azure/azure-functions-host#2852]
Hi, I'm developing Azure Functions v2 in Visual Studio with latest tools installed. (.NET Core)

After an attempt to apply Azure KeyVault secrets to my functions (like described here https://medium.com/statuscode/getting-key-vault-secrets-in-azure-functions-37620fd20a0b) I've faced with issue on startup of function app in Azure.
Kudu logs dump says the following:

`Hosting environment: Production
Content root path: D:\Program Files (x86)\SiteExtensions\Functions\2.0.11651-alpha
Now listening on: http://localhost:12938
Warning: Only got partial types from assembly: MiddleWare.External.Functions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
`

#### Investigative information

- Timestamp: 2018-05-14 15:31:55.862
- Function App version (1.0 or 2.0-beta): v2.0-beta
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

1. Azure Functions working, retrieving secrets from the Key Vault instance on demand, correctly authenticating in Azure AD.

#### Actual behavior

Azure functions not starting, manual triggering causes 400 error. 
Kudu log dump provided above.

#### Known workarounds

Implementing custom Token Provider like on the screen below resolves the issue.
![image](https://user-images.githubusercontent.com/5691429/40048826-e4368154-583b-11e8-992f-fc75420cc0f7.png)

So I think the issue is in the AppAuthentication package. 
I've debugged functions remotely in visual studio, but unfortunately it takes a lot of time to attach, and filter all not related exceptions during the debugging of actual issue with AzureServiceTokenProvider.

As soon as I got rid of the Microsoft.Azure.Services.AppAuthentication dependency, functions are able to start.

Now, switching to v1 version and will implement it there.
So, not waiting for a quick answer, just want to recollect the thoughts and maybe I've missed something.

**Comment by Bubeee** [comment]
Migrated to Functions v1 and faced with the same issue.

`2018-05-15T14:08:25  Welcome, you are now connected to log-streaming service.
2018-05-15T14:08:26.569 [Info] Function started (Id=10e4932a-705f-4879-bb00-db2a6857e3c7)
2018-05-15T14:08:26.585 [Info] C# Timer trigger function executed at: 5/15/2018 2:08:26 PM
2018-05-15T14:08:26.632 [Error] Function completed (Failure, Id=10e4932a-705f-4879-bb00-db2a6857e3c7, Duration=60ms)`

After applying this code:

![image](https://user-images.githubusercontent.com/5691429/40062131-2e67fb64-5863-11e8-972f-4a0b081e2ac7.png)

**Comment by paulbatum** [comment]
What can you tell us about the assembly `MiddleWare.External.Functions`? This error message about partial types is not familiar. Is there something unusual about this assembly?

**Comment by Bubeee** [comment]
@paulbatum hi,
If talking about the first attempt with Functions v2, it's usual Functions project.

![image](https://user-images.githubusercontent.com/5691429/40167363-8a1721b2-59c9-11e8-9dab-5e54c270d7c2.png)
