### ISSUE TITLE
Don't start Grpc server when not needed

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2946]
My function app only contains a single C# function. However, in the logs I see lots of Grpc failures (I was doing a load test):

```
System.IO.IOException : Failed to bind port "127.0.0.1:0"
   at Grpc.Core.Server.CheckPortsBoundSuccessfully()
   at Grpc.Core.Server.Start()
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcServer.StartAsync() at C:\azure-webjobs-sdk-script\src\WebJobs.Script.Grpc\Server\GrpcServer.cs : 36
   at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeWorkers() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 716
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 305
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 196
```

We should only be starting up this server if it is needed (i.e. other languages are being used).

**Comment by davidebbo** [comment]
There are two slightly different things here:

1. the fact that we start it when not needed
1. the fact that we get an exception

Or are the two somehow connected?

**Comment by safihamid** [comment]
This is also affecting cold start. we should not start when they are not needed.

**Comment by mhoeger** [comment]
@pragnagopa - i'm going to wait to do this work until your [enforce single Language functions per function app](https://github.com/Azure/azure-functions-host/pull/3265) PR gets checked in. adding you to this thread for awareness/context on future questions i will likely ask you :)

**Comment by fabiocav** [comment]
We continue to see this, and it does have an impact on specialization. It would be good to prioritize this work.

**Comment by mathewc** [comment]
@pragnagopa / @mhoeger Can this be done now for GA?

**Comment by pragnagopa** [comment]
Yes. Logic for not starting Grpc server will be simpler after I merge the changes for enforcing single language. Discussed with @mhoeger  offline.
