### ISSUE TITLE
Azure Function

### ISSUE THREAD

**Issue by envoy-mcapodici** [Azure/azure-functions-host#2954]
#### Investigative information

- Timestamp: Current time is 23:33:27 UTC, Wednesday, 6 June 2018
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: bcs-live-preview
- Function name(s) (as appropriate): GeneratePreview
- Invocation ID: N/A
- Region: Australia East

#### Repro steps

Provide the steps required to reproduce the problem:

1. Monitor the queue that this function is consuming (generatepreview on bcsfiles)

#### Expected behavior

Queue is processed always

#### Actual behavior

Queue is not processed
Queue was processed yesterday but required a restart.

#### Known workarounds

A function restart seemed to fix this but only once.

#### Related information 

Other functions working OK for us

Function Sig:

`		[FunctionName("GeneratePreview"), Timeout("00:01:00")]
		public static async Task Run(
			[QueueTrigger("generatepreview", Connection = "AzureStorageConnectionString")] PreviewGenerationRequest request
			)
		{`

**Comment by envoy-mcapodici** [comment]
Function decided to kick off again without intervention just now. However I still would like to get some investigation as to why it get stuck. I've seen other issues here about this happening if the queue is too large. With just 5k items, I don't think that is unreasonable queue size.

**Comment by tohling** [comment]
@envoy-mcapodici , I checked our logs and it seems that there were a lot of runtime errors between 2018-06-06 20:33:46 UTC and 2018-06-06 23:40:50 UTC.  Could you check your Application Insights logs/Functions logs for those errors?

**Additional comments:**
1. Here's a sample stack trace from one of the errors,

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: GeneratePreview ---> WebSupergoo.ABCpdf11.Internal.PDFException : The read operation failed, see inner exception. ---> System.IO.IOException : The read operation failed, see inner exception. ---> System.Net.WebException : The request was aborted: The request was canceled.
   at System.Net.ConnectStream.Read(Byte[] buffer,Int32 offset,Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer,Int32 offset,Int32 count) 
   End of inner exception
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer,Int32 offset,Int32 count)
   at System.Net.Http.DelegatingStream.Read(Byte[] buffer,Int32 offset,Int32 count)
   at WebSupergoo.ABCpdf11.Internal.FileUtils.StreamToStream(Stream inSrc,Stream inDst,Int64 inLen,Int64 inMaxLen)
   at WebSupergoo.ABCpdf11.Internal.FileUtils.StreamToStream(Stream inSrc,Stream inDst)
   at WebSupergoo.ABCpdf9.XReadOptions.Read(Doc doc,Stream stream,ReadModuleType module)
   at WebSupergoo.ABCpdf9.XReadOptions.Read(Doc doc,Stream stream) 
   End of inner exception
   at WebSupergoo.ABCpdf9.XReadOptions.Read(Doc doc,Stream stream)
   at WebSupergoo.ABCpdf9.Doc.Read(Stream stream)
   at Buildaform.PreviewGeneration.AzureFunctions.Generation.ThumbnailGenerator.Generate(Stream pdfStream,Int32 width,Int32 height,Int32 page)
   at async Buildaform.PreviewGeneration.AzureFunctions.GeneratePreview.Run(PreviewGenerationRequest request)
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```

2. There are log entries `Message has reached MaxDequeueCount of 1. Moving message to queue 'generatepreview-poison'.` Kindly check the poison queue to see if some messages may have accumulated there.

**Comment by envoy-mcapodici** [comment]
@tohling 

Thanks. This is most likely because the blob urls supplied to the function have timed out (in terms of the security token) which is a symptom of the function being down for a period of time.

There is only 36 in the poison of 5k messages.

What I am thinking is, is there a way to scale up the processing speed for this function. When it IS running it can't keep up with demand. I have increased queues.batchsize to 32.

**Comment by envoy-mcapodici** [comment]
I have fixed it by entering the AzureStorageConnectionString as a setting as well as a connection string, as per https://github.com/Azure/azure-functions-host/issues/1240#issuecomment-337011076

If you have one or the other it doesn't work. I need the connection string both as a connection string and a setting to get it to consistently work.

I am guessing once is to do with processing and the other is to do with triggering?

**Comment by fabiocav** [comment]
@tohling does the scale controller expect this to be set as a connection string? For the runtime, this shouldn't matter and setting the app setting only should work.

**Comment by envoy-mcapodici** [comment]
@fabiocav - I just had a look at the code I am using, and we are explicitly asking for the connection string in the function:

`var storageAccount = CloudStorageAccount.Parse(ConfigurationManager.ConnectionStrings["AzureStorageConnectionString"].ConnectionString);`

so without that a setting alone may be good enough, I will try that at some point (don't have time today though).
