### ISSUE TITLE
Cannot enqueue data after PromiseNotToEnqueue

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#3145]
Still seeing this periodically in production. This issue will lead to general flakiness, so it would be good to find a fix for it.

```
Microsoft.Azure.WebJobs.Script.Description.CompilationServiceException : C# compilation service error: Cannot enqueue data after PromiseNotToEnqueue. ---> System.InvalidOperationException : Cannot enqueue data after PromiseNotToEnqueue.
   at Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1.EnqueueCore(TElement value)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol,Int32 methodOrdinal,ProcessedFieldInitializers& processedInitializers,SynthesizedSubmissionFields previousSubmissionFields,TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by mathewc** [comment]
Dupe of https://github.com/Azure/azure-functions-host/issues/999
