### ISSUE TITLE
Http request with content-type header application/json;charset='utf-8' fails

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3151]
Issue reported in a CRI.

Http request with content-type header application/json;charset='utf-8' fails in V1. Specifying content-type without single quotes works: Content-Type=application/json; charset=utf-8 

Note: Customer cannot change the headers as the requests are auto generated from devices
#### Repro steps

1) Create a Http Trigger Function.
2) Sent a Post Request using Postman with Content-Type using application/json;charset='utf-8' as the Content-Type

#### Expected behavior

Invocation succeeds

#### Actual behavior

Exception while executing function: Functions.send
　Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.send --->
　System.InvalidOperationException : Exception binding parameter 'req' --->
　System.InvalidOperationException : The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set. --->
　System.ArgumentException : ''utf-8'' is not a supported encoding name.
　For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
　Parameter name: name
   at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at System.Net.Http.HttpContent.<>c__DisplayClass13_0.<ReadAsStringAsync>b__0(Task task) 
   End of inner exception
   at async Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider.HttpTriggerBinding.GetRequestBindingDataAsync(HttpRequestMessage request,Dictionary`2 bindingDataContract)
   at async Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider.HttpTriggerBinding.BindAsync(Object value,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 

#### Known workarounds

Works in V2

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-webjobs-sdk-extensions#438

**Comment by pragnagopa** [comment]
Fixing the headers in the function runtime is better approach. Reactivating this issue.

**Comment by fabiocav** [comment]
Fixed in #3173
