### ISSUE TITLE
CosmosDB binding regression: listener unable to start.

### ISSUE THREAD

**Issue by elprans** [Azure/azure-functions-host#3229]
Recently, azure-functions-python-worker tests are failing consistently on Windows with host version `2.0.11886`.  I have been able to reproduce locally.  The scenario involves two simple functions: one writes a document into a collection, and another reads it via a `CosmosDBTrigger` trigger binding.

**put_document/function.json**:

```json
{
  "scriptFile": "__init__.py",
  "disabled": false,

  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "direction": "out",
      "type": "cosmosDB",
      "name": "doc",
      "databaseName": "test",
      "collectionName": "items",
      "leaseCollectionName": "leases",
      "createIfNotExists": true
    },
    {
      "direction": "out",
      "name": "$return",
      "type": "http"
    }
  ]
}
```

**put_document/__init__.py**:
```python
import azure.functions as func


def main(req: func.HttpRequest, doc: func.Out[func.Document]):
    doc.set(func.Document.from_json(req.get_body()))

    return 'OK'
```

**cosmosdb_trigger/function.json**:
```json
{
  "scriptFile": "__init__.py",
  "disabled": false,

  "bindings": [
    {
      "direction": "in",
      "type": "cosmosDBTrigger",
      "name": "docs",
      "databaseName": "test",
      "collectionName": "items",
      "id": "cosmosdb-trigger-test",
      "leaseCollectionName": "leases",
      "createLeaseCollectionIfNotExists": true
    },
    {
      "type": "blob",
      "direction": "out",
      "name": "$return",
      "connection": "AzureWebJobsStorage",
      "path": "python-worker-tests/test-cosmosdb-triggered.txt"
    },
  ]
}

```

***cosmosdb_trigger/__init__.py**:

```python
import azure.functions as azf

def main(docs: azf.DocumentList) -> str:
    return docs[0].to_json()
```

Running the above function app fails consistently with

```
info: Host.Startup[0]
      Retrying to start listener for function 'Functions.cosmosdb_trigger' (Attempt 3)
fail: Host.Startup[0]
      The listener for function 'Functions.cosmosdb_trigger' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'Functions.cosmosdb_trigger' was unable to start. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Documents.ChangeFeedProcessor.ChangeFeedEventHost.StartAsync()
   at Microsoft.Azure.Documents.ChangeFeedProcessor.ChangeFeedEventHost.RegisterObserverFactoryAsync(IChangeFeedObserverFactory factory)
   at Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBTriggerListener.StartAsync(CancellationToken cancellationToken) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Trigger\CosmosDBTriggerListener.cs:line 53
   at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 68
   --- End of inner exception stack trace ---
fail: Function.cosmosdb_trigger[0]
      The listener for function 'Functions.cosmosdb_trigger' was unable to start. Microsoft.Azure.Documents.ChangeFeedProcessor: Object reference not set to an instance of an object.
```

The trigger never fires. Here is a little more info: https://ci.appveyor.com/project/appsvc/azure-functions-python-worker/build/1.0.332?fullLog=true#L323

**Comment by asavaritayal** [comment]
@pragnagopa can you investigate this? The Python experience is blocked due to this issue.

**Comment by pragnagopa** [comment]
As discussed, this is very specific to python function on windows. I will investigate but no ETA

**Comment by pragnagopa** [comment]
CI is back up!
