### ISSUE TITLE
Function v2: Update host.json logger section throws startup parser exception

### ISSUE THREAD

**Issue by cnlogistics** [Azure/azure-functions-host#3474]
**Azure Cloud Hosting**

URL: https://truckerwebapp-fx-dev.azurewebsites.net/
Internal Server Error - https://truckerwebapp-fx-dev.azurewebsites.net/admin/host/keys
Session Id: 4e04b7f2ecd44ed8854bb0cdcc85906a
Timestamp: 2018-09-18T07:15:22.841Z

**Local Development Environment**

Visual StudioEnterprise: **15.8.4**
![image](https://user-images.githubusercontent.com/41715515/45670039-0d3a3200-bb22-11e8-971b-cb3358f8033f.png)
Microsoft.NET.Sdk.Functions: **v. 1.0.21**

According to the logging section sample provided [https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)](https://github.com/Azure/azure-functions-host/wiki/host.json-(v2))

I updated my host.json to

```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "logging": {
    "logLevel": {
      "TruckerWebApp.Functions.NotifySignalrHubUserFunction": "Trace",
      "default": "Information"
    }
  }
  }
}
```

and get that startup exception trace

```
Azure Functions Core Tools (2.0.1-beta.39)
Function Runtime Version: 2.0.12095.0
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\brunneer\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Host.General[0]
      Building host: startup suppressed:False, configuration suppressed: False
fail: Host.General[0]
      A host error has occurred
System.FormatException: Unable to parse host configuration file 'C:\Source\VSTS\TruckerWebApp\TruckerWebApp.Functions\TruckerWebApp.Functions\bin\Debug\netstandard2.0\host.json'. ---> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: }. Path '', line 5, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Microsoft.Azure.WebJobs.Script.Configuration.HostJsonFileConfigurationSource.HostJsonFileConfigurationProvider.LoadHostConfig(String configFilePath) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Config\HostJsonFileConfigurationSource.cs:line 212
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Script.Configuration.HostJsonFileConfigurationSource.HostJsonFileConfigurationProvider.LoadHostConfig(String configFilePath) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Config\HostJsonFileConfigurationSource.cs:line 216
   at Microsoft.Azure.WebJobs.Script.Configuration.HostJsonFileConfigurationSource.HostJsonFileConfigurationProvider.LoadHostConfigurationFile() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Config\HostJsonFileConfigurationSource.cs:line 137
   at Microsoft.Azure.WebJobs.Script.Configuration.HostJsonFileConfigurationSource.HostJsonFileConfigurationProvider.Load() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Config\HostJsonFileConfigurationSource.cs:line 64
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(Boolean skipHostStartup, Boolean skipHostConfigurationParsing) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DefaultScriptHostBuilder.cs:line 59
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.BuildHost(Boolean skipHostStartup, Boolean skipHostJsonConfiguration) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 267
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartHostAsync(CancellationToken cancellationToken, Int32 attemptCount, JobHostStartupMode startupMode) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 134
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
Value cannot be null.
Parameter name: provider
Press any to continue....info: Host.General[0]
```
Please update the sample and provide the documentation or give me a valid sample. Thanks.

**Comment by paulbatum** [comment]
@cnlogistics  Your host.json has three `{` and four `}`.

**Comment by ericbrunner** [comment]
Thanks. Is the content valid? I wanna log all Trace Log only from the SignalR related func and else only Information level.

**Comment by paulbatum** [comment]
Sorry I'm confused, is which content valid? The samples we have are valid as far as I can tell.

**Comment by paulbatum** [comment]
I believe the content above but with correctly matching braces is valid.

```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "logging": {
    "logLevel": {
      "TruckerWebApp.Functions.NotifySignalrHubUserFunction": "Trace",
      "default": "Information"
    }
  }  
}
```

**Comment by ericbrunner** [comment]
Is there a logging documenation for v2 already available? You can close that issue after answered. Thanks.

**Comment by paulbatum** [comment]
I believe there are some pending updates to the monitoring doc [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring) based on the more recent V2 changes. 

@alexkarcher-msft @jeffhollan can either of you share details? For example, I would expect [this section](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-logging-in-hostjson) to be updated based on the "logger" config section being renamed to be "logging" to be consistent with .NET Core conventions.

**Comment by alexkarcher-msft** [comment]
Paging @brettsam 

Based on my test it looks like `logging` works. Unfortunately `logger` seems to cause the log settings to be ignored without throwing any kind of error. @brettsam , can we add an error message to the portal and functions startup in that throws every time you have `logger` instead of `logging` in v2?

In the meantime I'm going to push a doc test, although it won't be live until Monday after the Ignite keynote.

**Comment by alexkarcher-msft** [comment]
Submitted the PR for this change. https://github.com/MicrosoftDocs/azure-docs-pr/pull/53018
