### ISSUE TITLE
Error starting up Docker Linux based node function app that runs fine locally

### ISSUE THREAD

**Issue by mpseidel** [Azure/azure-functions-host#3500]
#### Investigative information

I'm getting exceptions when trying to run a Docker Linux based node function app that runs fine locally and gives me exceptions on startup in Azure.

Maybe the exceptions look familiar and someone can give me pointers on what happens.
Happy to share the function name privately.

Exceprt from Dockerfile:

```
FROM mcr.microsoft.com/azure-functions/node:2.0

RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg && \
    mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/ && \
    wget -q https://packages.microsoft.com/config/debian/9/prod.list && \
    mv prod.list /etc/apt/sources.list.d/microsoft-prod.list && \
    chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
    chown root:root /etc/apt/sources.list.d/microsoft-prod.list

RUN apt-get update && \
    apt-get install -y dotnet-sdk-2.1

RUN mkdir -p /home/site/wwwroot

RUN npm i -g azure-functions-core-tools@core --unsafe-perm true

COPY src/host.json /home/site/wwwroot

RUN cd /home/site/wwwroot && func settings add FUNCTIONS_WORKER_RUNTIME node
RUN cd /home/site/wwwroot && func extensions install -p Microsoft.Azure.WebJobs.Extensions.Storage --version 3.0.0-beta8

```

Please provide the following:

- Timestamp: see log output
- Function App version (1.0 or 2.0):  shows `2.0.12116.0` in the portal - when running locally the image uses `2.0.12115.0`
- Function App name:  (Basic AppService Plan)
- Function name(s) (as appropriate):
- Invocation ID:
- Region: `West Europe`

#### Repro steps

1. Created new function app (OS Linux Preview, App Service Plan Basic West Europe)
2. Changed container settings to use my image
3. Try to start / restart App

#### Expected behavior

App starts up fine as it does locally using the same docker image on Docker for Windows.

#### Actual behavior

- Getting the output below in the log streaming service
- JavaScript Function is parsed and displayed correctly in the UI
- Portal says Function App is Running and available
- Function can't be called via the test interface or by adding queue messages that should trigger (works when running locally)

```
2018-09-21 13:40:18.306 INFO  - Recycling container because of AppSettingsChange and isMainSite = True
2018-09-21 13:40:18.807 INFO  - Issuing docker pull: imagename ==*****
2018-09-21 13:40:20.378 INFO  - Issuing docker pull: imagename =*****
2018-09-21 13:40:21.103 INFO  - Issuing docker pull =*****
2018-09-21T13:40:15.116881323Z Hosting environment: Production
2018-09-21T13:40:15.117005127Z Content root path: /home/site/wwwroot
2018-09-21T13:40:15.117151533Z Now listening on: http://[::]:80
2018-09-21T13:40:15.117200334Z Application started. Press Ctrl+C to shut down.
2018-09-21T13:39:59.825914318Z [40m[32minfo[39m[22m[49m: Middleware[0]
2018-09-21T13:39:59.835128650Z       Destination base URL is http://172.20.0.5
2018-09-21T13:40:00.678422360Z Hosting environment: Production
2018-09-21T13:40:00.678567165Z Content root path: /app
2018-09-21T13:40:00.679016281Z Now listening on: http://0.0.0.0:8081
2018-09-21T13:40:00.679628503Z Application started. Press Ctrl+C to shut down.
2018-09-21T13:40:16.740915788Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2018-09-21T13:40:16.769673925Z       Request starting HTTP/1.1 GET http://127.0.0.1:49165/robots933456.txt
2018-09-21T13:40:17.791973690Z Unhandled exception in request pipeline: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.AppService.Authentication.Properties.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.AppService.Middleware" at compile time, or that all the satellite assemblies required are loadable and fully signed.
2018-09-21T13:40:17.791998191Z    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
2018-09-21T13:40:17.792002891Z    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
2018-09-21T13:40:17.792007191Z    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
2018-09-21T13:40:17.792011091Z    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
2018-09-21T13:40:17.792014891Z    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
2018-09-21T13:40:17.792018392Z    at Microsoft.Azure.AppService.Middleware.Properties.SRResources.get_NoOriginHeader() in /Microsoft.Azure.AppService.Middleware/Properties/Resources.Designer.cs:line 87
2018-09-21T13:40:17.792022092Z    at System.Web.Cors.CorsEngine.TryValidateOrigin(CorsRequestContext requestContext, CorsPolicy policy, CorsResult result) in /Microsoft.Azure.AppService.Middleware/Cors/System.Web.Cors/CorsEngine.cs:line 217
2018-09-21T13:40:17.792025692Z    at System.Web.Cors.CorsEngine.EvaluatePolicy(CorsRequestContext requestContext, CorsPolicy policy) in /Microsoft.Azure.AppService.Middleware/Cors/System.Web.Cors/CorsEngine.cs:line 42
2018-09-21T13:40:17.792029292Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.TryEvaluateCorsPolicy(CorsRequestContext requestContext, CorsPolicy corsPolicy, CorsResult& corsResult) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 100
2018-09-21T13:40:17.792033692Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.HandleCorsRequest(CorsRequestContext corsRequestContext, HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 80
2018-09-21T13:40:17.792037492Z    at Microsoft.Azure.AppService.Cors.CorsModule.OnSendResponse(HttpContextBase context) in /Microsoft.Azure.AppService.Middleware/Cors/CorsModule.cs:line 68
2018-09-21T13:40:17.792048193Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<SendResponseAsync>d__7.MoveNext() in /MiddlewareLinux/Startup.cs:line 134
2018-09-21T13:40:17.792052393Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:40:17.792055793Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:40:17.792059293Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:40:17.792062693Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<OnRequest>d__6.MoveNext() in /MiddlewareLinux/Startup.cs:line 121
2018-09-21T13:40:17.821049639Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
2018-09-21T13:40:17.821065139Z       Connection id "0HLGVOV1NGNKF", Request id "0HLGVOV1NGNKF:00000001": An unhandled exception was thrown by the application.
2018-09-21T13:40:17.821070739Z System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.AppService.Authentication.Properties.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.AppService.Middleware" at compile time, or that all the satellite assemblies required are loadable and fully signed.
2018-09-21T13:40:17.821076439Z    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
2018-09-21T13:40:17.821081040Z    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
2018-09-21T13:40:17.821085940Z    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
2018-09-21T13:40:17.821090540Z    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
2018-09-21T13:40:17.821095040Z    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
2018-09-21T13:40:17.821099440Z    at Microsoft.Azure.AppService.Middleware.Properties.SRResources.get_NoOriginHeader() in /Microsoft.Azure.AppService.Middleware/Properties/Resources.Designer.cs:line 87
2018-09-21T13:40:17.821104040Z    at System.Web.Cors.CorsEngine.TryValidateOrigin(CorsRequestContext requestContext, CorsPolicy policy, CorsResult result) in /Microsoft.Azure.AppService.Middleware/Cors/System.Web.Cors/CorsEngine.cs:line 217
2018-09-21T13:40:17.821108741Z    at System.Web.Cors.CorsEngine.EvaluatePolicy(CorsRequestContext requestContext, CorsPolicy policy) in /Microsoft.Azure.AppService.Middleware/Cors/System.Web.Cors/CorsEngine.cs:line 42
2018-09-21T13:40:17.821113941Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.TryEvaluateCorsPolicy(CorsRequestContext requestContext, CorsPolicy corsPolicy, CorsResult& corsResult) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 100
2018-09-21T13:40:17.821118941Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.HandleCorsRequest(CorsRequestContext corsRequestContext, HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 80
2018-09-21T13:40:17.821130941Z    at Microsoft.Azure.AppService.Cors.CorsModule.OnSendResponse(HttpContextBase context) in /Microsoft.Azure.AppService.Middleware/Cors/CorsModule.cs:line 68
2018-09-21T13:40:17.821136142Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<SendResponseAsync>d__7.MoveNext() in /MiddlewareLinux/Startup.cs:line 134
2018-09-21T13:40:17.821140942Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:40:17.821145442Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:40:17.821149742Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:40:17.821154342Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<OnRequest>d__6.MoveNext() in /MiddlewareLinux/Startup.cs:line 126
2018-09-21T13:40:17.821159042Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:40:17.821163343Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:40:17.821167643Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:40:17.821172143Z    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
2018-09-21T13:40:17.821176743Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:40:17.821181143Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:40:17.821185443Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:40:17.821189944Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-09-21T13:40:18.478191036Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2018-09-21T13:40:18.478220837Z       Request finished in 1504.8261ms 500

..
2018-09-21T13:42:28  No new trace in the past 1 min(s).
2018-09-21T13:43:32.082354794Z [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[22]
2018-09-21T13:43:32.300695870Z       Heartbeat took longer than "00:00:01" at "09/21/2018 13:42:26 +00:00".
2018-09-21T13:43:32.300716770Z [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[22]
2018-09-21T13:43:32.300722370Z       Heartbeat took longer than "00:00:01" at "09/21/2018 13:43:22 +00:00".
2018-09-21T13:43:32.300726471Z [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[22]
2018-09-21T13:43:32.300730571Z       Heartbeat took longer than "00:00:01" at "09/21/2018 13:42:40 +00:00".
2018-09-21T13:43:32.300734471Z [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[22]
2018-09-21T13:43:32.300738271Z       Heartbeat took longer than "00:00:01" at "09/21/2018 13:43:06 +00:00".
2018-09-21T13:43:32.300741971Z [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[22]
2018-09-21T13:43:32.300753372Z       Heartbeat took longer than "00:00:01" at "09/21/2018 13:43:00 +00:00".

...

2018-09-21T13:44:00.002629163Z Unhandled exception in request pipeline: System.InvalidOperationException: Headers are read-only, response has already started.
2018-09-21T13:44:00.002648963Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
2018-09-21T13:44:00.002653863Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Remove(String key)
2018-09-21T13:44:00.002658864Z    at Microsoft.Azure.AppService.MiddlewareShim.Http.HttpResponseWrapper.DeleteHeader(String name) in /MiddlewareLinux/Http/HttpResponseWrapper.cs:line 27
2018-09-21T13:44:00.002663164Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.RemoveAllCorsHeaders(HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 91
2018-09-21T13:44:00.002667564Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.HandleCorsRequest(CorsRequestContext corsRequestContext, HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 77
2018-09-21T13:44:00.002671764Z    at Microsoft.Azure.AppService.Cors.CorsModule.OnSendResponse(HttpContextBase context) in /Microsoft.Azure.AppService.Middleware/Cors/CorsModule.cs:line 68
2018-09-21T13:44:00.002675864Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<SendResponseAsync>d__7.MoveNext() in /MiddlewareLinux/Startup.cs:line 134
2018-09-21T13:44:00.002680164Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:44:00.002684065Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:44:00.002687965Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:44:00.002691865Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<OnRequest>d__6.MoveNext() in /MiddlewareLinux/Startup.cs:line 121
2018-09-21T13:44:00.002740267Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
2018-09-21T13:44:00.002747467Z       Connection id "0HLGVOV1NGNKG", Request id "0HLGVOV1NGNKG:00000001": An unhandled exception was thrown by the application.
2018-09-21T13:44:00.002751567Z System.InvalidOperationException: Headers are read-only, response has already started.
2018-09-21T13:44:00.002755267Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
2018-09-21T13:44:00.002758867Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Remove(String key)
2018-09-21T13:44:00.002762867Z    at Microsoft.Azure.AppService.MiddlewareShim.Http.HttpResponseWrapper.DeleteHeader(String name) in /MiddlewareLinux/Http/HttpResponseWrapper.cs:line 27
2018-09-21T13:44:00.002766768Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.RemoveAllCorsHeaders(HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 91
2018-09-21T13:44:00.002770568Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.HandleCorsRequest(CorsRequestContext corsRequestContext, HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 77
2018-09-21T13:44:00.002776868Z    at Microsoft.Azure.AppService.Cors.CorsModule.OnSendResponse(HttpContextBase context) in /Microsoft.Azure.AppService.Middleware/Cors/CorsModule.cs:line 68
2018-09-21T13:44:00.002781568Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<SendResponseAsync>d__7.MoveNext() in /MiddlewareLinux/Startup.cs:line 134
2018-09-21T13:44:00.002785368Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:44:00.002789168Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:44:00.002792668Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:44:00.002796369Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<OnRequest>d__6.MoveNext() in /MiddlewareLinux/Startup.cs:line 126
2018-09-21T13:44:00.002800169Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:44:00.002803769Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:44:00.002807369Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:44:00.002811269Z    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
2018-09-21T13:44:00.002815169Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:44:00.002818869Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:44:00.002822470Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:44:00.002826070Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-09-21T13:44:00.002833170Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2018-09-21T13:44:00.002837370Z       Request finished in 5046.5862ms 200 text/html
2018-09-21T13:45:26  No new trace in the past 1 min(s).
2018-09-21T13:46:26  No new trace in the past 2 min(s).
2018-09-21T13:47:09.728636748Z [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[22]
2018-09-21T13:47:09.728663549Z       Heartbeat took longer than "00:00:01" at "09/21/2018 13:47:08 +00:00".
2018-09-21T13:48:26  No new trace in the past 1 min(s).
2018-09-21T13:49:16.742797831Z Unhandled exception in request pipeline: System.InvalidOperationException: Headers are read-only, response has already started.
2018-09-21T13:49:16.742824432Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
2018-09-21T13:49:16.742830532Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Remove(String key)
2018-09-21T13:49:16.742836232Z    at Microsoft.Azure.AppService.MiddlewareShim.Http.HttpResponseWrapper.DeleteHeader(String name) in /MiddlewareLinux/Http/HttpResponseWrapper.cs:line 27
2018-09-21T13:49:16.742841233Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.RemoveAllCorsHeaders(HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 91
2018-09-21T13:49:16.742846233Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.HandleCorsRequest(CorsRequestContext corsRequestContext, HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 77
2018-09-21T13:49:16.742851533Z    at Microsoft.Azure.AppService.Cors.CorsModule.OnSendResponse(HttpContextBase context) in /Microsoft.Azure.AppService.Middleware/Cors/CorsModule.cs:line 68
2018-09-21T13:49:16.742856433Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<SendResponseAsync>d__7.MoveNext() in /MiddlewareLinux/Startup.cs:line 134
2018-09-21T13:49:16.742861633Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:49:16.742866233Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:49:16.742870934Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:49:16.742875534Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<OnRequest>d__6.MoveNext() in /MiddlewareLinux/Startup.cs:line 121
2018-09-21T13:49:16.743729065Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
2018-09-21T13:49:16.743740865Z       Connection id "0HLGVOV1NGNKH", Request id "0HLGVOV1NGNKH:00000001": An unhandled exception was thrown by the application.
2018-09-21T13:49:16.743746265Z System.InvalidOperationException: Headers are read-only, response has already started.
2018-09-21T13:49:16.743751065Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
2018-09-21T13:49:16.743763866Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Remove(String key)
2018-09-21T13:49:16.743769266Z    at Microsoft.Azure.AppService.MiddlewareShim.Http.HttpResponseWrapper.DeleteHeader(String name) in /MiddlewareLinux/Http/HttpResponseWrapper.cs:line 27
2018-09-21T13:49:16.743773966Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.RemoveAllCorsHeaders(HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 91
2018-09-21T13:49:16.743778666Z    at Microsoft.Azure.AppService.Cors.CorsRequestHandler.HandleCorsRequest(CorsRequestContext corsRequestContext, HttpResponseBase response) in /Microsoft.Azure.AppService.Middleware/Cors/CorsRequestHandler.cs:line 77
2018-09-21T13:49:16.743783267Z    at Microsoft.Azure.AppService.Cors.CorsModule.OnSendResponse(HttpContextBase context) in /Microsoft.Azure.AppService.Middleware/Cors/CorsModule.cs:line 68
2018-09-21T13:49:16.743787867Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<SendResponseAsync>d__7.MoveNext() in /MiddlewareLinux/Startup.cs:line 134
2018-09-21T13:49:16.743792667Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:49:16.743797567Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:49:16.743801867Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:49:16.743806267Z    at Microsoft.Azure.AppService.MiddlewareShim.Startup.<OnRequest>d__6.MoveNext() in /MiddlewareLinux/Startup.cs:line 126
2018-09-21T13:49:16.743811068Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:49:16.743815368Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:49:16.743819768Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:49:16.743824768Z    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
2018-09-21T13:49:16.743829568Z --- End of stack trace from previous location where exception was thrown ---
2018-09-21T13:49:16.743833968Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-21T13:49:16.743838269Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-21T13:49:16.743842669Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-09-21T13:49:16.743847369Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2018-09-21T13:49:16.743852069Z       Request finished in 18289.754ms 200 text/html
2018-09-21T13:50:26  No new trace in the past 1 min(s).
...

```

**Comment by mpseidel** [comment]
Added some more info. Hope this helps.

**Comment by mpseidel** [comment]
Just tested it creating a new Function App choosing Docker as the OS not Linux and voila it works with the same Docker image.

![grafik](https://user-images.githubusercontent.com/2457819/45918843-faf72580-be8c-11e8-8c70-c8662cf3b968.png)

I need the base OS to be linux based so I assumed I had to pick Linux but I see that choosing Docker I actually get what I need under the hood as well.

The above might still be a bug though.

**Comment by mhoeger** [comment]
@asavaritayal as FYI, but closing issue as resolved. Thanks!
