### ISSUE TITLE
ARM Authentication doesn't work on dedicated linux without setting MACHINEKEY_DecryptionKey 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3518]
Repro steps:

- Create a dedicated Linux App
- Make sure your app doesn't have `MACHINEKEY_DecryptionKey` app setting. **Note:** that going to the functions UX will add it, so make sure to remove it or rename it.  
- do a 
```
GET https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.Web/sites/.../hostruntime/admin/host/systemkeys/_master?api-version=2018-02-01 
```

or even just 

```
GET https://{appName}.azurewebsites.net/admin/host/systemkeys/_master
```

This results in a generic 500 with no body

I tried setting 
```
AZURE_FUNCTIONS_ENVIRONMENT = Development
logging__console__isEnabled = true
host__logging__console__isEnabled = true
```

and setting `host.json` to 
```json
{
  "version": "2.0",
  "logging": {
      "console": {
          "isEnabled": true
      },
      "logLevel": "Trace"
  }
}
```

and the error response is the same. Just a 500 with no body. 

Trying to invoke a function however results in 

```
System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.InvalidOperationException: The key ring does not contain a valid default protection key. The data protection system cannot create a new key because auto-generation of keys is disabled.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext)
   at Microsoft.Azure.WebJobs.Script.WebHost.DataProtectionKeyValueConverter.WriteValue(Key key) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Security/KeyManagement/DataProtectionKeyValueConverter.cs:line 59
   at Microsoft.Azure.WebJobs.Script.WebHost.KeyValueConverterFactoryExtensions.WriteKey(IKeyValueConverterFactory factory, Key key) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Security/KeyManagement/KeyValueConverterFactoryExtensions.cs:line 23
   at Microsoft.Azure.WebJobs.Script.WebHost.HostSecrets.Refresh(IKeyValueConverterFactory factory) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Security/KeyManagement/HostSecrets.cs:line 44
   at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.RefreshSecretsAsync[T](T secrets, String keyScope) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs:line 377
   at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.GetHostSecretsAsync() in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs:line 88
   at Microsoft.Azure.WebJobs.Script.WebHost.Authentication.AuthenticationLevelHandler.GetAuthorizationKeyInfoAsync(HttpRequest request, ISecretManagerProvider secretManagerProvider) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Security/Authentication/Keys/AuthenticationLevelHandler.cs:line 83
   at Microsoft.Azure.WebJobs.Script.WebHost.Authentication.AuthenticationLevelHandler.HandleAuthenticateAsync() in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Security/Authentication/Keys/AuthenticationLevelHandler.cs:line 42
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.AuthenticateAndAuthorizeAsync(HttpContext context, FunctionDescriptor descriptor) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs:line 193
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.GetResultAsync(HttpContext context, IFunctionExecutionFeature functionExecution) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs:line 120
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.Invoke(HttpContext context) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs:line 56
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HttpThrottleMiddleware.Invoke(HttpContext httpContext, IOptions`1 httpOptions, HttpRequestQueue requestQueue, HostPerformanceManager performanceManager, IMetricsLogger metricsLogger) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/HttpThrottleMiddleware.cs:line 66
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HomepageMiddleware.Invoke(HttpContext context) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/HomepageMiddleware.cs:line 34
   at Microsoft.AspNetCore.Buffering.ResponseBufferingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HttpExceptionMiddleware.Invoke(HttpContext context) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/HttpExceptionMiddleware.cs:line 23
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.ScriptHostRequestServiceProviderMiddleware.Invoke(HttpContext httpContext, WebJobsScriptHostService manager) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/ScriptHostRequestServiceProviderMiddleware.cs:line 36
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HostWarmupMiddleware.Invoke(HttpContext httpContext) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/HostWarmupMiddleware.cs:line 34
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HostAvailabilityCheckMiddleware.Invoke(HttpContext httpContext, IScriptHostManager scriptHostManager) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/HostAvailabilityCheckMiddleware.cs:line 47
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.EnvironmentReadyCheckMiddleware.Invoke(HttpContext httpContext, IScriptWebHostEnvironment webHostEnvironment) in /azure-functions-host-dev/src/WebJobs.Script.WebHost/Middleware/EnvironmentReadyCheckMiddleware.cs:line 29
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

setting `MACHINEKEY_DecryptionKey` fixes all these issues. 

I can see the following environment variables available by default

```
"APPSETTING_WEBSITE_NODE_DEFAULT_VERSION": "8.11.1",
"APPSETTING_FUNCTIONS_WORKER_RUNTIME": "node",
"WEBSITE_SITE_NAME": "...",
"APPSETTING_logging__console__isEnabled": "true",
"AzureWebJobsScriptRoot": "/home/site/wwwroot",
"WEBSITE_AUTH_LOGOUT_PATH": "/.auth/logout",
"APPSETTING_MACHINEKEY_DecryptionKey": "...",
"AzureWebJobsStorage": ...",
"HTTP_LOGGING_ENABLED": "1",
"APPSETTING_FUNCTIONS_EXTENSION_VERSION": "~2",
"APPSETTING_WEBSITE_SITE_NAME": "...",
"REMOTEDEBUGGINGVERSION": "11.0.611103.400",
"WEBSITE_CORS_ALLOWED_ORIGINS": "https://functions.azure.com,https://functions-staging.azure.com,https://functions-next.azure.com",
"FUNCTIONS_WORKER_RUNTIME": "node",
"APPSETTING_APPINSIGHTS_INSTRUMENTATIONKEY": "...",
"APPSETTING_AZURE_FUNCTIONS_ENVIRONMENT": "Development",
"FUNCTIONS_EXTENSION_VERSION": "~2",
"ASPNETCORE_URLS": "http://+:80",
"WEBSITE_NODE_DEFAULT_VERSION": "8.11.1",
"ASPNETCORE_VERSION": "2.1.4",
"APPSETTING_AzureWebJobsStorage": "...",
"logging__console__isEnabled": "true",
"APPINSIGHTS_INSTRUMENTATIONKEY": "...",
"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"DOTNET_RUNNING_IN_CONTAINER": "true",
"WEBSITE_AUTH_ENCRYPTION_KEY": "...",
"APPSETTING_WEBSITE_SLOT_NAME": "Production",
"WEBSITE_ROLE_INSTANCE_ID": "0",
"ScmType": "None",
"APPSETTING_host__logging__console__isEnabled": "true",
"APPSETTING_REMOTEDEBUGGINGVERSION": "11.0.611103.400",
"WEBSITE_AUTH_ENABLED": "False",
"WEBSITE_AUTH_SIGNING_KEY": "...",
"APPSETTING_WEBSITE_AUTH_ENABLED": "False",
"host__logging__console__isEnabled": "true",
"APPSETTING_ScmType": "None",
"PORT": "80",
"AZURE_FUNCTIONS_ENVIRONMENT": "Development",
"WEBSITE_AUTH_AUTO_AAD": "False",
"WEBSITE_SLOT_NAME": "Production",
"HOSTNAME": "...",
"APPSETTING_WEBSITE_AUTH_AUTO_AAD": "False",
"WEBSITE_INSTANCE_ID": "....",
"APPSETTING_WEBSITE_AUTH_LOGOUT_PATH": "/.auth/logout",
"HOME": "/home"
```

as you can see there is a `WEBSITE_AUTH_ENCRYPTION_KEY` defined, but I guess it's not used on dedicated linux for some reason.

**Comment by patricklee2** [comment]
This python script can repro the issue
https://gist.github.com/patricklee2/ac2272a36d3dad6d5b1697304252620c

**Comment by aluong** [comment]
Is there any documentation on this setting?

**Comment by ahmelsayed** [comment]
not that I know of

**Comment by patricklee2** [comment]
the cli generates the key here, https://github.com/Azure/azure-cli/blob/e6990a1b5873f881d741351f3fc247baeff45535/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1837
