### ISSUE TITLE
Functions host dies when using WSL with Google.Protobuf assembly error

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-functions-host#3537]
### Using Functions locally under WSL (Ubuntu), the host fails to start when using JavaScript/Node and Python runtimes
Caused by error `Microsoft.Azure.WebJobs.Script.Grpc: Could not load file or assembly 'Google.Protobuf, Version=3.5.1.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. The module was expected to contain an assembly manifest`

#### Investigative information

Please provide the following:

- Timestamp: 2018-09-29 13:50
- Function App version (1.0 or 2.0): 2.0
- Function App name: newfunc (local, not in Azure)
- Function name(s) (as appropriate): testFunc
- Invocation ID: ???
- Region: N/A

#### Repro steps

Provide the steps required to reproduce the problem:
1. Use WSL (Windows Subsystem for Linux) with Node 8.x installed. 
1. Install Function Core Tools (v2.0.3) `npm i -g azure-functions-core-tools`
2. Create new local function app `func init newfunc --worker-runtime node`
3. Create new HTTP trigger function `cd newfunc` and `func new -l node -t httptrigger -n testFunc`
4. Start the host `func host start`

#### Expected behavior

The host starts successfully

#### Actual behavior

The host dies with a lot of errors and trace. The except from the log where the error occurs is:
```
[9/29/18 12:48:06 PM] Initializing Host.
[9/29/18 12:48:06 PM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[9/29/18 12:48:06 PM] Starting JobHost
[9/29/18 12:48:06 PM] Starting Host (HostId=becolem-1798755081, InstanceId=6a642377-035e-4e58-b4e8-9be192b4773e, Version=2.0.12115.0, ProcessId=3706, AppDomainId=1, Debug=False, FunctionsExtensionVersion=)
[9/29/18 12:48:06 PM] A host error has occurred
[9/29/18 12:48:06 PM] Microsoft.Azure.WebJobs.Script.Grpc: Could not load file or assembly 'Google.Protobuf, Version=3.5.1.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. The module was expected to contain an assembly manifest.
[9/29/18 12:48:06 PM] Stopping JobHost
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
Container is disposed and should not be used: Container is disposed.
You may include Dispose stack-trace into the message via:
container.With(rules => rules.WithCaptureContainerDisposeStackTrace())
Application is shutting down...
info: Host.General[0]
      Initialization cancellation requested by runtime.
crit: Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor[9]
      An error occurred starting the application
System.AggregateException: One or more errors occurred. (The operation was canceled.) ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.<>c__DisplayClass29_0.<StartHostAsync>b__1(Task t) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 207
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Known workarounds

None

#### Related information 

Provide any related information 

* Error does not happen with Dotnet runtime only with JavaScript/Node and Python (I assume as GRPC is not used to communicate with the out of process worker)
* Error does not happen on Ubuntu VM only under WSL
* I've only tested Ubuntu WSL distro but I don't believe issue is distro specific

**Comment by benc-uk** [comment]
Strange... the problem has gone away since I reinstalled the Functions core tools
