### ISSUE TITLE
Null refs possible in ScriptHost.AddFunctionError

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#3581]
In both v1 and v2. Example query showing issue below (eas region).

```
System.ArgumentNullException : Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key,TValue& value)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.AddFunctionError(Dictionary`2 functionErrors,String functionName,String error,Boolean isFunctionShortName) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 271
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ReadFunctionMetadata(String functionDirectory,TraceWriter traceWriter,ILogger logger,Dictionary`2 functionErrors,ScriptSettingsManager settingsManager,IEnumerable`1 functionWhitelist) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 1154
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ReadFunctionMetadata(IEnumerable`1 functionDirectories,TraceWriter traceWriter,ILogger logger,Dictionary`2 functionErrors,ScriptSettingsManager settingsManager,IEnumerable`1 functionWhitelist) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 1098
   at Microsoft.Azure.WebJobs.Script.ScriptHost.LoadFunctionMetadata() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 667
```

FunctionsLogs
| where PreciseTimeStamp > datetime(2018-10-08 22:00:00) and PreciseTimeStamp < datetime(2018-10-08 23:50:00)
| where HostInstanceId == "81ec10f7-f452-41b7-9d53-6968a790d4e9"

**Comment by brainded** [comment]
+1

**Comment by mathewc** [comment]
@brainded Is this affecting you? Are you seeing this in your app? Can you share details on your function/configuration causing you to see this?

**Comment by brainded** [comment]
Yeah it is but it hasn’t happened a lot. I will take a look and see if I can get you some more information around it but it was pretty sparse.

**Comment by pragnagopa** [comment]
The issue reproes more often when multiple jobhost restarts are triggered during a deployment
