### ISSUE TITLE
An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/azure-functions-host#3610]
#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App version (1.0 or 2.0): 2.0
- Function App name: n/a
- Function name(s) (as appropriate): n/a
- Invocation ID: n/a
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:
Please see 
https://github.com/Azure/azure-functions-durable-extension/issues/452

#### Expected behavior

Provide a description of the expected behavior.
No random exception

#### Actual behavior

Provide a description of the actual behavior observed.
This happen randomly on function app which running on app service plan

#### Known workarounds

Provide a description of any known workarounds.
Change app service plan seems fix the issue for a while

#### Related information 

Provide any related information 

* Programming language used 
c#
* Links to source
Please see 
https://github.com/Azure/azure-functions-durable-extension/issues/452
* Bindings used

**Comment by andrew-vandenbrink** [comment]
I have 2 function app, one in consumption plan, the other one in app service plan

The one in consumption plan working just fine (other than that random object disposed exception) reported here https://github.com/Azure/azure-functions-host/issues/1690

The one in app service plan, have random exception reported here

The code is as simple as this code below
```
private static HttpClientService httpClient = new HttpClientService(new System.Net.Http.HttpClient());
        [FunctionName("HttpPost")]
        public static async Task<bool> Run([ActivityTrigger]string input, ILogger log)
        {
           
            await httpClient.PostAsync(input);
            return true;
        }
```

**Comment by andrew-vandenbrink** [comment]
I already contacted azure support, so you should have access to my function app

stack trace
```
73f0c2197bac45fcaf7c0f62ad20e1e5: Function 'HttpPost (Activity)' failed with an error. Reason: System.Net.Http.HttpRequestException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance. ---> System.InvalidOperationException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
   at System.Net.Sockets.SocketAsyncEventArgs.ThrowForNonFreeStatus(Int32 status)
   at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket, SocketAsyncOperation operation)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at {redacted}.Common.Services.HttpClientService.PostAsync(String uri) in C:\Users\andrew\source\repos\{redacted}\{redacted}.Common\Services\HttpClientService.cs:line 21
   at {redacted}.Ocr.TesseractService.Services.Client.Http.HttpPost.Run(JObject input, ILogger log) in C:\Users\andrew\source\repos\{redacted}.Ocr.TesseractService\{redacted}.Ocr.TesseractService\Services\Client\Http\HttpPost.cs:line 28
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 63
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 561
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 508
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 444
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 249. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: {redacted}. SlotName: Production. ExtensionVersion: 1.6.2. SequenceNumber: 162.
```
