### ISSUE TITLE
cold start with an authenticated function always causes a SemaphoreFullException 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3618]
Repro:

``` bash
func init . # select python 
func new # select an http trigger
func azure functionapp publish {consumption-linux-app} 
```

invoke the function after an app restart

If the request to invoke the function causes a cold start, it always fails with 

```
System.Threading.SemaphoreFullException : Adding the specified count to the semaphore would cause it to exceed its maximum count.
    at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
    at async Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.GetHostSecretsAsync() at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs : 131
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Authentication.AuthenticationLevelHandler.GetAuthorizationKeyInfoAsync(HttpRequest request,ISecretManagerProvider secretManagerProvider) at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Security/Authentication/Keys/AuthenticationLevelHandler.cs : 83
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Authentication.AuthenticationLevelHandler.HandleAuthenticateAsync() at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Security/Authentication/Keys/AuthenticationLevelHandler.cs : 42
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync[TOptions]()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context,String scheme)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy,HttpContext context)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.AuthenticateAndAuthorizeAsync(HttpContext context,FunctionDescriptor descriptor) at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs : 195
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.GetResultAsync(HttpContext context,IFunctionExecutionFeature functionExecution) at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs : 120
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.Invoke(HttpContext context) at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs : 56
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HttpThrottleMiddleware.Invoke(HttpContext httpContext,IOptions`1 httpOptions,HttpRequestQueue requestQueue,HostPerformanceManager performanceManager,IMetricsLogger metricsLogger) at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Middleware/HttpThrottleMiddleware.cs : 66
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HomepageMiddleware.Invoke(HttpContext context) at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Middleware/HomepageMiddleware.cs : 34
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Buffering.ResponseBufferingMiddleware.Invoke(HttpContext httpContext)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.ExceptionMiddleware.Invoke(HttpContext context) at /azure-functions-host-c6f267f283a8dce8b01c3ac6f8edaba7f2870414/src/WebJobs.Script.WebHost/Middleware/ExceptionMiddleware.cs : 28
```

then subsequent requests work fine. This also doesn't happen if the function was anonymous.

**Comment by balag0** [comment]
Fixed by 62665194b0fda66b369bc1da00b77c3352f13889

**Comment by ahmelsayed** [comment]
Lets keep this open until it's merged into dev

**Comment by kshyju** [comment]
We have not observed this behavior in the last few years. Closing.
