### ISSUE TITLE
Errors when writing to a log file. The process cannot access the file.

### ISSUE THREAD

**Issue by elenavoy** [Azure/azure-functions-host#3768]
When running a function in Azure, the log file gets locked by the process causing the function to throw an exception.

#### Investigative information
- Timestamp: 2018-11-10 00:30:00.003
- Function App version: 2.0
- Invocation ID: AmPPo3jYejo=
- Region: Central US

#### Repro steps
A manually triggered function eventually terminates half way through the execution due to the logger exception below without finishing processing all the entities it's supposed to process.

#### Expected behavior
The function completes execution without logging failures.

#### Actual behavior
The function throws an exception: 
LogInfo(380): Policy(ffc4ad50-1501-4c75-8f7d-ec495e3899db): System.IO.IOException: The process cannot access the file 'D:\home\LogFiles\Application\Functions\Function\<function name>\2018-11-10T00-20-52Z-6c8b979fa4.log' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access)
   at Microsoft.Azure.WebJobs.Script.FileWriter.AppendToFile(FileInfo fileInfo, String content) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Diagnostics\FileWriter.cs:line 114
   at Microsoft.Azure.WebJobs.Script.FileWriter.Flush() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Diagnostics\FileWriter.cs:line 92
   at Microsoft.Azure.WebJobs.Script.Diagnostics.FileLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Diagnostics\FileLogger.cs:line 94
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)

#### Related information 
Looking at the FileWriter code in your code base, it appears that in the AppendToFile method, the file stream doesn't get closed at the end of the execution, causing the file to stay locked by the process (line 114).

Simply adding fs.Close() at the end of the method or using a "using" statement to open the stream might fix the problem.   

The issue is a big blocker for my team, so we would really appreciate your help.

Thanks!

**Comment by f2bo** [comment]
Not that it helps, but we reported a similar problem a few days ago (https://github.com/Azure/azure-functions-host/issues/3745). Only in our case, the unhandled exception is bringing down the host, not just the function.

**Comment by fabiocav** [comment]
Closing this as a duplicate of #3745 . Please follow that issue for updates.
