### ISSUE TITLE
MSDeploy fails in Azure Release Pipeline b/c App Offline fails

### ISSUE THREAD

**Issue by timmkrause** [Azure/azure-functions-host#4013]
#### Investigative information

- Timestamp: See log
- Function App version (1.0 or 2.0): 2.0

#### Related information 

```
2019-01-25T13:27:30.7059096Z Info: Using ID '82b64137-2e17-4f18-b3bc-4a0918d640f3' for connections to the remote server.
2019-01-25T13:27:32.3955558Z ##[error]Failed to deploy web package to App Service.
2019-01-25T13:27:32.4131859Z ##[error]Error: (25.01.2019 14:27:31) An error occurred when the request was processed on the remote computer.
Error: Could not find file 'D:\home\site\wwwroot\App_Offline.htm'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at Microsoft.Web.Deployment.AppOfflineRuleHandler.AddAppOfflineFilesToEachApp(DeploymentBaseContext baseContext, Boolean whatIf)
   at Microsoft.Web.Deployment.AppOfflineRuleHandler.Update(DeploymentSyncContext syncContext, DeploymentObject destinationObject, DeploymentObject& sourceObject, Boolean& proceed)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleUpdate(DeploymentObject destObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)
Error count: 1.

Has somebody see/encountered this before? The deployment worked flawlessly for months and all of a sudden...
```

**Comment by Merurino** [comment]
Hey, had the same issue.

Ended up solving by changing the WEBSITE_RUN_FROM_PACKAGE from 1 to 0.

Found the answer here: https://github.com/Azure/Azure-Functions/issues/1108#issuecomment-456295104

**Comment by kashimiz** [comment]
This feels like a one-off; something else might have brought the app online, thus deleting the `App_Offline.htm` file, such as viewing the functions site in the portal.

Setting WEBSITE_RUN_FROM_PACKAGE from 1 to 0 is a valid workaround.

Please reopen if you experience this issue again.
