### ISSUE TITLE
Java placeholders doesn't work in linux

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#4257]
#### Repro steps

```bash
docker pull ahmelsayed/runtime-mount:no-encryption-11
docker run -it -e WEBSITE_CONTAINER_READY=0 -e WEBSITE_PLACEHOLDER_MODE=1 -e AZURE_FUNCTIONS_ENVIRONMENT=Development -p 8081:80 ahmelsayed/runtime-mount:no-encryption-11
```
Then you need to send the assign request:

```http
POST http://localhost:8081/admin/instance/assign
Content-Type: application/json

{
    "siteId": 123,
    "siteName": "blah",
    "environment": {
        "WEBSITE_USE_ZIP": "https://ahmelswestusstorage.blob.core.windows.net/public/java-hello.zip",
        "FUNCTIONS_WORKER_RUNTIME": "java",
        "WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT": "2",
        "FUNCTIONS_EXTENSION_VERSION": "~2",
        "WEBSITE_AUTH_ENCRYPTION_KEY": "18B7DC869D30630329407E2E12939EE52153AF75F45D0657123E8EE0C7D92683",
        "WEBSITE_INSTANCE_ID": "blah",
    },
    "lastModifiedTime": "2018-10-10T01:00:00Z"
}
```

here is a curl command 

```bash
curl --request POST   --url http://localhost:8081/admin/instance/assign   --header 'content-type: application/json'  --data '{"siteId": 123,"siteName": "blah","environment": {"WEBSITE_USE_ZIP": "https://ahmelswestusstorage.blob.core.windows.net/public/java-hello.zip","FUNCTIONS_WORKER_RUNTIME": "java","WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT": "2","FUNCTIONS_EXTENSION_VERSION": "~2","WEBSITE_AUTH_ENCRYPTION_KEY": "18B7DC869D30630329407E2E12939EE52153AF75F45D0657123E8EE0C7D92683","WEBSITE_INSTANCE_ID": "blah",},"lastModifiedTime": "2018-10-10T01:00:00Z"}' --verbose
```

then hit  `https://localhost:8081/api/HttpTrigger-Java`

#### Expected behavior

To work

#### Actual behavior

```
System.TimeoutException: The operation has timed out.
   at System.Reactive.Subjects.AsyncSubject`1.GetResult()
   at Microsoft.Azure.WebJobs.Script.Rpc.LanguageWorkerChannelManager.SpecializeAsync() in /workingdir/src/WebJobs.Script/Rpc/LanguageWorkerChannelManager.cs:line 141
   at Microsoft.Azure.WebJobs.Script.WebHost.StandbyManager.SpecializeHostCoreAsync() in /workingdir/src/WebJobs.Script.WebHost/Standby/StandbyManager.cs:line 71
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.PlaceholderSpecializationMiddleware.InvokeSpecializationCheck(HttpContext httpContext) in /workingdir/src/WebJobs.Script.WebHost/Middleware/PlaceholderSpecializationMiddleware.cs:line 38
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.PlaceholderSpecializationMiddleware.Invoke(HttpContext httpContext) in /workingdir/src/WebJobs.Script.WebHost/Middleware/PlaceholderSpecializationMiddleware.cs:line 31
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.EnvironmentReadyCheckMiddleware.Invoke(HttpContext httpContext, IScriptWebHostEnvironment webHostEnvironment) in /workingdir/src/WebJobs.Script.WebHost/Middleware/EnvironmentReadyCheckMiddleware.cs:line 29
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.SystemTraceMiddleware.Invoke(HttpContext context) in /workingdir/src/WebJobs.Script.WebHost/Middleware/SystemTraceMiddleware.cs:line 47
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

#### Known workarounds
None

**Comment by kshyju** [comment]
Not an issue anymore. We have java placeholder and specialization support today.
