### ISSUE TITLE
NullRef in LanguageWorkerChannel.Dispose()

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4326]
While reviewing "top 20" error messages, I've seen this stack pop up quite a bit:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Diagnostics.Process.Close()
   at System.Diagnostics.Process.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.Azure.WebJobs.Script.Rpc.LanguageWorkerChannel.Dispose(Boolean disposing) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Rpc\LanguageWorkerChannel.cs : 531
```

It looks like we simply log it, rather than rethrow, but it may be worth seeing if we can clean it up (it's likely a race).

/cc @pragnagopa

**Comment by pragnagopa** [comment]
Thanks for opening tracking issue. PR #https://github.com/Azure/azure-functions-host/pull/4210 addresses this issue. It makes sense to no log this error as by the time this code gets hit, language worker process is already disposed.
