### ISSUE TITLE
System.Linq.Expressions: No coercion operator is defined between types 'System.Object' and 'System.Void'.

### ISSUE THREAD

**Issue by OneCyrus** [Azure/azure-functions-host#4413]
i'm trying to convert an existing demo project (graphql server) with custom DI to the new native dependency injection of azure functions but i get a `No coercion operator is defined between types 'System.Object' and 'System.Void'.`

working branch with custom DI: https://github.com/OneCyrus/GraphQL-AzureFunctions-HotChocolate/tree/master

migrated project which gives the error: https://github.com/OneCyrus/GraphQL-AzureFunctions-HotChocolate/tree/feat_nativeDI

#### Investigative information

local dev environment

Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0

#### Repro steps

1. checkout this branch and start the project. https://github.com/OneCyrus/GraphQL-AzureFunctions-HotChocolate/tree/feat_nativeDI
2. calling the function at http://localhost:7071/api/graphql
3. gives the following error

```
[13.05.2019 19:15:13] An unhandled host error has occurred.
[13.05.2019 19:15:13] System.Linq.Expressions: No coercion operator is defined between types 'System.Object' and 'System.Void'.
```

checking out the master with custom DI works fine.

**Comment by pragnagopa** [comment]
cc @brettsam / @fabiocav 
We need to investigate this.

**Comment by brettsam** [comment]
@OneCyrus -- Is there any stacktrace along with the exception?

**Comment by OneCyrus** [comment]
i couldn't get to the stack trace as it happens outside of my code.

this is what i get in the console:
![image](https://user-images.githubusercontent.com/7747800/58280511-12323e00-7da1-11e9-8742-ce373e93c2d6.png)

and the diagnostic events:
![image](https://user-images.githubusercontent.com/7747800/58280594-3d1c9200-7da1-11e9-8a89-ed9e053dc2f5.png)

**Comment by crashdebug** [comment]
I'm getting the same error as well. 

Azure Functions Core Tools (2.7.1948 Commit hash: 29a0626ded3ae99c4111f66763f27bb9fb564103)
Function Runtime Version: 2.0.12888.0

Here's a stack trace:
```
System.InvalidOperationException: No coercion operator is defined between types 'System.Object' and 'System.Void'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at DryIoc.DelegateFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7719
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.WrappersSupport.GetFuncOrActionExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 2990
   at DryIoc.ExpressionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7690
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.FactoryMethod.IsResolvableParameter(ParameterInfo parameter, Func`2 parameterSelector, Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 3862
   at DryIoc.FactoryMethod.<>c__DisplayClass5_1.<Constructor>b__4(ParameterInfo p) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 3757
   at ImTools.ArrayTools.FindFirst[T](T[] source, Func`2 predicate) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\ImTools.cs:line 205
   at DryIoc.FactoryMethod.<>c__DisplayClass5_1.<Constructor>b__2(ConstructorInfo x) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 3757
   at ImTools.ArrayTools.FindFirst[T](T[] source, Func`2 predicate) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\ImTools.cs:line 205
   at DryIoc.FactoryMethod.<>c__DisplayClass5_0.<Constructor>b__0(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 3756
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7011
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6625
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 210
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 846
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 116
```

**Comment by basil-twisleton** [comment]
I encounter the same error in V3

Azure Functions Core Tools (3.0.2009 Commit hash: 77395527a4e9c28da8400dcfd1a450f4e0d0c36c)
Function Runtime Version: 3.0.12930.0

Is there any news on this?
@OneCyrus Did you manage to find a way to get this working?

**Comment by OneCyrus** [comment]
@b-twis no, couldn't get it to work. I guess this issue may be related to a major flaw with the way DI works in azure functions and doesn't follow the spec.

https://github.com/Azure/azure-functions-dotnet-extensions/issues/34

nothing heard from @brettsam, @fabiocav or @pragnagopa yet.

**Comment by galvesribeiro** [comment]
Hey folks!

I'm falling into the exact same issue. Using the V3 functions and just upgraded my graphql-dotnet server to the latest package that supports System.Text.Json and I'm having the exactly same exception:

![image](https://user-images.githubusercontent.com/4714040/77570395-7be01480-6eaa-11ea-9a72-33e7854bbe98.png)

Any workarounds? Or should we revert back to previous release and handcraft everything?

**Comment by galvesribeiro** [comment]
Found a workaround myself...

I was registering the `IDocumentWriter` like this:

```csharp
builder.Services.AddSingleton<IDocumentWriter, DocumentWriter>();
```

Then I had the coercion exception. However, if I register it like this it works:

```csharp
builder.Services.AddSingleton<IDocumentWriter>(sp => new DocumentWriter(opt =>
            {
                opt.IgnoreNullValues = true;
                opt.PropertyNameCaseInsensitive = true;
                opt.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
                opt.ReadCommentHandling = JsonCommentHandling.Skip;
                opt.WriteIndented = false;
            }));
```

Definitively there is something wrong with this `DryIoc` and the `Microsoft.Extensions.DependencyInjection` binding... I tried this because I remember I had something similar elsewhere in my code that required me to do the same.

@fabiocav do you have any ideas on what that may be?

**Comment by elvirus839** [comment]
Hi guys, I am experiencing the same error. 

using 

- Microsoft.Azure.Functions.Extensions 1.0.0, 

- Microsoft.NET.Sdk.Functions 3.0.7

- Microsoft.Extensions.DependencyInjection (3.1.5)

- Microsoft.Azure.WebJobs (3.0.16)

```
Trace:
  at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at DryIoc.DelegateFactory.CreateExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7718
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6544
   at DryIoc.WrappersSupport.GetFuncOrActionExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 2989
   at DryIoc.ExpressionFactory.CreateExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7689
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6544
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7073
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6544
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6624
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 209
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 194
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 99
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetRequiredService(Type serviceType) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 82
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at SummoxOne.AzureFunctions.DataProcessing.Startup.<>c.<Configure>b__0_1(IServiceProvider s) in D:\Projects\Log10\applications\Software\Cloud\src\SummoxOne.AzureFunctions.DataProcessing\Startup.cs:line 20
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\DryIocAdapter.cs:line 156
   at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 4540
   at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6595
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7839
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7824
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6594
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6554
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6624
   at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7736
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 209
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 194
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in d:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 846
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsyncCore>d__16.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 117
```

Any work around or which version of the sdk contains the fix? 
Thanks.

**Comment by lookingcloudy** [comment]
> @galvesribeiro 
> Found a workaround myself...
> 
> @fabiocav do you have any ideas on what that may be?

Good on you for finding the problem and solution.  This worked for me also - specifically trying to use the StackExchange.Redis packages.  I had to downgrade the StackExchange packages to v8.x due to the Microsoft functions packages forcing an old version of Microsoft.Extensions.Logging.Abstractions and causing a runtime problem.  Another problem that was reported about 5 years ago and remains unfixed.

Just an editorial comment - whichever genius developer on the Microsoft Functions team decided to take a perfectly functioning dependency injection system and mess it up should be ejected from this team.  Crazy that it is nearly 5 years later and this dependency injection problem still hasn't been fixed.  Did the good developers quit the team?

The other problem (probably related) is the fact that there is not a root IServiceProvider (non-scoped) available at StartUp as there is in a standard project.  Maybe a better way of describing this, is builder.Services.BuildServiceProvider() provides a service provider with no services.
