### ISSUE TITLE
Scoped services not working when running in container

### ISSUE THREAD

**Issue by jmezach** [Azure/azure-functions-host#4422]
I'm having issues using ASP.NET Core Health Checks in my Azure Functions app when running the app in an Azure Functions container. I've written a custom health check, that depends on another service that I've registered as a singleton in my FunctionsStartup class. When running the health checks I'm getting an exception indicating that the service cannot be resolved. However it works fine when running it locally. 

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 2.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

**Note:** I'm unable to provide much of the above since I'm running in containers.

#### Repro steps

Provide the steps required to reproduce the problem:

- Create a .NET Azure Function app
- Add a Startup class and add the following to the `Configure` function:

```
builder.Services.AddSingleton<IMyService, MyService>()
builder.Services.AddHealthChecks()
                            .AddCheck<MyCustomCheck>("customCheck", HealthStatus.Degraded);
```
- Add a new class `MyService` implementing a new interface `IMyService`
- Add a new class `MyCustomCheck` and add a parameter of type `IMyService` to the constructor and let it implement the `IHealthCheck` interface
- Add an HttpTriggered function and add the `HealthCheckService` as a parameter to the constructor
- Call `CheckHealthAsync()` from the function
- Run the app locally and invoke the function and see that it works correctly
- Build a Docker container using `mcr.microsoft.com/azure-functions/dotnet:2.0-alpine` as the base image
- Run the container and invoke the function and see that it throws an exception

#### Expected behavior

I would expect the function to run successfully without throwing an exception.

#### Actual behavior
I'm getting the following exception when running the function app in the container:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Health ---> System.InvalidOperationException: Unable to resolve service for type 'MyFunctionApp.IMyService' while attempting to activate 'MyFunctionApp.MyCustomCheck'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.HealthChecksBuilderAddCheckExtensions.<>c__1`1.<AddCheck>b__1_0(IServiceProvider s)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at MyFunctionApp.Functions.HealthCheck(HttpRequest req, DurableOrchestrationClientBase orchestrator, ILogger log) in /app/Functions/Api/HealthCheck.cs:line 53
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 63
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 556
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 503
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 439
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 249
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 293
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 89
```

#### Known workarounds
None that I know of. My current solution would be to disable my custom health check, but I really want to have that in there.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source: cannot share unfortunately
* Bindings used

**Note:** According to [this piece of code](https://github.com/aspnet/Diagnostics/blob/f19a191d9eb8c6ba0542ae3ccd618fa9398734a6/src/Microsoft.Extensions.Diagnostics.HealthChecks/DefaultHealthCheckService.cs#L44) the health check service is using an IServiceScopeFactory internally, which is why I think that it is related to scoped services.

**Comment by anarsen** [comment]
@jmezach Did you remember to include this:
```
assembly: FunctionsStartup(typeof(Startup))]
```

If not, please provide a minimum example in a public repo. It would make it a lot more convenient to verify it locally.

**Comment by jmezach** [comment]
I did add that yes. I've even added a `Console.WriteLine()` to my `Configure` method to see if it was being invoked and I do see that line being written.

I'll try to come up with a small repro.

**Comment by jmezach** [comment]
Hmm, of course I'm unable to reproduce it in a new project. I think I have all the same things setup as in my actual application, but it seems to be working fine in my repro project, but it's not working in my actual application.

Are there any things I should check? Perhaps some NuGet packages that need updating, or files that need tweaking for this to work?

**Comment by jmezach** [comment]
Ah, I think I found my issue. My repro project was using the regular Docker images, while my production application was using the Alpine images. Looks like those haven't been updated to support the new DI stuff.

Question is, is that something that was missed, or was it intentional?

**Comment by fabiocav** [comment]
@ahmelsayed can you provide some guidance on the image that needs to be used? Are we updating Alpine images with the same cadence?

**Comment by ahmelsayed** [comment]
@jmezach which image were you using?

**Comment by jmezach** [comment]
I was using `FROM mcr.microsoft.com/azure-functions/dotnet:2.0-alpine` and after switching to `FROM mcr.microsoft.com/azure-functions/dotnet:2.0` my app was working as I expected.

**Comment by ahmelsayed** [comment]
Sorry for the delay @jmezach. The alpine image should work now. I didn't notice that the alpine image for dotnet wasn't being tagged correctly.
