### ISSUE TITLE
Durable function - Unhandled exception while executing task: System.ObjectDisposedException: Cannot access a disposed object. Object name: 'LoggerFactory'

### ISSUE THREAD

**Issue by george-ayris** [Azure/azure-functions-host#4521]
Durable function fails because of `System.ObjectDisposedException`  for `LoggerFactory` in an activity function. Potentially related to #1690.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 2.0
- Function name(s): `CosmosReprocessProcedureRuns` invoking `CosmosReprocessProcedureRuns_ProcessRun`
- Invocation ID: 4b7d91ec-eace-47f5-b3c0-62d3effde5e6
- Region: West Europe

#### Stack trace

```
Exception while executing function: CosmosReprocessProcedureRuns Orchestrator function 'CosmosReprocessProcedureRuns' failed: The activity function 'CosmosReprocessProcedureRuns_ProcessRun' failed: "Failed to deserialize exception from TaskActivity: Unhandled exception while executing task: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 68
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 55
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 158
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87
   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57
   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135
	   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 68
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 55
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 158
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87
   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57
   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135". See the function execution logs for additional details. 
```

#### Related information 

* Programming language used: C#
* Bindings used:
  * Durable function (triggered by a `QueueTrigger`)
  * Calls activity function, which has two `CosmosDb` bindings (one `DocumentClient` and one `IAsyncCollector<dynamic>`)

**Comment by george-ayris** [comment]
Small update: having tried to do some more digging I'm now seeing the function app hitting a connection limit, which then seems to cause the function app itself to restart and, on the resumed execution of the durable function, the `ObjectDisposedException` is thrown.

**Comment by lymedo** [comment]
I've received a similar exception today. It was thrown during a fan-out stage in the orchestrator.

> Orchestrator function 'O_ExtractProcess' failed: The activity function 'A_ApiSpread' failed: "Failed to deserialize exception from TaskActivity: 
Unhandled exception while executing task: System.ObjectDisposedException: Cannot access a disposed object.Object name: 'LoggerFactory'.   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 68   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 60   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 158   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135	   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 68   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 60   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 158   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135". See the function execution logs for additional details.

**Comment by yojagad** [comment]
Looping in @ConnorMcMahon and @cgillum to get more insights into this. Does DurableFunction hold an instance of LoggerFactory from a disposed JobHost in this scenario?

**Comment by ConnorMcMahon** [comment]
@yojagad 

We just use whatever instance of `ILoggerFactory` we are provided via the dependency injection pipeline for extensions. We only use it during initialization to create an `ILogger` for internal use.

**Comment by bootzin** [comment]
Same thing happened here in the fan out stage.. I'm limitting concurrent activities to 50 in the host.json file, but it seems that this property is considered on a per machine basis. This means that the orchestrator is instantiating new machines to run the 50 activities, but the total activity count is  far greater than that, which then hits the connection limit and throws the exception

**Comment by larryeby** [comment]
Any insight on this? Occasionally seeing this same issue pop up.

**Comment by ConnorMcMahon** [comment]
We have[ done some work](https://github.com/Azure/azure-functions-durable-extension/pull/1139) on the Durable Functions side of this in a recent release. If you are able to, I would recommend trying 2.1.1 to see if that prevents the issue from appearing.

**Comment by larryeby** [comment]
Thanks for quick the update. I will give this a go and see if the update fixes it.
