### ISSUE TITLE
System.Net.Http.HttpRequestException: Remote Certificate is invalid

### ISSUE THREAD

**Issue by raskhdb** [Azure/azure-functions-host#4532]
#### Investigative information

Please provide the following:

- Timestamp: 2019-06-04T18:31:09.209
- Function App version :  2.0.12493.0
- Function name(s) (as appropriate): 
      1. GameAzureConsume   - This works only on first invocation
      2. GameAzureToken   - This  always works as expected , in spite of having the same code for the part that retrieves Access Token 
- Invocation ID:  c6cd6c33-9c00-4f82-9483-dd0c147b1872
- Region: West India

#### Repro steps

Provide the steps required to reproduce the problem:

1. Run the function GameAzureConsume with query parameters emailid , storeKey and productId
    make sure that emailId contains "@" , and that storeKey and productId have more than two characters. Azure AD Access token will be retrieved, then if  we are using a mock storeKey and productId the function will end as succeeded but with status code 500
2. Run the function again - it will fail because Azure AD Access token will fail to be retrieved. 
Failure message will be : The remote certificate is invalid according to the validation procedure.

<details>
<summary>**Detailed Exception**</summary>
If  I use a try catch block to catch the exception , then it is as follows. (I am not using try catch block anymore so that on the Azure portal the function can be recorded as "failed"

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

</details>

#### Expected behavior

The function should be able to retrieve Access Token not just on first invocation but on every invocation

#### Actual behavior

The function only retrieves Access token on first invocation. The second invocation on wards, it always fails
##### Same code works in one function and fails in another
It is strange that both these functions : 
1. GameAzureConsume   -
  2. GameAzureToken   

have the same code  for the part that retrieves Azure AD Access Token. Yet GameAzureConsume only works on the first invocation whereas GameAzureToken always works as expected and succeeds in retrieving the Azure AD Access Token. 

#### Known workarounds

None.  Tried this :
`ServicePointManager.ServerCertificateValidationCallback +=
             (sender, cert, chain, error) =>
             {
                 return true;
             };
`
does not make any difference

#### Related information 

Provide any related information 

* Programming language used  : c#

<details>
<summary>**This part of code is same for both functions but only works for one**</summary>

```csharp

 private static HttpClient httpClient = GetHttpClient();


        private static HttpClient GetHttpClient()
        {
            ServicePointManager.ServerCertificateValidationCallback +=
             (sender, cert, chain, error) =>
             {
                 return true;
             };

            HttpClient httpClient = new HttpClient();
            return httpClient;
        }

        private static async Task<JsonResult> GetNewToken
           (string tenantID, string clientId, string clientSecret, string resource , ILogger log)
        {
            
            FormUrlEncodedContent postContent = new FormUrlEncodedContent(new Dictionary<string, string>
            {
                { "grant_type", "client_credentials" },
                { "client_id", clientId },
                { "client_secret", clientSecret },
                { "resource", resource }
            });

            postContent.Headers.ContentType = new MediaTypeHeaderValue("application/x-www-form-urlencoded");
            log.LogInformation("GetNewToken try");

       
                HttpResponseMessage response = await httpClient.PostAsync($"https://login.microsoftonline.com/{tenantID}/oauth2/token", postContent);
                string responseContent = await response.Content.ReadAsStringAsync();
                log.LogInformation("GotNewToken");
                log.LogInformation($"token response is {response.StatusCode.ToString()}");
                log.LogInformation($"token response is {responseContent}");
                switch (response.StatusCode)
                {
                    case System.Net.HttpStatusCode.OK:
                        
                        JsonADToken jsonObject = JsonConvert.DeserializeObject<JsonADToken>(responseContent);
                        JsonResult jsonResult = new JsonResult(jsonObject);
                        jsonResult.StatusCode = 240;
                        return jsonResult;

                    case System.Net.HttpStatusCode.InternalServerError:
                        JsonResult jsonServerErrorResult = new JsonResult("");
                        jsonServerErrorResult.StatusCode = 540;
                        return jsonServerErrorResult;

                    default:
                        JsonResult jsonOtherErrorResult = new JsonResult("");
                        jsonOtherErrorResult.StatusCode = 440;
                        return jsonOtherErrorResult;
                }


        }
```
</details>

**Comment by brettsam** [comment]
Are you able to reproduce this outside of a function app? How about in a .NET Core console app? I'm not sure how Functions would be doing anything specific here to break this...

Also, ServicePointManager doesn't work in .NET Core, you'll need to pass in an `HttpClientHandler` to the `HttpClient` with the settings you want. For example: https://stackoverflow.com/a/44540071/3516125

**Comment by ruskh** [comment]
Thank you so much for looking into this , i will try
1. Passing in an` HttpClientHandler`
2. Reproducing outside a function app
And report back this week

**Comment by ruskh** [comment]
I tried two things :

1. Reproducing with Console App
I tried the existing code (i.e without the HttpClientHandler)
Result : Could not reproduce, Console App works without any errors

2. Passing in an HttpClientHandler
Result : 

token response is Redirect
2019-07-28T09:19:48.169 [Information] token response is <html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://login.microsoftonline.com:443/{**tenantId**}/oauth2/token">here</a>.</h2>

(I redacted the tenant id above)


Since the existing code works ok on a console app and also on another Azure Function , it feels like a Azure Function bug


**************

Other people seem to have had a similar / same issue  as per this thread : 

https://social.msdn.microsoft.com/Forums/azure/en-US/f2f35ab9-3d0a-490f-b639-8ea5abda92d5/intermittent-the-remote-certificate-is-invalid-according-to-the-validation-procedure?forum=windowsazurewebsitespreview

**Comment by raskhdb** [comment]
Just realised I have two accounts , just posting to confirm that the previous comment is mine

**Comment by raskhdb** [comment]
Hi can you please help me with this, it is critical to me in order to enable IAP in my UWP game.

**Comment by fabiocav** [comment]
@raskhdb , apologies for the delayed response here. Is this something you're still experiencing?
