### ISSUE TITLE
Publishing failed error: System.AggregateException

### ISSUE THREAD

**Issue by NRKirby** [Azure/azure-functions-host#4646]
When I try publishing my TimerFunction to Azure I get a publishing failed error:

The temp file has the following exception:

```
07/07/2019 08:54:32
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__176.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

===================

```

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: 2.0
- Function App name: SiteScraper89
- Function name:  ScrapeFunction
- Invocation ID: ?
- Region: UK South

#### Repro steps

1. Right-click the project in Visual Studio
2. Select publish

#### Expected behavior

The function is successfully published to Azure.

#### Actual behavior

The function is not published as an exception is thrown.

**Comment by soninaren** [comment]
Have a few related questions / comments:
- If you are using the VS 2017 or earlier please make sure the latest version of Azure Functions and Web Jobs Tools version is installed.
    1. Open Visual Studio, `Go to Tools -> Extension and Updates -> Updates`
    2. Select "Azure Functions and Web Jobs Tools", Click update
    <img src="https://user-images.githubusercontent.com/8119379/48643038-7f4cbd00-e993-11e8-868b-63146fb80061.png" width="600">
- There is a fix going out that should resolve an issue where some of the files were locked in azure which caused visual studio publishing to fail. Can try publishing via `Run from package`?
