### ISSUE TITLE
Access to the registry key 'Global' is denied

### ISSUE THREAD

**Issue by alex-mocanu** [Azure/azure-functions-host#4706]
I am running an executable in a Function App and in the log generated by my executable I get the following error:

```
Error|Fatal Exception - Message: Access to the registry key 'Global' is denied.
StackTrace:    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalGetValue(String name, Object defaultValue, Boolean doNotExpand, Boolean checkSecurity)
   at Microsoft.Win32.RegistryKey.GetValue(String name)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName)
   at Microsoft.Eco.WindowsPerformanceCounter..ctor(String categoryName, String counterName, String counterHelp, PerformanceCounterType counterType, Int64 counterValue, String instanceName, EcoPerformanceCounter totalInstanceCounter) in c:\xsrc\EcoISS\source\eco_iss\Library\Source\PerfCounters\WindowsPerformanceCounter.cs:line 150
   at Microsoft.Eco.EcoPerformanceCounter.CreateCounter(String categoryName, String counterName, String counterHelp, PerformanceCounterType counterType, Int64 initialValue, String instanceName, EcoPerformanceCounter totalInstanceCounter) in c:\xsrc\EcoISS\source\eco_iss\Library\Source\PerfCounters\EcoPerformanceCounter.cs:line 328
   at Microsoft.Eco.EcoCountersInstance..ctor(String categoryName, String categoryHelp, String instanceName, EcoCountersInstance totalCountersInstance) in c:\xsrc\EcoISS\source\eco_iss\Intermediate\EcoPerfCounters.cs:line 237
   at Microsoft.Eco.EcoCounters.<.ctor>b__7(String name) in c:\xsrc\EcoISS\source\eco_iss\Intermediate\EcoPerfCounters.cs:line 179
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Eco.EcoMultiInstancePerformanceCategory.GetOrAddCounterInstance(String instanceName, Func`2 instanceFactory) in c:\xsrc\EcoISS\source\eco_iss\Library\Source\PerfCounters\EcoMultiInstancePerformanceCategory.cs:line 140
   at Microsoft.Eco.EcoCounters..ctor() in c:\xsrc\EcoISS\source\eco_iss\Intermediate\EcoPerfCounters.cs:line 179
   at Microsoft.Eco.EcoCounters.get_Instance() in c:\xsrc\EcoISS\source\eco_iss\Intermediate\EcoPerfCounters.cs:line 66
   at Microsoft.Eco.EcoCounters.GetCounterInstance(String instanceName) in c:\xsrc\EcoISS\source\eco_iss\Intermediate\EcoPerfCounters.cs:line 91
   at Microsoft.Eco.AsyncBinaryFileWriter..ctor(String filePrefix, String fileExtension, ByteBufferPool bufferPool, Func`2 configDelegate) in c:\xsrc\EcoISS\source\eco_iss\Library\Source\EventLog\AsyncBinaryFileWriter.cs:line 159
   at Microsoft.Eco.EventsFile..ctor(String customName) in c:\xsrc\EcoISS\source\eco_iss\Library\Source\EventLog\EventsFile.cs:line 181
   at Microsoft.Eco.EventsFile..ctor() in c:\xsrc\EcoISS\source\eco_iss\Library\Source\EventLog\EventsFile.cs:line 204
   at Microsoft.Eco.EventLogger.Initialize() in c:\xsrc\EcoISS\source\eco_iss\Library\Source\EventLog\EventLogger.cs:line 406
   at Microsoft.Eco.EcoRuntime.PreInitialize() in c:\xsrc\EcoISS\source\eco_iss\Library\Source\Configuration\EcoRuntime.cs:line 617
   at Microsoft.Eco.EcoRuntime.Initialize() in c:\xsrc\EcoISS\source\eco_iss\Library\Source\Configuration\EcoRuntime.cs:line 275
   at Microsoft.Xbox.SQLizer.Console.Program.Initialize() in c:\B\305\DataGrid_Live\S\private\DataGrid\Tools\SQLizer\DataMart\SQLizer.Console\Program.cs:line 211
   at Microsoft.Xbox.SQLizer.Console.Program.Start(String inputManifest, String appConfig) in c:\B\305\DataGrid_Live\S\private\DataGrid\Tools\SQLizer\DataMart\SQLizer.Console\Program.cs:line 161
   at Microsoft.Xbox.SQLizer.Console.Program.Main(String[] args) in c:\B\305\DataGrid_Live\S\private\DataGrid\Tools\SQLizer\DataMart\SQLizer.Console\Program.cs:line 121
```

Can you give me a hint about what could be the problem?

**Comment by fabiocav** [comment]
If you can provide the app information requested in the issue template, that would help validate, but based on the error above, you seem to be running into a sandbox limitation when one of your dependencies is attempting to read that registry key. While reads are generally allowed, depending on the key/hive you're working with, you may run into permission issues. You can find more information here: https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#writing-to-registry
