### ISSUE TITLE
ModuleNotFoundError for functions worker

### ISSUE THREAD

**Issue by SpicySyntax** [Azure/azure-functions-host#4779]
#### Investigative information

Please provide the following:

- Timestamp: 08/08/2019 9:43 AM central time
- Function App version (1.0 or 2.0): 2.0
- Run on AKS CLuster
-  Source Code with PIP dependencies and docker build found at this [Gist](https://gist.github.com/SpicySyntax/ab2fed3babbf6d6f980b668352ca193d)

#### Repro steps

Running locally works as expected.
After deploying using Helm to AKS my deployments started failing when using python.

See logs from pod running the azure function below:
```
Worker.LanguageWorkerProcess.python.1cf0bff3-1818-44c6-b145-1cba3eac0813[0]
      Starting language worker process:bash  "/azure-functions-host/workers/python/start.sh" --host 127.0.0.1 --port 40231 --workerId 1cf0bff3-1818-44c6-b145-1cba3eac0813 --requestId 728b2d4c-eca7-41c6-b8ec-15b30518a619 --grpcMaxMessageLength 134217728
info: Worker.LanguageWorkerProcess.python.1cf0bff3-1818-44c6-b145-1cba3eac0813[0]
      bash process with Id=38 started
info: Host.Function.Console[0]
      python == /usr/local/bin/python
info: Host.Function.Console[0]
      PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
info: Host.Function.Console[0]
      starting the python worker
info: Host.Function.Console[0]
      Traceback (most recent call last):
info: Host.Function.Console[0]
        File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
info: Host.Function.Console[0]
          from azure.functions_worker import main
info: Host.Function.Console[0]
      ModuleNotFoundError: No module named 'azure.functions_worker'
```

#### Known workarounds
NA

**Comment by alrod** [comment]
cc: @maiqbal11

**Comment by ankitkumarr** [comment]
Could you share your `requirements.txt`? If you do have any references of `azure-functions-worker` there, would you mind removing it and retrying?

+ @Hazhzeng

**Comment by SpicySyntax** [comment]
@ankitkumarr please see the [Gist](https://gist.github.com/SpicySyntax/ab2fed3babbf6d6f980b668352ca193d) I included here or in the initial question. I am not sure what happened but when I redeployed a third time I stopped receiving this error. (This was after a Kubernetes version update)

**Comment by ankitkumarr** [comment]
`functions_worker` moved out of `azure` namespace and became `azure_functions_worker` over `azure.functions_worker`. So I suspect, there was a discrepancy where you had `azure_functions_worker` in your image, while our Python worker needed `azure.functions_worker`. Now that the image is updated, all references should be to `azure_functions_worker`.

You shouldn't see this issue going forward.
@maiqbal11 or @Hazhzeng might have a better insight.

**Comment by maiqbal11** [comment]
@SpicySyntax, as @ankitkumarr pointed out, we moved the internal implementation of the Python worker out of the `azure` namespace to avoid conflicts with user provided `azure` packages. It's likely that this was a point in time issue with the entry point that was being used to start the worker. It seems like your latest deployment has moved this into a consistent state and you likely won't see issues in the future. Please let us know if you have further concerns or if we should be good to close on this.

**Comment by SpicySyntax** [comment]
@ankitkumarr @maiqbal11 Thank you for the timely response. Closing now.

**Comment by SpicySyntax** [comment]
@ankitkumarr strangely when I deployed to a new cluster (our QA) the opposite version of this problem started showing up. I have not changed the requirements or docker build provided above.

I.E. we now get "ModuleNotFoundError: No module named 'azure_functions_worker'"

Note the dev cluster that works is Kubernetes 1.13.7, the QA cluster now with this problem is on Kubernetes 1.13.9/
Logs:
```
Host.Startup[503]
      Initializing Host.
Host.Startup[504]
      Host initialization: ConsecutiveErrors=0, StartupCount=1
Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      ApplicationInsightsLoggerOptions
      {
        "SamplingSettings": {
          "EvaluationInterval": "00:00:15",
          "InitialSamplingPercentage": 100.0,
          "MaxSamplingPercentage": 100.0,
          "MaxTelemetryItemsPerSecond": 20.0,
          "MinSamplingPercentage": 0.1,
          "MovingAverageRatio": 0.25,
          "SamplingPercentageDecreaseTimeout": "00:02:00",
          "SamplingPercentageIncreaseTimeout": "00:15:00"
        },
        "SnapshotConfiguration": null,
        "EnablePerformanceCountersCollection": true,
        "HttpAutoCollectionOptions": {
          "EnableHttpTriggerExtendedInfoCollection": true,
          "EnableW3CDistributedTracing": true,
          "EnableResponseHeaderInjection": true
        }
      }
Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      LoggerFilterOptions
      {
        "MinLevel": "None",
        "Rules": [
          {
            "ProviderName": null,
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": "None",
            "Filter": null
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
            "CategoryName": null,
            "LogLevel": "Trace",
            "Filter": null
          }
        ]
      }
Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      LoggerFilterOptions
      {
        "MinLevel": "None",
        "Rules": [
          {
            "ProviderName": null,
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": "None",
            "Filter": null
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
            "CategoryName": null,
            "LogLevel": "Trace",
            "Filter": null
          }
        ]
      }
Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      FunctionResultAggregatorOptions
      {
        "BatchSize": 1000,
        "FlushTimeout": "00:00:30",
        "IsEnabled": true
      }
Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      SingletonOptions
      {
        "LockPeriod": "00:00:15",
        "ListenerLockPeriod": "00:01:00",
        "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
        "LockAcquisitionPollingInterval": "00:00:05",
        "ListenerLockRecoveryPollingInterval": "00:01:00"
      }
Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      HttpOptions
      {
        "DynamicThrottlesEnabled": false,
        "MaxConcurrentRequests": -1,
        "MaxOutstandingRequests": -1,
        "RoutePrefix": "api"
      }
Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Starting JobHost
Host.Startup[401]
      Starting Host (HostId=crackdetectionsegmentationdaemon, InstanceId=f2efd8c3-823c-4750-902f-a2a8a4cb2bcb, Version=2.0.12625.0, ProcessId=1, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
Host.Startup[314]
      Loading functions metadata
Host.Startup[315]
      1 functions loaded
Host.Startup[0]
      Generating 0 job function(s)
[40m[1m[33mwarn[39m[22m[49m: Host.Startup[0]
      No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Host.Startup[412]
      Host initialized (466ms)
Host.Startup[413]
      Host started (553ms)
Host.Startup[0]
      Job host started
[41m[30mfail[39m[22m[49m: Host.Startup[402]
      The following 1 functions are in error:
      segment: The binding type(s) 'queueTrigger, queue' are not registered. Please ensure the type is correct and the binding extension is installed.

Host.Function.Console[0]
      python == /usr/local/bin/python
Host.Function.Console[0]
      PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
Host.Function.Console[0]
      starting the python worker
Host.Function.Console[0]
      Traceback (most recent call last):
Host.Function.Console[0]
        File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
Host.Function.Console[0]
          from azure_functions_worker import main
Host.Function.Console[0]
      ModuleNotFoundError: No module named 'azure_functions_worker'
Host.Function.Console[0]
      python == /usr/local/bin/python
Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher[0]
      Exceeded language worker restart retry count for runtime:python. Shutting down Functions Host
Host.Function.Console[0]
      PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
Host.Function.Console[0]
      starting the python worker
Host.Function.Console[0]
      Traceback (most recent call last):
Host.Function.Console[0]
        File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
Host.Function.Console[0]
          from azure_functions_worker import main
 Host.Function.Console[0]
      ModuleNotFoundError: No module named 'azure_functions_worker'
Host.Function.Console[0]
      python == /usr/local/bin/python
 Host.Function.Console[0]
      PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
Host.Function.Console[0]
      starting the python worker
Host.Function.Console[0]
      Traceback (most recent call last):
Host.Function.Console[0]
        File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
Host.Function.Console[0]
          from azure_functions_worker import main
Host.Function.Console[0]
      ModuleNotFoundError: No module named 'azure_functions_worker'
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Stopping JobHost
Host.Startup[0]
      Job host stopped
Application is shutting down...
```

Any idea how I can resolve this?

**Comment by SpicySyntax** [comment]
@ankitkumarr I have found a fix.

Firstly I targeted 'mcr.microsoft.com/azure-functions/python:2.0-python3.6' with my Docker image manifest.

Secondly I removed the requirements below from requirements.txt

```
azure-functions==1.0.0b5
azure-functions-worker==1.0.0b10
grpcio==1.20.1
grpcio-tools==1.20.1
```

Thanks
