### ISSUE TITLE
Wait for function dispatcher to drain invocation buffer before job host shuts down

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4817]
If host started invocations and if application is shutting down before invocations complete, invocations will fails with following error because language worker process is disposed before it handles buffered invocations

```
System.InvalidOperationException : Did not find any initialized language workers
   at Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 languageWorkerChannels,Int32 maxProcessCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Rpc\FunctionRegistration\FunctionDispatcherLoadBalancer.cs : 27
   at Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher.Invoke(ScriptInvocationContext invocationContext) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Rpc\FunctionRegistration\FunctionDispatcher.cs : 215
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\Rpc\WorkerLanguageInvoker.cs : 79
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 85
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 584
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 531
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 467
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 277
```

To prevent this, wait for FunctionDispatcher to finish invocations i.e inflgiht requests before shutting down a worker process.

ASP.NET Webhost has default graceful shutdown set to 5 secs:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#shutdown-timeout

We should consider similar timeout for draining invocations from language worker channels
cc @yojagad

**Comment by FinVamp1** [comment]
Looks like we have on average at least 100 apps a day seeing this issue. 

let strError="System.InvalidOperationException : Did not find any initialized language workers";
union     
    cluster("wawscus").database("wawsprod").FunctionsLogs,
    cluster("wawseas").database("wawsprod").FunctionsLogs,
    cluster("wawseus").database("wawsprod").FunctionsLogs,
    cluster("wawsneu").database("wawsprod").FunctionsLogs,
    cluster("wawsweu").database("wawsprod").FunctionsLogs,
    cluster("wawswus").database("wawsprod").FunctionsLogs
| where PreciseTimeStamp > ago(14d)
| where Details contains strError
| summarize dcount(AppName) by  bin(PreciseTimeStamp,1d)

  | PreciseTimeStamp | dcount_AppName
  | 2019-09-09 00:00:00.0000000 | 249
  | 2019-09-10 00:00:00.0000000 | 304
  | 2019-09-11 00:00:00.0000000 | 281
  | 2019-09-12 00:00:00.0000000 | 283
  | 2019-09-13 00:00:00.0000000 | 300
  | 2019-09-14 00:00:00.0000000 | 218
  | 2019-09-15 00:00:00.0000000 | 191
  | 2019-09-16 00:00:00.0000000 | 291
  | 2019-09-17 00:00:00.0000000 | 306
  | 2019-09-18 00:00:00.0000000 | 278
  | 2019-09-19 00:00:00.0000000 | 318
  | 2019-09-20 00:00:00.0000000 | 325
  | 2019-09-21 00:00:00.0000000 | 227
  | 2019-09-22 00:00:00.0000000 | 222
  | 2019-09-23 00:00:00.0000000 | 111

**Comment by fabiocav** [comment]
We need to discuss the design on this.
