### ISSUE TITLE
Function host is unable to start(MSI auth issue)

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-functions-host#4832]
#### Investigative information
After successfully running for several hours, all functions in function app starting to return `503` response codes. There are no error logs in Kudu (`LogFiles/Application/Functions/Host`). The only meaningful error I'm getting when navigating to the portal and opening any function:
```
The function runtime is unable to start. Microsoft.Azure.Services.AppAuthentication: Parameters: Connection String: RunAs=App; AppId=32cf9ead-4ce3-4401-b318-8e436bd4a0e4, Resource: https://vault.azure.net, Authority: https://login.windows.net/9813be10-1a37-4d76-a898-cb2a979e60f3. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: BadRequest, Response: .
Session Id: 3280621819f04b04a13fbd1957f13422

Timestamp: 2019-08-22T07:49:00.896Z
```
Function app works as usual after the restart of the app through the portal or after redeployment.

- Timestamp: 2019-08-22T07:49:00.896Z
- Function App version: 2.0
- Function App name: feedme-dvui
- Function name(s) (as appropriate): all
- Region: central us

**Comment by brettsam** [comment]
@Badabum -- I'm assuming you have an MSI configured? Can you give us some background on your setup?

@mattchenderson -- do we have an MSI expert that can help debug this?

**Comment by Badabum** [comment]
@brettsam sorry for being inactive. So for the setup, it's pretty simple and standard - Function App with configured User-Assigned managed identity. This identity is used in several other function apps as well. Then I have custom Function startup and configuration. This is how I'm relacing the configuration provided by the host with newly built.
```
public static IConfigurationServices BuildConfiguration(this IFunctionsHostBuilder builder)
        {
            var enhancedConfig = new ConfigurationServices();

            var descriptor = builder.Services.FirstOrDefault(d => d.ServiceType == typeof(IConfiguration));
            if (descriptor?.ImplementationInstance is IConfiguration configRoot)
            {
                enhancedConfig.AddConfiguration(configRoot);
                var config = enhancedConfig.Configuration;
                builder.Services.Replace(ServiceDescriptor.Singleton(typeof(IConfiguration), config));
            }

            return enhancedConfig;
        }
```
Then in `ConfigurationServices` I have following code that adds KeyVault configuration provider:
```
            AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider("RunAs=App; AppId=<removed guid of user-assigned managed identity>");

            KeyVaultClient.AuthenticationCallback authCallback = new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback);
            KeyVaultClient keyVaultClient = new KeyVaultClient(authCallback);

            builder.AddEnvironmentVariables()
                   .AddAzureKeyVault(KeyVaultConfig.VaultName, keyVaultClient, new DefaultKeyVaultSecretManager());
```
Strange thing is that it works normally for some amount of time and then starts to fail. AND for the last week it was working normally.

**Comment by brettsam** [comment]
The error is coming from custom configuration that we don't support (or monitor) by default, so I don't know that there's much the Functions team can do here. You were unable to connect, so the function app wasn't able to start up. I'm not sure how the KeyVault config provider should handle it, but stopping the site seems reasonable (you don't want to start up with missing config due to a connection error). We continuously retry to see if the issue is transient, and it appears that it eventually succeeded again (correct me if I'm wrong). Maybe there was an issue in the KeyVault or MSI side of things?

@mattchenderson / @Hamster-Huey -- is there anything that App Service does if a Function app tries to use KeyVault? Could something have happened in App Service to cause this connection failure?

For reference, the full stack and error is:

```
Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException : Parameters: Connection String: RunAs=App; AppId=-----, Resource: https://vault.azure.net, Authority: https://login.windows.net/-----. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: BadRequest, Response: 
   at async Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String authority,String resource,String scope,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<get_KeyVaultTokenCallback>b__8_0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.KeyVault.KeyVaultCredential.PreAuthenticate(Uri url)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl,Nullable`1 maxresults,Dictionary`2 customHeaders,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations,String vaultBaseUrl,Nullable`1 maxresults,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at feedme.platform.shared.Services.Application.ConfigurationServices.BuildAvailableConfiguration() at d:\a\1\s\feedme.platform.shared\Services\Application\ConfigurationServices.cs : 96
   at feedme.platform.shared.Services.Application.ConfigurationServices..ctor() at d:\a\1\s\feedme.platform.shared\Services\Application\ConfigurationServices.cs : 37
   at feedme.platform.shared.StartupExtensions.BuildConfiguration(IFunctionsHostBuilder builder) at d:\a\1\s\feedme.platform.shared\StartupExtensions.cs : 16
   at feedme.platform.api.Startup.Configure(IFunctionsHostBuilder builder) at d:\a\1\s\feedme.platform.api\Startup.cs : 18
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseWebJobsStartup(IWebJobsBuilder builder,Type startupType) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 74
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalStartup(IWebJobsBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 103
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.UseScriptExternalStartup(IWebJobsBuilder builder,String rootScriptPath,ILoggerFactory loggerFactory,IExtensionBundleManager extensionBundleManager) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\ScriptHostBuilderExtensions.cs : 208
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass3_0.<AddScriptHostCore>b__0(HostBuilderContext context,IWebJobsBuilder webJobsBuilder) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\ScriptHostBuilderExtensions.cs : 115
   at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureWebJobs>b__1(HostBuilderContext context,IServiceCollection services) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsHostBuilderExtensions.cs : 49
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(Boolean skipHostStartup,Boolean skipHostConfigurationParsing) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DefaultScriptHostBuilder.cs : 59
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.BuildHost(Boolean skipHostStartup,Boolean skipHostJsonConfiguration) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 378
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(CancellationToken cancellationToken,Int32 attemptCount,JobHostStartupMode startupMode) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 177
```
