### ISSUE TITLE
DryIoc.ContainerException : Container is disposed and should not be used: Container is disposed.

### ISSUE THREAD

**Issue by MaxHogervorst** [Azure/azure-functions-host#5034]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 10/7/2019 1:13:45 AM
- Function App version (1.0 or 2.0): 2.0
- Function App name: azf-umcloud-validations
- Function name(s) (as appropriate): orch-get-azure-usage-per-sub
- Invocation ID:
- Region: Australia East

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Run without errors

#### Actual behavior

Timestamp : 10/6/2019 8:42:29 PM
Inner Exception Type: DurableTask.Core.Exceptions.OrchestrationFailureException
Total Occurrences: 101
Latest Exception Message: Orchestrator function 'orch-get-azure-usage-per-sub' failed: One or more errors occurred. (Result: Failure Exception: Error: Cannot cancel a completed task. Stack: Error: Cannot cancel a completed task. at TimerTask.cancel (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\timertask.js:17:19) at timeoutActivity (D:\home\site\wwwroot\orch-get-azure-usage-per-sub\index.js:12:17) at timeoutActivity.next () at Orchestrator.fn (D:\home\site\wwwroot\orch-get-azure-usage-per-sub\index.js:29:37) at Generator.next () at Orchestrator. (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\orchestrator.js:95:29) at Generator.next () at D:\home\site\wwwroot\node_modules\durable-functions\lib\src\orchestrator.js:7:71 at new Promise () at __awaiter (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\orchestrator.js:3:12))

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by fabiocav** [comment]
@ConnorMcMahon we may need to review this in the context of what the JS implementation is doing. It's likely it is attempting to work against the container after the invocation has completed.

@MaxHogervorst is this causing an invocation exception?
