### ISSUE TITLE
Rpc.ScriptInvocationContextExtensions.GetRpcTraceContext "Key already Exists"

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#5054]
Some customers are getting duplicate key errors from the Rpc execution pipeline.
```
Stack Trace:

System.ArgumentException : Key already exists in map Parameter name: key
    at Google.Protobuf.Collections.MapField`2.Add(TKey key,TValue value)
    at Microsoft.Azure.WebJobs.Script.Rpc.ScriptInvocationContextExtensions.GetRpcTraceContext(String activityId,String traceStateString,IEnumerable`1 tags,ILogger logger) at /azure-functions-host-1725a6c52a213f9130429b5814df30bf9cf98fff/src/WebJobs.Script/Rpc/MessageExtensions/ScriptInvocationContextExtensions.cs : 63
    at Microsoft.Azure.WebJobs.Script.Rpc.ScriptInvocationContextExtensions.ToRpcInvocationRequest(ScriptInvocationContext context,Boolean isTriggerMetadataPopulatedByWorker,ILogger logger,Capabilities capabilities) at /azure-functions-host-1725a6c52a213f9130429b5814df30bf9cf98fff/src/WebJobs.Script/Rpc/MessageExtensions/ScriptInvocationContextExtensions.cs : 17
    at Microsoft.Azure.WebJobs.Script.Rpc.LanguageWorkerChannel.SendInvocationRequest(ScriptInvocationContext context) at /azure-functions-host-1725a6c52a213f9130429b5814df30bf9cf98fff/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs : 307
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at /azure-functions-host-1725a6c52a213f9130429b5814df30bf9cf98fff/src/WebJobs.Script/Description/Rpc/WorkerLanguageInvoker.cs : 82
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at /azure-functions-host-1725a6c52a213f9130429b5814df30bf9cf98fff/src/WebJobs.Script/Description/FunctionInvokerBase.cs : 85
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs : 20
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 585
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 532
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 470
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 278
```

**Comment by mathewc** [comment]
Might be related to recent changes https://github.com/Azure/azure-functions-host/commit/01441291af9d8fe550fa23b81a99c298d7bdfef5
