### ISSUE TITLE
The type initializer for 'Converter' threw an exception. Scope disposed{no name, Parent=disposed{no name}} is disposed and scoped instances are disposed and no longer available.

### ISSUE THREAD

**Issue by kgoderis** [Azure/azure-functions-host#5074]
Refers to https://github.com/Azure/azure-functions-host/issues/5060

This issue seems not be solved, not with the latest ~2 runtime or any other recent version
I get a massive amount of these errors since yesterday with no change from my side.

```
System.TypeInitializationException:
   at be.signdisplay.fieldwire.Project+<ReadOne>d__28.MoveNext (Flow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf569fd40f74a9d5Flow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf569fd40f74a9d5: D:\home\site\repository\shared\fieldwire\FieldwireProject.csFlow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf569fd40f74a9d5: 389)
Inner exception DryIoc.ContainerException handled at be.signdisplay.fieldwire.Project+<ReadOne>d__28.MoveNext:
   at DryIoc.Throw.It (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 8991)
   at DryIoc.Scope.TryGet (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 7881)
   at DryIoc.Container+InstanceFactory.GetAndUnwrapOrDefault (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 1480)
   at DryIoc.Container+InstanceFactory.GetInstanceFromScopeChainOrSingletons (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 1469)
   at DryIoc.Container.DryIoc.IResolver.Resolve (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 265)
   at lambda_method (Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
   at DryIoc.Container.DryIoc.IResolver.Resolve (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 195)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 101)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 79)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService (Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at be.signdisplay.fieldwire.FieldwireBase`2+Converter..cctor (Flow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf569fd40f74a9d5Flow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf569fd40f74a9d5: D:\home\site\repository\shared\fieldwire\FieldwireBase.csFlow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf569fd40f74a9d5: 245)
```

#### Investigative information

- Timestamp: 15/10/2019, 10:09:59 (Local time)
- Function App version (1.0 or 2.0): 2
- Function App name: sndflow
- Invocation ID: e6074a10-c0fc-4108-8ddd-9055e5d954d5 
- Region: West Europe

#### Related information 

I have the following code in place (shortened)

```csharp
    public class StartUp : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
     	builder.Services.AddTransient<DependencyInjectionContractResolver>();
     	}
     }
```

```csharp
    public class DependencyInjectionContractResolver : CamelCasePropertyNamesContractResolver
    {
        DependencyInjectionMetadataProvider mp;
        IServiceProvider sp;
        IServiceCollection sc;
        public DependencyInjectionContractResolver(DependencyInjectionMetadataProvider mp, IServiceProvider sp)
        {
            this.mp = mp;
            this.sp = sp;
        }

        protected override JsonObjectContract CreateObjectContract(Type objectType)
        {
            if (mp.IsRegistred(objectType))
            {
                JsonObjectContract contract = DependencyInjectionResolveContract(objectType);
                contract.DefaultCreator = () => sp.GetService(objectType);

                return contract;
            }

            return base.CreateObjectContract(objectType);
        }

        private JsonObjectContract DependencyInjectionResolveContract(Type objectType)
        {
            var fType = mp.RegistredTypeFor(objectType);
            if (fType != null) return base.CreateObjectContract(fType);
            else return CreateObjectContract(objectType);
        }
    }
```

```csharp
        public static class Converter
        {
            public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
            {
                ContractResolver = Provider.GetService<DependencyInjectionContractResolver>(),
                NullValueHandling = NullValueHandling.Ignore,
                MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
                DateParseHandling = DateParseHandling.None,
                Converters = {
                    NullableDateTimeOffsetConverter.Singleton,
                    GuidConverter.Singleton,
                    new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
                }
            };
        }
```

**Comment by kgoderis** [comment]
Why do we now suddenly get this? It is seemingly impossible to manually set the runtime version anymore

<img width="700" alt="image" src="https://user-images.githubusercontent.com/5459062/66817943-d4df7000-ef3c-11e9-9da7-dd1083dc5890.png">

**Comment by kgoderis** [comment]
Why do we suddenly get these? e.g. it is impossible to downgrade the runtime in order to test a solution for the issue above

<img width="825" alt="image" src="https://user-images.githubusercontent.com/5459062/66818171-343d8000-ef3d-11e9-9c74-1eeadcb44d5e.png">

**Comment by fabiocav** [comment]
@kgoderis in the converter code above, where is `Provider` coming from? How are you caching that instance?

Also, the previous deployed version was `2.0.12742.0`. `2.0.12775.0` is `2.0.12673.0` + patch

**Comment by kgoderis** [comment]
Part of the solution was to replace 

`                contract.DefaultCreator = () => sp.GetService(objectType);
`

with 

`                contract.DefaultCreator = () => ActivatorUtilities.CreateInstance(sp, objectType);
`

In fact, I have other locations in my code where I get similar errors when using sp.GetService() or sp.GetService<>, with each time sp being an injected IServiceProvider instance.

I have no clue why sp.GetService() does not work anymore

**Comment by kgoderis** [comment]
> @kgoderis in the converter code above, where is `Provider` coming from? How are you caching that instance?
> 
> Also, the previous deployed version was `2.0.12742.0`. `2.0.12775.0` is `2.0.12673.0` + patch

Provider is an assigned member of that class

`Provider = provider ?? throw new ArgumentNullException(nameof(provider));
`
with provider coming through the constructor

`        public FieldwireBase(TelemetryClient telemetryClient, IFlowCache cache, IFlowStorage storage, IFlowHelper flow, IFlowMutexProvider mutexProvider, IServiceProvider provider)`

**Comment by kgoderis** [comment]
> I'm suspecting you're caching an instance that is going out of scope.

That is what it looks like, but my code 'magically" ran ok for months, and it is broken since yesterday/today

The provider is coming through the constructor that declares/encapsulates the Converter class, which then, I presume, is the fully resolved service provider.

That being said, I also use Refit, and because of the parameterised initialisation of the service, I had to fiddle around and I also have some static intialisation of the members, which I trigger by means of a helper class (DepedencyProviderService)

```csharp            builder.Services.AddSingleton<IDependencyProviderService, DependencyProviderService>();```

```csharp 
    public class DependencyProviderService : IDependencyProviderService
    {
        public DependencyProviderService(TelemetryClient telemetryClient, IServiceProvider serviceProvider, IFlowCache cache, IFlowHelper flow, IFlowStorage storage, IFlowMutexProvider mutexProvider)
        {
           Attachment.Initialize(telemetryClient, serviceProvider, cache, flow, storage, mutexProvider);
   }
}
```

The Attachment class contains code like (There are some intermediate paramterized classes that I left out in this post)

```csharp 
        public Attachment(TelemetryClient telemetryClient, IFlowCache cache, IFlowStorage storage, IFlowHelper flow, IFlowMutexProvider mutexProvider, IServiceProvider provider)
            : base(telemetryClient, cache, storage, flow, mutexProvider, provider)
        {
            Initialize(telemetryClient, provider, cache, flow, storage, mutexProvider);
        }

        new public static void Initialize(TelemetryClient telemetryClient, IServiceProvider provider, IFlowCache cache, IFlowHelper flow, IFlowStorage storage, IFlowMutexProvider mutexProvider)
        {
            FieldwireBase<IFieldwireAttachmentAPI<Attachment, string, string>, Attachment>.Initialize(telemetryClient, provider, cache, flow, storage, mutexProvider);
        }
```

And the Initialze() of the base class FieldwireBase looks like

```csharp 
public static void Initialize(TelemetryClient telemetryClient, IServiceProvider provider, IFlowCache cache, IFlowHelper flow, IFlowStorage storage, IFlowMutexProvider mutexProvider)
        {
...
                //Moved JsonSetting initialisation away from the static Converter class
                JsonSettings = new JsonSerializerSettings
                {
                    ContractResolver = Provider.GetService<DependencyInjectionContractResolver>(),
                    NullValueHandling = NullValueHandling.Ignore,
                    MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
                    DateParseHandling = DateParseHandling.None,
                    Converters = {
                        NullableDateTimeOffsetConverter.Singleton,
                        GuidConverter.Singleton,
                        new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
                }
                };
...
          if (RestServiceClient == null && Provider != null)
            {
                IHttpClientFactory cf = Provider.GetService<IHttpClientFactory>();
                HttpClient namedClient = cf.CreateClient("fieldwire");
                RestServiceClient = RestService.For<U>(namedClient, new RefitSettings
                {
                    JsonSerializerSettings = JsonSettings
                });
            }
    }
```

**Comment by kgoderis** [comment]
@fabiocav Something is definitely wrong with the dependency injection. In the IWebJobsStartup startup class in Configure(IWebJobsBuilder builder) I add 4 named httpClients, all in the very same way, using

```
builder.Services.AddHttpClient("global",
                    c =>
                    {
                        c.Timeout = Timeout.InfiniteTimeSpan;
                    }). ....
```

but when inspecting the IHttpClientFactory that gets injected by the runtime, I notice

<img width="654" alt="image" src="https://user-images.githubusercontent.com/5459062/66865045-b8702180-ef96-11e9-89aa-94bffa7d21df.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/5459062/66866679-0aff0d00-ef9a-11e9-9821-0f8a199a4b3a.png">

 
that only 3 clients are properly registered with the factory, and when invoking a CreateClient on the missing one, the same Exception is thrown as mentioned in the first post of this issue

**Comment by kgoderis** [comment]
@fabiocav I have some more inputs regarding this issue. 

In my Function App, after running an hour or so fine, I suddenly get the above exception out of the blue. The function that is queue triggered is as follows:

```csharp
        public SharepointWebhookProcessor(TelemetryClient telemetryClient, IFlowConfig config, IFlowStorage storage, IAzure azure, IFlowSlotProvider slotProvider, IDependencyProviderService ds, IServiceProvider serviceProvider, IFlowMutexProvider mutexProvider)
        {
            this.TelemetryClient = telemetryClient ?? throw new ArgumentNullException(nameof(telemetryClient));
            this.Config = config ?? throw new ArgumentNullException(nameof(config));
            this.Storage = storage ?? throw new ArgumentNullException(nameof(storage));
            this.Azure = azure ?? throw new ArgumentNullException(nameof(azure));
            this.SlotProvider = slotProvider ?? throw new ArgumentNullException(nameof(slotProvider));
            this.ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
            this.MutexProvider = mutexProvider ?? throw new ArgumentNullException(nameof(mutexProvider));
        }

        [FunctionName(nameof(SharepointWebhookProcessor))]
        [Disable("AzureWebJobs." + nameof(SharepointWebhookProcessor) + ".Disabled")]
        [Singleton]
        public async void Run([QueueTrigger("sharepoint-webhook-event", Connection = "AzureWebJobsStorage")]string myQueueItem, ILogger log, Microsoft.Azure.WebJobs.ExecutionContext context)
        {
     ....
            // Somewhere in the code
            IHttpClientFactory cf = ServiceProvider.GetService<IHttpClientFactory>();
            httpClient = cf.CreateClient("azure");
        }
```

Suddenly, the IServiceProvider passed to the constructor goes out of scope. How is that possible?
Ok, it gets assigned to a local member, but I presume that before Run() is triggered, the class gets instantiated, and the constructor is properly called, right?

The stack trace is

```
DryIoc.ContainerException: Scope disposed{no name, Parent=disposed{no name}} is disposed and scoped instances are disposed and no longer available.
      at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 8991
      at DryIoc.Scope.TryGet(Object& item, Int32 id) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7881
      at DryIoc.Container.InstanceFactory.GetAndUnwrapOrDefault(IScope scope, Int32 factoryId) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 1480
      at DryIoc.Container.InstanceFactory.GetInstanceFromScopeChainOrSingletons(IResolverContext r) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 1469
      at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 308
      at lambda_method(Closure , IResolverContext )
      at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 224
      at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195
      at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
      at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
      at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
      at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
      at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1()
      at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
      at System.Lazy`1.CreateValue()
      at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
      at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
      at be.signdisplay.SharepointWebHookManager..ctor(AuthenticationResult sharepointAuthenticationResult, TelemetryClient telemetryClient, IFlowStorage storage, IFlowSlotProvider slotProvider, IServiceProvider serviceProvider) in D:\home\site\repository\shared\azure\SharepointWebhookManager.cs:line 31
      at be.signdisplay.SharepointWebhookProcessor.Run(String myQueueItem, ILogger log, ExecutionContext context) in D:\home\site\repository\sharepoint\SharepointWebhookProcessor.cs:line 104
```

**Comment by kgoderis** [comment]
> @kgoderis in the converter code above, where is `Provider` coming from? How are you caching that instance?
> 
> Also, the previous deployed version was `2.0.12742.0`. `2.0.12775.0` is `2.0.12673.0` + patch

@fabiocav Is there a way to discover what previously deployed versions are available? When I input some of the versions base don the release numbers of this repo then that does not work very well

**Comment by fabiocav** [comment]
@kgoderis having a static service provider cache may be leading to some of the issues you're seeing. It would be interesting to look at potential host restarts in your app, as that could potentially cause some of the issues you're seeing.

Could you share the timeframe you saw the issue above?

Also, for the HttpClient issue you've mentioned previously, is this something you can consistently repro? If so, would you mind sharing the repro code in a repo here?

**Comment by kgoderis** [comment]
@fabiocav I removed static references to the ServiceProvider, what now rests is the IServiceProvider and/or IHttpClientFactory going out of scope, with that last one being not static at all. I started seeing this as of yesterday. I will see if I can share a private repo with you

**Comment by fabiocav** [comment]
Thank you! One thing that would also be helpful to understand is if you're following a pattern where you're kicking off any background work that runs beyond the function invocation lifetime (e.g. background threads, unobserved tasks, etc.)

**Comment by kgoderis** [comment]
@fabiocav I have sent you an access code to our repo to your microsoft email address

**Comment by kgoderis** [comment]
For all completeness, I noticed that I was using

`[assembly: WebJobsStartup(typeof(StartUp))]`

whereas nowadays it is documented that it should be done via

`[assembly: FunctionsStartup(typeof(StartUp))]`

Not sure if this is of any importance. 

I have implemented a partial work-around by adding

```csharp
builder.Services.AddHttpContextAccessor();
builder.Services.AddSingleton<IServiceProviderProxy, HttpContextServiceProviderProxy>();
          ServiceLocator.Initialize(builder.Services.BuildServiceProvider().GetService<IServiceProviderProxy>());

```
to Configure(IFunctionsHostBuilder builder)

and defining a ServiceLocator class as follows

```sharp
    public interface IServiceProviderProxy
    {
        T GetService<T>();
        IEnumerable<T> GetServices<T>();
        object GetService(Type type);
        IEnumerable<object> GetServices(Type type);
        IServiceProvider GetProvider();
    }

    public static class ServiceLocator
    {
        private static IServiceProviderProxy diProxy;

        public static IServiceProviderProxy ServiceProvider => diProxy ?? throw new Exception("You should Initialize the ServiceProvider before using it.");

        public static void Initialize(IServiceProviderProxy proxy)
        {
            diProxy = proxy;
        }

        public static IServiceProvider GetProvider()
        {
            return ServiceProvider.GetProvider();
        }
    }

    public class HttpContextServiceProviderProxy : IServiceProviderProxy
    {
        private readonly IHttpContextAccessor contextAccessor;

        public HttpContextServiceProviderProxy(IHttpContextAccessor contextAccessor)
        {
            this.contextAccessor = contextAccessor;
        }

        public T GetService<T>()
        {
            return contextAccessor.HttpContext.RequestServices.GetService<T>();
        }

        public IEnumerable<T> GetServices<T>()
        {
            return contextAccessor.HttpContext.RequestServices.GetServices<T>();
        }

        public object GetService(Type type)
        {
            return contextAccessor.HttpContext.RequestServices.GetService(type);
        }

        public IEnumerable<object> GetServices(Type type)
        {
            return contextAccessor.HttpContext.RequestServices.GetServices(type);
        }

        public IServiceProvider GetProvider()
        {
            return contextAccessor.HttpContext.RequestServices;
        }
    }
```

which then can be called like

`IHttpClientFactory cf = ServiceLocator.GetProvider().GetService<IHttpClientFactory>();`

or

`IHttpClientFactory cf = ServiceLocator.ServiceProvider.GetService<IHttpClientFactory>();` when using the proxy class

**Comment by heikkilamarko** [comment]
Same here. As a fix to Azure Functions DI issues, we had the following pinning in place (FUNCTIONS_EXTENSION_VERSION = 2.0.12673.0). After this pinning stopped working our function DI has been broken again.

**Comment by fabiocav** [comment]
@heikkilamarko could you please open a separate issue ans share the details of your code (service registration, pattern for accessing the service, etc.). Even though the exception message might be the same, the issue above is pretty specific to the pattern being used.

**Comment by heikkilamarko** [comment]
Done #5098

**Comment by kgoderis** [comment]
@fabiocav I close this one as I have rewritten our code so that it uses cached IHttpClient instead

**Comment by t-l-k** [comment]
@fabiocav I believe I reproduced the HttpClient issues in a repo for ticket #4914 BTW
