### ISSUE TITLE
I tried Entity Framework Core 3 (netstandard2.1) with Azure Functions v3 (netcoreapp3.0), an error occurred in Metadata Generator.

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#5106]
I tried Entity Framework Core 3 (netstandard2.1) with Azure Functions v3 (netcoreapp3.0), an error occurred in Metadata Generator.

```
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 指定されたファイルが見つかりません。
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes()
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun()
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Error generating functions metadata
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Metadata generation failed.
```

#### Repro

1. Create new function v3 project and change TFM to `netcoreapp3.0`
2. Install Entity Framework Core 3 (`Microsoft.EntityFrameworkCore.SqlServer`)
3. Add `DbContext` implementation
4. Build

_Originally posted by @shibayan in https://github.com/Azure/app-service-announcements-discussions/issues/115#issuecomment-543479631_

**Comment by ngg** [comment]
I have the same issue, I'm using .NET Core 3.0.100 on Linux.
Minimal repro case:

test.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.30-beta2" />
  </ItemGroup>
</Project>
```

Program.cs:
```csharp
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace TestNamespace
{
    public partial class TestDb : DbContext
    {
    }

    public static class TestClass
    {
        [FunctionName("testfunc")]
        public static void TestFunc([HttpTrigger(AuthorizationLevel.Anonymous, "get")]HttpRequest req)
        {
        }
    }
}
```

`dotnet build` fails with:
```
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :  [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes() [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons() [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun() [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :  [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :  [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Error generating functions metadata [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :  [/tmp/test/test.csproj]
/home/ngg/.nuget/packages/microsoft.net.sdk.functions/1.0.30-beta2/build/Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Metadata generation failed. [/tmp/test/test.csproj]
```

**Comment by andrewduffy77** [comment]
I'm getting this also.....

**Comment by SimonOrdo** [comment]
Weirdest thing.  My implementation WAS working locally, until I tried doing a WebPublish to Azure.  After that, it keeps blowing up with the same error as noted above.

**Comment by gblmarquez** [comment]
Same here!

**Comment by a-vishar** [comment]
Can this please be triaged?  This has been open for weeks and it's just being ignored.
