### ISSUE TITLE
Dependency Injection : ValueFactory attempted to access the Value property of this instance.

### ISSUE THREAD

**Issue by kgoderis** [Azure/azure-functions-host#5109]
This is a follow up on issue https://github.com/Azure/azure-functions-host/issues/5074

In FunctionStartup (FYI same error when using IWebJobsStartup) I have this:

```csharp    
 builder.Services.AddHttpClient("global",...... //shortened
 builder.Services.AddSingleton<ServiceDependencyInjectionProxy>();
 builder.Services.AddSingleton<SharepointServiceProvider>();
```

```csharp
    public class SharepointServiceProvider
    {
        private readonly ServiceDependencyInjectionProxy Proxy;
        private readonly HttpClient HttpClient;

        public SharepointServiceProvider(ServiceDependencyInjectionProxy proxy)
        {
            this.Proxy = proxy ?? throw new ArgumentNullException(nameof(proxy));
            HttpClient = Proxy.HttpClientFactory.CreateClient("global");
            HttpClient.Timeout = Timeout.InfiniteTimeSpan;
        }
    }
```

and ServiceDependencyInjectionProxy is getting IHttpClientFactory injected in its constructor.

I get the following thrown at me 

```csharp
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'ValueFactory attempted to access the Value property of this instance.'
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at be.signdisplay.SharepointServiceProvider..ctor(ServiceDependencyInjectionProxy proxy)
```

when SharepointServiceProvider is getting injected in any other constructor

**Comment by kgoderis** [comment]
Maybe this is misunderstanding from my side, but I thought that the HttpClientFactory was registered as a singleton, and thus, that it would be thread-safe.

When I add the following line to the constructor (and make HttpClient non readonly)

`            Task.Run(() => { HttpClient = Proxy.HttpClientFactory.CreateClient("global"); });
`
in order to off-load the client creation to a different thread, the exception is not thrown.

Maybe some can enlighten me ?

**Comment by fabiocav** [comment]
Sorry about the delay. Just looking at the stack and your latest update, but this does seem like an issue with t he HttpClientFactory. Would need to take a closer look to validate.
