### ISSUE TITLE
Functions host is crashing when AzureWebJobsDashboard app setting is set

### ISSUE THREAD

**Issue by divyagandhii** [Azure/azure-functions-host#5167]
`System.FormatException : No valid combination of account information found.
    at Microsoft.WindowsAzure.Storage.CloudStorageAccount.<>c.<Parse>b__97_0(String err)
    at Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseImpl(String connectionString,CloudStorageAccount& accountInformation,Action1 error)
    at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)
    at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger..ctor(IFunctionMetadataManager metadataManager,IProxyMetadataManager proxyMetadataManager,IMetricsLogger metrics,IHostIdProvider hostIdProvider,IConfiguration configuration,ILoggerFactory loggerFactory) at /azure-functions-host-b9807ebab1b8084dd0aae8b8d20953c6f2bf6972/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs : 57
    at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogCollectorProvider.Create() at /azure-functions-host-b9807ebab1b8084dd0aae8b8d20953c6f2bf6972/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogCollectorProvider.cs : 35
`

**Comment by balag0** [comment]
Is this crashing even for valid storage connection strings?
