### ISSUE TITLE
Handle WorkerErrorEvent in placeholder mode 

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#5207]
Null ref if WorkerErrorEvent thrown in placeholder mode

2019-11-05T18:02:12.6187618Z stderr F Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2019-11-05T18:02:12.6187618Z stderr F    at Microsoft.Azure.WebJobs.Script.Rpc.RpcFunctionInvocationDispatcher.ShouldRestartWorkerChannel(String runtime, Boolean isWebHostChannel, Boolean isJobHostChannel) in /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 320
2019-11-05T18:02:12.6187618Z stderr F    at Microsoft.Azure.WebJobs.Script.Rpc.RpcFunctionInvocationDispatcher.DisposeAndRestartWorkerChannel(String runtime, String workerId) in /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 311
2019-11-05T18:02:12.6187618Z stderr F    at Microsoft.Azure.WebJobs.Script.Rpc.RpcFunctionInvocationDispatcher.WorkerError(WorkerErrorEvent workerError) in /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 284
2019-11-05T18:02:12.6187618Z stderr F    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-11-05T18:02:12.6187618Z stderr F --- End of stack trace from previous location where exception was thrown ---
2019-11-05T18:02:12.6257798Z stderr F    at System.Threading.ThreadPoolWorkQueue.Dispatch()System.NullReferenceException: Object reference not set to an instance of an object.
2019-11-05T18:02:12.6257798Z stderr F    at Microsoft.Azure.WebJobs.Script.Rpc.RpcFunctionInvocationDispatcher.ShouldRestartWorkerChannel(String runtime, Boolean isWebHostChannel, Boolean isJobHostChannel) in /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 320
2019-11-05T18:02:12.6257798Z stderr F    at Microsoft.Azure.WebJobs.Script.Rpc.RpcFunctionInvocationDispatcher.DisposeAndRestartWorkerChannel(String runtime, String workerId) in /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 311
2019-11-05T18:02:12.6257798Z stderr F    at Microsoft.Azure.WebJobs.Script.Rpc.RpcFunctionInvocationDispatcher.WorkerError(WorkerErrorEvent workerError) in /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 284
2019-11-05T18:02:12.6257798Z stderr F    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-11-05T18:02:12.6257798Z stderr F --- End of stack trace from previous location where exception was thrown ---
2019-11-05T18:02:12.6257798Z stderr F    at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by mhoeger** [comment]
cc: @pragnagopa and @divyagandhii
