### ISSUE TITLE
Function on Linux Consumption plan stopped working

### ISSUE THREAD

**Issue by Fabian-Schmidt** [Azure/azure-functions-host#5211]
#### Investigative information

Please provide the following:

- Function App version: 2.0
- Function App name: DevFabian2Durable
- Region: Australia East
- FUNCTIONS_EXTENSION_VERSION: ~2
- FUNCTIONS_WORKER_RUNTIME: dotnet

#### Repro steps

Azure Function on Linux Consumption plan does no longer start.

Application Insight logging:
```
Version ~2 is not supported for language python
System.NotSupportedException:
   at Microsoft.Azure.WebJobs.Script.Rpc.RpcWorkerDescription.ValidateRuntimeVersion (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/RpcWorkerDescription.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 141)
   at Microsoft.Azure.WebJobs.Script.Rpc.RpcWorkerDescription.ValidateWorkerPath (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/RpcWorkerDescription.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 115)
   at Microsoft.Azure.WebJobs.Script.Rpc.WorkerConfigFactory.GetHydratedWorkerPath (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/Configuration/WorkerConfigFactory.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 253)
   at Microsoft.Azure.WebJobs.Script.Rpc.WorkerConfigFactory.AddProvider (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/Configuration/WorkerConfigFactory.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 142)
```

The function is pure .NET Core 2.2. No python is used.
The function was working 2 days ago. Assumption is something in the Azure Function Host has changed triggering this issue.

#### Expected behavior

Azure Function is woking.

#### Actual behavior

Azure Function is not starting.
HTTP calls result in `Function host is not running.`

**Comment by divyagandhii** [comment]
@Fabian-Schmidt  The python worker failing to launch here is by design for non-python apps. This is the actual exception causing the problem-

`System.ArgumentNullException : Value cannot be null. Parameter name: type
    at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.GetAllProperties(TypeInfo type)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration,Object instance,BinderOptions options)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type,Object instance,IConfiguration config,BinderOptions options)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindDictionary(Object dictionary,Type dictionaryType,IConfiguration config,BinderOptions options)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type,Object instance,IConfiguration config,BinderOptions options)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property,Object instance,IConfiguration config,BinderOptions options)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration,Object instance,BinderOptions options)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type,Object instance,IConfiguration config,BinderOptions options)
    at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration,Object instance,Action`1 configureOptions)
    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
    at Microsoft.Azure.WebJobs.Hosting.WebJobsOptionsFactory`1.Create(String name) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\OptionsFormatter\WebJobsOptionsFactory.cs : 37
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)
    at System.Lazy`1.CreateValue()
    at Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProviderFactory..ctor(IOptions1 options,IConnectionStringResolver connectionStringResolver) at d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\AzureStorageDurabilityProviderFactory.cs : 24`

**Comment by Fabian-Schmidt** [comment]
Thanks for the stack trace.

I found that `Microsoft.Azure.WebJobs.Extensions.DurableTask` changed the `host.json` configuration without proper documentation in breaking changes from beta to GA.

They removed the `azureStorage` configuration sub node under `storageProvider`.

Thank you for helping me figuring it out.

**Comment by thelgevold** [comment]
@Fabian-Schmidt Did you find a way to prevent the error from showing up in the logs?
