### ISSUE TITLE
HttpTrigger-Node: req.body for a HTTP post request returns an object of type string and makes the properties undefined

### ISSUE THREAD

**Issue by kaffeskogen** [Azure/azure-functions-host#5301]
- Timestamp: 2019-11-26 20:33 UTC
- Function App version (1.0 or 2.0): 2.0.12888.0
- Invocation ID: 19967757-184b-4ffd-ae4f-a647e428b4f5
- Region: West EU

#### Issue
`req.body` is of type `string` instead of `object` which seems to make the body properties "unreachable".

#### Repro steps
Created a node function in the portal with the following code:

```javascript
module.exports = async function (context, req) {
    context.log('JavaScript trigger function processed a request.');
    context.log(req.body);
    context.log(typeof req.body);
    const { pattern, flags, input } = req.body;
    context.log(pattern, flags, input)
    context.res = {
        status: 202
    };
};
```

Log:
```log
2019-11-26T20:36:57.415 [Information] Executing 'functionname' (Reason='This function was programmatically called via the host APIs.', Id=19967757-184b-4ffd-ae4f-a647e428b4f5)
2019-11-26T20:36:58.070 [Information] JavaScript trigger function processed a request.
2019-11-26T20:36:58.071 [Information] {
    "pattern": "test",
    "flags": "g",
    "input": "this is a test",
}
2019-11-26T20:36:58.072 [Information] string
2019-11-26T20:36:58.072 [Information] undefined undefined undefined
2019-11-26T20:36:58.073 [Information] Executed 'functionname' (Succeeded, Id=19967757-184b-4ffd-ae4f-a647e428b4f5)
```

As you can see in the log, the request body contains a simple json-object but is inferred as a string, and the properties is nothing but undefined. 

I've tried to go around the issue by parsing it with `JSON.parse()`, but it returns an error:

```
Result: Failure
Exception: SyntaxError: Unexpected token } in JSON at position 78
Stack: SyntaxError: Unexpected token } in JSON at position 78
    at JSON.parse (<anonymous>)
    at module.exports (D:\home\site\wwwroot\functionname\index.js:4:22)
    at WorkerChannel.invocationRequest (D:\Program Files (x86)\SiteExtensions\Functions\2.0.12888\32bit\workers\node\worker-bundle.js:16636:26)
    at ClientDuplexStream.WorkerChannel.eventStream.on (D:\Program Files (x86)\SiteExtensions\Functions\2.0.12888\32bit\workers\node\worker-bundle.js:16503:30)
    at ClientDuplexStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:219:10)
    at Object.onReceiveMessage (D:\Program Files (x86)\SiteExtensions\Functions\2.0.12888\32bit\workers\node\worker-bundle.js:20589:19)
    at InterceptingListener.module.exports.InterceptingListener.recvMessageWithContext (D:\Program Files (x86)\SiteExtensions\Functions\2.0.12888\32bit\workers\node\worker-bundle.js:19904:19)
```

**Comment by kaffeskogen** [comment]
Turns out i was sending a comma too much in the request

```
{
    "pattern": "test",
    "flags": "g",
    "input": "this is a test", // <---
}
````
