### ISSUE TITLE
Newtonsoft.Json.dll is loaded twice in version 3.0.12930.0 of the Azure runtime and versions 3.0.4 and 3.1.0 of AzureFunctionTools

### ISSUE THREAD

**Issue by MyselfWhat** [Azure/azure-functions-host#5360]
We are developing an Azure Function using Event Grid Triggers which are triggered by blob storage uploads. The function signature is as follows:
```csharp
public async Task Run(
	[EventGridTrigger]EventGridEvent eventGridEvent,
	[Blob("{data.url}", FileAccess.ReadWrite)] CloudBlockBlob blob,
	ILogger log)
```

This was previously working, but when testing yesterday (9 December 2019) we encountered the following error
```
Error while accessing 'url': Ambiguous match found.
   at Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplateToken.ExpressionToken.Evaluate(IReadOnlyDictionary`2 bindingData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Path\BindingTemplateToken.cs:line 197
   at Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplate.Bind(IReadOnlyDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Path\BindingTemplate.cs:line 110
   at Microsoft.Azure.WebJobs.DefaultResolutionPolicy.TemplateBind(PropertyInfo propInfo, Attribute attribute, BindingTemplate template, IReadOnlyDictionary`2 bindingData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\DefaultResolutionPolicy.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.TemplateBind(IResolutionPolicy policy, PropertyInfo prop, Attribute attr, BindingTemplate template, IReadOnlyDictionary`2 bindingData, Action`1 validator) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 376
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.<>c__DisplayClass13_0.<GetTemplateResolver>b__0(Attribute newAttr, IReadOnlyDictionary`2 bindingData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 262
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.<>c__DisplayClass20_0.<ResolveFromBindings>b__0(Func`3 func) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 357
   at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.ResolveFromBindings(IReadOnlyDictionary`2 bindingData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 357
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingBase`1.BindAsync(BindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingBase.cs:line 49
   at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync(ValueBindingContext context, Object value, IDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 98
```

#### Investigation

Using the VS debugger, we were able to determine that the exception was occurring in the GetProperty method from https://github.com/Azure/azure-webjobs-sdk/blob/v3.0.14/src/Microsoft.Azure.WebJobs.Host/Bindings/Path/BindingTemplateToken.cs shown below (refer to my comments with // >>>):
```csharp
public static object GetProperty(object o, string member)
{
	Type scope = o.GetType();

	// >>> Debugger indicated that o is a JObject, however this cast fails so jobj is null
	JObject jobj = o as JObject;
	if (jobj != null)
	{
		........
	}

	object result;
	// >>> TryGetValue uses reflection to obtain a method named TryGetValue on object.
	// >>> JObject contains multiple overloads for TryGetValue, so this is what
	// >>> triggers the "Ambiguous match found." error message
	if (TryGetValue(o, member, out result))
	{
		........
	}

	........
```

Further investigation revealed that the reason the object failed to cast to a JObject instance was that the type associated with the `o` object passed in to `GetProperty` was from a different assembly than the reference to `JObject` on the cast.

Referring to the Debug > Modules window in Visual Studio when running locally, we can see that there is an instance of Newtonsoft.Json loaded from `%USERPROFILE%\AppData\Local\AzureFunctionsTools\Releases\3.0.4\cli_x64` **and** another instance loaded from `bin\netcoreapp3.0\bin\Newtonsoft.Json.dll`. 
When attaching a debugger to the instance running in Azure Functions, there is similar behaviour where the dll is loaded from both `D:\Program Files (x86)\SiteExtensions\Functions\3.0.12930\32bit\Newtonsoft.Json.dll` and`bin\netcoreapp3.0\bin\Newtonsoft.Json.dll`.

This behaviour is **not** present in version 3.0.2 of the AzureFunctionTools, however I'm not able to determine the version where this issue started occurring in Azure Functions as I cannot select a specific runtime version.

#### Repro steps

 - Create an Azure Function (v3) with an EventGridTrigger
 - Run this in Visual Studio and ensure that the cli is either version 3.0.4 or 3.1.0
 - Open the Debug > Windows > Modules window
 - Filter by **Newtonsoft.Json**

#### Expected behaviour
 A single dll for Newtonsoft.Json.dll is listed.

#### Actual behaviour
Multiple Newtonsoft.Json.dll files are listed.

#### Workaround

We have implemented a workaround which deletes the Newtonsoft.Json.dll from the bin folder with the following post build event, however this is obviously not an ideal solution :)

```xml
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    .......
    <Exec Command="del $(OutDir)bin\Newtonsoft.Json.dll" />
  </Target>
```

**Comment by fabiocav** [comment]
@MyselfWhat apologies for the delayed response. This has been addressed with a release that has been deployed to Azure (3.0.12939). Can you please test with that release and let us know if you're having problems? 

The Azure Functions Core Tolls update for that version will be released early next week.

**Comment by MyselfWhat** [comment]
@fabiocav thanks so much for the update, I've just tested in Azure and the issue is indeed resolved :)

**Comment by fabiocav** [comment]
Closing as resolved.
