### ISSUE TITLE
Function language not always set in metadata when indexed 

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#5420]
Edited description after input from Fabio:
[LanguageWorkerOptions](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/Configuration/LanguageWorkerOptionsSetup.cs) appear to not always be the correct value for the JobHost instance. 

In one case, we saw a node placeholder app (which only reads node configs) specialized to a powershell function app (which requires a powershell config) fail to initialized with a null ref. Likely, the invalidation / change token isn't being used correctly to ensure correct ordering before reading the latest LanguageWorkerOptions.

This race condition manifests as a null ref when validating a functions. The null value comes from this code to [ParseLanguage](https://github.com/Azure/azure-functions-host/blob/7c6ae82f215282c3d936cf9bb21b897d971933a0/src/WebJobs.Script/Host/FunctionMetadataProvider.cs#L165-L189) of the function. This code also needs revisiting to guard against future null refs.

Exception example:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Script.Utility.<>c__DisplayClass44_0.<ContainsFunctionWithWorkerRuntime>b__1(FunctionMetadata f) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 595
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source,Func`2 predicate)
   at Microsoft.Azure.WebJobs.Script.Utility.ContainsFunctionWithWorkerRuntime(IEnumerable`1 functions,String workerRuntime) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 595
   at Microsoft.Azure.WebJobs.Script.Utility.IsSingleLanguage(IEnumerable`1 functions,String workerRuntime) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 546
   at Microsoft.Azure.WebJobs.Script.Utility.VerifyFunctionsMatchSpecifiedLanguage(IEnumerable`1 functions,String workerRuntime,Boolean isPlaceholderMode,Boolean isHttpWorker) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 518
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.GetFunctionDescriptorsAsync(IEnumerable`1 functions,IEnumerable`1 descriptorProviders) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 668
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFunctionDescriptorsAsync(IEnumerable`1 functionMetadata) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 488
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 288
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 244
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 235
```

cc: @fabiocav

**Comment by mhoeger** [comment]
@pragnagopa - this is the new issue I opened

**Comment by pragnagopa** [comment]
Assigned this to Sprint 67. Will investigate.

**Comment by pragnagopa** [comment]
Related issue#4574
A recent optimization done in commit #https://github.com/Azure/azure-functions-host/commit/9ec12339f5c38d28f9644dc594482e7a7fac50a6, LanguageWorkerOptions when the app starts in placeholder mode only loaded worker provider for the language set by AppSetting 'FUNCTIONS_WORKER_RUNTIME`

This resulted in worker config not found for a given language if worker runtime did not match before and after specialization.

Loading all the worker configs in placeholder mode will solve this issue. In future, issues like this can be avoided by fixing #4574

**Comment by nuno-tiago-reis** [comment]
Hello, is there any workaround for this issue? I had a FunctionApp that was working previously but now I'm getting the same exception from the original comment. If not, when will the fix in #5454 be available?

**Comment by pragnagopa** [comment]
@nuno-tiago-reis - We are in the process of release fix for this issue. Can you please share either
- Function App name or
- Invocation Id, FunctionApp region and approximate timerage you saw the error?

**Comment by nuno-tiago-reis** [comment]
@pragnagopa 

The function app name is 'med-dev-log-engine-api'. However the error hasn't occurred again, I'm not sure exactly when it started since it seems to randomly happen after some time.

I know that the error occured yesterday, 21-01-2020, after 10:30 GMT. I'm not sure about the specific time, sorry.
