### ISSUE TITLE
[HTTPWorker]Invoking HttpTrigger with input bindings using Auth key throws exception

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#5425]
#### Repro steps

1. Clone repo https://github.com/anthonychu/test-httpworker
1. Create local.settings.json and add storage connection string
1. Create a blob container named `foo` in the storage account, place a file in there named `bar.txt`
1. Run the app with `func start`
1. Upload a new file into the container and function `BlobTrigger` runs successfully.
1. Invoking `HttpBlobInput` function which has a blob input binding throws an exception. `System.Private.CoreLib: Exception while executing function: Functions.HttpBlobInput. Newtonsoft.Json: Self referencing loop detected for property 'Subject' with type 'System.Security.Claims.ClaimsIdentity'. Path '[0].Claims[0]'.`

I had the same error with a SignalR input binding.

#### Expected behavior

Function should work, passing blob input metadata to HTTP worker.

#### Actual behavior

Exception:

```
antchu-macbook:test-httpworker antchu$ func start
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1948 Commit hash: 29a0626ded3ae99c4111f66763f27bb9fb564103)
Function Runtime Version: 2.0.12888.0
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]
[2019-12-28 7:17:59 AM] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '9fa390b0-09a8-4a8c-849c-dbdae9967664'
[2019-12-28 7:17:59 AM] Reading host configuration file '/Users/antchu/source/temp/test-httpworker/host.json'
[2019-12-28 7:17:59 AM] Host configuration file read:
[2019-12-28 7:17:59 AM] {
[2019-12-28 7:17:59 AM]   "version": "2.0",
[2019-12-28 7:17:59 AM]   "extensionBundle": {
[2019-12-28 7:17:59 AM]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2019-12-28 7:17:59 AM]     "version": "[1.*, 2.0.0)"
[2019-12-28 7:17:59 AM]   }
[2019-12-28 7:17:59 AM] }
[2019-12-28 7:17:59 AM] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /var/folders/8z/8jgdqh2d34s_zl_0n0m_42640000gn/T/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2019-12-28 7:17:59 AM] Found a matching extension bundle at /var/folders/8z/8jgdqh2d34s_zl_0n0m_42640000gn/T/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.1.1
[2019-12-28 7:17:59 AM] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2019-12-28 7:17:59 AM] Skipping bundle download since it already exists at path /var/folders/8z/8jgdqh2d34s_zl_0n0m_42640000gn/T/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.1.1
[2019-12-28 7:17:59 AM] Loading Extention bundle from /var/folders/8z/8jgdqh2d34s_zl_0n0m_42640000gn/T/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.1.1
[2019-12-28 7:17:59 AM] Reading functions metadata
[2019-12-28 7:17:59 AM] 3 functions found
[2019-12-28 7:17:59 AM] Loading startup extension 'AzureStorage'
[2019-12-28 7:17:59 AM] Loaded extension 'AzureStorage' (3.0.10.0)
[2019-12-28 7:18:00 AM] Initializing Warmup Extension.
[2019-12-28 7:18:00 AM] Initializing Host. OperationId: '9fa390b0-09a8-4a8c-849c-dbdae9967664'.
[2019-12-28 7:18:00 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=9fa390b0-09a8-4a8c-849c-dbdae9967664
[2019-12-28 7:18:00 AM] LoggerFilterOptions
[2019-12-28 7:18:00 AM] {
[2019-12-28 7:18:00 AM]   "MinLevel": "None",
[2019-12-28 7:18:00 AM]   "Rules": [
[2019-12-28 7:18:00 AM]     {
[2019-12-28 7:18:00 AM]       "ProviderName": null,
[2019-12-28 7:18:00 AM]       "CategoryName": null,
[2019-12-28 7:18:00 AM]       "LogLevel": null,
[2019-12-28 7:18:00 AM]       "Filter": "<AddFilter>b__0"
[2019-12-28 7:18:00 AM]     },
[2019-12-28 7:18:00 AM]     {
[2019-12-28 7:18:00 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2019-12-28 7:18:00 AM]       "CategoryName": null,
[2019-12-28 7:18:00 AM]       "LogLevel": "None",
[2019-12-28 7:18:00 AM]       "Filter": null
[2019-12-28 7:18:00 AM]     },
[2019-12-28 7:18:00 AM]     {
[2019-12-28 7:18:00 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2019-12-28 7:18:00 AM]       "CategoryName": null,
[2019-12-28 7:18:00 AM]       "LogLevel": null,
[2019-12-28 7:18:00 AM]       "Filter": "<AddFilter>b__0"
[2019-12-28 7:18:00 AM]     }
[2019-12-28 7:18:00 AM]   ]
[2019-12-28 7:18:00 AM] }
[2019-12-28 7:18:00 AM] FunctionResultAggregatorOptions
[2019-12-28 7:18:00 AM] {
[2019-12-28 7:18:00 AM]   "BatchSize": 1000,
[2019-12-28 7:18:00 AM]   "FlushTimeout": "00:00:30",
[2019-12-28 7:18:00 AM]   "IsEnabled": true
[2019-12-28 7:18:00 AM] }
[2019-12-28 7:18:00 AM] SingletonOptions
[2019-12-28 7:18:00 AM] {
[2019-12-28 7:18:00 AM]   "LockPeriod": "00:00:15",
[2019-12-28 7:18:00 AM]   "ListenerLockPeriod": "00:00:15",
[2019-12-28 7:18:00 AM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2019-12-28 7:18:00 AM]   "LockAcquisitionPollingInterval": "00:00:05",
[2019-12-28 7:18:00 AM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2019-12-28 7:18:00 AM] }
[2019-12-28 7:18:00 AM] QueuesOptions
[2019-12-28 7:18:00 AM] {
[2019-12-28 7:18:00 AM]   "BatchSize": 16,
[2019-12-28 7:18:00 AM]   "NewBatchThreshold": 8,
[2019-12-28 7:18:00 AM]   "MaxPollingInterval": "00:00:02",
[2019-12-28 7:18:00 AM]   "MaxDequeueCount": 5,
[2019-12-28 7:18:00 AM]   "VisibilityTimeout": "00:00:00"
[2019-12-28 7:18:00 AM] }
[2019-12-28 7:18:00 AM] BlobsOptions
[2019-12-28 7:18:00 AM] {
[2019-12-28 7:18:00 AM]   "CentralizedPoisonQueue": false
[2019-12-28 7:18:00 AM] }
[2019-12-28 7:18:00 AM] HttpOptions
[2019-12-28 7:18:00 AM] {
[2019-12-28 7:18:00 AM]   "DynamicThrottlesEnabled": false,
[2019-12-28 7:18:00 AM]   "MaxConcurrentRequests": -1,
[2019-12-28 7:18:00 AM]   "MaxOutstandingRequests": -1,
[2019-12-28 7:18:00 AM]   "RoutePrefix": "api"
[2019-12-28 7:18:00 AM] }
[2019-12-28 7:18:00 AM] Starting JobHost
[2019-12-28 7:18:00 AM] Starting Host (HostId=antchumacbook-867775539, InstanceId=d197798e-b5c3-4852-a7dd-333a5be075c0, Version=2.0.12888.0, ProcessId=22668, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2019-12-28 7:18:00 AM] Loading functions metadata
[2019-12-28 7:18:00 AM] 3 functions loaded
[2019-12-28 7:18:00 AM] Starting worker process:node  "/Users/antchu/source/temp/test-httpworker/server.js" --workerId afb47e0b-2636-4502-9594-ff731f81718d --port 60105
[2019-12-28 7:18:00 AM] node process with Id=22680 started
[2019-12-28 7:18:01 AM] Generating 3 job function(s)
[2019-12-28 7:18:01 AM] Found the following functions:
[2019-12-28 7:18:01 AM] Host.Functions.HttpTrigger
[2019-12-28 7:18:01 AM] Host.Functions.HttpBlobInput
[2019-12-28 7:18:01 AM] Host.Functions.BlobTrigger
[2019-12-28 7:18:01 AM] 
[2019-12-28 7:18:01 AM] Initializing function HTTP routes
[2019-12-28 7:18:01 AM] Mapped function route 'api/HttpTrigger' [get,post] to 'HttpTrigger'
[2019-12-28 7:18:01 AM] Mapped function route 'api/HttpBlobInput' [get,post] to 'HttpBlobInput'
[2019-12-28 7:18:01 AM] 
[2019-12-28 7:18:01 AM] Host initialized (974ms)

Http Functions:

        HttpTrigger: [GET,POST] http://localhost:7071/api/HttpTrigger

        HttpBlobInput: [GET,POST] http://localhost:7071/api/HttpBlobInput

[2019-12-28 7:18:01 AM] Host started (1136ms)
[2019-12-28 7:18:01 AM] Job host started
[2019-12-28 7:18:01 AM] port60105
Hosting environment: Production
Content root path: /Users/antchu/source/temp/test-httpworker
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[2019-12-28 7:18:07 AM] Host lock lease acquired by instance ID '000000000000000000000000A9DD002B'.
[2019-12-28 7:19:04 AM] Executing HTTP request: {
[2019-12-28 7:19:04 AM]   "requestId": "e0938e92-81db-4df4-a847-6e3a163f5b7a",
[2019-12-28 7:19:04 AM]   "method": "GET",
[2019-12-28 7:19:04 AM]   "uri": "/api/HttpBlobInput"
[2019-12-28 7:19:04 AM] }
[2019-12-28 7:19:05 AM] Executing 'Functions.HttpBlobInput' (Reason='This function was programmatically called via the host APIs.', Id=6337b4c7-222c-4dfd-b5e1-c8f71412d988)
[2019-12-28 7:19:05 AM] Executed 'Functions.HttpBlobInput' (Failed, Id=6337b4c7-222c-4dfd-b5e1-c8f71412d988)
[2019-12-28 7:19:05 AM] System.Private.CoreLib: Exception while executing function: Functions.HttpBlobInput. Newtonsoft.Json: Self referencing loop detected for property 'Subject' with type 'System.Security.Claims.ClaimsIdentity'. Path '[0].Claims[0]'.
[2019-12-28 7:19:05 AM] Executed HTTP request: {
[2019-12-28 7:19:05 AM]   "requestId": "e0938e92-81db-4df4-a847-6e3a163f5b7a",
[2019-12-28 7:19:05 AM]   "method": "GET",
[2019-12-28 7:19:05 AM]   "uri": "/api/HttpBlobInput",
[2019-12-28 7:19:05 AM]   "identities": [
[2019-12-28 7:19:05 AM]     {
[2019-12-28 7:19:05 AM]       "type": "WebJobsAuthLevel",
[2019-12-28 7:19:05 AM]       "level": "Admin"
[2019-12-28 7:19:05 AM]     }
[2019-12-28 7:19:05 AM]   ],
[2019-12-28 7:19:05 AM]   "status": 500,
[2019-12-28 7:19:05 AM]   "duration": 835
[2019-12-28 7:19:05 AM] }
```

**Comment by mhoeger** [comment]
Adding @pragnagopa for Triage

**Comment by pragnagopa** [comment]
Cannot repro this issue locally (running the functions host itslef) or on Azure. This looks like a issue with CoreTools. Will continue investigating

**Comment by anthonychu** [comment]
OK thanks! Let me know if there's a specific version of core tools I should try this on to confirm.

**Comment by pragnagopa** [comment]
Invoking HttpBlobInput with a function key reproes the issue in Azure: https://<appName>/api/HttpBlobInput?code=<functionKey>

**Comment by pragnagopa** [comment]
Converting HttpContext user identities to JSON [here](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Extensions/HttpRequestExtensions.cs#L134) is throwing circular reference error.

Full stack:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.HttpBlobInput ---> Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Subject' with type 'System.Security.Claims.ClaimsIdentity'. Path '[0].Claims[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at Microsoft.Azure.WebJobs.Script.Extensions.HttpRequestExtensions.GetRequestAsJObject(HttpRequest request) in D:\pgopaGit\azure-functions-host\src\WebJobs.Script\Extensions\HttpRequestExtensions.cs:line 139
   at Microsoft.Azure.WebJobs.Script.Workers.ScriptInvocationContextExtensions.ToHttpScriptInvocationContext(ScriptInvocationContext scriptInvocationContext) in D:\pgopaGit\azure-functions-host\src\WebJobs.Script\Workers\MessageExtensions\ScriptInvocationContextExtensions.cs:line 81
   at Microsoft.Azure.WebJobs.Script.Workers.Http.DefaultHttpWorkerService.ProcessDefaultInvocationRequest(ScriptInvocationContext scriptInvocationContext) in D:\pgopaGit\azure-functions-host\src\WebJobs.Script\Workers\Http\DefaultHttpWorkerService.cs:line 107
   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in D:\pgopaGit\azure-functions-host\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs:line 82
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in D:\pgopaGit\azure-functions-host\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 85
   at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in D:\pgopaGit\azure-functions-host\src\WebJobs.Script\Description\FunctionGenerator.cs:line 225
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 470
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 322
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 117
```

Similar to post here: https://stackoverflow.com/questions/46871412/jsonconvert-serializeobject-circular-reference-error-while-serializing-user-iden
