### ISSUE TITLE
Improve logging on Host startup

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5445]
This is follow up item from CRI investigation. When new function runtime `2.0.12888.0` rolled out, customer's application restarted but Jobhost took ~16 minutes to start causing all inflight http requests to timeout.

```
 PreciseTimeStamp	Source	Summary
2019-12-15 03:18:31.6108487	Host.Startup	Host started (984193ms)
```

Logs do not have any details on where the startup got stuck. 

Only exception in the logs:

```
The listener for function 'Functions.HopperHubTrigger' was unable to start.
System.OperationCanceledException : The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e,CancellationTokenSource cts)
   at async System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask,HttpRequestMessage request,CancellationTokenSource cts,Boolean disposeCts)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd,IRetryPolicy policy,OperationContext operationContext,CancellationToken token)
```

**Comment by pragnagopa** [comment]
Functions host should be shutdown if host startup exceeds threshold possibly ~2mins to ensure function app does not get stuck in a bad state.
