### ISSUE TITLE
Function app stops working

### ISSUE THREAD

**Issue by faarbaek** [Azure/azure-functions-host#5461]
In the last month or two, we have experienced more and more function apps suddenly stops working. When entering the app in Azure Portal we see the message "You have created a function app! - Now it is time to add your code", even though we haven't changed anything in the function app.
Restarting the app makes it available again.

We tried using the "Diagnose and solve problems" feature in the function app (selecting keyword "Downtime" then "Function App Down or Reporting Errors", which generates a report with exclamation mark in "Function Executions and Errors". The report specifies that it "Detected host offline in your function app" with the following details:

Description: A host error has occurred during startup operation '78428b28-12d3-42e5-b555-be26fec6a78a'.
Last offline at: 1/9/2020 11:43:22 PM
Details: 
```
System.IO.IOException : The network path was not found : 'D:\home\LogFiles\Application\Functions\Host'

  at System.IO.FileSystem.CreateDirectory(String fullPath)

  at System.IO.Directory.CreateDirectory(String path)

  at System.IO.Abstractions.DirectoryWrapper.CreateDirectory(String path)

  at Microsoft.Azure.WebJobs.Script.FileUtility.EnsureDirectoryExists(String path) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Extensions\FileUtility.cs : 38

  at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFileSystem() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 435

  at Microsoft.Azure.WebJobs.Script.ScriptHost.PreInitialize() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 427

  at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 263

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 244

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 235
```

#### Investigative information

Please provide the following:

- Timestamp: 1/9/2020 11:41:40.688 PM
- Function App version (1.0 or 2.0): 2.0
- Invocation ID: dd2cae03-06d3-4576-8e1b-10ec6b629e2e
- Region: westeurope

#### Repro steps

Provide the steps required to reproduce the problem:

The problem happens randomly

#### Expected behavior

Application automatically restarts when function host initialization errors occur

#### Actual behavior

Function stops

#### Known workarounds

Restarting the app fixes the issue

#### Related information 

N/A

**Comment by TynThordin** [comment]
We are also having same issues lately. Possibly related to https://github.com/Azure/azure-functions-host/issues/5151 ?

**Comment by pragnagopa** [comment]
cc @yojagad 
Closing as this is dup for #5151
