### ISSUE TITLE
Investigate V1  initialization errors

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5575]
Follow up to #https://github.com/Azure/azure-functions-host/issues/4951

Logs now have following error: `Host failed to initialize in StandbyMode.`

```
System.Net.NetworkInformation.NetworkInformationException : The system cannot find the file specified
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetFixedInfo()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.get_FixedInfo()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.get_DomainName()
   at System.Net.CookieContainer..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager..ctor(ScriptHostConfiguration config,ISecretManagerFactory secretManagerFactory,IScriptEventManager eventManager,ScriptSettingsManager settingsManager,WebHostSettings webHostSettings,ILoggerFactory loggerFactory,IScriptHostFactory scriptHostFactory,ISecretsRepositoryFactory secretsRepositoryFactory,HostPerformanceManager hostPerformanceManager,Int32 hostTimeoutSeconds,Int32 hostPollingIntervalMilliseconds) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebScriptHostManager.cs : 48
   at Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver.EnsureInitializedStandbyMode(WebHostSettings settings) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\App_Start\WebHostResolver.cs : 151

```
Needs further investigation,

**Comment by pragnagopa** [comment]
Moving this to Triage to find a new owner.

**Comment by pragnagopa** [comment]
cc @brettsam .
We continue to see application initialization errors and the error is not scoped to placeholders. This came up in a recent CRI. Stack trace from event logs:
```
<Data>D:\Program Files (x86)\SiteExtensions\Functions\1.0.12967\</Data><Data>RD00155D1111D8</Data><Data/><Data>10048</Data><Data>w3wp.exe</Data><Data>IIS APPPOOL\dmc-verification-west</Data><Data>HttpException</Data><Data>
   at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object&amp; instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.Integration.WebApi.AutofacWebApiDependencyScope.GetService(Type serviceType)
   at Autofac.Integration.WebApi.AutofacWebApiDependencyResolver.GetService(Type serviceType)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyResolverExtensions.GetService[TService](IDependencyResolver resolver) in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Extensions\DependencyResolverExtensions.cs:line 12
   at Microsoft.Azure.WebJobs.Script.WebHost.WebApiApplication.&lt;&gt;c__DisplayClass0_0.&lt;Application_Start&gt;b__0(HttpConfiguration c) in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Global.asax.cs:line 34
   at System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebApiApplication.Application_Start() in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Global.asax.cs:line 34
   at Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver.EnsureInitializedNonStandbyMode(WebHostSettings settings) in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\App_Start\WebHostResolver.cs:line 224
   at Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver.EnsureInitialized(WebHostSettings settings) in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\App_Start\WebHostResolver.cs:line 131
   at Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver.GetActiveInstance[TInstance](WebHostSettings settings, TInstance&amp; activeInstance, TInstance&amp; standbyInstance) in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\App_Start\WebHostResolver.cs:line 326
   at Microsoft.Azure.WebJobs.Script.WebHost.AutofacBootstrap.&lt;&gt;c__DisplayClass0_0.&lt;Initialize&gt;b__4(IComponentContext ct) in C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\App_Start\AutofacBootstrap.cs:line 33
   at Autofac.RegistrationExtensions.&lt;&gt;c__DisplayClass5_0`1.&lt;Register&gt;b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.&lt;&gt;c__DisplayClass0_0`1.&lt;ForDelegate&gt;b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessContr</Data><Data>https://dmc-verification-west.azurewebsites.net:443/</Data><Data>/</Data><Data>IPV4_ADDRESS_REDACTED</Data><Data/><Data>False</Data><Data/><Data>IIS APPPOOL\dmc-verification-west</Data><Data>24</Data><Data>IIS APPPOOL\dmc-verification-west</Data><Data>False</Data><Data>
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
</Data></EventData></Event>
```

**Comment by pragnagopa** [comment]
Added more logging in the referenced PR.
