### ISSUE TITLE
Function app throwing NullRef exception after upgrade to v2.0.12998

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#5686]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.IsMinorMatchOrLowerPolicyEvaluator(AssemblyName requestedAssembly,Assembly runtimeAssembly) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs : 157
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.LoadRuntimeAssembly(AssemblyName assemblyName,ScriptRuntimeAssembly scriptRuntimeAssembly) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs : 219
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.Load(AssemblyName assemblyName) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs : 213
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext,AssemblyName assemblyName)
```

Related to https://github.com/Azure/app-service-announcements-discussions/issues/139

**Comment by soninaren** [comment]
For anyone getting the above exception after moving to 2.0.12998, Set the FUNCTIONS_EXTENSION_VERSION in app setting to `2.0.12961.0` to mitigate the issue.

**Comment by soninaren** [comment]
The fix for this issue has been released
