### ISSUE TITLE
Durable Function Deserialization May Be Failing, but only in Azure

### ISSUE THREAD

**Issue by RyanMorrisroe** [Azure/azure-functions-host#5721]
#### Investigative information
- Timestamp: 2020-03-02 06:58:14.605
- Function App version (1.0 or 2.0): 2.0 (for the host.json version, the function app is version 3.0)
- Function App name: (redacted)
- Function name(s) (as appropriate): MonitorBatchJob
- Invocation ID: 2016985d-6f47-4e49-8f20-d84c823293a4
- Region: EastUS2

#### Repro steps
1. Create a durable function that gets passed a serialized class object and reads it using context.GetInput i.e. var input = context.GetInput<T>();
2. Call this durable function with a http invoked function, and pass input to it using starter.StartNewAsync() i.e. string instanceId = await starter.StartNewAsync("functionName", input);

In my case input is just a simple class with the following definition as passing only a string was also failing (both locally and in Azure):
public class DurableInput { Public string JobId {get; set; } }

#### Expected behavior
The durable function should run (and in my case continue to call itself, running as new until the Azure Batch job that it polls is complete). It works fine locally, polling the same Azure Batch account. It fails in Azure.

#### Actual behavior
The durable function immediately fails upon first invocation in Azure (runs fine with the same inputs):
Exception Stacktrace:
```
Function` 'MonitorBatchJob (Orchestrator)' failed with an error. Reason: System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at BatchController.Functions.MonitorBatchJob.Run(IDurableOrchestrationContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 86. 
```
This seems like it could be related to #3370. This is pretty major as none of the workarounds there appear to be applicable (I don't think I can override the deserialization behavior of context.GetInput like they could with HttpRequest)

#### Known workarounds
None

#### Related information 
Language: C#, .NET Core 3.1
[Full Source Code](https://github.com/RyanMorrisroe/HelloWorldAppForAzureBatch)

**Comment by madelinegordon** [comment]
cc @ConnorMcMahon
