### ISSUE TITLE
Exception: Worker was unable to load function XXX : 'TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty st

### ISSUE THREAD

**Issue by yid0** [Azure/azure-functions-host#5792]
I have same issue, with Nest js project + azure function

**Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
Function Runtime Version: 3.0.13139.0**

Trace:

[13/03/2020 09:23:32] Mapped function route 'api/{*segments}' [all] to 'main'
[13/03/2020 09:23:32] Worker failed to function id 38e52893-1203-48c4-aeaa-9321fa219fe4.
[13/03/2020 09:23:32]
[13/03/2020 09:23:32] Result: Failure
Exception: Worker was unable to load function email: 'TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received '''
Stack: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
    at Module.require (internal/modules/cjs/loader.js:689:11)
    at require (internal/modules/cjs/helpers.js:25:18)
    at FunctionLoader.load (C:\Users\HP ELITEBOOK 840 G3\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20061:22)
    at WorkerChannel.functionLoadRequest (C:\Users\HP ELITEBOOK 840 G3\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:17821:38)
    at ClientDuplexStream.WorkerChannel.eventStream.on (C:\Users\HP ELITEBOOK 840 G3\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:17738:30)
    at ClientDuplexStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:224:10)
    at Object.onReceiveMessage (C:\Users\HP ELITEBOOK 840 G3\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21909:19).[13/03/2020 09:23:32] Host initialized (1077ms)

[13/03/2020 09:23:33] Host started (1844ms)
[13/03/2020 09:23:33] Job host started
[13/03/2020 09:23:33] Host restarted.
[13/03/2020 09:23:33] Stopping JobHost
[13/03/2020 09:23:33] Job host stopped
[13/03/2020 09:23:38] Host lock lease acquired by instance ID '000000000000000000000000016D8F5A'.

![image](https://user-images.githubusercontent.com/24977828/76608342-c01bfe00-6515-11ea-8b92-78566a7ab1b6.png)

**Comment by gzuber** [comment]
@Yani06 Thanks for submitting this -- do you have a repro of this or a code sample that we could use to diagnose? Or is this happening when using one of our templates? Thanks!
