### ISSUE TITLE
Getting "Did not find any initialized language workers" error when running in debugger

### ISSUE THREAD

**Issue by josh-qf** [Azure/azure-functions-host#5811]
Trying set up a Azure time triggered function and getting `System.Private.CoreLib: Exception while executing function: Functions.TimerTrigger. Microsoft.Azure.WebJobs.Script: Did not find any initialized language workers.`

#### Investigative information

Please provide the following:

- Timestamp: `[3/19/20 10:04:20 PM]`
- Function App version: 1.2.0
- Function App name: `quantum-function`
- Function name(s) (as appropriate):
- Invocation ID: n/a
- Region: `westus`

#### Repro steps

1. F5 to start debugger
2. Seeing:
```
[3/19/20 10:03:20 PM] Host initialized (698ms)
[3/19/20 10:03:21 PM] Executing 'Functions.TimerTrigger' (Reason='Timer fired at 2020-03-19T15:03:21.2133527-07:00', Id=2cc9a96d-0099-4b42-beb5-2c5bf7edcfae)
[3/19/20 10:03:21 PM] Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2020-03-19T15:00:00.0000000-07:00
[3/19/20 10:04:20 PM] Starting worker process failed
[3/19/20 10:04:20 PM] The operation has timed out.
[3/19/20 10:04:20 PM] Starting worker process:python  /home/josh/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py --default --host 127.0.0.1 --port 9091 --wait "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/worker.py" --host 127.0.0.1 --port 55974 --workerId 81d4ad61-9d42-4db8-8b14-44afe633ac3d --requestId 835551f8-be3a-47fc-8664-2dbb19a2b710 --grpcMaxMessageLength 134217728
[3/19/20 10:04:20 PM] python process with Id=11797 started
[3/19/20 10:04:20 PM] Executed 'Functions.TimerTrigger' (Failed, Id=2cc9a96d-0099-4b42-beb5-2c5bf7edcfae)
[3/19/20 10:04:20 PM] System.Private.CoreLib: Exception while executing function: Functions.TimerTrigger. Microsoft.Azure.WebJobs.Script: Did not find any initialized language workers.
```

#### Expected behavior

I should not be seeing this error. My function is modifying cosmosdb, and nothing happens. 

#### Actual behavior

See error above.

#### Known workarounds

n/a

#### Related information 

Provide any related information 

* Azure Functions for Python 1.2.0
* Basic starter time trigger function works locally in the debugger.
* I've tried deploying with no success either.

**Comment by yojagad** [comment]
@josh-qf Are you using vscode ? If yes, could you please check if any of these threads can help?
https://github.com/Azure/azure-functions-host/issues/5262
https://github.com/microsoft/vscode-azurefunctions/issues/1492

**Comment by josh-qf** [comment]
@yojagad yes I am. These don't help as I'm not using runonstartup.

**Comment by yojagad** [comment]
Although the titles say that, the issue does not particularly have to do with runonstartup. It has to do with one of the lines you posted from vscode.

```
[3/19/20 10:04:20 PM] Starting worker process:python  /home/josh/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py --default --host 127.0.0.1 --port 9091 **--wait** "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/worker.py" --host 127.0.0.1 --port 55974 --workerId 81d4ad61-9d42-4db8-8b14-44afe633ac3d --requestId 835551f8-be3a-47fc-8664-2dbb19a2b710 --grpcMaxMessageLength 134217728
```

To give an overview, vscode extension relies on a particular log message to figure out if the runtime initialization is complete and that log message does not always get printed. We're tracking the fix for this issue here https://github.com/Azure/azure-functions-host/issues/4384. It's specific to non-C# languages and vscode.

**Comment by josh-qf** [comment]
I see. I ran the script without the `--wait` flag as suggested
```
josh@DESKTOP-SCVR80R:~/quantum$ python3 /home/josh/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/ptvsd_launcher.py --default --host 127.0.0.1 --port 9091 "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/worker.py" --host 127.0.0.1 --port 52271 --workerId a6ca48f1-7e12-44c7-882d-ad4175aebcc6 --requestId 7709e56c-19ee-48fb-a2a1-55279d889b3d --grpcMaxMessageLength 134217728
LanguageWorkerConsoleLog INFO: Starting Azure Functions Python Worker.
LanguageWorkerConsoleLog INFO: Worker ID: a6ca48f1-7e12-44c7-882d-ad4175aebcc6, Request ID: 7709e56c-19ee-48fb-a2a1-55279d889b3d, Host Address: 127.0.0.1:52271
LanguageWorkerConsoleLog ERROR: unhandled error in functions worker
Traceback (most recent call last):
  File "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/azure_functions_worker/main.py", line 40, in main
    args.grpc_max_msg_len))
  File "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/azure_functions_worker/aio_compat.py", line 49, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/azure_functions_worker/main.py", line 49, in start_async
    connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
  File "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 90, in connect
    await disp._grpc_connected_fut
  File "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 448, in __poll_grpc
    timeout=self._grpc_connect_timeout)
  File "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/usr/lib/azure-functions-core-tools/workers/python/3.6/LINUX/X64/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
```

**Comment by yojagad** [comment]
Being in the same directory, can you try

```
func start
```

as specified in the document here? https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash

**Comment by josh-qf** [comment]
That worked! The confusion was because I was following [this tutorial](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-04?tabs=bash). I believe the original issue still is an issue - up to you guys if you want to close it.

**Comment by yojagad** [comment]
Glad it worked. And yes, the vscode is still an issue and it's being tracked here https://github.com/Azure/azure-functions-host/issues/4384 . Will go ahead and close this thread.
