### ISSUE TITLE
V1 Function Queue Trigger message failing consistently after random amount of time.

### ISSUE THREAD

**Issue by Frankwayne** [Azure/azure-functions-host#5907]
#### Investigative information

Please provide the following:   I cannot provide some of the information. I will be glad to give it over an email though.

- Timestamp:     
- Function App version:    V1
- Function App name:       
- Function name(s) (as appropriate):  NhsApplicationUpdate
- Invocation ID: 
- Region:        East US 2 / Central US

This is my failed Message information pulled from the queue.

ExpirationTime | 4/30/2020   2:21:08 PM +00:00
-- | --
Id | 70f00f6f-8199-4ec6-b956-10b8f57ea699
InsertionTime | 4/23/2020   2:21:08 PM +00:00
NextVisibleTime | 4/23/2020   2:34:21 PM +00:00
PopReceipt | AgAAAAMAAAAAAAAAnd74RnwZ1gE=

#### Repro steps

Provide the steps required to reproduce the problem:

This is challenging.  It only happens in our live environment and not constantly.  We have a function that generates a message for another function call.  When the depended function is called  it does not execute for some reason.  Our App Insights logging does not capture the failure since it wrapped around the function and not the host runtime.  

Restarting the Functions App, and then feeding the message back into the queue   causes the  depended function to run as expected.

#### Expected behavior

Provide a description of the expected behavior.

Once the queue message is placed inside of the function queue, the function execute and is logged.
the function uses attributes  for a QueueTrigger.  Off of that queue trigger we are pulling message properties  and placing them in a DocumentDB attribute for a SQL query into CosmosDB.  I expect that the correct CosmosDB document is pulled  and the function is executed updating the CosmosDB document.

#### Actual behavior

Function runs as expected for awhile.  Then all calls to that functions does not work at all.  Since I restarted the function, I  did not think to see if other function were running correctly or failing.  Once it happens again, I will attempt other functions and see if they start to fail too.

#### Known workarounds

Restart the functions App

#### Related information 

The functions runtime is C#  .Net Framework 4.61
We are running inside of an ASE that  is in a vNet.  The azure portal cannot access the functions runtime.

The function in question has a  DocumentDB attribute with a SQL query.  The SQL query should be doing  SQL parameterization via the documentation for it. 

I did run into an issue like this before where I had a SQL query to cosmos DB in the middle of another function execution.  It was not using SQL parameterization  though in its call, and replacing the call to Cosmos DB with a SQL parameterization seem to have fixed that execution.  I was never able to hit the root cause of it though.

Since we are not getting app insights logging, I expect the issue to be within the Functions host, although I'm unsure of what it is.

**Comment by Frankwayne** [comment]
It started to happen to us again today.  Other Function calls are running just fine.   This is the only call with a cosmosDB attribute  and SQL query.

**Comment by Frankwayne** [comment]
Reviewing with a support ticket I was able to pull the following information out.  It would appear that I have one instance that is working just fine in the centralus datacenter, but my instance in eastus2 is constantly failing now.

Inner Exception Type: Newtonsoft.Json.JsonReaderException
Total Occurrences: 2
Latest Exception Message: Unexpected character encountered while parsing value: ≻. Path '', line 0, position 0.

Full Exception :
 Exception while executing function: NhsApplicationUpdate 
 System.InvalidOperationException : Exception binding parameter 'metadatas' 
 Newtonsoft.Json.JsonReaderException : Unexpected character encountered while parsing value: ≻. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader,JsonContract contract,Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader,Type objectType,Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value,Type type,JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,JsonSerializerSettings settings)
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.GetPartitionedQueryExecutionInfoInternal(SqlQuerySpec querySpec,PartitionKeyDefinition partitionKeyDefinition,Boolean requireFormattableOrderByQuery,Boolean isContinuationExpected)
   at async Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.GetPartitionedQueryExecutionInfoAsync(PartitionKeyDefinition partitionKeyDefinition,Boolean requireFormattableOrderByQuery,Boolean isContinuationExpected,CancellationToken token)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextFactory.CreateDocumentQueryExecutionContextAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.Documents.Linq.DocumentQuery`1.CreateDocumentQueryExecutionContextAsync[T](Boolean isContinuationExpected,CancellationToken token)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.Documents.Linq.DocumentQuery`1.ExecuteNextPrivateAsync[T,TResponse](CancellationToken token)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.DocumentDB.DocumentDBService.ExecuteNextAsync[T](Uri documentCollectionUri,SqlQuerySpec sqlSpec,String continuation)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.DocumentDB.DocumentDBEnumerableBuilder`1.ConvertAsync[T](DocumentDBAttribute attribute,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Host.Bindings.PatternMatcher.AsyncInvoker`2.<>c__DisplayClass0_0.b__0(Object input)
   at Microsoft.Azure.WebJobs.Host.Bindings.BindToInputBindingProvider`2.ExactBinding`1.BuildAsync(TAttribute attrResolved,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Bindings.BindingBase`1.BindAsync[TAttribute](??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)

**Comment by Frankwayne** [comment]
I would like to say this issue has been resolved.   I had to update the following nuget packages  

    <PackageReference Include="Microsoft.Azure.DocumentDB" Version="2.10.3" />
