### ISSUE TITLE
Availability of V3 stable linux dotnet runtime?

### ISSUE THREAD

**Issue by kentonbmax** [Azure/azure-functions-host#6034]
According to the docker hub page only v2 runtime is supported and stable for linux, however; using Microsoft.NET.Sdk.Functions 3.0.7 seems to work. We had previously tried to use dotnet core v3.1 as v2 is no longer supported. V2 funciton runtime only supports the unsupported dotnetcore v2 version.

**Comment by pragnagopa** [comment]
Azure Functions V3 (.Net Core 3.1) is supported on linux. Can you clarify which page your are referring to? We will update the docs
cc @ankitkumarr

**Comment by kentonbmax** [comment]
Looks like base and this one [DockerHub](https://hub.docker.com/_/microsoft-azure-functions-dotnet). I'm surprised that its supported we are unable to confirm EF Core 3.1 works correctly in the v3 runtime on linux.

**Comment by pragnagopa** [comment]
@ankitkumarr / @ahmelsayed - Any idea how we can get the [page](https://hub.docker.com/_/microsoft-azure-functions-dotnet) updated to include V3 info?

@kentonbmax - Please share any errors / stack traces you are seeing when using EF Core 3.1

**Comment by kentonbmax** [comment]
I created this question on stackoverflow [here](https://stackoverflow.com/questions/61739932/azure-functions-v3-dotnet-core-v3-1-ef-core-ef-core-sql-3-1-x-no-errors-no-dat?noredirect=1#comment109214080_61739932). I have tried v3 and all v3 tags up to latest. EF inits, then nothing in linux docker image. Please let me know if you require more details. Rolling ef back to 2.2.0 and using the v2 runtime in docker, with Microsoft.NET.Sdk.Functions = 3.0.7 seems to be a fix but its not pretty and kinda janky.

**Comment by ahmelsayed** [comment]
The dockerhub readme is out of date. There is the readme on the repo https://github.com/Azure/azure-functions-docker/blob/master/README.md with the latest tags. 

The exception in the SO question is coming from the host 

```
Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService[0]
      Breaking change analysis operation failed
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService.LogBreakingChangeReport(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/ChangeAnalysisService.cs:line 140
   at 
...
```

**Comment by kentonbmax** [comment]
Hi is there any update on this? currently we are targeting EF Core 2.2, using Runtime.2.0 in our docker file and targeting 3.1 for our functions with Net.Functions v3.0.7. This is working but leading to other version issues down stream  with Linux compatibility. For example we found that a nuget library (netcore 3.1) that injects an IOptions<T> prevents the function from starting when we inject that into our function constructor. With 0 errors our ms logging is using trace levels in the host file, we cannot see what the issue is. This works great using the emulator vs2019 on windows 10 latest but not so much in runtime2.0 docker.
