### ISSUE TITLE
V1 app initialization failures - In placeholder mode

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6089]
cc @brettsam 

Follow up from issue #5575

Added logs for application initialization errors. Full stack trace:

```
Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = WebScriptHostManager (DelegateActivator), Services = [Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = WebHostResolver (ReflectionActivator), Services = [Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ScriptEventManager (ReflectionActivator), Services = [Microsoft.Azure.WebJobs.Script.Eventing.IScriptEventManager], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'ScriptEventManager'. ---> Could not load file or assembly 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. Old version error. (Exception from HRESULT: 0x80131107) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = WebHostResolver (ReflectionActivator), Services = [Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ScriptEventManager (ReflectionActivator), Services = [Microsoft.Azure.WebJobs.Script.Eventing.IScriptEventManager], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'ScriptEventManager'. ---> Could not load file or assembly 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. Old version error. (Exception from HRESULT: 0x80131107) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ScriptEventManager (ReflectionActivator), Services = [Microsoft.Azure.WebJobs.Script.Eventing.IScriptEventManager], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'ScriptEventManager'. ---> Could not load file or assembly 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. Old version error. (Exception from HRESULT: 0x80131107) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException : An exception was thrown while invoking the constructor 'Void .ctor()' on type 'ScriptEventManager'. ---> Could not load file or assembly 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. Old version error. (Exception from HRESULT: 0x80131107) (See inner exception for details.) ---> System.BadImageFormatException : Could not load file or assembly 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. Old version error. (Exception from HRESULT: 0x80131107) ---> System.BadImageFormatException : Old version error. (Exception from HRESULT: 0x80131107) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Script.Eventing.ScriptEventManager..ctor() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Eventing\ScriptEventManager.cs : 11
   at lambda_method(Closure ,Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() 
   End of inner exception
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context,IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) 
   End of inner exception
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id,Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope,IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context,IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) 
   End of inner exception
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id,Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope,IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context,Service service,IEnumerable`1 parameters,Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context,Service service,IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context,IEnumerable`1 parameters)
   at Microsoft.Azure.WebJobs.Script.WebHost.AutofacBootstrap.<>c__DisplayClass0_0.<Initialize>b__4(IComponentContext ct) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\App_Start\AutofacBootstrap.cs : 33
   at Autofac.RegistrationExtensions.<>c__DisplayClass5_0`1.<Register>b__0(IComponentContext c,IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c,IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) 
   End of inner exception
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope,IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration,IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context,Service service,IEnumerable`1 parameters,Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context,Service service,IEnumerable`1 parameters)
   at Autofac.Integration.WebApi.AutofacWebApiDependencyScope.GetService(Type serviceType)
   at Autofac.Integration.WebApi.AutofacWebApiDependencyResolver.GetService(Type serviceType)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyResolverExtensions.GetService[TService](IDependencyResolver resolver) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Extensions\DependencyResolverExtensions.cs : 12
   at Microsoft.Azure.WebJobs.Script.WebHost.WebApiApplication.<>c__DisplayClass0_0.<Application_Start>b__0(HttpConfiguration c) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Global.asax.cs : 35
   at System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebApiApplication.Application_Start() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Global.asax.cs : 35
```

**Comment by pragnagopa** [comment]
@fabiocav - we missed moving this during sprint planning. Moving this now.

**Comment by pragnagopa** [comment]
moving this back to Triaged due to other higher priority tasks.

**Comment by penguinawesome** [comment]
Hi @pragnagopa we are encountering this issue: https://github.com/Azure/azure-functions-host/issues/5575 in our azure web app premium tiers. I hope azure could check and fix this issue as well in azure web app
