### ISSUE TITLE
ScriptHost  startup error during specialization

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6120]
cc @divyagandhii - for linux consumption
cc @FinVamp1 - for CRIs

After specialization, sometimes host fails to start with following error:

Stack trace:
```
Microsoft.Azure.WebJobs.Script.HostInitializationException : Did not find functions with language [node].
    at Microsoft.Azure.WebJobs.Script.Utility.VerifyFunctionsMatchSpecifiedLanguage(IEnumerable`1 functions,String workerRuntime,Boolean isPlaceholderMode,Boolean isHttpWorker) at /src/azure-functions-host/src/WebJobs.Script/Utility.cs : 562
    at async Microsoft.Azure.WebJobs.Script.ScriptHost.GetFunctionDescriptorsAsync(IEnumerable`1 functions,IEnumerable`1 descriptorProviders) at /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs : 673
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFunctionDescriptorsAsync(IEnumerable`1 functionMetadata) at /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs : 493
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs : 295
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs : 248
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 264
```

Errors are spread across host runtime versions and languages. Both windows and linux consumption apps are affected by this.

**Comment by divyagandhisethi** [comment]
@pragnagopa , @FinVamp1  So that means this error is not limited to powershell apps right if it's affecting linux also?

**Comment by pragnagopa** [comment]
> So that means this error is not limited to powershell apps right if it's affecting linux also?

Yes. Error is not limited to powershell apps.

**Comment by pragnagopa** [comment]
Need to investigate why these errors show up for sla sites.

**Comment by pragnagopa** [comment]
cc @brettsam 

Error happens during specialization.

- Template site starts in placeholder mode. 
- Scripthost is initializing
- Specialization is triggered
- Scripthost startup is cancelled
- But Scripthost initialization continues and throws above error.

Need to ensure child tasks are cancelled when scripthost start is aborted.
