### ISSUE TITLE
[CustomHandler] Investigate process startup

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6172]
cc @yojagad @anthonychu @jdubois

On linux consumption, following custom handler is taking up to ~8secs to start vs 100ms locally
https://github.com/jdubois/azure-native-spring-function

Need to investigate why such a huge difference in process startup times.

**Comment by jdubois** [comment]
Thanks for creating the issue @pragnagopa !
This is a native build on Linux, I will do the same one for Windows in the next days, as I believe it will be easier for you to investigate.

**Comment by pragnagopa** [comment]
@jdubois - Please update this issue once you have setup instructions for windows

Moving issue back to Triaged.

**Comment by jdubois** [comment]
Thanks @pragnagopa - doing the Windows build is in fact more complicated than expected, so I can't commit on a date.

**Comment by pragnagopa** [comment]
@jdubois  - I am trying to set up the code to run locally on mac. Here is the error when running `build.sh`

```
Error: Unable to detect supported DARWIN native software development toolchain.
com.oracle.svm.core.util.UserError$UserException: Unable to detect supported DARWIN native software development toolchain.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.<init>(CCompilerInvoker.java:72)
	at com.oracle.svm.hosted.c.codegen.CCompilerInvoker$DarwinCCompilerInvoker.<init>(CCompilerInvoker.java:205)
	at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.create(CCompilerInvoker.java:82)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:851)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)

```

Any ideas how to fix this?

**Comment by anthonychu** [comment]
@jdubois Another option is to build a VS Code devcontainer. Maybe that’s easier than providing instructions on Windows. Like @pragnagopa, I want able to get it working on macOS either. I got close with a devcontainer but the build would never finish.

**Comment by jdubois** [comment]
@pragnagopa I'm guessing this is because you don't have XCode installed (in order to compile natively on your Mac). Installing GraalVM can indeed be painful (this is why in my tutorial I'm pushing people to use GitHub Actions, but of course that won't be enough for you, as you need to debug).
I was going to work on porting this to Windows -> which is the most important for you, having this inside a Linux devcontainer, or having this work on Windows?

**Comment by pragnagopa** [comment]
Linux DevContainer will work with that is easier! Thanks.

Regarding porting to windows: Simple instructions on how to build the function locally will help. Do not have to port the deploy  setup you have to windows. 

I will keep trying to build it locally on mac / windows.

**Comment by jdubois** [comment]
Thanks! devcontainers should also be easier for me!

**Comment by jdubois** [comment]
@pragnagopa as promised, DevContainer support is available! Here is the documentation: https://github.com/jdubois/azure-native-spring-function/blob/master/.devcontainer/post-create.sh
BTW this uses the GraalVM "Community Edition": there is an "Entreprise Edition" which we should be able to use for this kind of work (no technical issue, and the license should be OK for this). With the "Enterprise Edition" you will have access to debug flags, so maybe you will need it - just ask me if you find this might be interesting.

**Comment by pragnagopa** [comment]
Thanks. Assigning this to next sprint for initial investigation.

**Comment by fabiocav** [comment]
Moving this to sprint 80 as a stretch goal due to capacity.

**Comment by pragnagopa** [comment]
cc @TsuyoshiUshio

**Comment by jdubois** [comment]
This is still very important to me, don't hesitate to get back to me to do more testing

**Comment by pragnagopa** [comment]
Assigning to @TsuyoshiUshio for further investigation.

**Comment by TsuyoshiUshio** [comment]
Hi @jdubois 
Do you think this scenario is still important for you? or would you want to prioritize other scenario? 
Let's discuss on the meeting.

**Comment by jdubois** [comment]
Hi @TsuyoshiUshio yes this is very important if want to have GraalVM support.
Then, now that I understand better how this all work, I might also find a solution by myself. Also, I'm going to work with this with @abhirockzz this afternoon, hopefully this will help.

**Comment by TsuyoshiUshio** [comment]
Hi @jdubois 
Sure. I'll take time for it. However, You also need to understand the architecture. I think, custom handler is slower than consumption plan architecture. It might not immediate because of the priority, however, I'll do it.
