### ISSUE TITLE
Function app throwing System.OperationCanceledException

### ISSUE THREAD

**Issue by yashrmaa** [Azure/azure-functions-host#6192]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2020-06-08T23:12:26.694Z
- Function App version: 2.0
- Function App name: debtmanagementfunction
- Function name(s) (as appropriate): ArtifactServiceSubscription
- Invocation ID: 848af3c6-32b1-4722-b110-183c796f66c4
- Region: West US

#### Repro steps

Provide the steps required to reproduce the problem:

Function host throws System.OperationCanceledException with no other information. There are no repro steps. 

````    
System.OperationCanceledException : The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async Microsoft.Azure.WebJobs.ServiceBus.Triggers.MessageToStringConverter.ConvertAsync(Message input,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Bindings.PatternMatcher.AsyncInvoker`2.<>c__DisplayClass0_0.<Execute>b__0[TSrc,TDest](??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\PatternMatcher.cs : 383
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.IConverterManagerExtensions.<>c__DisplayClass1_0`2.<AsTyped>b__0[TSource,TDestination](??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\IConverterManager.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.CustomTriggerArgumentBinding`3.ConvertAsync[TMessage,TTriggerValue,TUserType](TMessage value,Dictionary`2 bindingData,ValueBindingContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\CustomTriggerArgumentBinding.cs : 46
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.SimpleTriggerArgumentBinding`2.BindAsync[TMessage,TTriggerValue](TTriggerValue value,ValueBindingContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\SimpleTriggerArgumentBinding.cs : 86
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs : 57
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindAsync[TTriggerValue](??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs : 33
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.BindAsync(IBindingSource bindingSource,ValueBindingContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 915
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 263
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 117
````
    

#### Expected behavior

Should not throw this exception.

#### Actual behavior

Throws System.OperationCanceledException with no other information.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used: Service bus

This seems really similar to another solved [issue](https://github.com/Azure/azure-functions-host/issues/1955).

**Comment by hanvyj** [comment]
Also seeing this.

**Comment by v-bbalaiagar** [comment]
Can we know if you are seeing this issue still and requires further follow up.

**Comment by yashrmaa** [comment]
No, this doesn't need any follow up. I had a conversation with folks from functions team and seems like whenever Azure cancel's an operation is always retried.

**Comment by v-bbalaiagar** [comment]
Thank you for the update. Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
