### ISSUE TITLE
Entity Framework Core 2.0 compatibility broken in latest functions 3 runtime (Could not load file or assembly 'System.Interactive.Async)

### ISSUE THREAD

**Issue by yougoh** [Azure/azure-functions-host#6203]
Hello,

We recently had an issue where one of our azure functions suddenly started to throw constant exceptions after we had restarted the function app. This azure function was targeting function runtime 3 via ~3. We later realized that targeting the function runtime this way would cause the latest released 3.x version of the runtime to be installed whenever the function app restarts. 

This is the exception we started receiving once our function app updated to the latest runtime:

```
System.InvalidOperationException: Error constructing handler for request of type [entity type]. Register your handlers with the container.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.
File name: 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.Extensions.DependencyInjection.SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at lambda_method(Closure )
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7839
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7824
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 194
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 99
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 77
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c__DisplayClass20_0.<Decorate>b__0(IServiceProvider provider)
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\DryIocAdapter.cs:line 156
   at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 4540
   at lambda_method(Closure )
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7839
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7824
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 194
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 99
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 77
   at PPT.Core.Factories.ServiceFactoryExtensions.GetInstance[T](ServiceFactory factory)
   at PPT.Core.Factories.HandlerBase.GetHandler[THandler](ServiceFactory factory)
   --- End of inner exception stack trace ---
   at PPT.Core.Factories.HandlerBase.GetHandler[THandler](ServiceFactory factory)
   at PPT.Core.Queries.QueryHandlerWrapperImpl`2.Dispatch(IEntityQuery`1 query, ServiceFactory serviceFactory)
   at Trigger.RunAsync(TimerInfo timerInfo, IDurableClient starter) in Trigger.cs:line 47
```

Once we realized the framework for 3.x updated to a later version than we had been developing and testing against, we changed the setting from ~3.x to the version we were developing against  3.0.13353.

Once we made this change the exceptions stopped and everything resumed working as expected. I didnt see anything in the release notes about breaking compatibility with  EF Core 2.0 in the latest functions 3.x release so I am assuming this is a bug.

Let me know if I can provide anything else to help resolve this issue.

Thanks!

**Comment by brettsam** [comment]
Thank you @yougoh -- we understand the issue -- this was not an expected breaking change. There are two ways to fix this while we work on a hotfix:
1. set `FUNCTIONS_EXTENSION_VERSION` to `3.0.13353` to pin yourself back to the previous version.
2. add `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` to your project file and re-deploy. This will include the assembly that is missing in your deployment.

Also, I believe this only affects EF Core 2.0 as 3.0 no longer has a dependency on this file.

**Comment by yougoh** [comment]
Hello @brettsam,

You are correct also upgrading to EF Core 3.0 resolves this issue. The only problem we have with that is there are some queries in this function app that break in EF Core 3.0 that need to be refactored. Unfortunately we have not had the time to address that tech debt yet.

Also I wanted to note for work around option 1 we also have to add: 

```<DisableFunctionExtensionVersionUpdate>true</DisableFunctionExtensionVersionUpdate>```

to the .csproj file in order to republish from visual studio. Normally we would deploy from a pipeline in Azure Dev Ops but we have not tried a normal deployment with this issue yet.

Thanks!

**Comment by brettsam** [comment]
Here's our RCA for future reference
-	We updated our references to Grpc.Core here: https://github.com/Azure/azure-functions-host/pull/5802
-	The new version of Grpc.Core removed a dependency on System.Interactive.Async.
-	Our newer versions of ExtensionsMetadataGenerator clean the output by removing files that are already a part of the Functions site extension.
-	Well, this file is no longer a part of the site extension. So it fails.

We'll be re-adding this reference to maintain compatibility and releasing this as a hotfix. I'll follow-up with a test to catch this scenario as well.
