### ISSUE TITLE
Automatically Opt Out BlobChangeAnalysisStateProvider When Hosting Environment is not App Service

### ISSUE THREAD

**Issue by wenhzha** [Azure/azure-functions-host#6253]
The function host logs the below exception while deploying to K8S without a Azure Storage Account. The exception does not break the host but just noisy, and can be misleading for customers who run function apps not in app service.

```
System.InvalidOperationException: The BlobChangeAnalysisStateProvider requires the default storage account 'Storage', which is not defined.
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.BlobChangeAnalysisStateProvider.GetCurrentAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/BlobChangeAnalysisStateProvider.cs:line 40
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService.TryLogBreakingChangeReportAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/ChangeAnalysisService.cs:line 92
```

[Proposed Solution]
The function host can sniff out hosting environment and decide to opt out the BlobChangeAnalysisStateProvider feature if it is not supposed to run in the given hosting environment.

**Comment by pragnagopa** [comment]
cc @fabiocav 
PR needs to be reviewed. Moving to next sprint.
