### ISSUE TITLE
Internal Server Error after activating Function Proxy

### ISSUE THREAD

**Issue by itpropro** [Azure/azure-functions-host#6281]
In some scenarios, Azure Functions fail with the following error after creating an Azure Function Proxy:
```
2020-05-03T13:28:02.980 [Error] Executed 'Functions.GetTest' (Failed, Id=fe2f9871-7e77-4464-b5bc-216f019f7081)

System.InvalidOperationException : Missing value for trigger parameter 'req'.

   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindAsync[TTriggerValue](??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs : 41

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.BindAsync(IBindingSource bindingSource,ValueBindingContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 915

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 263

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 117
```

#### Repro steps

1. Create new Function App with the following settings:
![image](https://user-images.githubusercontent.com/15030951/80917418-07c54600-8d5f-11ea-9ceb-fb5297cf5040.png)
2. Create a new Function called "getTest" with Authorization Level "Anonymous".
3. Create Function Proxy with the following settings:
![image](https://user-images.githubusercontent.com/15030951/80915574-72708480-8d53-11ea-8098-efcfd0045f68.png)
```
"proxies": {
        "Get Test": {
            "matchCondition": {
                "route": "/v1/test"
            },
            "backendUri": "https://localhost/api/getTest"
        }
    }
```
4. Try to execute the "getTest" Function directly in the portal, via REST or via Proxy Url. It will always throw the above error.
5. Delete Proxy and verify that the Function can execute successful again.

#### Expected behavior

Azure function proxy should not lead to break Azure Functions.

#### Actual behavior

Azure Function Proxies break the function behind the specified backend Url.

#### Known workarounds

Maybe it has something to do with a space in the proxy name?

#### Related information 

Current Azure Function Experience:
Runtime Version: ~3
Worker: powershell
Worker Version: 6

**Comment by kashimiz** [comment]
Hi @itpropro, my apologies for the delayed response. I was unable to repro the issue using your steps (on PowerShell 6.2, as we no longer support PowerShell 6.0, only 6.2 and 7.0.) Are you still observing the issue when you try this repro on either 6.2/7.0?
