### ISSUE TITLE
SqlClient Errror in Azure app function V3 when launching in Docker with Visual Studio

### ISSUE THREAD

**Issue by amtandon** [Azure/azure-functions-host#6303]
Getting the following error with Azure function V3. 
```csharp
{System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```
Please provide the following:

- Timestamp:
- Function App version: V3
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps:

In Visual Studio, create a V3 Function with a Service Bus Trigger (the trigger should not matter), with docker support. 
Add Entity Framework to the project 
Add some code to query against a DB
Run the project locally in DEBUG config against Docker. 

#### Workarounds

Run the project locally in RELEASE config against Docker

#### Related information 
Here is the .csproj file for reference
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <DockerFastModeProjectMountDirectory>/home/site/wwwroot</DockerFastModeProjectMountDirectory>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.KeyPerFile" Version="3.1.5" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

Here is the docker file for reference

```
FROM mcr.microsoft.com/azure-functions/dotnet:3.0 AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["dir/blah.csproj", "blah/"]
RUN dotnet restore "blah.csproj"
COPY . .
WORKDIR "/src/blah"
RUN dotnet build "blah.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "blah.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot
AzureFunctionsJobHost__Logging__Console__IsEnabled=true
```

**Comment by brettsam** [comment]
I highly suspect we're hitting something with Visual Studio's "fast mode" for debugging here: https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#debugging. When I turn off the optimizations, my app works (but I don't get the debugger attached automatically, it looks like).

Adding a bunch of people that may know -- @fabiocav / @ahmelsayed / @ankitkumarr / @balag0 / @divyagandhii -- do any of you have insights into VS support for debugging docker containers? It does seem like we've got an issue when loading native dependencies. I'm wondering if the rid is incorrect?

**Comment by ahmelsayed** [comment]
@vijayrkn @BigMorty Not sure if you might know more about this. I wonder if the json deps manifest is pointing to windows dependencies for sql inside the container.

**Comment by vijayrkn** [comment]
@NCarlsonMSFT

**Comment by NCarlsonMSFT** [comment]
@amtandon I'm guessing by the exception you are seeing that (at least in Debug) you are using a SQL Express LocalDB instance? If you're not sure your connection string would start with "Data Source=(localdb)\". If so, then that is indeed not supported as the exception indicates (locadb is windows only). What you can do is run a second container with the [sql-server image](https://hub.docker.com/_/microsoft-mssql-server) and configure your app to connect to that for local debugging in a container. Please let me know if that is not the source of your issue, or if using sql-server in a container does not fix the issue.

**Comment by amtandon** [comment]
@NCarlsonMSFT I am trying to connect to an Azure SQL DB and not a Local DB

**Comment by NCarlsonMSFT** [comment]
@amtandon searching around on the web I found: https://github.com/dotnet/runtime/issues/23639 which indicates this error can happen when you don't specify a RID for the target platform. Can you try adding this to a property group in your project: 
```
<RuntimeIdentifier>linux</RuntimeIdentifier>
```

**Comment by fabiocav** [comment]
With a portable deployment, as long as you have the deps file in the appropriate folder, this should work without a RID. Can you confirm you have a `function.deps` in the bin folder of your deployed payload when running?

Also, @ahmelsayed, is the runtime we have in that image a self-contained build? That has an impact on RID resolution.

**Comment by ahmelsayed** [comment]
That's correct, the runtime is self-contained in that image. built with `--runtime linux-x64`

**Comment by fabiocav** [comment]
It would only be an issue if the appropriate RID for the target environment isn't present in our static catalog (which is what is used when running a self-contained host as we don't have the shared framework RID and that would also not be populated). I don't expect that to be the case with what is used in that image, but something to validate after taking a look at the deps file (and whether it's present)

**Comment by ahmelsayed** [comment]
```console
$  docker run -it mcr.microsoft.com/azure-functions/dotnet:3.0 cat /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost.deps.json
```

[output.txt](https://github.com/Azure/azure-functions-host/files/4867202/output.txt)

**Comment by brettsam** [comment]
Also note that this isn't related to what SQL instance you connect to -- I can repro this by doing this in a Function: `var conn = new SqlConnection("");`. We're failing to find the native assembly, which causes the problem.

**Comment by fabiocav** [comment]
@ahmelsayed I'm talking about the deps file for the function itself

@brettsam did you have the function's deps? If so, I'll setup a repro and take a look at this.

**Comment by amtandon** [comment]
> With a portable deployment, as long as you have the deps file in the appropriate folder, this should work without a RID. Can you confirm you have a `function.deps` in the bin folder of your deployed payload when running?
> 
> Also, @ahmelsayed, is the runtime we have in that image a self-contained build? That has an impact on RID resolution.

There is a function.deps.json file in the bin folder under /debug/netcoreapp3.1/bin

**Comment by amtandon** [comment]
@NCarlsonMSFT and @fabiocav adding the RID as `<RuntimeIdentifier>linux</RuntimeIdentifier>` solves the problem.

Attached is a ZIP file of the failing solution

[BugReprod.zip](https://github.com/Azure/azure-functions-host/files/4874295/BugReprod.zip)

**Comment by brettsam** [comment]
Side note -- the issue here is unrelated to any connection string (I put "" in there for my repro). 

Here's two deps files to compare:
- Broken in VS "fast mode": [function.deps.fast.txt](https://github.com/Azure/azure-functions-host/files/4880385/function.deps.fast.txt)
- Works when running a container myself: [function.deps.regular.txt](https://github.com/Azure/azure-functions-host/files/4880386/function.deps.regular.txt)

**Comment by fabiocav** [comment]
@amtandon I'm glad that provides you a workaround. 

As mentioned above, that shouldn't be needed, so we'll investigate and address the root cause here. Thanks for all the information.
