### ISSUE TITLE
Function still tries creating secondary file watcher folder when fileWatchingEnabled is set to false

### ISSUE THREAD

**Issue by SatishRanjan** [Azure/azure-functions-host#6344]
https://github.com/Azure/azure-functions-host/blob/e9ac4ec2ead96f6fca1084fb464252aff6fecd10/src/WebJobs.Script.WebHost/FileMonitoringService.cs#L123

**Comment by SatishRanjan** [comment]
Eet fileWatchingEnabled to false

{
    fileWatchingEnabled: false
}

**Comment by brandonros** [comment]
> Eet fileWatchingEnabled to false
> 
> { fileWatchingEnabled: false }

in what file? `host.json`? doesn't work. `appsettings.json`? doesn't work

**Comment by waleed-salama** [comment]
Any update on this? My development is stuck on this, it's kinda frustrating.

**Comment by serefacet** [comment]
I’ve encountered the same issue, and it results in an exception. There’s currently no way to prevent InitializeSecondaryFileWatchers from being called.

```
System.IO.IOException: The configured user limit (1024) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher.InitializeWatcher() in /_/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs:line 64
   at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher..ctor(String path, String filter, Boolean includeSubdirectories, WatcherChangeTypes changeTypes, ILoggerFactory loggerFactory) in /_/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs:line 43
   at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.InitializeSecondaryFileWatchers() in /_/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 196
   at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.InitializeFileWatchers() in /_/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 170
   at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.StartAsync(CancellationToken cancellationToken) in /_/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 93
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 426
```
