### ISSUE TITLE
Azure Functions just started breaking.

### ISSUE THREAD

**Issue by jwisener** [Azure/azure-functions-host#6425]
We had an azure function we created by hand, inside the azure function app instance (aka inside the portal). This morning around 7/27/2020 4:00 PM'ish CST, the function started breaking, no code change has been done to the function. The function app does use the extension per the documentation provided by microsoft. I think the Controller (azure function code) must have changed. Because, or azure function team did not update the extension bundle (the one that is added by default when you create a new azure function instance).

Here is the error:
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.Bounce'. Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.

Here is the stacktrace.
```
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Functions.Bounce' ---> System.InvalidOperationException : Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.
at Microsoft.Azure.WebJobs.Host.Tables.TableAttributeBindingProvider.TryCreate(BindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Tables\TableAttributeBindingProvider.cs : 60
at Microsoft.Azure.WebJobs.Host.Tables.TableAttributeBindingProvider.<>c_DisplayClass5_0.<TryCreateAsync>b0() at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Tables\TableAttributeBindingProvider.cs : 84
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b_274_0(Object obj)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread,ExecutionContext executionContext,ContextCallback callback,Object state)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread,ExecutionContext executionContext,ContextCallback callback,Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot,Thread threadPoolThread)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.Azure.WebJobs.Host.Bindings.GenericCompositeBindingProvider`1.TryCreateAsync[TAttribute](BindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingProviders\GenericCompositeBindingProvider.cs : 61
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.Azure.WebJobs.Host.Bindings.CompositeBindingProvider.TryCreateAsync(BindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingProviders\CompositeBindingProvider.cs : 25
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 222
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 137
End of inner exception
at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 145
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 73
```

Note: If I remove the parameter and create a new tableClient and call tableClient.GetTableReference(....) , it works fines, but as soon as the parameter is added it's broken with the above message

#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2020-07-29T12:27:32.309
- Function App version:  3
- Function App name: test-url-shortner
- Function name(s) (as appropriate): BounceBroken
- Invocation ID: there is none, because it's just giving me: 2020-07-29T12:27:32.309 [Error] run.csx(8,62): error CS0246: The type or namespace name 'CloudTable' could not be found (are you missing a using directive or an assembly reference?)
- Region: EASTUS

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by fabiocav** [comment]
Can you please provide the `host.json` and the information requested in the template above so we can take a closer look here? Thanks!

**Comment by jwisener** [comment]
@fabiocav  I updated the original post to include as much in the requested template. 

Here is the host.json

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 3.0.0]"
  },
  "extensions": {
    "http": {
      "routePrefix": "",
      "maxOutstandingRequests": 200,
      "maxConcurrentRequests": 100,
      "dynamicThrottlesEnabled": true,
      "hsts": {
        "isEnabled": true,
        "maxAge": "10"
      },
      "customHeaders": {
        "X-Content-Type-Options": "nosniff"
      }
    }
  }
}
```

**Comment by fabiocav** [comment]
@jwisener we were unable to locate the function app `test-url-shortner`, is that the correct name?

Even without that information, the `host.json` file shared above does provide some clues about that might be happening here. Your function, based on the stack above, an as expected by default in CSX, is binding to the version of the Storage SDK supported by the previous version of the binding, but looks like you've expanded the bundle version reference to span across multiple major version ranges (moving you to a new major version), which uses the new version of the Storage SDK.

It's possible you had this working before, as bundles 2.0 didn't exist until recently, but once that was deployed, the range you've specified loaded that instead.

Changing the range to `[1.*, 2.0.0]` should address the issue.

**Comment by fabiocav** [comment]
Closing as answered.

@soninaren , this feels like a good candidate for a detector so this information is visible in the portal.

**Comment by jwisener** [comment]
@fabiocav I had already tried changing that, that was first thing we tried when attempting to fix production. There is still a 500 error even after changing it. But, I can't find any logging information for the 500 error and I can't get any invocationid, I have an invocationid of a success (because I had to comment out the binding) it is: 

f7123d49-e201-4e69-8fcc-808c1b1fb912

I have put the binding parameter back in and changed the host file to the [1.*, 2.0.0]. Do you can see any detail about the 500, because it's not logging anything that I can find, just throws a 500 back.

**Comment by jwisener** [comment]
@fabiocav I can email you log file, I think it may have more information it.

**Comment by soninaren** [comment]
@jwisener can you restart the function app after changing the host file.  Sometimes you get assembly already loaded exception, it should be fixed in the next runtime release.

**Comment by jwisener** [comment]
@fabiocav , @soninaren yes, I did that. Completely stopped it and restarted it. Here is a snippet of the log i've XXX out parts that seemed "private".

.................................................................
2020-07-29T20:58:29.197 [Error] Error indexing method 'Functions.Bounce' Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Functions.Bounce' ---> System.InvalidOperationException : Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.
   at Microsoft.Azure.WebJobs.Host.Tables.TableAttributeBindingProvider.TryCreate(BindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Tables\TableAttributeBindingProvider.cs : 60
....................................................................

2020-07-29T20:58:29.485 [Error] The 'Bounce' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.Bounce'. Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.
2020-07-29T20:58:30.803 [Information] Host Status: {
  "id": "test-url-shortener",
  "state": "Running",
  "version": "3.0.14191.0",
  "versionDetails": "3.0.14191 Commit hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "processUptime": 21317,
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "2.0.0"
  }
}
2020-07-29T20:58:31.011 [Information] Host Status: {
  "id": "test-url-shortener",
  "state": "Running",
  "version": "3.0.14191.0",
  "versionDetails": "3.0.14191 Commit hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "processUptime": 21349,
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "2.0.0"
  }
}
2020-07-29T20:58:54.524 [Information] Loading functions metadata
2020-07-29T20:58:54.629 [Information] 2 functions loaded
2020-07-29T20:59:44.603 [Information] Host lock lease acquired by instance ID 'XXXXXXXXXXXXXXXXX'.
2020-07-29T21:00:11.941 [Information] Host Status: {
  "id": "test-url-shortener",
  "state": "Running",
  "version": "3.0.14191.0",
  "versionDetails": "3.0.14191 Commit hash: XXXXXXXXXXXXXXXXX",
  "processUptime": 122466,
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "2.0.0"
  }
}

**Comment by fabiocav** [comment]
@soninaren can you please follow up here, the bundle version explains the issue, but if the version range was updated to the default, we shouldn't be binding to 2.0

**Comment by fabiocav** [comment]
@jwisener can you confirm you're also unable to compile your Function? 

How are you referencing the storage SDK?

**Comment by soninaren** [comment]
@fabiocav it looks like the version range you provided is inclusive of 2.0.0 because of square bracket.

@jwisener can you set the version property to host.json to `"[1.*, 2.0.0)"`. Please note there is a round bracket in the end.

**Comment by soninaren** [comment]
To clarify by version property i mean the version property for extension bundle
```
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
```

**Comment by fabiocav** [comment]
Good catch. That's my fault for the typo above, as the bracket will make it inclusive (meant to update and didn't after a paste, my apologies)

@jwisener can you please use `[1.*, 2.0.0)` and retry?

**Comment by jwisener** [comment]
@fabiocav , @soninaren  yes, changing it to 2.0.0**)** did it.  My apologies I should have seen that, it is spelled out in the documentation located here: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

**Comment by jwisener** [comment]
Thanks for your help!!!
