### ISSUE TITLE
Function apps running on Linux App Service Plans hitting open file descriptors limit

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-host#6466]
**Description**

I have received a customer issue for a customer running on a dedicated Linux app service plan where their app is hitting IOExceptions of the following form:

`System.IO.IOException : The configured user limit (1024) on the number of inotify instances has been reached`.

It appears this may be [some issue](https://github.com/dotnet/runtime/issues/37610) with .NET Core on Linux, but it is not immediately clear the root cause.

Depending when the app hits this exception, it can result in issues such as key API operations failing, or sync triggers operations failing. Sometimes the exception is caught and the customer's app is able to continue operating normally.

Running queries across our telemetry, I found that between 7/29/20-08/05/20, ~35 sites had been impacted by this exception.

All of the stack traces seem to link to [AutoRecoveringFileSystemWatcher.cs](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs), so that is likely the problem class.

**Sample stacktraces:**

1. Unhandled host error during Keys operation

```
System.IO.IOException : The configured user limit (1024) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
    at System.IO.FileSystemWatcher.StartRaisingEvents()
    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
    at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher.InitializeWatcher() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs : 64
    at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher..ctor(String path,String filter,Boolean includeSubdirectories,WatcherChangeTypes changeTypes,ILoggerFactory loggerFactory) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs : 43
    at Microsoft.Azure.WebJobs.Script.WebHost.BaseSecretsRepository..ctor(String secretsSentinelFilePath) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/BaseSecretsRepository.cs : 34
    at Microsoft.Azure.WebJobs.Script.WebHost.BaseSecretsRepository..ctor(String secretsSentinelFilePath,ILogger logger) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/BaseSecretsRepository.cs : 38
    at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository..ctor(String secretSentinelDirectoryPath,String accountConnectionString,String siteSlotName,ILogger logger) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs : 36
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.CreateSecretsRepository() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 82
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.Create() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 53
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Lazy`1.CreateValue()
    at System.Lazy`1.get_Value()
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.get_Current() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 49
    at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.KeysController.GetHostSecretsByScope(String secretsScope,Boolean includeMasterInSystemKeys) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Controllers/KeysController.cs : 226
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.KeysController.GetHostKey(String name) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Controllers/KeysController.cs : 99
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,ObjectMethodExecutor executor,Object controller,Object[] arguments)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at async Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next,Scope& scope,Object& state,Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next,Scope& scope,Object& state,Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.Invoke(HttpContext context) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs : 52
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Middleware.DefaultMiddlewarePipeline.<>c.<BuildPipeline>b__7_0(??) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/JobHostMiddleware/DefaultMiddlewarePipeline.cs : 31
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Middleware.HstsConfigurationMiddleware.<>c.<-ctor>b__1_0(??) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/HstsConfigurationMiddleware.cs : 24
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Middleware.HstsConfigurationMiddleware.Invoke(HttpContext context,RequestDelegate next) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/HstsConfigurationMiddleware.cs : 42
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Middleware.DefaultMiddlewarePipeline.<>c__DisplayClass8_1.<GetMiddlewareDelegate>b__1(??) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/JobHostMiddleware/DefaultMiddlewarePipeline.cs : 45
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.CustomHttpHeadersMiddleware.Invoke(HttpContext context,RequestDelegate next) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/CustomHttpHeadersMiddleware.cs : 34
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Middleware.DefaultMiddlewarePipeline.<>c__DisplayClass8_1.<GetMiddlewareDelegate>b__1(??) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/JobHostMiddleware/DefaultMiddlewarePipeline.cs : 45
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.JobHostPipelineMiddleware.Invoke(HttpContext httpContext,IJobHostMiddlewarePipeline middleware) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/JobHostPipelineMiddleware.cs : 26
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.ResponseContextItemsCheckMiddleware.Invoke(HttpContext context) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/ResponseContextItemsCheckMiddleware.cs : 29
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HomepageMiddleware.Invoke(HttpContext context) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/HomepageMiddleware.cs : 34
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.ExceptionMiddleware.Invoke(HttpContext context) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Middleware/ExceptionMiddleware.cs : 27
```

2. Sync triggers failure
```
System.IO.IOException : The configured user limit (1024) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
    at System.IO.FileSystemWatcher.StartRaisingEvents()
    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
    at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher.InitializeWatcher() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs : 64
    at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher..ctor(String path,String filter,Boolean includeSubdirectories,WatcherChangeTypes changeTypes,ILoggerFactory loggerFactory) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs : 43
    at Microsoft.Azure.WebJobs.Script.WebHost.BaseSecretsRepository..ctor(String secretsSentinelFilePath) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/BaseSecretsRepository.cs : 34
    at Microsoft.Azure.WebJobs.Script.WebHost.BaseSecretsRepository..ctor(String secretsSentinelFilePath,ILogger logger) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/BaseSecretsRepository.cs : 38
    at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository..ctor(String secretSentinelDirectoryPath,String accountConnectionString,String siteSlotName,ILogger logger) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs : 36
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.CreateSecretsRepository() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 82
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.Create() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 53
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Lazy`1.CreateValue()
    at System.Lazy`1.get_Value()
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.get_Current() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 49
    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.FunctionsSyncManager.GetSyncTriggersPayload() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs : 308
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.FunctionsSyncManager.TrySyncTriggersAsync(Boolean isBackgroundSync) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs : 110
```

3. Caught exception during Host startup (host startup seemed to resume fine)

```
System.IO.IOException : The configured user limit (1024) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
    at System.IO.FileSystemWatcher.StartRaisingEvents()
    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
    at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher.InitializeWatcher() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs : 64
    at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher..ctor(String path,String filter,Boolean includeSubdirectories,WatcherChangeTypes changeTypes,ILoggerFactory loggerFactory) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs : 43
    at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.InitializeFileWatchers() at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/FileMonitoringService.cs : 104
    at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.StartAsync(CancellationToken cancellationToken) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/FileMonitoringService.cs : 89
    at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at /azure-functions-host-bebb2800d0d3f2bed0131ca60473e4b87b3aaa98/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 264
```

**Comment by BKB503** [comment]
@mhoeger is there any temporary solution for this issue, as we are experiencing same issue in timer trigger function app and blocking all the function app which using same app service plan i.e linux

**Comment by mhoeger** [comment]
Adding @balag0 and @divyagandhii to help and see if there is a mitigation?

**Comment by BKB503** [comment]
@mhoeger we have updated function app with reloadOnchange to false seems to better not getting any exceptions, but still monitoring it... in the mean while any other solution is there please let me know  

config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile(configFileName, optional: true, reloadOnChange: false)
                .AddEnvironmentVariables().Build();

**Comment by ankitkumarr** [comment]
In our last platform upgrade (last week ANT 90), the limit was increased to 4096 (by Steve Ernst). This issue should now be fixed. I will clsoe this issue, but please let us know if you continue to see this and we can reopen.
