### ISSUE TITLE
Breaking change analysis operation failed System.InvalidOperationException: Unsupported TypeRef 

### ISSUE THREAD

**Issue by deyanp** [Azure/azure-functions-host#6475]
#### Check for a solution in the Azure portal
Upon starting I get the following warning in a Azure Function App hosted in AKS (Linux, F#, .NET Core 3.1):

info: Host.Startup[412]
      Host initialized (1016ms)
info: Host.Startup[413]
      Host started (1023ms)
info: Host.Startup[0]
      Job host started
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
info: Host.General[316]
      Host lock lease acquired by instance ID '000000000000000000000000A5EAB0E9'.
info: Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService[0]
      Initiating breaking change analysis...
warn: Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService[0]
      Breaking change analysis operation failed
System.InvalidOperationException: Unsupported TypeRef (has module as resolution scope)
   at Marklio.Metadata.MetadataExtensions.<GetFullName>g__RecursiveGetFullName|9_0(TypeRefRow type, <>c__DisplayClass9_0& )
   at Marklio.Metadata.MetadataExtensions.<GetFullName>g__RecursiveGetFullName|9_0(TypeRefRow type, <>c__DisplayClass9_0& )
   at Marklio.Metadata.MetadataExtensions.GetFullName(TypeRefRow type)
   at Marklio.Metadata.DocIdExtensions.GetDocId(TypeRefRow typeRef)
   at DotNetTI.BreakingChangeAnalysis.BreakingChangeReportGenerator.GenerateProblematicApis(MDSkimmer md, Context context)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DotNetTI.BreakingChangeAnalysis.BreakingChangeReportGenerator.ProduceReport(MDSkimmer md)
   at DotNetTI.BreakingChangeAnalysis.BreakingChangeReportGenerator.ProduceReport(String assemblyPath)
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService.LogBreakingChangeReport(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/ChangeAnalysisService.cs:line 140
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService.TryLogBreakingChangeReportAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/ChangeAnalysisService.cs:line 103

#### Investigative information

- Region: West Europe
- AKS versions: 1.16.9 and 1.17.7

#### Repro steps

We migrated from Azure Functions (Premium Plan) to AKS, and I have the feeling this problem only started appearing after migration to AKS ...

#### Related information 

Provide any related information 

* Programming language used: F#
* Bindings used
Input only: HttpTrigger, TimerTrigger

**Comment by deyanp** [comment]
Similar question from another person on StackOverflow, but without any answers:

https://stackoverflow.com/questions/63011644/azure-functions-raises-an-error-with-marklio

**Comment by deyanp** [comment]
@gzuber , any ideas? I guess it is something related to AKS, but not sure what - storage account is properly set ...

**Comment by ghost** [comment]
I reported this same error to Micrsoft they investigated for over 3 weeks and basically came back and said "don't worry about it"

go figure!!

**Comment by auslavs** [comment]
I'm also seeing this in my logs and using F# Http triggers.
My app seems to work first time, but logs these errors after a cold start.
It's also refreshing all my function Keys.
Support ticket to Microsoft a week a ago has not provided anything of note.

**Comment by v-anvari** [comment]
Hi @deyanp , Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required

Hi @auslavs , Request you to submit a new issue with all the details on the form for us to go through the logs

**Comment by deyanp** [comment]
@v-anvari , solved it but you may not like the solution - we migrated away from Azure Functions (see https://dev.to/deyanp/use-azure-kubernetes-service-aks-traefik-instead-of-azure-functions-hosting-azure-api-management-1gkg) .. Of course, this issue was a minor one and not at all the deciding factor ;)

**Comment by v-anvari** [comment]
Thankyou for the confirmation. We are glad you could find a better solution. Closing this issue here.
