### ISSUE TITLE
Installing PowerShell module dependencies via requirements.psd1 doesn't work

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-functions-host#6479]
#### Summary

I am trying to create a Microsoft Azure Functions project that utilizes a third party module dependency from the PowerShell gallery. According to the documentation for Azure Functions, I should be able to simply add the dependency into the `requirements.psd1` file, and the Azure Functions runtime will automatically pull that module into my project. However, this functionality is not working as expected.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell

> Functions lets you leverage PowerShell gallery for managing dependencies. With dependency management enabled, the requirements.psd1 file is used to automatically download required modules.

#### Investigative information

I'm testing this locally for now, but also experienced the problem on Azure Functions. The same behavior occurs both locally and in the Azure Functions service.

#### Repro steps

1. Create an Azure Function App running PowerShell on Windows
2. Add a PowerShell module dependency to `requirements.psd1`
3. Add some code to `run.ps1` to call a command in the module dependency
4. Observe error message indicating that the command is not available

##### host.json

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "managedDependency": {
    "enabled": true
  }
}

```

#####

#### Expected behavior

The command exported by the PowerShell module dependency should be invoked successfully.

#### Actual behavior

The Azure Functions runtime throws an error indicating that the PowerShell command was not found.

```
[8/6/2020 9:10:39 PM] Job host started
Hosting environment: Production
Content root path: C:\Users\TrevorSullivan\git\azure-functions
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[8/6/2020 9:10:44 PM] Host lock lease acquired by instance ID '000000000000000000000000545DB49E'.
[8/6/2020 9:10:51 PM] Executing HTTP request: {
[8/6/2020 9:10:51 PM]   "requestId": "e52b0156-ae2f-4e7b-918f-30baf35c11f8",
[8/6/2020 9:10:51 PM]   "method": "GET",
[8/6/2020 9:10:51 PM]   "uri": "/api/GetNewName"
[8/6/2020 9:10:51 PM] }
[8/6/2020 9:10:51 PM] Executing 'Functions.GetNewName' (Reason='This function was programmatically called via the host APIs.', Id=05e39cfa-4c8c-4aef-8cb8-e76cd5df3788)
[8/6/2020 9:10:51 PM] System Log: { Invocation-Id: 05e39cfa-4c8c-4aef-8cb8-e76cd5df3788; Log-Level: Trace; Log-Message: Profile invocation completed in 127 ms. }
[8/6/2020 9:10:51 PM] System Log: { Invocation-Id: 05e39cfa-4c8c-4aef-8cb8-e76cd5df3788; Log-Level: Trace; Log-Message: Invoking function 'GetNewName' code 188 ms after receiving request. Invocation performance details: DependenciesAvailable: 0 ms; RunspaceAvailable: 152 ms; MetadataAndTraceContextReady: 186 ms; FunctionCodeReady: 187 ms; InputBindingValuesReady: 188 ms; InvokingFunctionCode: 188 ms;  }
[8/6/2020 9:10:51 PM] INFORMATION: PowerShell HTTP trigger function processed a request.
[8/6/2020 9:10:51 PM] System Log: { Invocation-Id: 05e39cfa-4c8c-4aef-8cb8-e76cd5df3788; Log-Level: Warning; Log-Message: CommandNotFoundException detected (error). }
[8/6/2020 9:10:51 PM] ERROR: Invoke-Generate : The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM] At C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1:27 char:12
[8/6/2020 9:10:51 PM] +     Body = Invoke-Generate -Template person
[8/6/2020 9:10:51 PM] +            ~~~~~~~~~~~~~~~
[8/6/2020 9:10:51 PM] + CategoryInfo          : ObjectNotFound: (Invoke-Generate:String) [], CommandNotFoundException
[8/6/2020 9:10:51 PM] + FullyQualifiedErrorId : CommandNotFoundException
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] Script stack trace:
[8/6/2020 9:10:51 PM]    at <ScriptBlock>, C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1: line 27
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] System.Management.Automation.CommandNotFoundException: The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] Result: ERROR: Invoke-Generate : The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM] At C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1:27 char:12
[8/6/2020 9:10:51 PM] +     Body = Invoke-Generate -Template person
[8/6/2020 9:10:51 PM] +            ~~~~~~~~~~~~~~~
[8/6/2020 9:10:51 PM] + CategoryInfo          : ObjectNotFound: (Invoke-Generate:String) [], CommandNotFoundException
[8/6/2020 9:10:51 PM] + FullyQualifiedErrorId : CommandNotFoundException
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] Script stack trace:
[8/6/2020 9:10:51 PM]    at <ScriptBlock>, C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1: line 27
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] System.Management.Automation.CommandNotFoundException: The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM]
Exception: The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Stack:    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame).
[8/6/2020 9:10:51 PM] Executed 'Functions.GetNewName' (Succeeded, Id=05e39cfa-4c8c-4aef-8cb8-e76cd5df3788)
[8/6/2020 9:10:51 PM] Executed HTTP request: {
[8/6/2020 9:10:51 PM]   "requestId": "e52b0156-ae2f-4e7b-918f-30baf35c11f8",
[8/6/2020 9:10:51 PM]   "method": "GET",
[8/6/2020 9:10:51 PM]   "uri": "/api/GetNewName",
[8/6/2020 9:10:51 PM]   "identities": [
[8/6/2020 9:10:51 PM]     {
[8/6/2020 9:10:51 PM]       "type": "WebJobsAuthLevel",
[8/6/2020 9:10:51 PM]       "level": "Admin"
[8/6/2020 9:10:51 PM]     }
[8/6/2020 9:10:51 PM]   ],
[8/6/2020 9:10:51 PM]   "status": 204,
[8/6/2020 9:10:51 PM]   "duration": 438
[8/6/2020 9:10:51 PM] }
```

#### Known workarounds

It might be possible to manually copy the module into the function project, but that would be challenging to maintain.

#### Related information 

Provide any related information 

* Windows 10 version 2004
* Azure Functions CLI `3.0.2630`

**Comment by fabiocav** [comment]
@Francisco-Gamino / @AnatoliB could you please assist?

**Comment by AnatoliB** [comment]
@pcgeek86 Which module are you trying to use? Could you please share the content of your `requirements.psd1`?
