### ISSUE TITLE
Java Function Host failing with Class Cast Exception

### ISSUE THREAD

**Issue by TurtleBeach** [Azure/azure-functions-host#6509]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Java Function App started failing for a function that is IN PRODUCTION and has been running for months
Result: Failure
Exception: ClassCastException: com.microsoft.azure.functions.shaded.com.google.gson.internal.LinkedTreeMap cannot be cast to com.google.gson.internal.LinkedTreeMap
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.microsoft.azure.functions.shaded.com.google.gson.internal.LinkedTreeMap cannot be cast to com.google.gson.internal.LinkedTreeMap
	at ai.com.neuralstudio.functions.GetJobPrice.httpHandler(GetJobPrice.java:410)

Please provide the following:

- Timestamp:
2020-08-14 15:57:31
- Function App version:

- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: (Failed, Id=880b2f47-1eaa-48fa-b1fe-3ebe9d776728, Duration=23ms
- Region: EAST US

#### Repro steps

NO REPRO - LOOK AT THE FUNCTION LOGS!

This is ridiculous. I should not have to debug / change my code for this kind of failure. What did MS do to the Java function host??? 

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by TurtleBeach** [comment]
Additional information - I was able to work around this by pinning the function to 2.0.14192.
1) WHERE does the ...microsoft.azure.functions.shaded.. garbage come from? I complained over a year ago about having to deal with internal Google classes as a result of Microsoft deciding to use gson, which also added a huge amount of unused code to Java functions. But I fixed my functions to deal with the Google class. Now MS is messing it up? IN A PRODUCTION RUNTIME???
2) WHY does MS deploy Java runtimes BEFORE they are available as a standard update to VS Code?? I get messages to update the core tools, and I do so within days. BUT THE JAVA Runtime was NOT updated with the most recent core tools update. I have also asked how to force that update, and have NEVER gotten a straight answer.

I am embarrassed to admit that I actually pay Microsoft for the privilege of using Azure functions.
Incredible.
