### ISSUE TITLE
[CustomHandler]Looking for language specific code with executable when running in a docker container 

### ISSUE THREAD

**Issue by steeling** [Azure/azure-functions-host#6531]
Verified in multiple worker runtimes (python and node), and on multiple distributions.

## Issue:
Running an azure function in a docker container that dispatches queueTriggers to either an httpWorker (deprecated), or a customHandler fails.

## Expected:

Success! It works when running `func start`, but docker run fails with the below error.

## Error Details
Using an httpWorker the error is:

```
Host.Startup[0]
      Error indexing method 'Functions.QueueTrigger'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.QueueTrigger'
 ---> System.InvalidOperationException: Storage account connection string 'AzureWebJobsStorage' does not exist. Make sure that it is a defined App Setting.
   at Microsoft.Azure.WebJobs.StorageAccountProvider.Get(String name) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\StorageAccountProvider.cs:line 43
   at Microsoft.Azure.WebJobs.Host.Queues.Triggers.QueueTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Triggers\QueueTriggerAttributeBindingProvider.cs:line 72
   at Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 162
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 137
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 145
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 73
fail: Function.QueueTrigger[0]
      Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTrigger'. Microsoft.Azure.WebJobs.Extensions.Storage: Storage account connection string 'AzureWebJobsStorage' does not exist. Make sure that it is a defined App Setting.
```

Using customHandler:
```
 Host.Startup[515]
      A host error has occurred during startup operation 'b5a57030-9b99-4795-a4f6-298dd7ffb7f7'.
Microsoft.Azure.WebJobs.Script.HostInitializationException: Did not find functions with language [node].
   at Microsoft.Azure.WebJobs.Script.Utility.VerifyFunctionsMatchSpecifiedLanguage(IEnumerable`1 functions, String workerRuntime, Boolean isPlaceholderMode, Boolean isHttpWorker) in /src/azure-functions-host/src/WebJobs.Script/Utility.cs:line 564
   at Microsoft.Azure.WebJobs.Script.ScriptHost.GetFunctionDescriptorsAsync(IEnumerable`1 functions, IEnumerable`1 descriptorProviders) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 692
   at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFunctionDescriptorsAsync(IEnumerable`1 functionMetadata) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 487
   at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 298
   at Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 251
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 266
``` 

## Steps to reproduce:
1. Download the newest version of azure/func
```
$ func --version
3.0.2798

$ func init --docker

$ func new # on prompts choose azure storage queues, and node as the runtime (happens on others as well)

$ rm QueueTrigger/index.js
```
2. Place some bogus executable file as main.exe (it won't get run) in the main folder.
3. Change the following:

host.json:
```
{
  "version": "2.0",
  "customHandler": {
    "description": {
      "defaultExecutablePath": "main.exe"
    },
    "enableForwardingHttpRequest": true
  },
  "logging": {
    "console": {
      "isEnabled": "true"
    }
  }
}
```
local.settings.json:
```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobs.HttpExample.Disabled": "true"
  },
  "Host": {
    "LocalHttpPort": 7071,
    "CORS": "*",
    "CORSCredentials": false
  }
}
```

QueueTrigger/function.json:
```
{
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "bets-queue",
      "connection": "AzureWebJobsStorage"
    }
  ]
}
```

**Comment by ankitkumarr** [comment]
@steeling, where are you running your docker container? Are you running in an Azure Functions using custom image or just running locally?

For customer handlers, you need to run `func init --worker-runtime custom --docker`, which will generate a Dockerfile for custom handlers. Right now, I think you are using a Node.js Azure Function Dockerfile to run custom handler functions, which only expects Node functions and not custom handlers.

@pragnagopa / @yojagad, do we have documentation on how customers could use Azure Functions Core Tools and deploy custom handlers in a docker environment? I guess the only difference might be `func init --worker-runtime custom`.

**Comment by anthonychu** [comment]
We have some docs updates that will be published after the next Core Tools version is published. (@ankitkumarr do you know if it'll be this week?)

There are a few things that could be happening here. (@pragnagopa and @yojagad  to confirm)

- When running in the docker container, you need to explicitly set the environment variables that are in local.settings.json. The file has no effect in a production environment (which it is in this case).
- You can't use the local storage emulator (`UseDevelopmentStorage=true`) inside the container as the emulator runs on your host machine, not the container. Use a storage account in Azure.
- For custom handlers, set `FUNCTIONS_WORKER_RUNTIME` to `custom`
- Your executable is named `main.exe`, which sounds like it could be a Windows exe. Make sure you compile your custom handler in the same architecture as your deployment target. (in a container, it should be Linux x64).

**Comment by pragnagopa** [comment]
Core tools that supports creating docker files for `Custom Handler` will be released soon. Until then please update docker file as pointed by @anthonychu
