### ISSUE TITLE
NodeJS -  FailureException: Worker was unable to load function IsActiveSponsor: 'TypeError: isPlainObject is not a function'

### ISSUE THREAD

**Issue by warrenbuckley** [Azure/azure-functions-host#6678]
### Problem
After upgrading to the latest version 4.5.6 of @octokit/graphql a NodeJS serverless Azure Function now complains about
**isPlainObject is not a function at Object.keys.forEach.key**

If I revert the package.json dependency back to **4.5.4** then it continues to work as it once did.

This works fine locally with the Azure Functions CLI with VSCode, however once deployed to Azure it gives the following error and is tricky to debug further & pass info onto the NPM package owner of @octokit/graphql

### Error

```
2020-09-21T19:59:05.569 [Information] Executing 'Functions.GithubIssue' (Reason='This function was programmatically called via the host APIs.', Id=d7811d3a-4ede-44c1-b9cf-2c59f48a126f)
2020-09-21T19:59:05.858 [Error] Executed 'Functions.GithubIssue' (Failed, Id=d7811d3a-4ede-44c1-b9cf-2c59f48a126f, Duration=287ms)Result: FailureException: Worker was unable to load function GithubIssue: 'TypeError: isPlainObject is not a function'Stack: TypeError: isPlainObject is not a functionat Object.keys.forEach.key (D:\home\site\wwwroot\node_modules\@octokit\endpoint\dist-node\index.js:24:9)
at Array.forEach (<anonymous>)at mergeDeep (D:\home\site\wwwroot\node_modules\@octokit\endpoint\dist-node\index.js:23:24)
at merge (D:\home\site\wwwroot\node_modules\@octokit\endpoint\dist-node\index.js:52:25)
at withDefaults (D:\home\site\wwwroot\node_modules\@octokit\endpoint\dist-node\index.js:348:20)
at Object.<anonymous> (D:\home\site\wwwroot\node_modules\@octokit\endpoint\dist-node\index.js:376:18)
at Module._compile (internal/modules/cjs/loader.js:778:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

![image](https://user-images.githubusercontent.com/1389894/93815413-d4238380-fc4d-11ea-8784-3256d80e1678.png)
![image](https://user-images.githubusercontent.com/1389894/93815382-c4a43a80-fc4d-11ea-8e00-2e404da7664d.png)

This is the same error reported here but it seems specific to once the code is in the Azure Infrastructure as I am able to run this Azure Function locally on my machine with no issues & with little debugging information available it is hard to pass on repro steps to the package author.
https://github.com/octokit/graphql.js/issues/195

#### Investigative information

Please provide the following:

- Timestamp: 2020-09-21 19:59:05.460
- Function App version: ~3
- Function App name:  https://github-sponsor-check-deploy.azurewebsites.net
- Function name(s) (as appropriate): GithubIssue
- Operation ID: d2b6d677eb2dfb4fbc780a1325880718
- Invocation ID: d7811d3a-4ede-44c1-b9cf-2c59f48a126f
- Region: West Europe
- FUNCTIONS_EXTENSION_VERSION: ~3
- FUNCTIONS_WORKER_RUNTIME: node
- WEBSITE_NODE_DEFAULT_VERSION: ~10

#### Repro steps

1. Deploy the example code at the bottom of this issue
2. Verify it works locally in Azure Functions CLI
3. Deploy/push to Azure Functions
4. Verify you get the same error with 

#### Expected behaviour
 -  The Azure Function to execute without errors

#### Actual behaviour

- Throws the error in the Azure Portal when testing invocation of HTTP Trigger

#### Related information 

Provide any related information 

* Programming language use: NodeJS
* Links to source: https://github.com/warrenbuckley/Is-Github-Sponsor/blob/master/GithubIssue/index.ts
* Deployed via GitHub Action - https://github.com/warrenbuckley/Is-Github-Sponsor/runs/1130600068?check_suite_focus=true#step:5:1

<details>
<summary>function.json</summary>

```json
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ],
  "scriptFile": "../dist/GithubIssue/index.js"
}
```
</details>

<details>
<summary>Source</summary>

```ts
import { Context, HttpRequest } from "@azure/functions"
import { graphql } from "@octokit/graphql";

// Azure Function HTTP Trigger entry point
export default async function (context: Context, req: HttpRequest): Promise<void> {
  const userToken = (req.query.token || (req.body && req.body.token));
  const graphqlWithAuth = graphql.defaults({
    headers: {
      authorization: `token ${userToken}`,
    },
  });

  try {
    const data = await graphqlWithAuth(`{
        viewer {
          login
        }
      }`);

    console.log(data);
    context.res = {
        status: 200,
        body: data
    }
  }
  catch (error) {
    context.res = {
        status: error.status,
        body: error.message
    };
  }

  context.done();
}
```
</details>

**Comment by pragnagopa** [comment]
@mhoeger - transferring this issue to node worker repo. Please investigate. Thanks!
