### ISSUE TITLE
Unable to resolve service for type Microsoft.Azure.WebJobs.Script.IEnvironment with EF DbContext and NServiceBus

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-host#6783]
I've got a project where an Azure Service Bus triggered Function is hosting NServiceBus endpoint registered as a singleton and [delegates/passes](https://github.com/SeanFeldman/NSB-Function-DI-repro/blob/master/AzureFunctions.ASBTrigger.DI/AzureServiceBusTriggerFunction.cs#L23) messages to NServiceBus. NServiceBus [adopts the service collection](https://github.com/SeanFeldman/NSB-Function-DI-repro/blob/3784d9b96ecbe96768e84f7e0d7e1cafd658f4e3/AzureFunctions.ASBTrigger.DI/Startup.cs#L44-L46) provided by the Functions builder to be used as its container as well. Normal services/scoped services [work w/o any issues](https://github.com/SeanFeldman/NSB-Function-DI-repro/blob/3784d9b96ecbe96768e84f7e0d7e1cafd658f4e3/AzureFunctions.ASBTrigger.DI/TriggerMessageHandler.cs#L22) and it works great. Entity Framework DbContext is the exception. When EF DbContext is created, the following exception is thrown:

```
Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IEnvironment' while attempting to activate 
  'Microsoft.Azure.WebJobs.Script.Configuration.ScriptHostOptionsSetup'.
```

<details>
<summary>Full exceptions details</summary>

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IEnvironment' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Configuration.ScriptHostOptionsSetup'.
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Internal.ScopedLoggerFactory.Create(IServiceProvider internalServiceProvider, IDbContextOptions contextOptions)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at AzureFunctions.ASBTrigger.DI.MyDbContext..ctor(DbContextOptions options) in C:\Users\feldm\Desktop\NSB-Function-DI-repro\AzureFunctions.ASBTrigger.DI\MyDbContext.cs:line 8
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at NServiceBus.Extensions.DependencyInjection.ServiceProviderAdapter.ChildScopeAdapter.Build(Type typeToBuild)
   at NServiceBus.Extensions.DependencyInjection.ContainerAdapter`1.ChildContainerAdapter.Build(Type typeToBuild)
   at NServiceBus.CommonObjectBuilder.Build(Type typeToBuild)
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
```

</details>

The repro is available [here](https://github.com/SeanFeldman/NSB-Function-DI-repro/tree/master/AzureFunctions.ASBTrigger.DI).

**Update 2020-10-13**: I've added a [stand-alone Azure Function project ](https://github.com/SeanFeldman/NSB-Function-DI-repro/tree/master/AzureFunctions.ServiceCollectionWrapper)to the repo that demonstrates what NServiceBus is doing (wrapping ServiceCollection). The project behaves exactly as the original repro provided earlier, just less NServiceBus dependency.

#### Repro steps

Provide the steps required to reproduce the problem:

- Provide an Azure Service Bus connection string using the key `AzureWebJobsServiceBus`.
- Provide a connection string to SQL Server using a connection named `MyDbConnectionString`.
- Create a DB with a `Users` table (table schema is below)
- Generate a trigger NServiceBus message using the [`AzureFunctions.Console` project](https://github.com/SeanFeldman/NSB-Function-DI-repro/tree/master/AzureFunctions.Console).
- A message will trigger the Azure Function named [`AzureServiceBusTriggerFunction`](https://github.com/SeanFeldman/NSB-Function-DI-repro/blob/3784d9b96ecbe96768e84f7e0d7e1cafd658f4e3/AzureFunctions.ASBTrigger.DI/AzureServiceBusTriggerFunction.cs).
- NServiceBus will attempt building [`MyDbContext`](https://github.com/SeanFeldman/NSB-Function-DI-repro/blob/3784d9b96ecbe96768e84f7e0d7e1cafd658f4e3/AzureFunctions.ASBTrigger.DI/MyDbContext.cs) and that's when the exception will be thrown.

DB Users table schema
```
CREATE TABLE [dbo].[Users](
	[UserId] [uniqueidentifier] NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
    [IsActive] [bit] NOT NULL)
```

#### Expected behavior

MyDbContext should have been created w/o throwing exceptions.

#### Actual behavior

The exception is thrown.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to the source: provided throughout the issue. The repo: https://github.com/SeanFeldman/NSB-Function-DI-repro/
* Bindings used: Azure Service Bus

**Comment by SeanFeldman** [comment]
It looks like holding on to the `ServiceCollection` provided by the `IFunctionsHostBuilder` and manually building a `IServiceProvider` off it is the issue as outlined [here](https://github.com/Azure/azure-functions-host/issues/4594#issuecomment-512101008). What is not clear, is wherever the service collection provided by `IFunctionsHostBuilder` is later merged by the Functions SDK into some other service collection and as a result of that, some of the services won't be found in the original service collection.

If so, the only way to get all the required services would be to use the `IServiceProvider` constructed by the Functions SDK and injected into the function constructor, as pointed out in this [comment](https://github.com/Azure/azure-functions-host/issues/4594#issuecomment-512101008). @fabiocav, is that the case?

**Comment by SeanFeldman** [comment]
Closing this one as I've resolved the issue having with both NServiceBus and Entity Framework.

For NServiceBus it was a matter of not depending on the reference to the `IServiceCollection` passed into the configuration method. For EF it was a bizarre situation with the `Microsoft.Data.SqlClient.dll` assembly, which is a transient dependency for the EF package `Microsoft.EntityFrameworkCore.SqlServer` brought into the solution was a wrong assembly. I'm still puzzled why. The workaround for that one was to forcefully copy the right assembly from the nuget cache. 

Would appreciate if the https://github.com/Azure/azure-functions-host/issues/6783#issuecomment-707985857 could be addressed, @fabiocav. There are many assumptions about how Azure Functions DI works that are not quite documented and would be good if those could be written down. 

/cc @anthonychu @jeffhollan

**Comment by AKomyshan** [comment]
@SeanFeldman could you please describe just a little bit more how to fix this exception for DbContext ?

**Comment by SeanFeldman** [comment]
The issue was with assembly scanning. Entity Framework package has a dependency on `Microsoft.Data.SqlClient` which is not a conventional package. It has a placeholder assembly that is found in the `bin` folder and it has a platform-specific assembly that is resolved at runtime. There are two options. One is to compile the Function project against a specific target and that places the correct target specific assembly in the `bin` folder. If you compile the project as portable, a workaround would be to copy the correct assembly into the `bin` folder manually after compilation takes place. I went with the first option, @AKomyshan.
