### ISSUE TITLE
Log a more descriptive error message when a language workers crashes or exists unexpectedly

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#6916]
Currently, when a language worker crashes or exists unexpectedly, we do not log a very describe error. Here is the current exception stack:

```
Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException : D:\Program Files (x86)\dotnet\dotnet.exe exited with code -1073741818
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs : 85
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at D:\a\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 85
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) at D:\a\1\s\src\WebJobs.Script\Description\FunctionGenerator.cs : 225
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 539
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 486
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 430
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 239
```
It would be great if we could detect this and write a better error message in the logs.

**Comment by Francisco-Gamino** [comment]
cc: @kashimiz @pragnagopa

**Comment by pragnagopa** [comment]
Unfortunately, error provided above ` D:\Program Files (x86)\dotnet\dotnet.exe exited with code -1073741818` is the exact error given by the language worker process when it crashed. Host is capturing and logging errors logged to console std error stream.

Assigned this to @Francisco-Gamino  - As part of CRI investigation please update the issue if you find anything else that can be improved. If not, please close the issue.

**Comment by mhoeger** [comment]
I think there is potential for a race condition though - 
Here is where we read exceptions from stderr:
https://github.com/Azure/azure-functions-host/blob/6a92bdf9dbb2118eef07b11a07a0b2d613438327/src/WebJobs.Script/Workers/ProcessManagement/WorkerProcess.cs#L137

But this is where std err data begins to be processed:
https://github.com/Azure/azure-functions-host/blob/6a92bdf9dbb2118eef07b11a07a0b2d613438327/src/WebJobs.Script/Workers/ProcessManagement/WorkerProcess.cs#L88

And it doesn't get added to the queue until here:
https://github.com/Azure/azure-functions-host/blob/6a92bdf9dbb2118eef07b11a07a0b2d613438327/src/WebJobs.Script/Workers/ProcessManagement/WorkerProcess.cs#L127

One enhancement could be to try to add more coordination here, although we my have to assume that `ErrorDataReceived` always happens before `Exited` :/

**Comment by andreesteve** [comment]
@mhoeger - do you believe this race condition is in the azure function exception handling side? As in, the dotnet error code "-1073741818" is not the actual underlying error code from the function itself, but thrown by the host exception handling code?

@Francisco-Gamino, we have a powershell azure function that is reproing this consistently whenever we call KeyVault from Az module. Let me know if you are looking for a repro - not sure how long ours will last, but I can certainly share the logs.
