### ISSUE TITLE
An unhandled storage exception occurred when reading/writing scale metrics

### ISSUE THREAD

**Issue by damoodamoo** [Azure/azure-functions-host#7234]
We have some functions hosted in the premium plan with the following setup:
- VNET integration
- WEBSITE_VNET_ROUTE_ALL = 1
- Runtime Scale Monitoring = On
- Cosmos (and other resources - Service Bus etc) accessed via private link

We're getting several of the following exceptions logged per minute for functions with Runtime Scale Monitoring on: 
```
An unhandled storage exception occurred when reading/writing scale metrics: Microsoft.Azure.Cosmos.Table.StorageException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Script.WebHost.TableStorageScaleMetricsRepository.ExecuteQuerySafeAsync(CloudTable metricsTable, TableQuery query) in D:\a\1\s\src\WebJobs.Script.WebHost\Scale\TableStorageScaleMetricsRepository.cs:line 306
   at Microsoft.Azure.WebJobs.Script.WebHost.TableStorageScaleMetricsRepository.ReadRecentMetrics(CloudTable metricsTable) in D:\a\1\s\src\WebJobs.Script.WebHost\Scale\TableStorageScaleMetricsRepository.cs:line 323
   at Microsoft.Azure.WebJobs.Script.WebHost.TableStorageScaleMetricsRepository.ReadMetricsAsync(IEnumerable`1 monitors) in D:\a\1\s\src\WebJobs.Script.WebHost\Scale\TableStorageScaleMetricsRepository.cs:line 104
```

It looks like the function host is attempting to reach out to some Cosmos instance somewhere, and failing. There doesn't seem to be any guidance over this in the docs.

#### Investigative information

Please provide the following:

- Timestamp: 	3/11/2021, 1:18:12 PM (Local time)	
- Function App version: azurefunctions: 3.0.15405.0
- Function App name: mesh-send-qcsly-premium
- Function name(s) (as appropriate): mesh-send
- Invocation ID: N/A
- Region: UK South

#### Repro steps

Environment set up as described - exceptions logged (3-4 per minute) without any interaction from us. Interestingly the functions *do* seem to still scale under load, so not sure what's going on here.

#### Expected behavior
No exceptions logged

**Comment by damoodamoo** [comment]
I think it would help us diagnose what's going on if we knew where the runtime scale metrics were supposed to be stored - where is the code trying to reach?

**Comment by damoodamoo** [comment]
I'm happy to close this - we found the issue - despite the Cosmos SDK being used, Runtime Scale Monitoring is actually logging things to Azure table storage, in the storage account linked to the function. We were missing a private endpoint connection to the table endpoint to allow this. Added that, recreated things, and I can see the Metrics table in our storage acct.
