### ISSUE TITLE
Function metadata load errors when app instance is under resource pressure

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-host#7238]
I'm frequently running into the following error when running my function app in my Kubernetes cluster.

```
fail: Function.HelloSequence[3]
Executed 'HelloSequence' (Failed, Id=1c29a263-870f-4621-989a-14d43f0a3380, Duration=0ms)
System.InvalidOperationException: Unable to load metadata for function 'HelloSequence'.
at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.StartFunction(FunctionInstanceLogEntry item) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstance
Logger.cs:line 124
at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebH
ost/Diagnostics/FunctionInstanceLogger.cs:line 88
at Microsoft.Azure.WebJobs.Host.Loggers.CompositeFunctionEventCollector.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azur
e.WebJobs.Host\Loggers\CompositeFunctionEventCollector.cs:line 21
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure
.WebJobs.Host\Executors\FunctionExecutor.cs:line 94
```

I spoke with @balag0 about this and we both suspect it's a race condition. The Kubernetes cluster I'm running in is resource constrained, which likely explains why we'd see this kind of problem there and not in proper Azure Functions environments.

### Investigative information

Please provide the following:

- Docker image: **mcr.microsoft.com/azure-functions/dotnet:3.0**
- Function App version: **3.0.15277**
- Function App name: **N/A**
- Function name(s) (as appropriate): **N/A**
- Invocation ID: **N/A**
- Region: **N/A**

### Repro steps

1. Create a .NET function app and deploy it to a small-ish K8s environment (2 VMs)
2. Add enough load to scale the function app to 5-10 instances (using KEDA)

### Expected behavior

We should never see this error. I verified there are no problems with the Function metadata.

### Actual behavior

See the description above. The issue is inconsistent, which is why I think it's a race condition, probably on app startup.

### Known workarounds

Run on faster VMs?

### Related information 

Provide any related information 

* Programming language used: **.NET 3.1 Precompiled**
* Links to source: **Probably not relevant**
* Bindings used: **Durable Functions**

**Comment by v-anvari** [comment]
Adding this issue triaged for further investigation

**Comment by AmyJeanes** [comment]
I'm seeing the same behaviour intermittently in a Kubernetes cluster as well, notably on a service bus triggered function which is disabled by not including it in the `AzureFunctionsJobHost__functions__X` environment variables

```
System.InvalidOperationException: Unable to load metadata for function 'FunctionName'.
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.StartFunction(FunctionInstanceLogEntry item) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:line 124
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:line 88
   at Microsoft.Azure.WebJobs.Host.Loggers.CompositeFunctionEventCollector.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\CompositeFunctionEventCollector.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 94
```

**Comment by AmyJeanes** [comment]
After further investigation it appears the problem is worse than this. It is picking messages off the service bus and dead lettering them before the other version of this function (scaled with KEDA to the service bus queue length) with the same function enabled with `AzureFunctionsJobHost__functions__X` can read them.

We have tried restarting the function several times with unconstrained CPU resources (2 Azure vCPU cores) but it consistently is coming back with this error every time the function tries to trigger which it should not even be attempting to.

We are correctly seeing the startup message which shows us that the function is not enabled but yet it is still erroring and picking messages off the queue for it: `A function allow list has been specified, excluding all but the following functions: [XXX, YYY, ZZZ]`.

**Comment by smokedlinq** [comment]
I get this under load in Azure Functions running v3 runtime and the dotnet-isolated worker. Happens when an EventHubTrigger has to process a large number of requests.

**Comment by mathewc** [comment]
The following query shows occurrences of this happening for many different apps. Should be enough for us to go on to investigate what host conditions are leading to this - I agree that it's likely a race condition in [FunctionMetadataManager](https://github.com/Azure/azure-functions-host/blob/ebe1aafa9bf01ed56202b21a1a47a1897d2cebf9/src/WebJobs.Script/Host/FunctionMetadataManager.cs#L70). There are situations where functions may be executing while the host is restarting, which will lead to the metadata manager internally reloading functions. @pragnagopa @fabiocav we should get this assigned to someone ASAP for investigation. Looks like it's happening quite often based on the below query.

FunctionsLogs
| where PreciseTimeStamp > ago(1d)
| where EventName == "FunctionCompleted"
| where Level == 2
| where Details startswith "System.InvalidOperationException : Unable to load metadata for function" and Details contains "WebHost.Diagnostics.FunctionInstanceLogger.StartFunction"
