### ISSUE TITLE
Exception while executing function: ... Did not find any initialized language workers

### ISSUE THREAD

**Issue by geg00** [Azure/azure-functions-host#7403]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

 System.InvalidOperationException: Did not find any initialized language workers
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels, Int32 maxProcessCount) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 283
   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 93
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
   at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 555
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 501
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 326

-->

#### Investigative information

Please provide the following:

- Timestamp:  All the time
- Function App version:   
- Function App name: HttpTrigger1
- Function name(s) (as appropriate):
- Invocation ID: 
- Region: US Central

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used   python 
* Links to source
* Bindings used

**Comment by v-anvari** [comment]
Hi @geg00, Thank you for your feedback! We will investigate this further, can you provide the following details:

Repro steps: (Provide the steps required to reproduce the problem)
Invocation ID:

**Comment by geg00** [comment]
Just invoke the code 
http://<<Azure function >/api/HttpTrigger1?name=Anusri+Varier+works+at+Microsoft

This is the expected results on my PC with localhost (This is a copy of the log Terminal log output)

[2021-05-24T13:57:23.012Z] Executing 'Functions.HttpTrigger1' (Reason='This function was programmatically called via the host APIs.', Id=135ca9e3-ec8c-4691-81cc-4835f84486bd)
[2021-05-24T13:58:04.711Z] Python HTTP trigger function processed a request.
[2021-05-24T13:58:04.817Z] [CLS] Hello, Anusri Varier works at Microsoft. This HTTP triggered function executed successfully. [SEP]
[2021-05-24T13:58:06.471Z] [{'word': 'An', 'score': 0.9994239211082458, 'entity': 'I-PER', 'index': 3, 'start': 7, 'end': 9}, {'word': '##us', 'score': 0.9959086179733276, 'entity': 'I-PER', 'index': 4, 'start': 9, 'end': 11}, {'word': '##ri', 'score': 0.9993330240249634, 'entity': 'I-PER', 'index': 5, 'start': 11, 'end': 13}, {'word': 'V', 'score': 0.9996984601020813, 'entity': 'I-PER', 'index': 6, 'start': 14, 'end': 15}, {'word': '##ari', 'score': 0.9937119483947754, 'entity': 'I-PER', 'index': 7, 'start': 15, 'end': 18}, {'word': '##er', 'score': 0.9966721534729004, 'entity': 'I-PER', 'index': 8, 'start': 18, 'end': 20}, {'word': 'Microsoft', 'score': 0.9989838600158691, 'entity': 'I-ORG', 'index': 11, 'start': 30, 'end': 39}]
[2021-05-24T13:58:06.814Z] Executed 'Functions.HttpTrigger1' (Succeeded, Id=135ca9e3-ec8c-4691-81cc-4835f84486bd, Duration=43824ms)

When publish the code to Azure
I get that error message every time that I invoke.

**Comment by geg00** [comment]
I thought maybe this issue is related to that I have a different version of python on my PC that Azure.
I deleted all my python versions from my PC and I went with python 3.8.6 windows version

Here are my results
This is the output of the deployment

12:03:59 AM: Error: Python projects are not supported on Windows Function Apps. Deploy to a Linux Function App instead.
12:04:27 AM: Error: Python projects are not supported on Windows Function Apps. Deploy to a Linux Function App instead.
9:01:47 AM KDone: Starting deployment...
9:01:48 AM KDone: Creating zip package...
9:11:44 AM KDone: Fetching changes.
9:11:45 AM KDone: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/76d2fb17-6d17-4418-bfa3-82a7e3e87b14.zip (1178.29 MB) to /tmp/zipdeploy/extracted
9:12:24 AM KDone: Updating submodules.
9:12:25 AM KDone: Preparing deployment for commit id '7d2548a269'.
9:12:26 AM KDone: Repository path is /tmp/zipdeploy/extracted
9:12:26 AM KDone: Running oryx build...
9:12:26 AM KDone: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
9:12:27 AM KDone: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
9:12:27 AM KDone: You can report issues at https://github.com/Microsoft/Oryx/issues
9:12:27 AM KDone: Oryx Version: 0.2.20201015.1, Commit: 1a35fbce482b20b71290f3a837a3469803ce4b44, ReleaseTagName: 20201015.1
9:12:27 AM KDone: Build Operation ID: |BtDdWry3CO0=.f93bef8a_
9:12:27 AM KDone: Repository Commit : 7d2548a2696047c6be169b926209167f
9:12:27 AM KDone: Detecting platforms...
9:12:28 AM KDone: Detected following platforms:
9:12:28 AM KDone:   python: 3.8.6
9:12:28 AM KDone: Version '3.8.6' of platform 'python' is not installed. Generating script to install it...
9:12:28 AM KDone: Source directory     : /tmp/zipdeploy/extracted
9:12:28 AM KDone: Destination directory: /home/site/wwwroot
9:12:28 AM KDone: Downloading and extracting 'python' version '3.8.6' to '/tmp/oryx/platforms/python/3.8.6'...
9:12:29 AM KDone: Downloaded in 1 sec(s).
9:12:29 AM KDone: Verifying checksum...
9:12:29 AM KDone: Extracting contents...
9:12:32 AM KDone: Done in 4 sec(s).
9:12:32 AM KDone: Python Version: /tmp/oryx/platforms/python/3.8.6/bin/python3.8
9:12:32 AM KDone: Running pip install...
9:12:33 AM KDone: [14:12:33+0000] Looking in links: https://download.pytorch.org/whl/torch_stable.html
9:12:34 AM KDone: [14:12:34+0000] Collecting azure-functions
9:12:34 AM KDone: [14:12:34+0000]   Downloading azure_functions-1.7.0-py3-none-any.whl (135 kB)
9:12:35 AM KDone: [14:12:35+0000] Collecting transformers
9:12:35 AM KDone: [14:12:35+0000]   Downloading transformers-4.6.1-py3-none-any.whl (2.2 MB)
9:12:36 AM KDone: [14:12:36+0000] Collecting torch==1.8.1+cpu
9:12:36 AM KDone: [14:12:36+0000]   Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp38-cp38-linux_x86_64.whl (169.1 MB)
9:12:50 AM KDone: [14:12:50+0000] Collecting torchvision==0.9.1+cpu
9:12:50 AM KDone: [14:12:50+0000]   Downloading https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp38-cp38-linux_x86_64.whl (13.3 MB)
9:12:51 AM KDone: [14:12:51+0000] Collecting torchaudio===0.8.1
9:12:51 AM KDone: [14:12:51+0000]   Downloading torchaudio-0.8.1-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
9:12:52 AM KDone: [14:12:52+0000] Collecting filelock
9:12:52 AM KDone: [14:12:52+0000]   Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
9:12:53 AM KDone: [14:12:53+0000] Collecting packaging
9:12:53 AM KDone: [14:12:53+0000]   Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
9:12:53 AM KDone: [14:12:53+0000] Collecting tqdm>=4.27
9:12:53 AM KDone: [14:12:53+0000]   Downloading tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
9:12:53 AM KDone: [14:12:53+0000] Collecting huggingface-hub==0.0.8
9:12:53 AM KDone: [14:12:53+0000]   Downloading huggingface_hub-0.0.8-py3-none-any.whl (34 kB)
9:12:55 AM KDone: [14:12:55+0000] Collecting regex!=2019.12.17
9:12:55 AM KDone: [14:12:55+0000]   Downloading regex-2021.4.4-cp38-cp38-manylinux2014_x86_64.whl (733 kB)
9:12:55 AM KDone: [14:12:55+0000] Collecting tokenizers<0.11,>=0.10.1
9:12:55 AM KDone: [14:12:55+0000]   Downloading tokenizers-0.10.2-cp38-cp38-manylinux2010_x86_64.whl (3.3 MB)
9:12:56 AM KDone: [14:12:56+0000] Collecting sacremoses
9:12:56 AM KDone: [14:12:56+0000]   Downloading sacremoses-0.0.45-py3-none-any.whl (895 kB)
9:12:56 AM KDone: [14:12:56+0000] Collecting requests
9:12:56 AM KDone: [14:12:56+0000]   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
9:12:57 AM KDone: [14:12:57+0000] Collecting numpy>=1.17
9:12:58 AM KDone: [14:12:57+0000]   Downloading numpy-1.20.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
9:12:58 AM KDone: [14:12:58+0000] Collecting typing-extensions
9:12:58 AM KDone: [14:12:58+0000]   Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
9:12:59 AM KDone: [14:12:59+0000] Collecting pillow>=4.1.1
9:12:59 AM KDone: [14:12:59+0000]   Downloading Pillow-8.2.0-cp38-cp38-manylinux1_x86_64.whl (3.0 MB)
9:13:00 AM KDone: [14:13:00+0000] Collecting pyparsing>=2.0.2
9:13:00 AM KDone: [14:13:00+0000]   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
9:13:00 AM KDone: [14:13:00+0000] Collecting click
9:13:00 AM KDone: [14:13:00+0000]   Downloading click-8.0.1-py3-none-any.whl (97 kB)
9:13:01 AM KDone: [14:13:01+0000] Collecting joblib
9:13:01 AM KDone: [14:13:01+0000]   Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
9:13:01 AM KDone: [14:13:01+0000] Collecting six
9:13:01 AM KDone: [14:13:01+0000]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
9:13:01 AM KDone: [14:13:01+0000] Collecting idna<3,>=2.5
9:13:01 AM KDone: [14:13:01+0000]   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
9:13:01 AM KDone: [14:13:01+0000] Collecting certifi>=2017.4.17
9:13:01 AM KDone: [14:13:01+0000]   Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
9:13:02 AM KDone: [14:13:02+0000] Collecting chardet<5,>=3.0.2
9:13:02 AM KDone: [14:13:02+0000]   Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
9:13:02 AM KDone: [14:13:02+0000] Collecting urllib3<1.27,>=1.21.1
9:13:02 AM KDone: [14:13:02+0000]   Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
9:13:03 AM KDone: [14:13:03+0000] Installing collected packages: azure-functions, filelock, pyparsing, packaging, tqdm, idna, certifi, chardet, urllib3, requests, huggingface-hub, regex, tokenizers, click, joblib, six, sacremoses, numpy, transformers, typing-extensions, torch, pillow, torchvision, torchaudio
9:13:32 AM KDone: [14:13:32+0000] Successfully installed azure-functions-1.7.0 certifi-2020.12.5 chardet-4.0.0 click-8.0.1 filelock-3.0.12 huggingface-hub-0.0.8 idna-2.10 joblib-1.0.1 numpy-1.20.3 packaging-20.9 pillow-8.2.0 pyparsing-2.4.7 regex-2021.4.4 requests-2.25.1 sacremoses-0.0.45 six-1.16.0 tokenizers-0.10.2 torch-1.8.1+cpu torchaudio-0.8.1 torchvision-0.9.1+cpu tqdm-4.60.0 transformers-4.6.1 typing-extensions-3.10.0.0 urllib3-1.26.4
9:13:32 AM KDone: WARNING: You are using pip version 20.2.3; however, version 21.1.2 is available.
9:13:32 AM KDone: You should consider upgrading via the '/tmp/oryx/platforms/python/3.8.6/bin/python3.8 -m pip install --upgrade pip' command.
9:13:33 AM KDone: Done in 61 sec(s).
9:13:33 AM KDone: Copying files to destination directory '/home/site/wwwroot'...
9:14:39 AM KDone: Done in 66 sec(s).
9:14:39 AM KDone: Removing existing manifest file
9:14:39 AM KDone: Creating a manifest file...
9:14:39 AM KDone: Manifest file created.
9:14:39 AM KDone: Done in 131 sec(s).
9:14:42 AM KDone: Running post deployment command(s)...
9:14:42 AM KDone: Triggering recycle (preview mode disabled).
9:14:42 AM KDone: Linux Consumption plan has a 1.5 GB memory limit on a remote build container.
9:14:42 AM KDone: To check our service limit, please visit https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits
9:14:42 AM KDone: Creating placeholder blob for linux consumption function app...
9:14:42 AM KDone: SCM_RUN_FROM_PACKAGE placeholder blob scm-latest-KDone.zip located
9:14:42 AM KDone: Writing the artifacts to a squashfs file
9:15:12 AM KDone: Parallel mksquashfs: Using 1 processor
9:15:12 AM KDone: Creating 4.0 filesystem on /home/site/artifacts/functionappartifact.squashfs, block size 131072.
9:15:15 AM KDone: [===========-                                                ]  4600/22946  20%
9:15:20 AM KDone: [================-                                           ]  6500/22946  28%
9:15:37 AM KDone: [=================|                                          ]  6700/22946  29%
9:15:47 AM KDone: [===================|                                        ]  7700/22946  33%
9:17:38 AM KDone: [=====================\                                      ]  8400/22946  36%
9:17:46 AM KDone: [=====================================================\      ] 21000/22946  91%
9:17:47 AM KDone: [=========================================================\  ] 22200/22946  96%
9:17:51 AM KDone: [=========================================================|  ] 22400/22946  97%
9:17:51 AM KDone: [===========================================================\] 22946/22946 100%
9:17:51 AM KDone: Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
9:17:51 AM KDone: 	compressed data, compressed metadata, compressed fragments, compressed xattrs
9:17:51 AM KDone: 	duplicates are removed
9:17:51 AM KDone: Filesystem size 1422052.00 Kbytes (1388.72 Mbytes)
9:17:52 AM KDone: 	69.87% of uncompressed filesystem size (2035427.24 Kbytes)
9:17:52 AM KDone: Inode table size 111227 bytes (108.62 Kbytes)
9:17:52 AM KDone: 	32.87% of uncompressed inode table size (338392 bytes)
9:17:52 AM KDone: Directory table size 92017 bytes (89.86 Kbytes)
9:17:52 AM KDone: 	36.75% of uncompressed directory table size (250413 bytes)
9:17:52 AM KDone: Number of duplicate files found 176
9:17:52 AM KDone: Number of inodes 8633
9:17:52 AM KDone: Number of files 7804
9:17:52 AM KDone: Number of fragments 629
9:17:52 AM KDone: Number of symbolic links  0
9:17:52 AM KDone: Number of device nodes 0
9:17:52 AM KDone: Number of fifo nodes 0
9:17:52 AM KDone: Number of socket nodes 0
9:17:52 AM KDone: Number of directories 829
9:17:52 AM KDone: Number of ids (unique uids + gids) 1
9:17:52 AM KDone: Number of uids 1
9:17:52 AM KDone: 	root (0)
9:17:52 AM KDone: Number of gids 1
9:17:52 AM KDone: 	root (0)
9:17:52 AM KDone: Uploading built content /home/site/artifacts/functionappartifact.squashfs for linux consumption function app...
9:18:26 AM KDone: Resetting all workers for kdone.azurewebsites.net
9:18:26 AM KDone: Deployment successful.
9:18:39 AM KDone: Syncing triggers...
9:19:23 AM KDone: Querying triggers...
9:19:25 AM KDone: HTTP Trigger Urls:
  HttpTrigger1: https://<<FunctionApp>>.azurewebsites.net/api/httptrigger1

Now, 
I'm getting a different error message in the Live Metrics 
https://<<FunctionApp>>.azurewebsites.net/api/httptrigger1?name=Anusri+Varier+works+at+Microsoft

Time	9:23:38 AM
Exception type	System.AggregateException
Exception message	Number of initialized language workers exceeded:1 exceeded maxProcessCount: 0
EventId	5
Category	Microsoft.Extensions.Hosting.Internal.Host
FormattedMessage	Hosting shutdown exception
System.AggregateException: One or more hosted services failed to stop. (Number of initialized language workers exceeded:1 exceeded maxProcessCount: 0)
 ---> System.InvalidOperationException: Number of initialized language workers exceeded:1 exceeded maxProcessCount: 0
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.GetInitializedWorkerChannelsAsync() in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 315
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.ShutdownAsync() in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 266
   at Microsoft.Azure.WebJobs.Script.Workers.FunctionInvocationDispatcherShutdownManager.StopAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Workers/FunctionInvocationDispatcherShutdownManager.cs:line 26
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

[requirements.txt](https://github.com/Azure/azure-functions-host/files/6533034/requirements.txt)

This is the code
''' python
import logging

import azure.functions as func
from transformers import  pipeline, AutoConfig, AutoModel, AutoTokenizer

import os


config = AutoConfig.from_pretrained('./model/')
tokenizer = AutoTokenizer.from_pretrained(
    './model/', truncation=True, padding=True, add_prefix_space=True)
model = AutoModel.from_config(config)
try:
    nlp = pipeline('ner', model='./model/', tokenizer='./model/', )
except Exception as e:
    logging.info(e)

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        encoded = tokenizer.encode(f"Hello, {name}. This HTTP triggered function executed successfully.")
        logging.info(tokenizer.decode(encoded))
        try:
            logging.info(nlp(f"Hello, {name}. This HTTP triggered function executed successfully."))
        except Exception as e:
            logging.info(e)
            logging.info(name)
        return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
    else:
        return func.HttpResponse(
             "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
             status_code=200
        )

'''

**Comment by v-anvari** [comment]
Transferring this issue to the python repository for further investigation
