### ISSUE TITLE
Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/azure-functions-host#7630]
I received the following error from a function running on a 5-minute timer in my log during the night:

```
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function '...' was unable to start.
 ---> Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:58b70f4d-901e-0082-4be0-95f491000000
Time:2021-08-20T16:30:26.3396767Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed
Additional Information:
AuthenticationErrorDetail: The MAC signature found in the HTTP request 'dSWB1Bhpne5spl5fSzzoOIw3zoyK7P887JynlGL/0IM=' is not the same as any computed signature. Server used following string to sign: 'PUT
x-ms-client-request-id:34246e38-a6d1-41f4-ab1f-912282e18740
x-ms-date:Fri, 20 Aug 2021 16:30:26 GMT
x-ms-lease-action:acquire
x-ms-lease-duration:60
x-ms-proposed-lease-id:d60b1040-c64c-4082-9816-0b0f39c07a3c
x-ms-return-client-request-id:true
x-ms-version:2020-04-08
/.../azure-webjobs-hosts/locks/.../....Run.Listener
comp:lease'.
Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 58b70f4d-901e-0082-4be0-95f491000000
x-ms-error-code: AuthenticationFailed
Date: Fri, 20 Aug 2021 16:30:26 GMT
Content-Length: 986
Content-Type: application/xml
   at Azure.Storage.Blobs.BlobRestClient.Blob.AcquireLeaseAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.AcquireLeaseAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, Nullable`1 timeout, Nullable`1 duration, String proposedLeaseId, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String ifTags, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.AcquireInternal(TimeSpan duration, RequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.AcquireAsync(TimeSpan duration, RequestConditions conditions, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Script.BlobLeaseDistributedLockManager.TryAcquireLeaseAsync(BlobLeaseDistributedLockManager lockManager, BlobClient blobClient, TimeSpan leasePeriod, String proposedLeaseId, CancellationToken cancellationToken, String accountOverride) in D:\a\1\s\src\WebJobs.Script\Host\DistributedLockManagers\BlobLeaseDistributedLockManager.cs:line 134
   at Microsoft.Azure.WebJobs.Script.BlobLeaseDistributedLockManager.TryLockAsync(String account, String lockId, String lockOwnerId, String proposedLeaseId, TimeSpan lockPeriod, CancellationToken cancellationToken) in D:\a\1\s\src\WebJobs.Script\Host\DistributedLockManagers\BlobLeaseDistributedLockManager.cs:line 82
   at Microsoft.Azure.WebJobs.Host.SingletonManager.TryLockAsync(String lockId, String functionInstanceId, SingletonAttribute attribute, CancellationToken cancellationToken, Boolean retry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonManager.cs:line 113
   at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonListener.cs:line 48
   at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 68
```

I have removed some application-specific details but let me know if you need anything else.

The application is running on Azure Functions v3 on .NET Core 3.1. The function is running on the app service plan.

Is this an error that I will need to worry about going forward? The function has been running successfully for months. I did deploy a new version of the function yesterday but the updates where only a couple of internal nuget package updates.

The function is running with the following NuGet packages and versions:

```
<PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.1.3" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
```

As additional info, there's another log message in the log two minutes before the error:

```
An unhandled exception has occurred. Host is shutting down.
```

**Comment by v-anvari** [comment]
Hi @ThomasArdal , To understand if this error was a result of the new version of packages, can we know the number of occurrences of this error. 

Can we have the below details of your App so as to check the backend logs:
Function failed invocation id 
Time stamp during the error
Region in which the function App is running

Also has any authentication changed recently? can you refresh the authentication used in your code or function App and check if that works

**Comment by ThomasArdal** [comment]
I think everything is in the stack trace I posted, right? Not sure about invocation id and if that compares to RequestId? In that case it's `58b70f4d-901e-0082-4be0-95f491000000`. Timestamp is `2021-08-20T16:30:26.3396767Z`. The error happened 6 times over two minutes. The function is running in West US.

**Comment by v-anvari** [comment]
Thank you for the details, We shall go through the backend logs and update our findings

**Comment by v-anvari** [comment]
Hi @ThomasArdal , Apologies, I was unable to find the App with the request ID. you will find the invocation id in the monitor logs of your functions. You can give me any one of those id's

**Comment by ThomasArdal** [comment]
I'm not sure where too look for these since I don't have monitoring enabled on application insights. Maybe this will help?

```
The MAC signature found in the HTTP request 'AG7s6GGJJ6xSr+2QFmkYAWQn4x5KgH7UGFIChpzrz7k=' is not the same as any computed signature. Server used following string to sign: 'PUT
x-ms-client-request-id:794a9f4c-e5fa-4056-b8a8-f6137a305d2c
x-ms-date:Fri, 20 Aug 2021 16:27:43 GMT
x-ms-lease-action:renew
x-ms-lease-id:189154ab-8fb8-4bff-8edb-8b53d10ac20a
x-ms-return-client-request-id:true
x-ms-version:2020-04-08
/uptimeschedulerv2/azure-webjobs-hosts/locks/elmah-io-uptime-scheduler-v2-wes/Elmah.Io.UptimeMonitoring.Scheduler.UptimeScheduler.Run.Listener
comp:lease'.
```

**Comment by v-anvari** [comment]
Hi @ThomasArdal , Unfortunately, This information wont help, can you share the App name on mail or teams- 
v-anvari@microsoft.com

**Comment by v-anvari** [comment]
Hi @ThomasArdal , 

Even I see the same error from your exception, I guess from the error its clear that there is a mismatch of the signature used. Since this is a client side mistake, there is not much we are able to conclude. 
The MAC signature found in the HTTP request 'dSWB1Bhpne5spl5fSzzoOIw3zoyK7P887JynlGL/0IM=' is not the same as any computed signature. Server used following string to sign: 'PUT. 

If you are using the managed identity for your App, then there may be a miss configuration from there as well. We are not sure of the changes that you have recently made.

You can also go to App Service Diagnostics to configure App Settings correctly.

**Comment by ThomasArdal** [comment]
I'm not running with any managed identity on that app. I did go through the logs, though. On the day of the error (August 20) I released a new version of the function at 9 AM in the morning. The release contained the following change:

```diff
-    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.16" />
+    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.18" />
```

I'm not sure if that could cause the error I'm seeing. The strange thing is that the function ran for several hours before logging that error.

**Comment by v-anvari** [comment]
It may have happened that while the web restarted, it lost the keys or was miss configured internally. Can you tell us in detail, how you are authenticating and a repro

**Comment by ThomasArdal** [comment]
I cannot repro this. The error is taken directly from my production log. Was only publishing it here since I thought you wanted to know. It's not something that I'm experiencing localhost or has seen since this error was logged. If you want to close the issue it's fine with me.

**Comment by v-anvari** [comment]
Thank you for the confirmation
