### ISSUE TITLE
Stopping Func Host Start

### ISSUE THREAD

**Issue by phillipharding** [Azure/azure-functions-host#7833]
After running ```func host start``` for debugging and testing, I press ```CTRL+C``` to terminate the session.

After upgrading to **v3.0.3904** an error message is displayed when I press ```CTRL+C```...
```
^Cinfo: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 281435.3278ms 200 application/grpc
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HMCP6FGIJID5", Request id "0HMCP6FGIJID5:00000001": the application completed without reading the entire request body.
info: Grpc.AspNetCore.Server.ServerCallHandler[14]
      Error reading message.
System.IO.IOException: The request stream was aborted.
 ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)
```
Reporting this as I'm not sure if there is an error or not

**Comment by v-anvari** [comment]
Hi @phillipharding , We would like to know the impact , are you able to terminate the process after all these errors.

**Comment by phillipharding** [comment]
Yes, all works as it should, the process terminates ➜ just with the error message displayed.

I can start the process again without a problem, only reporting it as I've never seen this behaviour before and didn't know if it was an error or not 🙂

**Comment by v-anvari** [comment]
Thank you for reporting the error. This could be an intermittent failure as well. We would try to reproduce this issue from our end as well.

**Comment by davidbutler-rldatix** [comment]
@phillipharding - I've got a very similar issue showing up in the Console when debugging.. The `System.IO.IOException` message is the same, but my statck trace is different - not sure if this is due to differences in Tools or Runtime, or Function SDK version. It consistently happens for me whenever I `Ctrl-C` in the debug console, or stop debugging in VS. What I've also noticed, is that  this began occurring for me consistently only after integrating `Serilog` into my function app project. Do you happen to be using `Serilog` as well?

@v-anvari It's unclear I'm facing the same issues as @phillipharding , or a different one. So, I thought I'd chime in with my own observations, in case it leads to a resolution for us both.

**My tools versions:**
``` console
Azure Functions Core Tools
Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0
```
* Visual Studio 16.11.7
* .NET 5 Azure Functions Isolated Process project with the following packages

**Package References**
``` xnl
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.0.0-beta.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.0.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
```

**Console after debugging is stopped:**
``` console
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 34154.5865ms 200 application/grpc
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HMDNAEOK6KG8", Request id "0HMDNAEOK6KG8:00000001": the application completed without reading the entire request body.
info: Grpc.AspNetCore.Server.ServerCallHandler[14]
      Error reading message.
System.IO.IOException: The request stream was aborted.
 ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ReadInputAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)

C:\Program Files\dotnet\dotnet.exe (process 34868) exited with code 0.
Press any key to close this window . . .
```
This `Program.cs` will reproduce the error above in the console every time debugging is stopped.

**Program.cs**
``` csharp
using System;
using Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions;
using Microsoft.Extensions.Hosting;
using Serilog;

namespace MedAvail.Station7.Azure.Functions.Rde
{
    public class Program
    {
        public static int Main()
        {
            //// create a logger that will be used to log startup events
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .WriteTo.Debug()
                .CreateBootstrapLogger();

            try
            {
                Log.Information("Getting the motors running...");

                var host = new HostBuilder()
                    .ConfigureFunctionsWorkerDefaults(worker => worker.UseNewtonsoftJson())
                    .ConfigureOpenApi()
                    .UseSerilog((context, loggerConfiguration) => loggerConfiguration
                        .Enrich.FromLogContext()
                        .WriteTo.Console()
                        .WriteTo.Debug())
                    .Build(); 

                host.Run();
                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
    }
}
```

Again, my stacktrace is different, but my issue is too similar, based on the available informration IMHO, to discount the possibility that it is somehow related to what @phillipharding reported.

**Comment by phillipharding** [comment]
For information, I'm using the v3 NodeJs runtime on Node v12 LTS with a mix of HTTP and Queue triggered functions

**Comment by sonic1981** [comment]
Can confirm I'm getting the same error. I also suspect that something isn't getting cleaned up correctly as I have a couple of instances where upon re-starting the program freezes and the only solution appears to be to re-start VS

**Comment by gvanriper** [comment]
This is also affecting me trying to create an HTTP trigger in Node. 

Node: 14.18.3
Azure Functions: 3.0.0

The only resolution I've been able to do is to restart Visual Code.

**Comment by prav33n** [comment]
I am getting a similar error making local development impossible
Node: 16
Azure Functions: 4.0.0

Not able to start azure functions even after a restart.

`Debugger listening on ws://127.0.0.1:9229/e28be91d-5f73-47f1-980f-e831fc53f985
[2022-01-26T18:06:16.252Z] For help, see: https://nodejs.org/en/docs/inspector
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://127.0.0.1:51024/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
[2022-01-26T18:06:16.376Z] Worker process started and initialized.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST http://127.0.0.1:51024/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc - - 200 - application/grpc 1672.1418ms
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HMF0UQ20P6O9", Request id "0HMF0UQ20P6O9:00000001": the application completed without reading the entire request body.
info: Grpc.AspNetCore.Server.ServerCallHandler[14]
      Error reading message.
      System.IO.IOException: The request stream was aborted.
       ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)`

**Comment by tsaeki-7bk** [comment]
I get the same error. I set `FUNCTIONS_V2_COMPATIBILITY_MODE` to `false` and I can start azure functions in local. I hope it helps.

Node: 14.16.1
Azure Functions:  3.3.1.0

**Comment by prav33n** [comment]
> I get the same error. I set `FUNCTIONS_V2_COMPATIBILITY_MODE` to `false` and I can start azure functions in local. I hope it helps.
> 
> Node: 14.16.1 Azure Functions: 3.3.1.0

Thank you, turns out there was a secret key missing in out keyvault which caused connection to cosmoDB fail, the error was not clear in azure functions core 4 , downgraded to version 2 and got the error message highlighting the root cause.

**Comment by wizsilex** [comment]
Im getting this in Macbook pro m1 osx 12.2.1,
vscode 1.64.2, node 16.13.2, func 4.0.3971.
VScode keeps saving files while im writing my code, and restarting host with half written lines and ending in error.
i don't have any auto save on, and there is not autosave when func host start is not running

[2022-02-21T13:05:03.746Z] Debugger listening on ws://127.0.0.1:9230/61a6155f-1f0c-4a2b-8368-e95d77660e90
[2022-02-21T13:05:03.747Z] For help, see: https://nodejs.org/en/docs/inspector
[2022-02-21T13:05:03.865Z] Debugger attached.
[2022-02-21T13:05:03.953Z] Host restarted.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://127.0.0.1:50912/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
[2022-02-21T13:05:04.001Z] Worker process started and initialized.
[2022-02-21T13:05:08.620Z] Host lock lease acquired by instance ID '0000000000000000000000003AC2E11C'.
[2022-02-21T13:06:00.406Z] Restarting host.
[2022-02-21T13:06:00.408Z] Stopping JobHost
[2022-02-21T13:06:00.408Z] Job host stopped
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
[2022-02-21T13:06:00.417Z] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '67f8ccee-6d75-40e7-af30-bc00fc736171'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST http://127.0.0.1:50912/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc - - 200 - application/grpc 56422.9072ms
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HMFL6ECU7DSP", Request id "0HMFL6ECU7DSP:00000001": the application completed without reading the entire request body.
info: Grpc.AspNetCore.Server.ServerCallHandler[14]
      Error reading message.
      System.IO.IOException: The request stream was aborted.
       ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)

**Comment by randomaxess** [comment]
I'm getting a similar issue with azure node functions:

'''
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST http://127.0.0.1:58834/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc - - 200 - application/grpc 15251.5608ms
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HMFLSCOQN7KV", Request id "0HMFLSCOQN7KV:00000001": the application completed without reading the entire request body.
info: Grpc.AspNetCore.Server.ServerCallHandler[14]
      Error reading message.
      System.IO.IOException: The request stream was aborted.
       ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
       ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host.
       ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|5_0(SocketError e)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult(Int16 token)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ReadInputAsync()
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
         --- End of inner exception stack trace ---
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)
'''

**Comment by wup-one** [comment]
FWIW I've been seeing this error recently when debugging my Azure Function written in node.

I noticed I only see the error when I had the following node script setup:

```
  "scripts": {
    "watch": "tsc -w",
    "dev": "concurrently --kill-others \"npm run watch\" \"func start\"",
```

running `npm run dev` here would result in the error. however, I updated the scripts to

```
  "scripts": {
    "watch": "tsc -w",
    "start": "func start",
    "dev": "concurrently --kill-others \"npm run watch\" \"npm run start\"",
```


running `npm run dev` no longer produces these errors. Somehow indirectly running `func start` through it's node command prevents the issue. I have no idea why, but figured I'd share my findings.
