### ISSUE TITLE
SSL Certificate Error in Linux Docker container

### ISSUE THREAD

**Issue by DrEight** [Azure/azure-functions-host#7912]
I'm using Azure function V4 in isolated mode inside a Linux Container.
The host machine is running Azurite configured in https. 
When the container tries to connect to the host I get: 

_Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostExceptionHandler[0]
      An unhandled exception has occurred. Host is shutting down.
      Microsoft.Azure.Storage.StorageException: The SSL connection could not be established, see inner exception.
       ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)_

My in my AzureWebJobsStorage I'm using 'host.docker.internal' instead of '127.0.0.1' to allow the container to connect to the external local host. This is the connection string: __"DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=https://host.docker.internal:10001/devstoreaccount1"_

I've tried to register 2 self created certificates with the names: 127.0.0.1.pem and host.docker.internal.pem in /etc/ssl/certs inside the docker container.

I understand that the runtime is searching for a certificate that I'm not providing, but I don't know which it is. 

Do you have any suggestions ?

**Comment by v-bbalaiagar** [comment]
Transferring this issue to docker repo for further investigation.
