### ISSUE TITLE
Unable to find a constructor to use for type Azure.Messaging.EventGrid.EventGridEvent

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-functions-host#7957]
I'm sending vanilla EventGridEvent objects to a function hook. 

Local is Azure.Messaging.EventGrid 4.7.0
.Net Core 3.1
Azure Function Runtime Version ~3

When I publish an event I get an exception on my log stream (below)

The interesting thing is that I only get this error on Event Grid Subscriptions I created today. The ones I created a few weeks/months ago are still working fine.

Error Message:

2021-12-07T07:14:34.974 [Information] Executing 'ITwoCXCompanyDownloadFunction' (Reason='EventGrid trigger fired at 2021-12-07T07:11:43.1491115+00:00', Id=640eb985-5ee8-441c-9fd1-51e76ca4486e)
2021-12-07T07:14:34.976 [Error] Executed 'ITwoCXCompanyDownloadFunction' (Failed, Id=640eb985-5ee8-441c-9fd1-51e76ca4486e, Duration=171827ms)Unable to find a constructor to use for type Azure.Messaging.EventGrid.EventGridEvent. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path '[0].id', line 1, position 7.

Stack Trace:

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Microsoft.Azure.WebJobs.Extensions.EventGrid.EventGridExtensionConfigProvider.JTokenToPocoConverter`1.Convert(JToken input)
   at Microsoft.Azure.WebJobs.Host.Bindings.PatternMatcher.Invoker`2.<>c__DisplayClass0_0.<Execute>b__0(Object input, Attribute attr, ValueBindingContext ctx) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\PatternMatcher.cs:line 365

#### Investigative information

Host Status: {"id": "xxxxx","state": "Running","version": "3.3.1.0","versionDetails": "3.3.1 Commit hash: bd2b318013cee8d608c88203ec4ee3516d2a9961","platformVersion": "96.0.7.599","instanceId": "137d58aaf0b82d41f44bfc95b44be87edda3d17005e447f5c157dd44b10bb63f","computerName": "10-30-3-211","processUptime": 440299}

**Comment by v-bbalaiagar** [comment]
Hi @RDavis3000, Thank you for your feedback! If you want to use the latest and greatest types, you have to be on the latest version of the extension as well.
Here is the latest version of the event grid extension - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/

Please check and let us know if you are able to solve the issue with this information.

**Comment by RDavis3000** [comment]
> Hi @RDavis3000, Thank you for your feedback! If you want to use the latest and greatest types, you have to be on the latest version of the extension as well. Here is the latest version of the event grid extension - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/
> 
> Please check and let us know if you are able to solve the issue with this information.

Yep that fixed it, thanks

**Comment by v-bbalaiagar** [comment]
Closing this issue as resolved, please feel free to reach back to us in case of any further queries related to this issue.
