### ISSUE TITLE
Setting up Non-C# language worker on Azure Functions Host Running locally

### ISSUE THREAD

**Issue by VinnyBonner** [Azure/azure-functions-host#8124]
#### Is your question related to a specific version? If so, please specify:
Dev branch

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
All beside C#

#### Background:
I am trying to get the Functions Host, which is running locally, to run local functions that are in languages other than C#. I am running into issues when I try to set it up to run other languages besides C# (Currently testing Node)

#### Questions:
How can I properly setup a language worker that is not C#?
How can I properly setup a Linux worker running to utilize OSS languages?

#### Current Settings:
I have been following along here: https://github.com/Azure/azure-functions-host/wiki/Contributor-Onboarding
I know it was a bit outdated. I even created a tutorial based on that doc to get the function host running here: https://github.com/VinnyBonner/LocalAzureFunctionsHostTutorial

##### WebHost appsettings.json
![image](https://user-images.githubusercontent.com/92878154/153078327-4276fa98-078f-4171-ad1f-09b8e395f5de.png)

##### Env Variables
![image](https://user-images.githubusercontent.com/92878154/153078406-436be681-cc65-4f17-a74b-8bf4dd4987c5.png)

##### Node function host.json
![image](https://user-images.githubusercontent.com/92878154/153078174-bd61b73d-4af2-43f9-a345-f28664636b90.png)

##### Exception:
Full exception from host when triggering a TimerTrigger function:
` Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.TimerTrigger
       ---> System.InvalidOperationException: Did not find any initialized language workers
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels) in C:\Users\v-vibonner\source\azure-functions-host-dev\azure-functions-host-dev\src\WebJobs.Script\Workers\Rpc\FunctionRegistration\RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in C:\Users\v-vibonner\source\azure-functions-host-dev\azure-functions-host-dev\src\WebJobs.Script\Workers\Rpc\FunctionRegistration\RpcFunctionInvocationDispatcher.cs:line 388
         at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in C:\Users\v-vibonner\source\azure-functions-host-dev\azure-functions-host-dev\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs:line 95
         at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in C:\Users\v-vibonner\source\azure-functions-host-dev\azure-functions-host-dev\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 82
         at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments)
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 596
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 542
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 320
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 367
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108`
         
Hoping to continue on with the walkthrough and add in oss languages. 

Thanks for the support!

**Comment by v-bbalaiagar** [comment]
Hi @VinnyBonner , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @VinnyBonner , Similar scenarios were fixed/ tracked earlier as mentioned here - https://github.com/Azure/azure-functions-dotnet-worker/issues/556
Please check and let us know if this helps.

**Comment by VinnyBonner** [comment]
Hi @v-bbalaiagar, I appreciate the follow up. I will review the supplied link when I have a chance and see what I can find and follow up.
