### ISSUE TITLE
SSL connection error after upgrading to v4

### ISSUE THREAD

**Issue by littlesvensson** [Azure/azure-functions-host#8168]
We upgraded to Azure function runtime version 4 (as we wanted to move to node16). However, we were not able to execute the function because of the following runtime error: System.Net.Http: The SSL connection could not be established, see inner exception. System.Net.Security: Received an unexpected EOF or 0 bytes from the transport stream.

- Region: West Europe

#### Expected behavior

Our AZ functions should work&run normally as before

#### Actual behavior

Function not executed, the following runtime error appearing:

System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception. 
 System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.
    at async System.Net.Security.SslStream.g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter,Boolean receiveFirst,Byte[] reAuthenticationData,Boolean isApm)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions,HttpRequestMessage request,Boolean async,Stream stream,CancellationToken cancellationToken)    End of inner exception
    at async System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions,HttpRequestMessage request,Boolean async,Stream stream,CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request,Boolean async,CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request,Boolean async,CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync[T](??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request,Boolean async,CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request,Boolean async,Boolean doRequestAuth,CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request,Boolean async,CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.HttpClient.g__Core|83_0(??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetLatestMatchingBundleVersionAsync(??) at /src/azure-functions-host/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 230
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetLatestMatchingBundleVersionAsync(??) at /src/azure-functions-host/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 221
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetExtensionBundleDetails() at /src/azure-functions-host/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs : 47
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() at /src/azure-functions-host/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 91
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__10_0() at /src/azure-functions-host/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 53
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)
    at System.Lazy`1.CreateValue()
    at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() at /src/azure-functions-host/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 68
    at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalConfigurationStartup(IWebJobsConfigurationBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator,WebJobsBuilderContext context,ILoggerFactory loggerFactory) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 362
    at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_3.b__8(IWebJobsStartupTypeLocator locator) at /src/azure-functions-host/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 229
    at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass6_0.b__2(HostBuilderContext context,IConfigurationBuilder configBuilder) at /src/azure-functions-host/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 129
    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
    at Microsoft.Extensions.Hosting.HostBuilder.Build()
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(Boolean skipHostStartup,Boolean skipHostConfigurationParsing) at /src/azure-functions-host/src/WebJobs.Script.WebHost/DefaultScriptHostBuilder.cs : 59
    at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 302

#### Known workarounds

Did not found any :(

#### Related information 

Provide any related information 

* node.js (16)

* function.json:
* {
  "bindings": [
    {
      "name": "incomingBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "<***path***>",
      "connection": "<***connection***>"
    },
    {
      "type": "eventHub",
      "direction": "out",
      "name": "outputEventHubMessages",
      "eventHubName": "<***eventhubname***>",
      "connection": "<***connection***>"
    }
  ],
  "scriptFile": "../main.js"
}

Function App is deployed as a docker image, using the node base 16 & azfunc_node_base:4-node16-slim image.

host.json is configured (extensionBundle adjusted according to the following github issue https://github.com/Azure/azure-functions-host/issues/8119 to avoid the extensionBundle error) this way : 

{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      },
      "enableLiveMetrics": true,
      "enableDependencyTracking": true,
      "enablePerformanceCountersCollection": true
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  }
}
* TLS set in TLS settings for 1.2

**Comment by AleksandarCetojevic** [comment]
In our case the problem was that the new version 4 of the Azure runtime makes a request to functionscdn.azureedge.net:443, which was not the case in prior versions. By allowing the function to make outbound calls over the firewall to this host the functions work again.

**Comment by littlesvensson** [comment]
Yes, it was in the end the firewall issue. Thanks a lot for your input
