### ISSUE TITLE
Host throws for .NET Isolated app if no payload deployed

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#8311]
If no actual payload has been deployed to an app set up for the .NET isolated worker, the host will throw an error. This should not be considered an error state.

#### Repro steps

1. Create a .NET 6 app, functions v4
2. Update the `FUNCTIONS_WORKER_RUNTIME` application setting to "dotnet-isolated"

![image](https://user-images.githubusercontent.com/4621560/173710127-7265a186-afc9-4af3-81ee-525ddfd81e36.png)

#### Expected behavior

The host should not throw and just sit in a waiting state. Logging a warning that the worker was not started would make sense.

#### Actual behavior

The host throws an error: "WorkerConfig for runtime: dotnet-isolated not found".

Trace from the logs:

```
A host error has occurred during startup operation '511f3b9e-017a-4f88-9d6a-7714019a9284'.
System.InvalidOperationException : WorkerConfig for runtime: dotnet-isolated not found
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeAsync(IEnumerable`1 functions,CancellationToken cancellationToken) at /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 236
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at /_/src/WebJobs.Script/Host/ScriptHost.cs : 328
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at /_/src/WebJobs.Script/Host/ScriptHost.cs : 265
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 309
```

#### Known workarounds

Deploy a payload, and the error goes away.

**Comment by ecoonradt** [comment]
Hello, I have been fighting with this issue for a couple days now and was wondering if there are any updates to share.  If this is expected behavior then can you please share how one is supposed to use Bicep / ARM to create .NET 6 isolated function apps?  On the surface this appears to be a chicken and egg problem because function code cannot be deployed via Bicep and the function app must be able to be deployed without error in order for a subsequent CI step to deploy the code for the first time.

**Comment by cloudmelon** [comment]
![image](https://user-images.githubusercontent.com/4621560/184699771-351cb17e-92b0-40b1-9dc6-a3366a17d2d7.png)

@kshyju would you have a look ? thanks

**Comment by cloudmelon** [comment]
for .NET 6 isolated. 

![image](https://user-images.githubusercontent.com/4621560/184700056-d6c7c366-510a-4429-916d-a8386e7a504c.png)
