### ISSUE TITLE
[Python] Protobuf Release 4.21.0 made breaking changes ("TypeError: Descriptors cannot not be created directly.")

### ISSUE THREAD

**Issue by istarbuxs** [Azure/azure-functions-host#8419]
#### Investigative information

Traceback (most recent call last):
```python
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/main.py", line 50, in main
    args.host, args.port, args.worker_id, args.request_id))
File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/main.py", line 57, in start_async
    from . import dispatcher
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 22, in <module>
    from . import bindings 
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/bindings/__init__.py", line 6, in <module>
    from .meta import check_input_type_annotation
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/bindings/meta.py", line 6, in <module>
    from .. import protos
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/protos/__init__.py", line 1, in <module>
    from .FunctionRpc_pb2_grpc import (  # NoQA
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/protos/FunctionRpc_pb2_grpc.py", line 5, in <module>
    from azure_functions_worker.protos import FunctionRpc_pb2 as FunctionRpc__pb2
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/protos/FunctionRpc_pb2.py", line 16, in <module>
    from azure_functions_worker.protos.identity import ClaimsIdentityRpc_pb2 as identity_dot_ClaimsIdentityRpc__pb2
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/protos/identity/ClaimsIdentityRpc_pb2.py", line 14, in <module>
    from azure_functions_worker.protos.shared import NullableTypes_pb2 as shared_dot_NullableTypes__pb2
File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/protos/shared/NullableTypes_pb2.py", line 44, in <module>
    serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
File "/home/site/wwwroot/.python_packages/lib/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    TypeError: Descriptors cannot not be created directly.
```

If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

#### Repro steps

Provide the steps required to reproduce the problem:

Redeploy function app

#### Expected behavior

Functions should work correctly

#### Actual behavior

Function host is currently stopped

#### Known workarounds

downgrade protobuf to a lower version based on the error message

#### Related information 

* Programming language used
- Python

* Links
- https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
- https://github.com/protocolbuffers/protobuf/issues/10051

**Comment by jmccomb** [comment]
Worth highlighting this leaves functions host dead in the water.
Description above is excellent but for those unsure of how to implement workaround (like me) the comment from @mike-luabase may be helpful:
Try adding
`protobuf==3.20.1`
to your requirements.txt, if that fixes it, don't set env var PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

**Comment by Ved2806** [comment]
Hi @vrdmr Could you please take a look?

**Comment by brettsam** [comment]
Looks like this is being tracked in the python worker repo here: https://github.com/Azure/azure-functions-python-worker/issues/1050.
