### ISSUE TITLE
Memory Leak When Failing to Watch Files

### ISSUE THREAD

**Issue by wsugarman** [Azure/azure-functions-host#8445]
#### Check for a solution in the Azure portal
N/A

#### Investigative information
We host our Azure Functions on our own AKS cluster using the official docker base image `mcr.microsoft.com/azure-functions/dotnet`, so you won't be able to check your internal logs/metrics.

#### Repro steps
- Docker Image: `mcr.microsoft.com/azure-functions/dotnet:4.5.2-slim@sha256:bf9cdcf20af9a8807583a3039857050510e744c4c79e162c5413052e1b734733`
  - Presumably this is version [4.5.2](https://github.com/Azure/azure-functions-host/releases/tag/v4.5.2) of the host

Start up the function container while failing to initialize the `AutoRecoveringFileSystemWatcher`. We were running the container as the user from the base image which appeared to be `root`. Memory usage should continue to grow over time.

#### Expected behavior

While the host shouldn't start-up, I expect the host to continually fail without continuing to grow its memory usage.

#### Actual behavior

We began hosting our Azure Function AKS pods on hosts whose `inotify` limit was much smaller, and as a result a number of our pods began to fail, including the Azure Functions pods. While we fixed this issue (running `nonroot`, disabling file watching via `AzureFunctionsJobHost__FileWatchingEnabled`, and switching hosts), this did seem to expose a curious behavior in the Azure Functions Host. Unsurprisingly, we did see function pods fail with the following error:

> A host error has occurred during startup operation '{operationId}'.
> System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
>   at System.IO.FileSystemWatcher.StartRaisingEvents()
>   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
>   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
>   at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher.InitializeWatcher() in /src/azure-functions-host/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs:line 64
>   at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher..ctor(String path, String filter, Boolean includeSubdirectories, WatcherChangeTypes changeTypes, ILoggerFactory loggerFactory) in /src/azure-functions-host/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs:line 43
>   at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.InitializeSecondaryFileWatchers() in /src/azure-functions-host/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 197
>   at Microsoft.Azure.WebJobs.Script.Utility.ExecuteAfterColdStartDelay(IEnvironment environment, Action targetAction, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Utility.cs:line 761
>   at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.InitializeFileWatchers() in /src/azure-functions-host/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 172
>   at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.StartAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 93
>   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
>   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 310

However, these pods would attempt to restart until they were actually killed by Kubernetes because they exceeded their memory limit. We set the memory limit to 2 GB, so it was surprising to hear that the pods were killed due to memory! I am speculating that the host is refusing to free some memory when failing to start up, perhaps in this code path specifically.

#### Known workarounds

Set `FileWatchingEnabled` to `false` either in the host config or via the environment variable `AzureFunctionsJobHost__FileWatchingEnabled`.

#### Related information 

- Docker Image: `mcr.microsoft.com/azure-functions/dotnet:4.5.2-slim@sha256:bf9cdcf20af9a8807583a3039857050510e744c4c79e162c5413052e1b734733`

**Comment by kshyju** [comment]
@wsugarman Checking on this. Are you still encountering this issue with the latest images?
