### ISSUE TITLE
Provide a way to disable FileSystemWatcher to make docker images work on Apple M1

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-functions-host#8666]
#### What problem would the feature you're requesting solve? Please describe.

Linux Amd64 images running on Apple M1 (ARM64) do not support file system watching due to limitations of the emulator.

This makes it impossible to run any function apps on M1 right now, and I literally have to find Intel based Mac for this.

* `mcr.microsoft.com/azure-functions` docker images only have AMD64 images, no ARM64 (see screenshot below)
* There does not seem to be a way to disable file system watcher. Looking at the code it's always enabled except if we run from package and actually configure everything for it correctly.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/300031/186706818-a198a82d-55bd-497f-b907-3c81a0a7c7c1.png">

Here is my Docker file:

```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS installer-env

COPY . /src/dotnet-function-app

RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish "MyFunction.csproj" --output /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4.0-dotnet-isolated6.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    FUNCTIONS_WORKER_RUNTIME=dotnet-isolated

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
```

And here is the crash:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

fail: Host.Startup[515]
      A host error has occurred during startup operation 'da4bd788-8ccc-46e0-8fe6-d263c1c97ed8'.
      System.IO.IOException: Function not implemented
         at System.IO.FileSystemWatcher.StartRaisingEvents()
         at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
         at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
         at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher.InitializeWatcher() in /src/azure-functions-host/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs:line 64
         at Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher..ctor(String path, String filter, Boolean includeSubdirectories, WatcherChangeTypes changeTypes, ILoggerFactory loggerFactory) in /src/azure-functions-host/src/WebJobs.Script/IO/AutoRecoveringFileSystemWatcher.cs:line 43
         at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.InitializeSecondaryFileWatchers() in /src/azure-functions-host/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 192
         at Microsoft.Azure.WebJobs.Script.Utility.ExecuteAfterColdStartDelay(IEnvironment environment, Action targetAction, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Utility.cs:line 749
         at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.InitializeFileWatchers() in /src/azure-functions-host/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 172
         at Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService.StartAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/FileMonitoringService.cs:line 93
         at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 309


info: Host.Startup[0]
      Job host stopped
```

#### Describe the solution you'd like

1. Provide a way to disable file watcher completely via `host.json` and env variable.
2. Proide images for ARM64, e.g either using separate tags or by having a multi-arch images.

#### Describe alternatives you've considered

* The only alternative I see is to buy and Intel based machine, and Apple of course no longer make those :)

**Comment by brandonros** [comment]
We're supposed to be able to disable `hostBuilder:reloadConfigOnChange` via `appsettings.json` or `-e DOTNET_hostBuilder:reloadConfigOnChange=false` but neither have worked for me.

What is very strange is... I am working on a Java function app and it ends up using .NET in the background (that's fine, that's specific to Azure function apps I'm sure)

I just don't get why despite `FROM --platform=linux/amd64 mcr.microsoft.com/azure-functions/java:4-java17-build AS installer-env` being in my Dockerfile and `docker run --platform=linux/amd64`, anything arm64/M1 related is taking place/getting in the way?

**Comment by brandonros** [comment]
https://github.com/Azure/azure-functions-host/issues/2976

Does this fix your issue?

**Comment by brandonros** [comment]
Adding `"fileWatchingEnabled": false` to host.json doens't fix my problem. 

`-e AzureFunctionsJobHost__FileWatchingEnabled=false` doesn't fix the problem.

**Comment by ppanyukov** [comment]
Yes, I tried https://github.com/Azure/azure-functions-host/issues/2976. I tried lots of things. :) 

And nope, nothing worked. And looking at the code, there is no way to set this. Maybe I'm looking in the wrong place.

**Comment by brandonros** [comment]
Do we know why despite the Docker container running as `amd64` (not `arm64`), something somewhere inside these Azure function host specific Docker images is "detecting" `arm64` (which results in the file system watcher not implemented bugs?)

**Comment by ppanyukov** [comment]
My understanding is you can run `amd64` images on `arm64`, and this is achieved using `qemu` in Docker desktop. One  limitation of that is specifically `inotify` (which is behind file change notifications) is not present:

> However, attempts to run Intel-based containers on Apple silicon machines under emulation can crash as qemu sometimes fails to run the container. In addition, filesystem change notification APIs (inotify) do not work under qemu emulation.

When something eventually calls `inotify` it returns "not implemented" which in turn causes this exception.

See: https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

Additionally, the presence of functioning `inotify` is an optional feature, just because it was merged into Linux kernel long time ago it shouldn't be assumed to be present in any scenarios.

And, additionally, when we run things in AKS, do we really care for this file watching? Not really. So why waste resource?

**Comment by brandonros** [comment]
I agree with you 100% that this should be configurable. The fact that it doesn't/isn't kind of shows nobody is using this on Apple M1 lol

Do you know if it is possible to run Intel flavor Docker Desktop on Apple Mac ARM? With whatever combination of Rosetta, etc.

It's kind of silly because, if we spent the time to run a Linux distro in QEMU, I don't think we'd run into the same "inotify not implemented". I could be wrong though.

**Comment by violetbrina** [comment]
+1 Just ran into this issue doing local development and testing of a python based azure function docker image. At least I'll stop trying to debug the local run now 😅

**Comment by npalmius** [comment]
Personally, I think there is a broader reason to want to disable file watching. In production, there should be no changes to the underlying function code post-deployment (this is obviously dependent on setup, but if the function app is built in CI then I don't see why you would expect changes post-deployment in production). If there are, that's probably malicious, so restarting is actually a security risk because it's enabling the change to be picked up.

In our case, we started looking into this because our python function app was restarting when the `__pycache__` directories were auto-generated for our functions (this doesn't need a restart anyway). In the end we have worked around it by pre-compiling the code in CI, but still would be nice to have the ability to just disable file watching.

**Comment by HillaShx** [comment]
I ran into the same issue. The exact same container is running smoothly on my amd64 intel-cpu Mac, and is giving the `System.IO.IOException: Function not implemented` error on my arm64 M1 Mac.

**Comment by MikeyT111** [comment]
Has anyone managed to resolve this issue yet? 
I’ve found that if I set `AzureFunctionsJobHost__Logging__Console__IsEnabled=false` in the docker file. It gets further and I can access the container from a browser, but i then get the error message `Function host is not running.` when I try accessing the webpage.

**Comment by mohamed-magdy-issa** [comment]
In case anyone encounters the same issue, I was able to solve this by adding this env var to the container `DOTNET_USE_POLLING_FILE_WATCHER=1`.

Disclaimers:
- This fix was suggested to me by ChatGPT
- ChatGPT claims that it's the same but less efficient
> By setting DOTNET_USE_POLLING_FILE_WATCHER to 1, you are instructing the .NET runtime to use the polling file watcher mechanism, which is less efficient but should work on platforms where inotify is not available.
- I don't write .net code, and the code was not mine, I was just deploying it and it passed e2e tests, so I'm not sure what other implications could this have.
