### ISSUE TITLE
Null Pointer Exception during custom scale out operation

### ISSUE THREAD

**Issue by prashantguleria** [Azure/azure-functions-host#8945]
#### Is your question related to a specific version? If so, please specify:
Java 1.8 with extension version ~4
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Java
#### Question

Hi,

We have a functions app with multiple queue triggeres configured. All the functions are working fine until we have auto-scaling turned on.

When a custom auto-scaling rule is triggered few of our queue messages are sent to poison queue without showing any proper error or stack trace. (Auto scaling rule is kept on CPU metric load, When avg load for 5 mins > 80 increase count by 1 and when avg load < 30 decrease count by 1)

Min instances = 1 , Max Instances = 3

Result: Failure
Exception: NullPointerException: 
Stack: java.lang.NullPointerException
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:80)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:37)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:12)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

I have analyzed this behaviour multiple times. I have observed that when a new instance is scaled up 3rd time this behaviour occurs.

**Comment by ramya894** [comment]
@prashantguleria Please provide us the function app name with time stamp and invocation ID details so that we can for the system logs and update you more insights.

**Comment by prashantguleria** [comment]
Hi @ramya894,
I tried to debug the error and created warmup trigger too which also throws the same exception during scale out. 

Name of the Application : NoesisInternalExtractor
Operation ID of Warmup trigger : exceptions
| where operation_Id contains "e661801c2c38ac2ae5c303bf5c582e46"

![image](https://user-images.githubusercontent.com/10485563/206336592-788d5e96-96b3-4088-a3f3-0c5083895de4.png)

**Comment by prashantguleria** [comment]
@ramya894 Any updates? This stops us from going live on production.

**Comment by bhagyshricompany** [comment]
@prashantguleria   Ramya went on long leave, and I will be looking into it. I'll provide an update as soon as possible

**Comment by prashantguleria** [comment]
Hi,

I have resolved this issue.
 There was a bug in major version of Azure function core tools .
 So I have pinned the version to 4.13 to overcome this issue.
