### ISSUE TITLE
Exception while executing function: <FunctionName> Did not find any initialized language workers

### ISSUE THREAD

**Issue by JesperNJessen** [Azure/azure-functions-host#9086]
### Function App information

- Timestamp: 2/9/2023, 1:13:16.2764438 PM (Local time)
- Function App version: 4.15.1.19904
- Function name(s) (as appropriate): Test
- Region: North Europe

### Invocation details from log

```
2023-02-09T12:53:46Z   [Verbose]   Request successfully matched the route with name 'Test' and template 'api/Test'
2023-02-09T12:53:46Z   [Information]   Executing 'Functions.Test' (Reason='This function was programmatically called via the host APIs.', Id=a5dad850-3053-4780-9013-44e70de94d40)
2023-02-09T12:53:46Z   [Verbose]   FunctionDispatcher state: Initializing
2023-02-09T12:53:56Z   [Verbose]   Initiating background SyncTriggers operation
2023-02-09T12:54:26Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1339
--- End of stack trace from previous location ---
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 271
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 154
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 146
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(IEnumerable`1 languages) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 137
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass56_0.<<StartWorkerProcesses>b__0>d.MoveNext() in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 229
2023-02-09T12:54:26Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: 'ddb1cf22-a46b-4d58-b636-55e4e8740bce', runtime: 'dotnet-isolated'
2023-02-09T12:54:26Z   [Verbose]   Disposing language worker channel with id:ddb1cf22-a46b-4d58-b636-55e4e8740bce
2023-02-09T12:54:26Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-02-09T12:54:26Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-02-09T12:54:26Z   [Error]   Failed to start a new language worker for runtime: dotnet-isolated.
2023-02-09T12:54:37Z   [Error]   Final functionDispatcher state: WorkerProcessRestarting. Initialization timed out and host is shutting down
2023-02-09T12:54:37Z   [Verbose]   Sending invocation id:a5dad850-3053-4780-9013-44e70de94d40
2023-02-09T12:54:37Z   [Error]   Executed 'Functions.Test' (Failed, Id=a5dad850-3053-4780-9013-44e70de94d40, Duration=50361ms)
2023-02-09T12:54:37Z   [Verbose]   Hosting stopping
2023-02-09T12:54:37Z   [Verbose]   Stopping file watchers.
2023-02-09T12:54:37Z   [Verbose]   Waiting for RpcFunctionInvocationDispatcher to shutdown
2023-02-09T12:54:37Z   [Verbose]   Draining invocations from language worker channel completed. Shutting down 'RpcFunctionInvocationDispatcher'
2023-02-09T12:54:37Z   [Information]   Stopping JobHost
2023-02-09T12:54:37Z   [Verbose]   Stopping ScriptHost instance 'e825dd2f-8bf1-4045-a9cd-f0ba1f597219'.
2023-02-09T12:54:37Z   [Information]   Job host stopped
2023-02-09T12:54:37Z   [Verbose]   Stopped ScriptHost instance 'e825dd2f-8bf1-4045-a9cd-f0ba1f597219'.
2023-02-09T12:54:37Z   [Verbose]   Hosting stopped
2023-02-09T12:54:37Z   [Verbose]   Disposing ScriptHost.
2023-02-09T12:54:37Z   [Verbose]   Disposing ScriptHost instance 'e825dd2f-8bf1-4045-a9cd-f0ba1f597219'.
2023-02-09T12:54:37Z   [Verbose]   Disposing FunctionDispatcher
2023-02-09T12:54:37Z   [Verbose]   Disposing language worker channel with id:5a22706a-a054-4fb7-9f48-9e2ef5c28a59
2023-02-09T12:54:37Z   [Verbose]   Disposed ScriptHost instance 'e825dd2f-8bf1-4045-a9cd-f0ba1f597219'.
2023-02-09T12:54:37Z   [Verbose]   Host instance '02769c8076e8121e085c735a03aac37e' released lock lease.
2023-02-09T12:54:37Z   [Verbose]   Disposing ScriptHost instance 'e825dd2f-8bf1-4045-a9cd-f0ba1f597219'.
2023-02-09T12:54:37Z   [Verbose]   Disposed ScriptHost instance 'e825dd2f-8bf1-4045-a9cd-f0ba1f597219'.
2023-02-09T12:57:54Z   [Verbose]   Initiating background SyncTriggers operation
2023-02-09T12:58:24Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1339
2023-02-09T12:58:24Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: '5ae61821-9185-4016-9b7a-0b1937f32039', runtime: 'dotnet-isolated'
2023-02-09T12:58:24Z   [Verbose]   Disposing language worker channel with id:5ae61821-9185-4016-9b7a-0b1937f32039
2023-02-09T12:58:24Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-02-09T12:58:24Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-02-09T12:58:24Z   [Error]   Failed to start a new language worker for runtime: dotnet-isolated.
2023-02-09T12:59:24Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1339
2023-02-09T12:59:24Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: '15381c84-98a3-44e6-b3a9-ac65ec5e54f8', runtime: 'dotnet-isolated'
2023-02-09T12:59:24Z   [Verbose]   Disposing language worker channel with id:15381c84-98a3-44e6-b3a9-ac65ec5e54f8
2023-02-09T12:59:24Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-02-09T12:59:24Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
```

### Description

Starting this morning, we are experiencing `Did not find any initialized language workers` when executing any function in our .NET 7 isolated function app.

According to [fabiocav](https://github.com/fabiocav)'s [comment](https://github.com/Azure/azure-functions-host/issues/7843#issuecomment-1423280524) on #7843 we should create issues when experiencing this error.

The first symptom was when we tried publishing a new version via our Azure pipeline. The below error persistently stopped the publish flow from completing until we deleted and re-created our Function App (note, this was the old function name which was 34 characters):

```
##[error]Failed to deploy web package to App Service.
##[error]To debug further please check Kudu stack trace URL : https://<function name>.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace
##[error]Error: Error: Failed to deploy web package to App Service. Internal Server Error (CODE: 500)
```

Accessing the stack trace URL revealed the below stack trace:

```
[IOException: The user name or password is incorrect.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +12601718
   System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost) +12404913
   System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost) +88
   System.IO.Directory.CreateDirectory(String path) +34
   System.IO.Abstractions.DirectoryWrapper.CreateDirectory(String path) +10
   Kudu.Core.Infrastructure.FileSystemHelpers.CreateDirectory(String path) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\FileSystemHelpers.cs:32
   Kudu.Core.Infrastructure.FileSystemHelpers.EnsureDirectoryIgnoreAccessExceptions(String path) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\FileSystemHelpers.cs:48
   Kudu.Core.Environment.get_DeploymentsPath() in C:\Kudu Files\Private\src\master\Kudu.Core\Environment.cs:181
   Kudu.Services.Web.App_Start.NinjectServices.GetSettingsPath(IEnvironment environment) in C:\Kudu Files\Private\src\master\Kudu.Services.Web\App_Start\NinjectServices.cs:796
   Kudu.Services.Web.App_Start.NinjectServices.EnsureValidDeploymentXmlSettings(IEnvironment environment) in C:\Kudu Files\Private\src\master\Kudu.Services.Web\App_Start\NinjectServices.cs:0
   Kudu.Services.Web.App_Start.NinjectServices.RegisterServices(IKernel kernel) in C:\Kudu Files\Private\src\master\Kudu.Services.Web\App_Start\NinjectServices.cs:154
   Kudu.Services.Web.App_Start.NinjectServices.CreateKernel() in C:\Kudu Files\Private\src\master\Kudu.Services.Web\App_Start\NinjectServices.cs:131
   Ninject.Web.Common.Bootstrapper.Initialize(Func`1 createKernelCallback) +16
   Kudu.Services.Web.App_Start.NinjectServices.Start() in C:\Kudu Files\Private\src\master\Kudu.Services.Web\App_Start\NinjectServices.cs:97

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +91
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +105
   WebActivatorEx.BaseActivationMethodAttribute.InvokeMethod() +73
   WebActivatorEx.ActivationManager.RunActivationMethods(Boolean designerMode) +637
   WebActivatorEx.ActivationManager.Run() +101

[InvalidOperationException: The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +646
   System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +147
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +107
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +165
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +590

[HttpException (0x80004005): The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10087920
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +99
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +263
```

The stage in the pipeline that failed:

```
  - stage: deploy
    dependsOn: build
    jobs:
      - job: run_publish
        pool:
          vmImage: "windows-latest"
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: "Download project build"
            inputs:
              source: "current"
              artifact: "function-app"
              path: '$(Pipeline.Workspace)\function-app'
          - task: AzureFunctionApp@1
            displayName: "Deploy zip"
            inputs:
              azureSubscription: "$(servicePrincipal)"
              resourceGroupName: "$(targetResourceGroup)"
              appType: "functionapp"
              appName: "$(functionAppName)"
              package: '$(Pipeline.Workspace)\function-app\function-app_$(Build.BuildNumber).zip'
```

After deleting and re-creating our Function App, the deployment was successful, however we then starting getting errors when executing functions.

Full call stack when executing the Test endpoint:

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.36.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:352)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__18.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.36.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:108)
Inner exception System.InvalidOperationException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel (Microsoft.Azure.WebJobs.Script, Version=4.15.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:27)
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher+<InvokeAsync>d__62.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.15.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:466)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker+<InvokeCore>d__9.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.15.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:95)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase+<Invoke>d__24.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.15.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Description/FunctionInvokerBase.cs:82)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator+<Coerce>d__3`1.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.15.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Description/FunctionGenerator.cs:225)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2+<InvokeAsync>d__10.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.36.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:52)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeWithTimeoutAsync>d__33.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.36.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:581)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__32.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.36.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:527)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.36.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:306)
```

### Additional information

- The function list at `https://<function name>.scm.azurewebsites.net/api/functions` appears to be empty.
- The function seems to time out, taking 50-60 seconds to respond with HTTP code 500.

### What we've tried

- Deleting and re-recreating the Function App targeting both .NET 6 and 7.
   - Renaming our Function App to ensure the name is no longer than 30 characters.
- Deleting and re-creating the App Service Plan.
- Synchronously/asynchronously invoking the Host.Run method in Program.cs.

**Comment by torepaulsson** [comment]
This has happened to us as well. We restarted the functino app and it started working again. We see it now happening again sporadically.

This has affected production and I've opened a support case as well, this occured on 2023-02-07
![image](https://user-images.githubusercontent.com/10498076/218118717-29f14378-98bc-42b9-ad43-402c7dbdf7d1.png)

Isolated function .net6, consumption based plan

Please, someone look at this ASAP, it's the weekend and I'm worried.

**Comment by JesperNJessen** [comment]
## Our workaround

In an effort to find the cause of this issue, we created a new .NET 7 isolated function (using the Visual Studio template) and uploaded it to a different subscription.
This worked well and the function was operating properly.
Our next step was to publish our broken project to that same subscription, which resulted in the same errors as before, proving that the problem was to be found somewhere in the project files and not in the Azure Portal.

Following this, I started transferring code to the new project, removing any and all references and dependencies that might not be needed. This eventually lead to us having a working function app in another subscription.
I then published this code via our Azure Devops pipeline to the original Function App/subscription and our app is now working as intended.

## What was removed.

Following this I compared the newly published project with what we had before. These package references were removed:

```
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
<PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.2.3" />
<PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.33" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi.Core" Version="1.5.1" />
<PackageReference Include="Microsoft.OpenApi" Version="1.5.0" />
```

Additionally, we had a reference to `Microsoft.AspNetCore.WebUtilities` which was used to parse query parameters. This was not needed since we were able to use parameter mapping.
I did however observe that using this package resulted in my function returning a `204 - no content` with no other errors logged.


Hope this helps someone.

**Comment by liliankasem** [comment]
Thanks for sharing your findings @JesperNJessen, I'm going to go ahead and resolve this.

In general, the `Did not find any initialized language workers` error is a very vague exception that could occur for a variety of reasons and will vary for every application. If folks encounter this issue, it is recommended to open a support ticket so we can properly investigate each application.
