### ISSUE TITLE
Unable to run Function in a container: System.Text.Json failing on IImmutableDictionary

### ISSUE THREAD

**Issue by jdluzen** [Azure/azure-functions-host#9319]
I am unable to run an out-of-the-box Http Function with dotnet-isolated in a container or debugging WebJobs.Script.WebHost locally.

#### Repro steps

Provide the steps required to reproduce the problem:

Created dotnet-isolated with `func init --docker`, tried .Net 6 and .Net 7.
Add new Http Function.
Publish to linux-x64 or windows-x64.
For Linux, started container and mounted the published files:
docker run \
-e AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
-e AzureWebJobsStorage="my storage string here" \
-e WEBSITE_HOSTNAME=localhost:80 \
-p 81:80 \
-v /root/linux-x64func:/home/site/wwwroot \
mcr.microsoft.com/azure-functions/dotnet-isolated:4.0-dotnet-isolated6.0
For Windows, I was able to set `AzureWebJobsScriptRoot` and debug in Visual Studio WebJobs.Script.WebHost.

#### Expected behavior
Default text in the browser

#### Actual behavior
Crashes with:
```Hosting environment: Production
Content root path: /azure-functions-host
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
info: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Worker process started and initialized.
info: Function.Function[1]
      Executing 'Functions.Function' (Reason='This function was programmatically called via the host APIs.', Id=6c77e96a-7d9c-490a-84e9-78fae22427f3)
fail: Function.Function[3]
      Executed 'Functions.Function' (Failed, Id=6c77e96a-7d9c-490a-84e9-78fae22427f3, Duration=78ms)
      Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.Function
       ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
      Exception: System.NotSupportedException: The type 'System.Collections.Immutable.IImmutableDictionary`2[System.String,Microsoft.Azure.Functions.Worker.BindingMetadata]' is not supported. Path: $.InputBindings.
       ---> System.NotSupportedException: The type 'System.Collections.Immutable.IImmutableDictionary`2[System.String,Microsoft.Azure.Functions.Worker.BindingMetadata]' is not supported.
         at System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(Type )
         at System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableDictionaryCreateRangeMethod(Type , Type , Type )
         at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableDictionaryCreateRangeDelegate(Type , Type , Type , Type )
         at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableDictionaryCreateRangeDelegate[TCollection,TKey,TValue]()
         at System.Text.Json.Serialization.Converters.ImmutableDictionaryOfTKeyTValueConverterWithReflection`3.Initialize(JsonSerializerOptions , JsonTypeInfo )
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type , JsonConverter , Type , JsonSerializerOptions )
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type , JsonSerializerOptions )
         at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo|112_0(Type , JsonSerializerOptions )
         at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type )
         at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type )
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.get_RuntimeTypeInfo()
         at System.Text.Json.WriteStack.Push()
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object , WriteStack& , Utf8JsonWriter )
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter , T , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& , NotSupportedException )
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter , TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.Serialize[TValue](TValue , JsonSerializerOptions )
         at Microsoft.Azure.Functions.Worker.Grpc.GrpcWorkerDiagnostics.OnFunctionLoaded(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Http\GrpcWorkerDiagnostics.cs:line 61
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 65
         at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 233
      Stack:    at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& , NotSupportedException )
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter , TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.Serialize[TValue](TValue , JsonSerializerOptions )
         at Microsoft.Azure.Functions.Worker.Grpc.GrpcWorkerDiagnostics.OnFunctionLoaded(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Http\GrpcWorkerDiagnostics.cs:line 61
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 65
         at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 233
         at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 101
         at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
         at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 581
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 527
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 352
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108
fail: Host.Results[0]
      Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.Function
       ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
      Exception: System.NotSupportedException: The type 'System.Collections.Immutable.IImmutableDictionary`2[System.String,Microsoft.Azure.Functions.Worker.BindingMetadata]' is not supported. Path: $.InputBindings.
       ---> System.NotSupportedException: The type 'System.Collections.Immutable.IImmutableDictionary`2[System.String,Microsoft.Azure.Functions.Worker.BindingMetadata]' is not supported.
         at System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(Type )
         at System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableDictionaryCreateRangeMethod(Type , Type , Type )
         at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableDictionaryCreateRangeDelegate(Type , Type , Type , Type )
         at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableDictionaryCreateRangeDelegate[TCollection,TKey,TValue]()
         at System.Text.Json.Serialization.Converters.ImmutableDictionaryOfTKeyTValueConverterWithReflection`3.Initialize(JsonSerializerOptions , JsonTypeInfo )
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type , JsonConverter , Type , JsonSerializerOptions )
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type , JsonSerializerOptions )
         at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo|112_0(Type , JsonSerializerOptions )
         at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type )
         at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type )
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.get_RuntimeTypeInfo()
         at System.Text.Json.WriteStack.Push()
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object , WriteStack& , Utf8JsonWriter )
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter , T , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& , NotSupportedException )
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter , TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.Serialize[TValue](TValue , JsonSerializerOptions )
         at Microsoft.Azure.Functions.Worker.Grpc.GrpcWorkerDiagnostics.OnFunctionLoaded(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Http\GrpcWorkerDiagnostics.cs:line 61
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 65
         at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 233
      Stack:    at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& , NotSupportedException )
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter , T& , JsonSerializerOptions , WriteStack& )
         at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter , TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& , JsonTypeInfo )
         at System.Text.Json.JsonSerializer.Serialize[TValue](TValue , JsonSerializerOptions )
         at Microsoft.Azure.Functions.Worker.Grpc.GrpcWorkerDiagnostics.OnFunctionLoaded(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Http\GrpcWorkerDiagnostics.cs:line 61
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 65
         at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 233
         at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 101
         at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
         at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 581
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 527
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 352
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108
info: Host.General[337]
      Host lock lease acquired by instance ID '000000000000000000000000EC3485F7'.
```
#### Known workarounds
None

**Comment by kshyju** [comment]
@jdluzen Would you mind sharing the full Docker file you used?

**Comment by jdluzen** [comment]
No custom Dockerfile, only running `mcr.microsoft.com/azure-functions/dotnet-isolated:4.0-dotnet-isolated6.0` with a mounted directory.

**Comment by jdluzen** [comment]
Do you need more information? Would appreciate if the bot were to not close this, but I do not see how to prevent it on my end.

**Comment by kshyju** [comment]
@jdluzen Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.

**Comment by jdluzen** [comment]
Sure thing, should be an out of the box default durable .net7 http project with no changes: https://github.com/jdluzen/FunctionHost9319
Publish linux-x64 self contained, copy/move to e.g. /root/funcHost9319
Run docker:
```
docker run \
-e AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
-e TableStorageConnectionString="my storage string here" \
-e WEBSITE_HOSTNAME=localhost:80 \
-e AzureWebJobsScriptRoot=/home/site/wwwroot \
-p 81:80 \
-v /root/funcHost9319:/home/site/wwwroot \
mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0
```

Then in another console, `wget localhost:81/api/Function1`

**Comment by kshyju** [comment]
Thanks for sharing the function app code. After publishing, I was able to successfully run this app & invoke the http trigger. See logs from the terminal below.

![image](https://github.com/Azure/azure-functions-host/assets/144469/1fa7c91f-203d-40ea-b1a0-5590efe7e662)

Pasting the entire logs as text.

> shkr  ~  ♥ 21:24  docker run -e AzureFunctionsJobHost__Logging__Console__IsEnabled=true -e WEBSITE_HOSTNAME=localhost:80 -e AzureWebJobsScriptRoot=/home/site/wwwroot -p 81:80 -v C:\Temp\app\dkr:/home/site/wwwroot mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0
info: Host.Triggers.Warmup[0]
      Initializing Warmup Extension.
info: Host.Startup[503]
      Initializing Host. OperationId: '9e790f16-fc20-46e3-9053-ded9dc44e613'.
info: Host.Startup[504]
      Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=9e790f16-fc20-46e3-9053-ded9dc44e613
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      LoggerFilterOptions
      {
        "MinLevel": "None",
        "Rules": [
          {
            "ProviderName": null,
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          },
          {
            "ProviderName": null,
            "CategoryName": "Host.Function.ToolingConsoleLog",
            "LogLevel": "Information",
            "Filter": null
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": "None",
            "Filter": null
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          }
        ]
      }
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      ConcurrencyOptions
      {
        "DynamicConcurrencyEnabled": false,
        "MaximumFunctionConcurrency": 500,
        "CPUThreshold": 0.8,
        "SnapshotPersistenceEnabled": true
      }
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      FunctionResultAggregatorOptions
      {
        "BatchSize": 1000,
        "FlushTimeout": "00:00:30",
        "IsEnabled": true
      }
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      SingletonOptions
      {
        "LockPeriod": "00:00:15",
        "ListenerLockPeriod": "00:01:00",
        "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
        "LockAcquisitionPollingInterval": "00:00:05",
        "ListenerLockRecoveryPollingInterval": "00:01:00"
      }
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      ScaleOptions
      {
        "ScaleMetricsMaxAge": "00:02:00",
        "ScaleMetricsSampleInterval": "00:00:10",
        "MetricsPurgeEnabled": true,
        "IsTargetScalingEnabled": true,
        "IsRuntimeScalingEnabled": false
      }
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Starting JobHost
info: Host.Startup[401]
      Starting Host (HostId=4e3db76f2918-2137340777, InstanceId=4fd834fa-0d8c-4807-a18b-517983d8dc6b, Version=4.21.1.1, ProcessId=1, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
info: Host.Startup[314]
      Loading functions metadata
info: Host.Startup[326]
      Reading functions metadata
info: Host.Startup[327]
      2 functions found
info: Host.Startup[315]
      1 functions loaded
info: Host.Startup[0]
      Generating 1 job function(s)
info: Host.Startup[0]
      Found the following functions:
      Host.Functions.Function1

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      HttpOptions
      {
        "DynamicThrottlesEnabled": false,
        "EnableChunkedRequestBinding": false,
        "MaxConcurrentRequests": -1,
        "MaxOutstandingRequests": -1,
        "RoutePrefix": "api"
      }
info: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager[0]
      Initializing function HTTP routes
      Mapped function route 'api/Function1' [get,post] to 'Function1'

info: Host.Startup[412]
      Host initialized (88ms)
info: Host.Startup[413]
      Host started (102ms)
info: Host.Startup[0]
      Job host started
Hosting environment: Production
Content root path: /azure-functions-host
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
info: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Worker process started and initialized.
info: Host.General[337]
      Host lock lease acquired by instance ID '000000000000000000000000D4F7268C'.
info: Function.Function1[1]
      Executing 'Functions.Function1' (Reason='This function was programmatically called via the host APIs.', Id=f12bfb4b-3874-4f7e-bd3d-6e3ab2fbcf77)
info: Function.Function1.User[0]
      C# HTTP trigger function processed a request.
info: Function.Function1[2]
      Executed 'Functions.Function1' (Succeeded, Id=f12bfb4b-3874-4f7e-bd3d-6e3ab2fbcf77, Duration=171ms)


FYI: I ran `dotnet publish -r linux-x64 -c release -o /mnt/c/Temp/app/dkr --self-contained` to publish the app from a debian terminal (debian installation via WSL for windows).

Can you double check your publish output is valid?

**Comment by jdluzen** [comment]
Thank you for checking on this. After installing WSL and publishing supposedly the same configuration in Visual Studio, it works. It's concerning for me that Visual Studio's publish somehow breaks this in unexpected ways. But that is a problem for another time.
