### ISSUE TITLE
NullReferenceException in GetFallbackWorkerConifg

### ISSUE THREAD

**Issue by jjshao-ms** [Azure/azure-functions-host#9481]
Message: Object reference not set to an instance of an object.
Exception type: System.NullReferenceException
Failed method: Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.GetFallbackWorkerConfig

This problem appears only after we migrate to isolated dotnet worker. And it happens a lot (4.5k exceptions in one day). Seems doesn't impact our functionality(?), but I still would like to point it out.

Callstack:
```
System.NullReferenceException:
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.GetFallbackWorkerConfig (Microsoft.Azure.WebJobs.Script, Version=4.22.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs:128)
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.LoadFunctionMetadata (Microsoft.Azure.WebJobs.Script, Version=4.22.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs:136)
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.GetFunctionMetadata (Microsoft.Azure.WebJobs.Script, Version=4.22.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs:89)
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.<TryGetFunctionMetadata>b__17_0 (Microsoft.Azure.WebJobs.Script, Version=4.22.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs:71)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd (System.Collections.Concurrent, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.TryGetFunctionMetadata (Microsoft.Azure.WebJobs.Script, Version=4.22.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs:69)
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.StartFunction (Microsoft.Azure.WebJobs.Script.WebHost, Version=4.22.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:65)
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.AddAsync (Microsoft.Azure.WebJobs.Script.WebHost, Version=4.22.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:53)
   at Microsoft.Azure.WebJobs.Host.Loggers.CompositeFunctionEventCollector+<AddAsync>d__2.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Loggers\CompositeFunctionEventCollector.cs:21)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__18.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:106)
```

PackageRefence:
```
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.14.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.1.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.10.0" />
```

**Comment by brettsam** [comment]
FYI @soninaren -- I see a lot of scenarios where this is throwing in our backend logs. We should investigate and fix them.

**Comment by fabiocav** [comment]
@soninaren is actively investigating this. Moving to the next sprint to continue investigation.

**Comment by ClassyCircuit** [comment]
@soninaren @fabiocav any updates on this? I am also experiencing the same issue right now.

```
Timestamp : 12/20/2023 11:06:18 AM
Inner Exception Type: System.NullReferenceException
Total Occurrences: 1
Latest Exception Message: An unhandled host error has occurred.
Object reference not set to an instance of an object.

Full Exception :
 System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.GetFallbackWorkerConfig() at /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs : 129
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.LoadFunctionMetadata(Boolean forceRefresh,Boolean includeCustomProviders,IFunctionInvocationDispatcher dispatcher,IList`1 workerConfigs) at /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs : 137
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.GetFunctionMetadata(Boolean forceRefresh,Boolean applyAllowList,Boolean includeCustomProviders,IList`1 workerConfigs) at /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs : 90
   at Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.GetFunctionsMetadata(Boolean includeProxies,Boolean forceRefresh) at /_/src/WebJobs.Script.WebHost/Management/WebFunctionsManager.cs : 74
   at async Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.GetFunctionsMetadata(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.List(Boolean includeProxies) at /_/src/WebJobs.Script.WebHost/Controllers/FunctionsController.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,ObjectMethodExecutor executor,Object controller,Object[] arguments)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Logged|12_1(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next,Scope& scope,Object& state,Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next,Scope& scope,Object& state,Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.Invoke(HttpContext context) at /_/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs : 41
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.Middleware.ExceptionMiddleware.Invoke(HttpContext context) at /_/src/WebJobs.Script.WebHost/Middleware/ExceptionMiddleware.cs : 27
```
