### ISSUE TITLE
Host stops due to error in startup

### ISSUE THREAD

**Issue by vinaydate** [Azure/azure-functions-host#9654]
#### Investigative information

- Timestamp: 2023-10-31T19:25:41.972
- Function App version: 4
- Function App name: sevapdffunctions
- Function name(s) (as appropriate): NA
- Invocation ID: 940edc45-d6e6-4b7b-8599-8088a6706936 (I did not understand, so providing operation id)
- Region: West India

#### Repro steps

When deployed or restarted, it displays an error in azure console and it does not work anymore

#### Expected behavior

There should not be any error during startup and function host should keep on running.

#### Actual behavior

The error displayed is:

`Microsoft.Azure.WebJobs.Script.WebHost: Host thresholds exceeded: [Sections]. For more information, see https://aka.ms/functions-thresholds.`

Also I downloaded the logs from Kudu and the relevant logs are:

`
2023-10-31T19:25:41.852 [Information] Starting JobHost
2023-10-31T19:25:41.852 [Information] Starting Host (HostId=sevapdffunctions, InstanceId=fd63b400-dfc3-4d09-adc1-24d9df44978b, Version=4.27.5.21549, ProcessId=4380, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~4)
2023-10-31T19:25:41.867 [Error] A host error has occurred during startup operation '940edc45-d6e6-4b7b-8599-8088a6706936'.
System.InvalidOperationException : Host thresholds exceeded: [Sections]. For more information, see https://aka.ms/functions-thresholds.
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.IsHostHealthy(Boolean throwWhenUnhealthy) at /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 685
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.OnHostInitializing(Object sender,EventArgs e) at /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 577
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at /_/src/WebJobs.Script/Host/ScriptHost.cs : 276
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at /_/src/WebJobs.Script/Host/ScriptHost.cs : 256
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 328
2023-10-31T19:25:41.972 [Information] Stopping JobHost
`

#### Known workarounds
NA

#### Related information 

* Programming language used : c#
* framework - dotnet framework 4.8
* FUNCTIONS_WORKER_RUNTIME - dotnet-isolated
* Links to source - NA
* Bindings used - Event Hub event for blob storage, http

**Comment by kshyju** [comment]
@vinaydate Can you double check your dotnet-isolated function app start up code (in Program.cs) to see there are anything which might be failing? You could take a binary search approach to reduce your startup code to see which minimal version of the code is working and when does it start breaking.

**Comment by vinaydate** [comment]
Appreciate your quick response.

This is the code that runs at startup, as far as I know. Even "Before running debugger" was not logged.

By _as far as I know_, I mean, all other code is azure function code, which will be run when trigger occurs. 

```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace SampleFunctionApp1 {
  internal class Program {
    static void Main(string[] args) {
      ILogger logger = LoggerFactory.Create(builder =>
      {
        builder.AddConsole();
      }).CreateLogger("MyLogger");

      logger.LogInformation("Before running debugger");

      if (System.Diagnostics.Debugger.IsAttached) {
        FunctionsDebugger.Enable();
      }

      logger.LogInformation("Before creating Host instance");

      var host = new HostBuilder()
          .ConfigureFunctionsWorkerDefaults()
          .Build();

      logger.LogInformation("After creating Host instance");

      host.Run();
      logger.LogInformation("After running Host instance");
    }
  }
}

```

 Tried with removing all other things and simply keeping
 
```
       var host = new HostBuilder()
          .ConfigureFunctionsWorkerDefaults()
          .Build();
      
      host.Run();
```

still it resulted in the same error

**Comment by vinaydate** [comment]
An update:

I removed [Function(...)] attributes from every function and deployed the app. So, I think, the Main function given above is the only code that is getting executed now. Still I am getting the same error

**Comment by kshyju** [comment]
> Host thresholds exceeded: [Sections]. For more information, see https://aka.ms/functions-thresholds

Is your function application using memory mapped files?

**Comment by vinaydate** [comment]
yes, I am using Stream (memory). But does this really matter if the code containing Stream is not going to be executed at all.

For two reasons: 
1. Error is in startup and stream is used in function execution. 
3. after removing all Function attributes, even that becomes irrelevant)?

**Comment by kshyju** [comment]
> An update:
> 
> I removed [Function(...)] attributes from every function and deployed the app. So, I think, the Main function given above is the only code that is getting executed now. Still I am getting the same error

Why would you remove the `Function` attribute? It is needed for the runtime to identify what methods are functions.

**Comment by cjaliaga** [comment]
@vinaydate could you remove the App Setting `SnapshotDebugger_EXTENSION_VERSION` or set the value to 'disabled'?

`SnapshotDebugger_EXTENSION_VERSION=disabled`

Please let us know if the issue is gone after applying those changes.

**Comment by vinaydate** [comment]
> @vinaydate could you remove the App Setting `SnapshotDebugger_EXTENSION_VERSION` or set the value to 'disabled'?
> 
> `SnapshotDebugger_EXTENSION_VERSION=disabled`
> 
> Please let us know if the issue is gone after applying those changes.

Works. Thank you.

Any special reason behind this removing the setting?

**Comment by cjaliaga** [comment]
Configuring Snapshot debugger in Azure Functions is not supported with those settings and can cause the issue that you were seeing here. The recommended way is to follow this doc page: https://learn.microsoft.com/en-us/azure/azure-monitor/snapshot-debugger/snapshot-debugger-function-app
