### ISSUE TITLE
Functions v4 .net 6.0 isolated job host stopping without errors

### ISSUE THREAD

**Issue by bart-vandervliet** [Azure/azure-functions-host#9664]
#### Description

I've been pulling my hair out over this one. We had a function v3 running .net core 3.1 functions, which was working fine.
We converted the function app to v4, .net 6.0 isolated and suddenly the function app is showing unexpected behavior. It won't display the available functions in the app through the Azure Portal and it won't run a very simple timer trigger with a log in it.

Function host logs shows a succesful startup of the function app, but stops immediately without errors.

For simplicity I have replaced the original function app with a new function app created in Visual Studio 2022 with no modifications  and 2 functions in it: Function1 (http) and Function2 (timer).

I have deployed it to
1. A new Azure function (created with the ARM template listed below): it works like expected
2. Our Azure function migrated from v3 to v4 (upgraded with the ARM template listed below): unexpected behavior

Function1.cs
```cs
    public class Function1
    {
        private readonly ILogger _logger;

        public Function1(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Function1>();
        }

        [Function("Function1")]
        public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");

            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

            response.WriteString("Welcome to Azure Functions!");

            return response;
        }
    }
```

Function2.cs
```cs
    public class Function2
    {
        private readonly ILogger _logger;

        public Function2(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Function2>();
        }

        [Function("Function2")]
        public void Run([TimerTrigger("* * * * *")] TimerInfo myTimer)
        {
            _logger.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
            
            if (myTimer.ScheduleStatus is not null)
            {
                _logger.LogInformation($"Next timer schedule at: {myTimer.ScheduleStatus.Next}");
            }
        }
    }
```

host.json
```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            },
            "enableLiveMetricsFilters": true
        }
    }
}
```

Program.cs
```cs
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .Build();

host.Run();
```

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

#### Investigative information

Please provide the following:

- Timestamp: 2023-11-07T16:46:27.305
- Function App version: ~4 (4.27.5.21549)
- Invocation ID: f70bbef9-4266-4256-8ec2-be2fd4b47b20
- Region: West Europe

#### Expected behavior

Having an up and running Azure Function.

#### Actual behavior

Azure Function is running, but doesn't show any functions.
Host log shows the job host is starting, but stops immediately.
Timer trigger isn't working
HTTP trigger seems to work; in the logs it starts the job host and stops it right after running the trigger.

#### Known workarounds

None.

#### Related information 

Function runs in an ASE v2.

Job host log:
```
2023-11-07T16:46:24.676 [Information] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: java
2023-11-07T16:46:24.683 [Information] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: node
2023-11-07T16:46:24.684 [Information] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: powershell
2023-11-07T16:46:24.845 [Information] Initializing Warmup Extension.
2023-11-07T16:46:24.893 [Information] Initializing Host. OperationId: '48c75cb8-d76c-4a48-9e37-b27011394062'.
2023-11-07T16:46:24.899 [Information] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=48c75cb8-d76c-4a48-9e37-b27011394062
2023-11-07T16:46:24.992 [Information] ApplicationInsightsLoggerOptions
{
  "SamplingSettings": {
    "EvaluationInterval": "00:00:15",
    "InitialSamplingPercentage": 100.0,
    "MaxSamplingPercentage": 100.0,
    "MaxTelemetryItemsPerSecond": 20.0,
    "MinSamplingPercentage": 0.1,
    "MovingAverageRatio": 0.25,
    "SamplingPercentageDecreaseTimeout": "00:02:00",
    "SamplingPercentageIncreaseTimeout": "00:15:00"
  },
  "SamplingExcludedTypes": "Request",
  "SamplingIncludedTypes": null,
  "SnapshotConfiguration": null,
  "EnablePerformanceCountersCollection": true,
  "HttpAutoCollectionOptions": {
    "EnableHttpTriggerExtendedInfoCollection": true,
    "EnableW3CDistributedTracing": true,
    "EnableResponseHeaderInjection": true
  },
  "LiveMetricsInitializationDelay": "00:00:15",
  "EnableLiveMetrics": true,
  "EnableLiveMetricsFilters": true,
  "EnableDependencyTracking": true,
  "DependencyTrackingOptions": null
}
2023-11-07T16:46:24.992 [Information] LoggerFilterOptions
{
  "MinLevel": "None",
  "Rules": [
    {
      "ProviderName": null,
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": "None",
      "Filter": null
    },
    {
      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
      "CategoryName": null,
      "LogLevel": null,
      "Filter": "<AddFilter>b__0"
    }
  ]
}
2023-11-07T16:46:24.992 [Information] ConcurrencyOptions
{
  "DynamicConcurrencyEnabled": false,
  "MaximumFunctionConcurrency": 500,
  "CPUThreshold": 0.8,
  "SnapshotPersistenceEnabled": true
}
2023-11-07T16:46:24.993 [Information] FunctionResultAggregatorOptions
{
  "BatchSize": 1000,
  "FlushTimeout": "00:00:30",
  "IsEnabled": true
}
2023-11-07T16:46:24.993 [Information] SingletonOptions
{
  "LockPeriod": "00:00:15",
  "ListenerLockPeriod": "00:01:00",
  "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
  "LockAcquisitionPollingInterval": "00:00:05",
  "ListenerLockRecoveryPollingInterval": "00:01:00"
}
2023-11-07T16:46:24.993 [Information] ScaleOptions
{
  "ScaleMetricsMaxAge": "00:02:00",
  "ScaleMetricsSampleInterval": "00:00:10",
  "MetricsPurgeEnabled": true,
  "IsTargetScalingEnabled": true,
  "IsRuntimeScalingEnabled": false
}
2023-11-07T16:46:24.994 [Information] Starting JobHost
2023-11-07T16:46:24.996 [Information] Starting Host (HostId=xxx, InstanceId=xxx, Version=4.27.5.21549, ProcessId=10868, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~4)
2023-11-07T16:46:25.163 [Information] Loading functions metadata
2023-11-07T16:46:25.197 [Information] Reading functions metadata (Custom)
2023-11-07T16:46:25.315 [Information] 2 functions found (Custom)
2023-11-07T16:46:25.353 [Information] 2 functions loaded
2023-11-07T16:46:25.380 [Information] Generating 2 job function(s)
2023-11-07T16:46:25.544 [Information] Found the following functions:
Host.Functions.Function1
Host.Functions.Function2
2023-11-07T16:46:25.552 [Information] Initializing function HTTP routes
Mapped function route 'api/Function1' [get,post] to 'Function1'
2023-11-07T16:46:25.556 [Information] Host initialized (554ms)
2023-11-07T16:46:25.612 [Information] HttpOptions
{
  "DynamicThrottlesEnabled": false,
  "EnableChunkedRequestBinding": false,
  "MaxConcurrentRequests": -1,
  "MaxOutstandingRequests": -1,
  "RoutePrefix": "api"
}
2023-11-07T16:46:25.652 [Information] The next 5 occurrences of the 'Function2' schedule (Cron: '* * * * *') will be:
11/07/2023 16:47:00Z
11/07/2023 16:48:00Z
11/07/2023 16:49:00Z
11/07/2023 16:50:00Z
11/07/2023 16:51:00Z
2023-11-07T16:46:25.667 [Information] Host started (669ms)
2023-11-07T16:46:25.667 [Information] Job host started
2023-11-07T16:46:25.983 [Information] Executing 'Functions.Function2' (Reason='Timer fired at 2023-11-07T16:46:25.9707937+00:00', Id=f70bbef9-4266-4256-8ec2-be2fd4b47b20)
2023-11-07T16:46:25.988 [Information] Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2023-11-07T16:42:00.0000000+00:00
2023-11-07T16:46:26.231 [Information] Stopping JobHost
2023-11-07T16:46:26.239 [Information] Stopping the listener 'Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener' for function 'Function2'
2023-11-07T16:46:27.202 [Information] Worker process started and initialized.
2023-11-07T16:46:27.305 [Error] Executed 'Functions.Function2' (Failed, Id=f70bbef9-4266-4256-8ec2-be2fd4b47b20, Duration=1328ms)
A task was canceled.
2023-11-07T16:46:27.506 [Information] Stopped the listener 'Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener' for function 'Function2'
2023-11-07T16:46:27.511 [Information] Job host stopped
```

ARM template used for converting the v3 function app to v4:
```json
{
  "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "functionName": {
      "type": "String"
    },
    "storageName": {
      "type": "string"
    },
    "hostingPlanName": {
      "type": "string"
    },
    "hostingEnvironment": {
      "type": "string"
    },
    "keyVaultName": {
      "type": "string"
    },
    "tenantId": {
      "type": "string",
      "defaultValue": "[subscription().tenantId]",
      "metadata": {
        "description": "Specifies the Azure Active Directory tenant ID that should be used for authenticating requests to the key vault. Get it by using Get-AzSubscription cmdlet."
      }
    }
  },
  "variables": {
    "appInsightsName": "[parameters('functionName')]"
  },
  "resources": [
    {
      "apiVersion": "2015-05-01",
      "name": "[variables('appInsightsName')]",
      "type": "Microsoft.Insights/components",
      "kind": "web",
      "location": "[resourceGroup().location]",
      "tags": {
        "[concat('hidden-link:', resourceGroup().id, '/providers/Microsoft.Web/sites/', variables('appInsightsName'))]": "Resource"
      },
      "properties": {
        "Application_Type": "web",
        "ApplicationId": "[variables('appInsightsName')]"
      }
    },
    {
      "type": "Microsoft.Web/sites",
      "kind": "functionapp",
      "apiVersion": "2015-08-01",
      "name": "[parameters('functionName')]",
      "location": "[resourceGroup().location]",
      "identity": {
        "type": "SystemAssigned"
      },
      "properties": {
        "name": "[parameters('functionName')]",
        "siteConfig": {
          "netFrameworkVersion": "v6.0",
          "appSettings": [
            {
              "name": "Serilog:MinimumLevel",
              "value": "Warning"
            },
            {
              "name": "FUNCTIONS_WORKER_RUNTIME",
              "value": "dotnet-isolated"
            },
            {
              "name": "AzureWebJobsStorage",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=',parameters('storageName'),';AccountKey=',listKeys(resourceId(resourceGroup().name,'Microsoft.Storage/storageAccounts', parameters('storageName')), '2015-05-01-preview').key1)]"
            },
            {
              "name": "FUNCTIONS_EXTENSION_VERSION",
              "value": "~4"
            },
            {
              "name": "WEBSITE_NODE_DEFAULT_VERSION",
              "value": "10.14.1"
            },
            {
              "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
              "value": "[reference(resourceId('microsoft.insights/components/', variables('appInsightsName')), '2015-05-01').InstrumentationKey]"
            }
          ],
          "alwaysOn": true
        },
        "clientAffinityEnabled": false,
        "serverFarmId": "[resourceId(resourceGroup().name,'Microsoft.Web/serverfarms',parameters('hostingPlanName'))]",
        "hostingEnvironment": "[parameters('hostingEnvironment')]"
      }
    },
    {
      "type": "Microsoft.KeyVault/vaults/accessPolicies",
      "name": "[concat(parameters('keyVaultName'), '/add')]",
      "apiVersion": "2016-10-01",
      "dependsOn": [
        "[resourceId('Microsoft.Web/sites', parameters('functionName'))]"
      ],
      "properties": {
        "accessPolicies": [
          {
            "tenantId": "[parameters('tenantId')]",
            "objectId": "[reference(concat('Microsoft.Web/sites/', parameters('functionName')), '2018-11-01', 'Full').identity.principalId]",
            "permissions": {
              "keys": [],
              "secrets": [
                "get",
                "list"
              ],
              "certificates": []
            }
          }
        ],
        "enabledForDeployment": false,
        "enabledForDiskEncryption": false,
        "enabledForTemplateDeployment": true
      }
    }
  ]
}
```

**Comment by bart-vandervliet** [comment]
Sometimes (currently once in 8 startups since I recreated the resource) the logs indicate the following error:
```
2023-11-08T08:54:30.192 [Error] Failed to start a new language worker for runtime: dotnet-isolated.
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at async Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) at /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs : 283
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(??) at /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 152
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(??) at /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 144
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(??) at /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 135
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass55_0.<StartWorkerProcesses>b__0(??) at /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 215
```

**Comment by bart-vandervliet** [comment]
I tried downgrading the `Microsoft.Azure.Functions.Worker` and `Microsoft.Azure.Functions.Worker.Sdk` packages to 1.14.1 and 1.10.0 respectively without result.

**Comment by bhagyshricompany** [comment]
Thanks for reporting.Pls share the invocation id ,timestamp  ,region.Thanks
