### ISSUE TITLE
Node v4 pm doesn't load APIS - error `has already been registered`

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-functions-host#9672]
I'm not sure where I'm going wrong. The code is in the [packages/api-v4](https://github.com/Azure-Samples/contoso-real-estate/tree/main/packages/api-v4). My branch in dev containers doesn't have any other function apps, I've removed the api folder which was v3. 

When I start the function locally, I get the following error which I'm not sure how to debug or what to look for. 

```
@dfberry ➜ /workspaces/contoso-real-estate/packages/api (dfberry/infra-env) $ npm run start:host

> api@1.0.0 start:host
> func start --typescript --verbose


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       4.0.5441 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.25.3.21264

[2023-11-08T00:32:30.472Z] Building host: version spec: , startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'dbbc6e6c-441f-4e08-8fd2-ae1399b23382'
[2023-11-08T00:32:30.478Z] Reading host configuration file '/workspaces/contoso-real-estate/packages/api/host.json'
[2023-11-08T00:32:30.479Z] Host configuration file read:
[2023-11-08T00:32:30.479Z] {
[2023-11-08T00:32:30.479Z]   "version": "2.0",
[2023-11-08T00:32:30.479Z]   "logging": {
[2023-11-08T00:32:30.479Z]     "applicationInsights": {
[2023-11-08T00:32:30.479Z]       "samplingSettings": {
[2023-11-08T00:32:30.479Z]         "isEnabled": true,
[2023-11-08T00:32:30.479Z]         "excludedTypes": "Request"
[2023-11-08T00:32:30.479Z]       }
[2023-11-08T00:32:30.480Z]     }
[2023-11-08T00:32:30.480Z]   },
[2023-11-08T00:32:30.480Z]   "extensionBundle": {
[2023-11-08T00:32:30.480Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2023-11-08T00:32:30.480Z]     "version": "[4.*, 5.0.0)"
[2023-11-08T00:32:30.480Z]   },
[2023-11-08T00:32:30.480Z]   "extensions": {
[2023-11-08T00:32:30.480Z]     "http": {
[2023-11-08T00:32:30.480Z]       "routePrefix": "api"
[2023-11-08T00:32:30.480Z]     }
[2023-11-08T00:32:30.480Z]   }
[2023-11-08T00:32:30.480Z] }
[2023-11-08T00:32:30.506Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: powershell
[2023-11-08T00:32:30.536Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: java
[2023-11-08T00:32:30.538Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: python
[2023-11-08T00:32:30.539Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /home/node/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2023-11-08T00:32:30.540Z] Found a matching extension bundle at /home/node/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.8.0
[2023-11-08T00:32:30.552Z] Loading functions metadata
[2023-11-08T00:32:30.554Z] Worker indexing is enabled
[2023-11-08T00:32:30.560Z] Fetching metadata for workerRuntime: node
[2023-11-08T00:32:30.560Z] Reading functions metadata
[2023-11-08T00:32:30.709Z] Worker 0a7676dc-e75a-4004-bdff-9bea94b69414 connecting on 127.0.0.1:41745
[2023-11-08T00:32:30.866Z] Worker 0a7676dc-e75a-4004-bdff-9bea94b69414 received WorkerInitRequest
[2023-11-08T00:32:31.604Z] Loading entry point file "dist/src/index.js"
[2023-11-08T00:32:31.606Z] Setting Node.js programming model to "@azure/functions" version "4.0.1"
[2023-11-08T00:32:31.718Z] Worker 0a7676dc-e75a-4004-bdff-9bea94b69414 received FunctionsMetadataRequest
[2023-11-08T00:32:31.718Z] Worker was unable to load entry point "dist/src/index.js": A function with id "get-reservations" has already been registered.
[2023-11-08T00:32:31.725Z] Worker failed to index functions
[2023-11-08T00:32:31.725Z] Result: Failure
[2023-11-08T00:32:31.725Z] Exception: Worker was unable to load entry point "dist/src/index.js": A function with id "get-reservations" has already been registered.
[2023-11-08T00:32:31.725Z] Stack: Error: Worker was unable to load entry point "dist/src/index.js": A function with id "get-reservations" has already been registered.
[2023-11-08T00:32:31.725Z]     at t.registerFunction (/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/bin/workers/node/dist/src/worker-bundle.js:2:28458)
[2023-11-08T00:32:31.725Z]     at generic (/workspaces/contoso-real-estate/node_modules/@azure/functions/dist/azure-functions.js:494:17)
[2023-11-08T00:32:31.725Z]     at http (/workspaces/contoso-real-estate/node_modules/@azure/functions/dist/azure-functions.js:428:5)
[2023-11-08T00:32:31.725Z]     at Object.patch (/workspaces/contoso-real-estate/node_modules/@azure/functions/dist/azure-functions.js:419:5)
[2023-11-08T00:32:31.726Z]     at Object.<anonymous> (/workspaces/contoso-real-estate/packages/api/dist/src/index.js:56:17)
[2023-11-08T00:32:31.726Z]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[2023-11-08T00:32:31.726Z]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[2023-11-08T00:32:31.726Z]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[2023-11-08T00:32:31.726Z]     at Module._load (node:internal/modules/cjs/loader:958:12)
[2023-11-08T00:32:31.726Z]     at Module.require (node:internal/modules/cjs/loader:1141:19).
[2023-11-08T00:32:31.728Z] 0 functions found
[2023-11-08T00:32:31.736Z] 0 functions loaded
[2023-11-08T00:32:31.737Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /home/node/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2023-11-08T00:32:31.738Z] Found a matching extension bundle at /home/node/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.8.0
[2023-11-08T00:32:31.738Z] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2023-11-08T00:32:31.833Z] Skipping bundle download since it already exists at path /home/node/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.8.0
[2023-11-08T00:32:31.835Z] Loading extension bundle from /home/node/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.8.0/bin
[2023-11-08T00:32:31.835Z] Script Startup resetting load context with base path: '/home/node/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.8.0/bin'.
[2023-11-08T00:32:31.842Z] Reading host configuration file '/workspaces/contoso-real-estate/packages/api/host.json'
[2023-11-08T00:32:31.842Z] Host configuration file read:
[2023-11-08T00:32:31.843Z] {
[2023-11-08T00:32:31.843Z]   "version": "2.0",
[2023-11-08T00:32:31.843Z]   "logging": {
[2023-11-08T00:32:31.843Z]     "applicationInsights": {
[2023-11-08T00:32:31.843Z]       "samplingSettings": {
[2023-11-08T00:32:31.843Z]         "isEnabled": true,
[2023-11-08T00:32:31.843Z]         "excludedTypes": "Request"
[2023-11-08T00:32:31.843Z]       }
[2023-11-08T00:32:31.843Z]     }
[2023-11-08T00:32:31.843Z]   },
[2023-11-08T00:32:31.843Z]   "extensionBundle": {
[2023-11-08T00:32:31.844Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2023-11-08T00:32:31.844Z]     "version": "[4.*, 5.0.0)"
[2023-11-08T00:32:31.844Z]   },
[2023-11-08T00:32:31.844Z]   "extensions": {
[2023-11-08T00:32:31.844Z]     "http": {
[2023-11-08T00:32:31.844Z]       "routePrefix": "api"
[2023-11-08T00:32:31.844Z]     }
[2023-11-08T00:32:31.844Z]   }
[2023-11-08T00:32:31.844Z] }
[2023-11-08T00:32:32.130Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: powershell
[2023-11-08T00:32:32.131Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: java
[2023-11-08T00:32:32.132Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: python
[2023-11-08T00:32:32.228Z] Initializing Warmup Extension.
[2023-11-08T00:32:32.277Z] Initializing Host. OperationId: 'dbbc6e6c-441f-4e08-8fd2-ae1399b23382'.
[2023-11-08T00:32:32.286Z] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=dbbc6e6c-441f-4e08-8fd2-ae1399b23382
[2023-11-08T00:32:32.327Z] Error: Worker was unable to load entry point "dist/src/index.js": A function with id "get-reservations" has already been registered.
[2023-11-08T00:32:32.327Z]     at t.registerFunction (/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/bin/workers/node/dist/src/worker-bundle.js:2:28458)
[2023-11-08T00:32:32.327Z]     at generic (/workspaces/contoso-real-estate/node_modules/@azure/functions/dist/azure-functions.js:494:17)
[2023-11-08T00:32:32.327Z]     at http (/workspaces/contoso-real-estate/node_modules/@azure/functions/dist/azure-functions.js:428:5)
[2023-11-08T00:32:32.328Z]     at Object.patch (/workspaces/contoso-real-estate/node_modules/@azure/functions/dist/azure-functions.js:419:5)
[2023-11-08T00:32:32.328Z]     at Object.<anonymous> (/workspaces/contoso-real-estate/packages/api/dist/src/index.js:56:17)
[2023-11-08T00:32:32.328Z]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[2023-11-08T00:32:32.328Z]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[2023-11-08T00:32:32.328Z]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[2023-11-08T00:32:32.328Z]     at Module._load (node:internal/modules/cjs/loader:958:12)
[2023-11-08T00:32:32.328Z]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[2023-11-08T00:32:32.332Z] LoggerFilterOptions
[2023-11-08T00:32:32.332Z] {
[2023-11-08T00:32:32.332Z]   "MinLevel": "None",
[2023-11-08T00:32:32.332Z]   "Rules": [
[2023-11-08T00:32:32.332Z]     {
[2023-11-08T00:32:32.332Z]       "ProviderName": null,
[2023-11-08T00:32:32.332Z]       "CategoryName": null,
[2023-11-08T00:32:32.332Z]       "LogLevel": null,
[2023-11-08T00:32:32.332Z]       "Filter": "<AddFilter>b__0"
[2023-11-08T00:32:32.332Z]     },
[2023-11-08T00:32:32.332Z]     {
[2023-11-08T00:32:32.333Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2023-11-08T00:32:32.333Z]       "CategoryName": null,
[2023-11-08T00:32:32.333Z]       "LogLevel": "None",
[2023-11-08T00:32:32.333Z]       "Filter": null
[2023-11-08T00:32:32.333Z]     },
[2023-11-08T00:32:32.333Z]     {
[2023-11-08T00:32:32.333Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2023-11-08T00:32:32.333Z]       "CategoryName": null,
[2023-11-08T00:32:32.333Z]       "LogLevel": null,
[2023-11-08T00:32:32.333Z]       "Filter": "<AddFilter>b__0"
[2023-11-08T00:32:32.333Z]     },
[2023-11-08T00:32:32.333Z]     {
[2023-11-08T00:32:32.333Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2023-11-08T00:32:32.334Z]       "CategoryName": null,
[2023-11-08T00:32:32.334Z]       "LogLevel": null,
[2023-11-08T00:32:32.334Z]       "Filter": "<AddFilter>b__0"
[2023-11-08T00:32:32.334Z]     }
[2023-11-08T00:32:32.334Z]   ]
[2023-11-08T00:32:32.334Z] }
[2023-11-08T00:32:32.334Z] LoggerFilterOptions
[2023-11-08T00:32:32.334Z] {
[2023-11-08T00:32:32.334Z]   "MinLevel": "None",
[2023-11-08T00:32:32.334Z]   "Rules": [
[2023-11-08T00:32:32.334Z]     {
[2023-11-08T00:32:32.334Z]       "ProviderName": null,
[2023-11-08T00:32:32.335Z]       "CategoryName": null,
[2023-11-08T00:32:32.335Z]       "LogLevel": null,
[2023-11-08T00:32:32.335Z]       "Filter": "<AddFilter>b__0"
[2023-11-08T00:32:32.335Z]     },
[2023-11-08T00:32:32.335Z]     {
[2023-11-08T00:32:32.335Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2023-11-08T00:32:32.335Z]       "CategoryName": null,
[2023-11-08T00:32:32.335Z]       "LogLevel": "None",
[2023-11-08T00:32:32.335Z]       "Filter": null
[2023-11-08T00:32:32.335Z]     },
[2023-11-08T00:32:32.335Z]     {
[2023-11-08T00:32:32.335Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2023-11-08T00:32:32.335Z]       "CategoryName": null,
[2023-11-08T00:32:32.335Z]       "LogLevel": null,
[2023-11-08T00:32:32.336Z]       "Filter": "<AddFilter>b__0"
[2023-11-08T00:32:32.336Z]     },
[2023-11-08T00:32:32.336Z]     {
[2023-11-08T00:32:32.336Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2023-11-08T00:32:32.336Z]       "CategoryName": null,
[2023-11-08T00:32:32.336Z]       "LogLevel": null,
[2023-11-08T00:32:32.336Z]       "Filter": "<AddFilter>b__0"
[2023-11-08T00:32:32.336Z]     }
[2023-11-08T00:32:32.336Z]   ]
[2023-11-08T00:32:32.336Z] }
[2023-11-08T00:32:32.336Z] ConcurrencyOptions
[2023-11-08T00:32:32.336Z] {
[2023-11-08T00:32:32.337Z]   "DynamicConcurrencyEnabled": false,
[2023-11-08T00:32:32.337Z]   "MaximumFunctionConcurrency": 500,
[2023-11-08T00:32:32.337Z]   "CPUThreshold": 0.8,
[2023-11-08T00:32:32.337Z]   "SnapshotPersistenceEnabled": true
[2023-11-08T00:32:32.337Z] }
[2023-11-08T00:32:32.337Z] FunctionResultAggregatorOptions
[2023-11-08T00:32:32.337Z] {
[2023-11-08T00:32:32.337Z]   "BatchSize": 1000,
[2023-11-08T00:32:32.337Z]   "FlushTimeout": "00:00:30",
[2023-11-08T00:32:32.337Z]   "IsEnabled": true
[2023-11-08T00:32:32.337Z] }
[2023-11-08T00:32:32.337Z] SingletonOptions
[2023-11-08T00:32:32.338Z] {
[2023-11-08T00:32:32.338Z]   "LockPeriod": "00:00:15",
[2023-11-08T00:32:32.338Z]   "ListenerLockPeriod": "00:00:15",
[2023-11-08T00:32:32.338Z]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2023-11-08T00:32:32.338Z]   "LockAcquisitionPollingInterval": "00:00:05",
[2023-11-08T00:32:32.338Z]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2023-11-08T00:32:32.338Z] }
[2023-11-08T00:32:32.338Z] ScaleOptions
[2023-11-08T00:32:32.338Z] {
[2023-11-08T00:32:32.338Z]   "ScaleMetricsMaxAge": "00:02:00",
[2023-11-08T00:32:32.338Z]   "ScaleMetricsSampleInterval": "00:00:10",
[2023-11-08T00:32:32.339Z]   "MetricsPurgeEnabled": true,
[2023-11-08T00:32:32.339Z]   "IsTargetScalingEnabled": true,
[2023-11-08T00:32:32.339Z]   "IsRuntimeScalingEnabled": false
[2023-11-08T00:32:32.339Z] }
[2023-11-08T00:32:32.340Z] Starting JobHost
[2023-11-08T00:32:32.343Z] Starting Host (HostId=codespaces74a47e-37961383, InstanceId=8023462f-4d43-4e34-931c-945746ed62b5, Version=4.25.3.21264, ProcessId=113842, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2023-11-08T00:32:32.361Z] Loading functions metadata
[2023-11-08T00:32:32.361Z] Worker indexing is enabled
[2023-11-08T00:32:32.361Z] Fetching metadata for workerRuntime: node
[2023-11-08T00:32:32.361Z] Reading functions metadata
[2023-11-08T00:32:32.361Z] 0 functions found
[2023-11-08T00:32:32.368Z] Reading functions metadata
[2023-11-08T00:32:32.381Z] 1 functions found
[2023-11-08T00:32:32.381Z] 0 functions loaded
[2023-11-08T00:32:32.398Z] Generating 0 job function(s)
[2023-11-08T00:32:32.417Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[2023-11-08T00:32:32.427Z] HttpOptions
[2023-11-08T00:32:32.427Z] {
[2023-11-08T00:32:32.427Z]   "DynamicThrottlesEnabled": false,
[2023-11-08T00:32:32.427Z]   "EnableChunkedRequestBinding": false,
[2023-11-08T00:32:32.427Z]   "MaxConcurrentRequests": -1,
[2023-11-08T00:32:32.428Z]   "MaxOutstandingRequests": -1,
[2023-11-08T00:32:32.428Z]   "RoutePrefix": "api"
[2023-11-08T00:32:32.428Z] }
[2023-11-08T00:32:32.429Z] Initializing function HTTP routes
[2023-11-08T00:32:32.429Z] No HTTP routes mapped
[2023-11-08T00:32:32.429Z] 
[2023-11-08T00:32:32.438Z] Host initialized (84ms)
[2023-11-08T00:32:32.440Z] Host started (96ms)
[2023-11-08T00:32:32.440Z] Job host started
[2023-11-08T00:32:37.342Z] Host lock lease acquired by instance ID '0000000000000000000000001B67BC3A'.
```

**Comment by glaucia86** [comment]
@dfberry did you created the `local.settings.json`?

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsFeatureFlags": "EnableWorkerIndexing"
  }
}

 ```
 
 And another thing: try to run the command: `npm audit` to update any package outdated. And then run again the command: `npm run start`
 
 If doesn't work, please reach me tomorrow. So we can see together what's going on here!

**Comment by diberry** [comment]
Found _my_ problem. `get-reservations` is used as the name for 2 functions apis. 

![image](https://github.com/Azure/azure-functions-core-tools/assets/41597107/4a3b5a5e-2efd-4ce6-b182-79d7ae08bb2c)

#please-close

**Comment by glaucia86** [comment]
@shreyabatra4 we found the issue. You can close this issue
