### ISSUE TITLE
.NET Core dependency injection not working on docker container microsoft

### ISSUE THREAD

**Issue by alexandredelnero** [Azure/azure-functions-host#9834]
moved the issue to "https://github.com/dotnet/core/issues".
please delete this

**Comment by alexandredelnero** [comment]
obs.: stack of the error

2024-01-25 19:40:20 fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2024-01-25 19:40:20       An unhandled exception has occurred while executing the request.
2024-01-25 19:40:20       System.InvalidOperationException: Unable to resolve service for type 'Negocio.interfaces.INegocioLog' while attempting to activate 'TRF3.Apresentacao.Controllers.HomeController'.
2024-01-25 19:40:20          at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ThrowHelperUnableToResolveService(Type type, Type requiredBy)
2024-01-25 19:40:20          at lambda_method2(Closure, IServiceProvider, Object[])
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2024-01-25 19:40:20       --- End of stack trace from previous location ---
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2024-01-25 19:40:20       --- End of stack trace from previous location ---
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
2024-01-25 19:40:20 fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
2024-01-25 19:40:20       An exception was thrown attempting to execute the error handler.
2024-01-25 19:40:20       System.InvalidOperationException: Unable to resolve service for type 'Negocio.interfaces.INegocioLog' while attempting to activate 'TRF3.Apresentacao.Controllers.HomeController'.
2024-01-25 19:40:20          at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ThrowHelperUnableToResolveService(Type type, Type requiredBy)
2024-01-25 19:40:20          at lambda_method4(Closure, IServiceProvider, Object[])
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2024-01-25 19:40:20       --- End of stack trace from previous location ---
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2024-01-25 19:40:20       --- End of stack trace from previous location ---
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-01-25 19:40:20          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatch
